// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c758d7da85a83cfb88befa73c2433365fcac082af2e0e49818d0bfd44b2a03db
// @sig-hash: sha256:ecc7a3d85c8b268b
// Source: Blizzard_APIDocumentationGenerated/abbreviatednumberformatterapidocumentation.lua
export const _AbbreviatedNumberFormatterAPI = `
AddBreakpoint = _nil("AddBreakpoint")
ClearBreakpoints = _nil("ClearBreakpoints")
Copy = _nil("Copy")
GetBreakpoints = _tbl("GetBreakpoints")
ResetBreakpoints = _nil("ResetBreakpoints")
SetBreakpoints = _nil("SetBreakpoints")
`;
