// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ffcb3f52cf9b4abeab5e800a75cdd12867dd6e9648bfca455edbeea1ef68aafc
// @sig-hash: sha256:cfd7eba56eeb0d75
// Source: Blizzard_APIDocumentationGenerated/abbreviateconfigapidocumentation.lua
export const _AbbreviateConfigAPI = `
GetAbbreviateNumberData = _tbl
SetAbbreviateNumberData = _nil
`;
