// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:123d78bf478de51c1e17ce53d82e0d68f37df74a9ac06aee760e1d6af9eb93dc
// @sig-hash: sha256:dfe4ac468bdc52d2
// Source: Blizzard_APIDocumentationGenerated/abbreviateconfigapidocumentation.lua
export const _AbbreviateConfigAPI = `
GetAbbreviateNumberData = _tbl("GetAbbreviateNumberData")
SetAbbreviateNumberData = _nil("SetAbbreviateNumberData")
`;
