// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:985bbe6a97bb2e84602d0efb2c403759a6dc032c5e67e4f56dccf44d65e392bb
// @sig-hash: sha256:2e47bda5e7a5e5cd
// Source: Blizzard_APIDocumentationGenerated/abbreviatednumberformatterapidocumentation.lua
export const _AbbreviatedNumberFormatterAPI = `
AddBreakpoint = _nil
ClearBreakpoints = _nil
Copy = _nil
GetBreakpoints = _tbl
ResetBreakpoints = _nil
SetBreakpoints = _nil
`;
