// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:86214e5c30e23ab16f50015313f10dc031eb2098b70e9aae2910ed6f7ed956b4
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/bagindexconstantsdocumentation.lua
export const _BagIndexConstants = `

`;
