// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:eb58006e65428984574dc2cbefe378e6b7d9e1805f4c62ad2ab355a8e911ff82
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/bagindexconstantsdocumentation.lua
export const _BagIndexConstants = `

`;
