// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d27637f8d12416f5c552a45b9e8011105af0bc36833a5bead8a913a95214793b
// @sig-hash: sha256:82b962f6df702685
// Source: Blizzard_APIDocumentationGenerated/builddocumentation.lua
export const _Build = `
GetBuildInfo = _str
Is64BitClient = _bool
IsBetaBuild = _bool
IsDebugBuild = _bool
IsLinuxClient = _bool
IsMacClient = _bool
IsPublicBuild = _bool
IsPublicTestClient = _bool
IsTestBuild = _bool
IsWindowsClient = _bool
SupportsClipCursor = _bool
`;
