// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3fd927f23b911175270d543ad280994de0e0acaeff1a51450f9dd8c3b559d227
// @sig-hash: sha256:bce85fa512ac6554
// Source: Blizzard_APIDocumentationGenerated/builddocumentation.lua
export const _Build = `
GetBuildInfo = _str("GetBuildInfo")
Is64BitClient = _bool("Is64BitClient")
IsBetaBuild = _bool("IsBetaBuild")
IsDebugBuild = _bool("IsDebugBuild")
IsLinuxClient = _bool("IsLinuxClient")
IsMacClient = _bool("IsMacClient")
IsPublicBuild = _bool("IsPublicBuild")
IsPublicTestClient = _bool("IsPublicTestClient")
IsTestBuild = _bool("IsTestBuild")
IsWindowsClient = _bool("IsWindowsClient")
SupportsClipCursor = _bool("SupportsClipCursor")
`;
