// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d27637f8d12416f5c552a45b9e8011105af0bc36833a5bead8a913a95214793b
// @sig-hash: sha256:82b962f6df702685
// Source: Blizzard_APIDocumentationGenerated/builddocumentation.lua
export const _Build = `
GetBuildInfo = _nil
Is64BitClient = _nil
IsBetaBuild = _nil
IsDebugBuild = _nil
IsLinuxClient = _nil
IsMacClient = _nil
IsPublicBuild = _nil
IsPublicTestClient = _nil
IsTestBuild = _nil
IsWindowsClient = _nil
SupportsClipCursor = _nil
`;
