// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d3a19d7b6d947cb000991104f55d1163ae77a3105350626a1d75d7b03896dc39
// @sig-hash: sha256:912e8d07589e17c4
// Source: Blizzard_APIDocumentationGenerated/cameradocumentation.lua
export const _Camera = `
GetCameraFOVDefaults = _num("GetCameraFOVDefaults")
GetUICameraInfo = _num("GetUICameraInfo")
`;
