// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:669fe3be80d47eba01717a6dea76766b4f443868f58d3f63c5861dac7e7a798d
// @sig-hash: sha256:87e0dd95afe8a16a
// Source: Blizzard_APIDocumentationGenerated/cameradocumentation.lua
export const _Camera = `
GetCameraFOVDefaults = _nil
GetUICameraInfo = _nil
`;
