// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a3b5519ed27f9eaf6a869e7f3737a600a51a44481ec4164ac3bbb211ed0049f3
// @sig-hash: sha256:bfd01ae7f037a494
// Source: Blizzard_APIDocumentationGenerated/cinematicdocumentation.lua
export const _Cinematic = `
CinematicFinished = _nil("CinematicFinished")
CinematicStarted = _nil("CinematicStarted")
GetCurrentCinematicSummary = _str("GetCurrentCinematicSummary")
InCinematic = _bool("InCinematic")
MouseOverrideCinematicDisable = _nil("MouseOverrideCinematicDisable")
OpeningCinematic = _nil("OpeningCinematic")
StopCinematic = _nil("StopCinematic")
-- Events: CINEMATIC_START, CINEMATIC_STOP, HIDE_SUBTITLE, PLAY_MOVIE, SHOW_SUBTITLE, STOP_MOVIE
`;
