// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3829e77236fca6691e5618aa8bbe1a08f2e4dbc09a86f85036618b0f2cf05779
// @sig-hash: sha256:fc462e8a48e101ec
// Source: Blizzard_APIDocumentationGenerated/cinematicdocumentation.lua
export const _Cinematic = `
CinematicFinished = _nil
CinematicStarted = _nil
GetCurrentCinematicSummary = _nil
InCinematic = _nil
MouseOverrideCinematicDisable = _nil
OpeningCinematic = _nil
StopCinematic = _nil
-- Events: CINEMATIC_START, CINEMATIC_STOP, HIDE_SUBTITLE, PLAY_MOVIE, SHOW_SUBTITLE, STOP_MOVIE
`;
