// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:adafada94428f4e8058e4aad67c8774068ce78bad531f5250c79511ef3032151
// @sig-hash: sha256:a7b0f300c6f126f2
// Source: Blizzard_APIDocumentationGenerated/clientdocumentation.lua
export const _Client = `
FlashClientIcon = _nil
GetBillingTimeRested = _nil
GetFileIDFromPath = _nil
GetFramerate = _nil
IsCpuBound = _nil
ReportBug = _nil
ReportSuggestion = _nil
RestartGx = _nil
Screenshot = _nil
UpdateWindow = _nil
`;
