// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4c7f1bbf4290b4f920f644375e24cbfa708696c6adddec72a8442e530c2f0ee1
// @sig-hash: sha256:732b63365513a9f1
// Source: Blizzard_APIDocumentationGenerated/clientdocumentation.lua
export const _Client = `
FlashClientIcon = _nil("FlashClientIcon")
GetBillingTimeRested = _num("GetBillingTimeRested")
GetFileIDFromPath = _nil("GetFileIDFromPath")
GetFramerate = _num("GetFramerate")
IsCpuBound = _nil("IsCpuBound")
ReportBug = _nil("ReportBug")
ReportSuggestion = _nil("ReportSuggestion")
RestartGx = _nil("RestartGx")
Screenshot = _nil("Screenshot")
UpdateWindow = _nil("UpdateWindow")
`;
