// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3a8f07f422abb42a45f0a88883f9b63892122a2001c6df25bb07ccac97482b2d
// @sig-hash: sha256:8f73035f12e15356
// Source: Blizzard_APIDocumentationGenerated/connectiondocumentation.lua
export const _ConnectionScript = `
CancelLogout = _nil
ForceLogout = _nil
ForceQuit = _nil
GetNativeRealmID = _num
GetNetIpTypes = _nil
GetNetStats = _num
GetRealmID = _num
GetRealmName = _str
IsOnTournamentRealm = _bool
Logout = _nil
Quit = _nil
SelectedRealmName = _str
`;
