// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5b16312c46dda09425e261fb3e235cf3c6deb5186e6ff5405142f0874823b9f8
// @sig-hash: sha256:5ccd57896f7e49f7
// Source: Blizzard_APIDocumentationGenerated/consoledocumentation.lua
export const _Console = `
CalculateStringEditDistance = _num("CalculateStringEditDistance")
ConsoleEcho = _bool("ConsoleEcho")
ConsoleExec = _bool("ConsoleExec")
ConsoleGetAllCommands = _tbl("ConsoleGetAllCommands")
ConsoleGetColorFromType = _nil("ConsoleGetColorFromType")
ConsoleGetFontHeight = _num("ConsoleGetFontHeight")
ConsoleIsActive = _bool("ConsoleIsActive")
ConsolePrintAllMatchingCommands = _nil("ConsolePrintAllMatchingCommands")
ConsoleSetFontHeight = _nil("ConsoleSetFontHeight")
SetConsoleKey = _nil("SetConsoleKey")
-- Events: CONSOLE_CLEAR, CONSOLE_COLORS_CHANGED, CONSOLE_FONT_SIZE_CHANGED, CONSOLE_LOG, CONSOLE_MESSAGE, CVAR_UPDATE, TOGGLE_CONSOLE
`;
