// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3d038c4b9b675621f52024613d7b1bd2d851af53c332a8f3d746ec37a477b23b
// @sig-hash: sha256:c74655853bea94ac
// Source: Blizzard_APIDocumentationGenerated/connectiondocumentation.lua
export const _ConnectionScript = `
CancelLogout = _nil("CancelLogout")
ForceLogout = _nil("ForceLogout")
ForceQuit = _nil("ForceQuit")
GetNativeRealmID = _num("GetNativeRealmID")
GetNetIpTypes = _nil("GetNetIpTypes")
GetNetStats = _num("GetNetStats")
GetRealmID = _num("GetRealmID")
GetRealmName = _str("GetRealmName")
IsOnTournamentRealm = _bool("IsOnTournamentRealm")
Logout = _nil("Logout")
Quit = _nil("Quit")
SelectedRealmName = _str("SelectedRealmName")
`;
