// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:44ccf7d9318ef9431a7720d907bd2ae63233194809c2738197eed98331e73e6d
// @sig-hash: sha256:8938db2d9541b3c9
// Source: Blizzard_APIDocumentationGenerated/consoledocumentation.lua
export const _Console = `
CalculateStringEditDistance = _num
ConsoleEcho = _bool
ConsoleExec = _bool
ConsoleGetAllCommands = _tbl
ConsoleGetColorFromType = _nil
ConsoleGetFontHeight = _num
ConsoleIsActive = _bool
ConsolePrintAllMatchingCommands = _nil
ConsoleSetFontHeight = _nil
SetConsoleKey = _nil
-- Events: CONSOLE_CLEAR, CONSOLE_COLORS_CHANGED, CONSOLE_FONT_SIZE_CHANGED, CONSOLE_LOG, CONSOLE_MESSAGE, CVAR_UPDATE, TOGGLE_CONSOLE
`;
