// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:25abdc90fb54f9d257affe3427ae306402ee1e53089a2b2b80dc6dadd06b0fc0
// @sig-hash: sha256:abe0a39fa1625211
// Source: Blizzard_APIDocumentationGenerated/debugtoggledocumentation.lua
export const _DebugToggle = `
IsCollisionEnabled = _bool
ToggleAnimKitDisplay = _nil
ToggleCollision = _nil
ToggleCollisionDisplay = _nil
ToggleDebugAIDisplay = _nil
ToggleGravity = _nil
TogglePlayerBounds = _nil
TogglePortals = _nil
ToggleTris = _nil
`;
