// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:bbb468526c1efe64901ad5e18d0912ec567caedbe8b301d260e728e67e412702
// @sig-hash: sha256:571b734c2dd45c5c
// Source: Blizzard_APIDocumentationGenerated/expansiondocumentation.lua
export const _Expansion = `
CanUpgradeToCurrentExpansion = _bool("CanUpgradeToCurrentExpansion")
DoesCurrentLocaleSellExpansionLevels = _bool("DoesCurrentLocaleSellExpansionLevels")
GetAccountExpansionLevel = _num("GetAccountExpansionLevel")
GetClientDisplayExpansionLevel = _num("GetClientDisplayExpansionLevel")
GetCurrentRegionName = _str("GetCurrentRegionName")
GetExpansionDisplayInfo = _nil("GetExpansionDisplayInfo")
GetExpansionForLevel = _num("GetExpansionForLevel")
GetExpansionLevel = _num("GetExpansionLevel")
GetExpansionTrialInfo = _bool("GetExpansionTrialInfo")
GetMaxLevelForExpansionLevel = _num("GetMaxLevelForExpansionLevel")
GetMaxLevelForLatestExpansion = _num("GetMaxLevelForLatestExpansion")
GetMaxLevelForPlayerExpansion = _num("GetMaxLevelForPlayerExpansion")
GetMaximumExpansionLevel = _num("GetMaximumExpansionLevel")
GetMinimumExpansionLevel = _num("GetMinimumExpansionLevel")
GetNumExpansions = _num("GetNumExpansions")
GetServerExpansionLevel = _num("GetServerExpansionLevel")
GetUpgradeExpansionLevel = _num("GetUpgradeExpansionLevel")
IsDemonHunterAvailable = _bool("IsDemonHunterAvailable")
IsExpansionTrial = _bool("IsExpansionTrial")
IsTrialAccount = _bool("IsTrialAccount")
IsVeteranTrialAccount = _bool("IsVeteranTrialAccount")
SendSubscriptionInterstitialResponse = _nil("SendSubscriptionInterstitialResponse")
ShouldShowExpansionUpgradeBanner = _bool("ShouldShowExpansionUpgradeBanner")
-- Events: MAX_EXPANSION_LEVEL_UPDATED, MIN_EXPANSION_LEVEL_UPDATED, SHOW_SUBSCRIPTION_INTERSTITIAL
`;
