// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:432136d274fb7b31b740e3100ab3a806c98cebfad2a7b3c3d46ead9d3248449b
// @sig-hash: sha256:1137f9a27f24cb1a
// Source: Blizzard_APIDocumentationGenerated/expansiondocumentation.lua
export const _Expansion = `
CanUpgradeToCurrentExpansion = _bool
DoesCurrentLocaleSellExpansionLevels = _bool
GetAccountExpansionLevel = _num
GetClientDisplayExpansionLevel = _num
GetCurrentRegionName = _str
GetExpansionDisplayInfo = _nil
GetExpansionForLevel = _num
GetExpansionLevel = _num
GetExpansionTrialInfo = _bool
GetMaxLevelForExpansionLevel = _num
GetMaxLevelForLatestExpansion = _num
GetMaxLevelForPlayerExpansion = _num
GetMaximumExpansionLevel = _num
GetMinimumExpansionLevel = _num
GetNumExpansions = _num
GetServerExpansionLevel = _num
GetUpgradeExpansionLevel = _num
IsDemonHunterAvailable = _bool
IsExpansionTrial = _bool
IsTrialAccount = _bool
IsVeteranTrialAccount = _bool
SendSubscriptionInterstitialResponse = _nil
ShouldShowExpansionUpgradeBanner = _bool
-- Events: MAX_EXPANSION_LEVEL_UPDATED, MIN_EXPANSION_LEVEL_UPDATED, SHOW_SUBSCRIPTION_INTERSTITIAL
`;
