// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6e51bdca71608ab5211b00036d408ed04d09f4c0850e6daeaed2b8c931f0f5c4
// @sig-hash: sha256:c6cfd80d31463bcd
// Source: Blizzard_APIDocumentationGenerated/fontdocumentation.lua
export const _Font = `
CreateFontFamily = _nil("CreateFontFamily")
GetFontInfo = _nil("GetFontInfo")
GetFonts = _tbl("GetFonts")
`;
