// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:53acdd81bfcb11f0ae24690683e438f65425f3a8ea31a86b03848d271c7ca47a
// @sig-hash: sha256:74e8364a2c0c3271
// Source: Blizzard_APIDocumentationGenerated/fontdocumentation.lua
export const _Font = `
CreateFontFamily = _nil
GetFontInfo = _nil
GetFonts = _tbl
`;
