// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5fb3a2cf1ee30312881d67f378f4ed687fa9422026b9e3719981c9c57ecc33e6
// @sig-hash: sha256:d995a36141c8606c
// Source: Blizzard_APIDocumentationGenerated/frameapicharactermodelbasedocumentation.lua
export const _FrameAPICharacterModelBase = `
ApplySpellVisualKit = _nil
CanSetUnit = _nil
FreezeAnimation = _nil
GetDisplayInfo = _nil
GetDoBlend = _nil
GetKeepModelOnHide = _nil
HasAnimation = _nil
PlayAnimKit = _nil
RefreshCamera = _nil
RefreshUnit = _nil
SetAnimation = _nil
SetBarberShopAlternateForm = _nil
SetCamDistanceScale = _nil
SetCreature = _nil
SetDisplayInfo = _nil
SetDoBlend = _nil
SetItem = _nil
SetItemAppearance = _nil
SetKeepModelOnHide = _nil
SetPortraitZoom = _nil
SetRotation = _nil
SetUnit = _nil
StopAnimKit = _nil
ZeroCachedCenterXY = _nil
`;
