// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8cc94664190f677ab0361f110fcb56ac012b4cde36285f2ecb46b0aa358eb1b2
// @sig-hash: sha256:1ad0f746713ff66c
// Source: Blizzard_APIDocumentationGenerated/frameapitabardmodeldocumentation.lua
export const _FrameAPITabardModel = `
GetLowerBackgroundFileName = _nil
GetLowerBorderFile = _nil
GetLowerEmblemFile = _nil
GetUpperBackgroundFileName = _nil
GetUpperBorderFile = _nil
GetUpperEmblemFile = _nil
`;
