// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:be026e8fa9138629490c7777c0bf58fe70fdae84b5cd2054e170377640c51fb1
// @sig-hash: sha256:4b874822b69a35a8
// Source: Blizzard_APIDocumentationGenerated/frameapiblobdocumentation.lua
export const _FrameAPIBlob = `
DrawAll = _nil("DrawAll")
DrawBlob = _nil("DrawBlob")
DrawNone = _nil("DrawNone")
EnableMerging = _nil("EnableMerging")
EnableSmoothing = _nil("EnableSmoothing")
GetMapID = _num("GetMapID")
SetBorderAlpha = _nil("SetBorderAlpha")
SetBorderScalar = _nil("SetBorderScalar")
SetBorderTexture = _nil("SetBorderTexture")
SetFillAlpha = _nil("SetFillAlpha")
SetFillTexture = _nil("SetFillTexture")
SetMapID = _nil("SetMapID")
SetMergeThreshold = _nil("SetMergeThreshold")
SetNumSplinePoints = _nil("SetNumSplinePoints")
`;
