// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c98b3f3406b5bd6a3dfab07f0bd7994e9a08736186e3f5e45315f6a6e97d6b66
// @sig-hash: sha256:c09dba13db5b064b
// Source: Blizzard_APIDocumentationGenerated/frameapiunitpositionframedocumentation.lua
export const _FrameAPIUnitPositionFrame = `
AddUnit = _nil("AddUnit")
ClearUnits = _nil("ClearUnits")
FinalizeUnits = _nil("FinalizeUnits")
GetMouseOverUnits = _nil("GetMouseOverUnits")
GetPlayerPingScale = _num("GetPlayerPingScale")
GetUiMapID = _num("GetUiMapID")
SetPlayerPingScale = _nil("SetPlayerPingScale")
SetPlayerPingTexture = _nil("SetPlayerPingTexture")
SetUiMapID = _nil("SetUiMapID")
SetUnitColor = _nil("SetUnitColor")
StartPlayerPing = _nil("StartPlayerPing")
StopPlayerPing = _nil("StopPlayerPing")
`;
