// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:83507392b9259696ba5ece4e9a117141bf1c1b7020a6b2061f8fdb6a0ae9e2a9
// @sig-hash: sha256:277db4abc1383de4
// Source: Blizzard_APIDocumentationGenerated/frameapimodelsceneframeactordocumentation.lua
export const _FrameAPIModelSceneFrameActor = `
AttachToMount = _nil
CalculateMountScale = _nil
DetachFromMount = _nil
Dress = _nil
DressPlayerSlot = _nil
GetAutoDress = _nil
GetItemTransmogInfo = _nil
GetItemTransmogInfoList = _tbl
GetObeyHideInTransmogFlag = _nil
GetPaused = _nil
GetSheathed = _nil
GetUseTransmogChoices = _nil
GetUseTransmogSkin = _nil
IsGeoReady = _nil
IsSlotAllowed = _nil
IsSlotVisible = _nil
ReleaseFrontEndCharacterDisplays = _nil
ResetNextHandSlot = _nil
SetAutoDress = _nil
SetFrontEndLobbyModelFromDefaultCharacterDisplay = _nil
SetItemTransmogInfo = _nil
SetModelByHyperlink = _nil
SetObeyHideInTransmogFlag = _nil
SetPaused = _nil
SetSheathed = _nil
SetSheathedCategory = _nil
SetUseTransmogChoices = _nil
SetUseTransmogSkin = _nil
Undress = _nil
UndressSlot = _nil
UseUnitSheatheCategory = _nil
`;
