// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:753966067152856941853fe2207cc0631bf98c778bc8214ca094047e5ce69664
// @sig-hash: sha256:163779cae34cf5dc
// Source: Blizzard_APIDocumentationGenerated/frameapisimplecheckoutdocumentation.lua
export const _FrameAPISimpleCheckout = `
CancelOpenCheckout = _nil("CancelOpenCheckout")
ClearFocus = _nil("ClearFocus")
CloseCheckout = _nil("CloseCheckout")
CopyExternalLink = _nil("CopyExternalLink")
OpenCheckout = _bool("OpenCheckout")
OpenExternalLink = _nil("OpenExternalLink")
SetFocus = _nil("SetFocus")
SetZoom = _nil("SetZoom")
`;
