// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:97ad2822365e4ce7a90025c2af1f026fa75909186cb6304fea75f994aa2a9d3f
// @sig-hash: sha256:e7ca876c610431d5
// Source: Blizzard_APIDocumentationGenerated/frameapifogofwarframedocumentation.lua
export const _FrameAPIFogOfWarFrame = `
GetFogOfWarBackgroundAtlas = _nil("GetFogOfWarBackgroundAtlas")
GetFogOfWarBackgroundTexture = _nil("GetFogOfWarBackgroundTexture")
GetFogOfWarMaskAtlas = _nil("GetFogOfWarMaskAtlas")
GetFogOfWarMaskTexture = _nil("GetFogOfWarMaskTexture")
GetMaskScalar = _num("GetMaskScalar")
GetUiMapID = _num("GetUiMapID")
SetFogOfWarBackgroundAtlas = _nil("SetFogOfWarBackgroundAtlas")
SetFogOfWarBackgroundTexture = _nil("SetFogOfWarBackgroundTexture")
SetFogOfWarMaskAtlas = _nil("SetFogOfWarMaskAtlas")
SetFogOfWarMaskTexture = _nil("SetFogOfWarMaskTexture")
SetMaskScalar = _nil("SetMaskScalar")
SetUiMapID = _nil("SetUiMapID")
`;
