// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:82c00f158bd60d347e8ca5abf15a05458b4fd7136d7722ec854a509b97ab52ac
// @sig-hash: sha256:818c40bee8c8a6f2
// Source: Blizzard_APIDocumentationGenerated/frameapidressupmodeldocumentation.lua
export const _FrameAPIDressUpModel = `
Dress = _nil("Dress")
GetAutoDress = _bool("GetAutoDress")
GetItemTransmogInfo = _nil("GetItemTransmogInfo")
GetItemTransmogInfoList = _tbl("GetItemTransmogInfoList")
GetObeyHideInTransmogFlag = _bool("GetObeyHideInTransmogFlag")
GetSheathed = _bool("GetSheathed")
GetUseTransmogChoices = _bool("GetUseTransmogChoices")
GetUseTransmogSkin = _bool("GetUseTransmogSkin")
IsGeoReady = _bool("IsGeoReady")
IsSlotAllowed = _bool("IsSlotAllowed")
IsSlotVisible = _bool("IsSlotVisible")
SetAutoDress = _nil("SetAutoDress")
SetItemTransmogInfo = _nil("SetItemTransmogInfo")
SetObeyHideInTransmogFlag = _nil("SetObeyHideInTransmogFlag")
SetSheathed = _nil("SetSheathed")
SetUseTransmogChoices = _nil("SetUseTransmogChoices")
SetUseTransmogSkin = _nil("SetUseTransmogSkin")
TryOn = _nil("TryOn")
Undress = _nil("Undress")
UndressSlot = _nil("UndressSlot")
`;
