// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7cc2f730b4006850aea34135f491cb060c7a3e1a9b6020ef50afcae2f17b1b46
// @sig-hash: sha256:5c584a2b7e5ef286
// Source: Blizzard_APIDocumentationGenerated/frameapisimplecheckoutdocumentation.lua
export const _FrameAPISimpleCheckout = `
CancelOpenCheckout = _nil
ClearFocus = _nil
CloseCheckout = _nil
CopyExternalLink = _nil
OpenCheckout = _nil
OpenExternalLink = _nil
SetFocus = _nil
SetZoom = _nil
`;
