// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ebdae9f93b73d7bbab43d88a1dc0da108085a1c0fa195041ce6761771596394b
// @sig-hash: sha256:f31eed7acebab748
// Source: Blizzard_APIDocumentationGenerated/frameapinameplatedocumentation.lua
export const _FrameAPINamePlate = `
CanChangeHitTestPoints = _nil
ClearAllHitTestPoints = _nil
GetHitTestPoints = _tbl
SetAllHitTestPoints = _nil
SetHitTestPoints = _nil
SetStackingBoundsFrame = _nil
`;
