// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:696a7dcde9f16bdb4731a6c612d8ef0f2964367cf91abf9fdaa8bb02ec02f227
// @sig-hash: sha256:a2f379bb422afa0f
// Source: Blizzard_APIDocumentationGenerated/frameapiquestpoidocumentation.lua
export const _FrameAPIQuestPOI = `
GetNumTooltips = _nil
GetTooltipIndex = _nil
UpdateMouseOverTooltip = _nil
`;
