// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2f1c7f742a3914222ac680ccd968ece3948107bac8c6329fac52e1a079af1d70
// @sig-hash: sha256:9b7aee7ae728dd46
// Source: Blizzard_APIDocumentationGenerated/frameapitabardmodelbasedocumentation.lua
export const _FrameAPITabardModelBase = `
CanSaveTabardNow = _nil
CycleVariation = _nil
GetLowerEmblemTexture = _nil
GetUpperEmblemTexture = _nil
InitializeTabardColors = _nil
IsGuildTabard = _nil
Save = _nil
`;
