// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f0eaff1220efd6b40c0a2df100d22a7a202f5794ca8476f030012039b3243869
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/frameapiarchaeologydigsitedocumentation.lua
export const _FrameAPIArchaeologyDigSiteFrame = `

`;
