// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f82dfc066f3c72e34304a7c79ab3c7f472694035f439c85119e17c3ce4f0f869
// @sig-hash: sha256:21fbd0767894945e
// Source: Blizzard_APIDocumentationGenerated/frameapitooltipdocumentation.lua
export const _FrameAPITooltip = `
ClearPadding = _nil("ClearPadding")
GetLeftLine = _nil("GetLeftLine")
GetMinimumWidth = _num("GetMinimumWidth")
GetPadding = _num("GetPadding")
GetRightLine = _nil("GetRightLine")
SetMinimumWidth = _nil("SetMinimumWidth")
SetPadding = _nil("SetPadding")
SetText = _nil("SetText")
`;
