// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:274e04589567258accf8fdde9722d9a9865b13ac3ecb29c57f7f5bf658a25d76
// @sig-hash: sha256:ecddc2d1b40f7bae
// Source: Blizzard_APIDocumentationGenerated/frameapicharactermodelbasedocumentation.lua
export const _FrameAPICharacterModelBase = `
ApplySpellVisualKit = _nil("ApplySpellVisualKit")
CanSetUnit = _nil("CanSetUnit")
FreezeAnimation = _nil("FreezeAnimation")
GetDisplayInfo = _num("GetDisplayInfo")
GetDoBlend = _bool("GetDoBlend")
GetKeepModelOnHide = _bool("GetKeepModelOnHide")
HasAnimation = _bool("HasAnimation")
PlayAnimKit = _nil("PlayAnimKit")
RefreshCamera = _nil("RefreshCamera")
RefreshUnit = _nil("RefreshUnit")
SetAnimation = _nil("SetAnimation")
SetBarberShopAlternateForm = _nil("SetBarberShopAlternateForm")
SetCamDistanceScale = _nil("SetCamDistanceScale")
SetCreature = _nil("SetCreature")
SetDisplayInfo = _nil("SetDisplayInfo")
SetDoBlend = _nil("SetDoBlend")
SetItem = _nil("SetItem")
SetItemAppearance = _nil("SetItemAppearance")
SetKeepModelOnHide = _nil("SetKeepModelOnHide")
SetPortraitZoom = _nil("SetPortraitZoom")
SetRotation = _nil("SetRotation")
SetUnit = _bool("SetUnit")
StopAnimKit = _nil("StopAnimKit")
ZeroCachedCenterXY = _nil("ZeroCachedCenterXY")
`;
