// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:be163094d60b59e9f86079e6e7e4b63639a8db760ab62e805a6527fd1c5bf674
// @sig-hash: sha256:aa382c8666fe8099
// Source: Blizzard_APIDocumentationGenerated/frameapidressupmodeldocumentation.lua
export const _FrameAPIDressUpModel = `
Dress = _nil
GetAutoDress = _nil
GetItemTransmogInfo = _nil
GetItemTransmogInfoList = _tbl
GetObeyHideInTransmogFlag = _nil
GetSheathed = _nil
GetUseTransmogChoices = _nil
GetUseTransmogSkin = _nil
IsGeoReady = _nil
IsSlotAllowed = _nil
IsSlotVisible = _nil
SetAutoDress = _nil
SetItemTransmogInfo = _nil
SetObeyHideInTransmogFlag = _nil
SetSheathed = _nil
SetUseTransmogChoices = _nil
SetUseTransmogSkin = _nil
TryOn = _nil
Undress = _nil
UndressSlot = _nil
`;
