// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:cee9f51c043da44306626c0512c21e7ed3226d2ee157e56bf0dccbfc6ac97095
// @sig-hash: sha256:9aaea2dd133b0390
// Source: Blizzard_APIDocumentationGenerated/frameapinameplatedocumentation.lua
export const _FrameAPINamePlate = `
CanChangeHitTestPoints = _bool("CanChangeHitTestPoints")
ClearAllHitTestPoints = _nil("ClearAllHitTestPoints")
GetHitTestPoints = _tbl("GetHitTestPoints")
SetAllHitTestPoints = _nil("SetAllHitTestPoints")
SetHitTestPoints = _nil("SetHitTestPoints")
SetStackingBoundsFrame = _nil("SetStackingBoundsFrame")
`;
