// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0fe3c877dc04c87faff314748ab801cf1f06468b9ed6f7d59518e0b8b547b5ed
// @sig-hash: sha256:30371361ae97f90d
// Source: Blizzard_APIDocumentationGenerated/frameapifogofwarframedocumentation.lua
export const _FrameAPIFogOfWarFrame = `
GetFogOfWarBackgroundAtlas = _nil
GetFogOfWarBackgroundTexture = _nil
GetFogOfWarMaskAtlas = _nil
GetFogOfWarMaskTexture = _nil
GetMaskScalar = _nil
GetUiMapID = _nil
SetFogOfWarBackgroundAtlas = _nil
SetFogOfWarBackgroundTexture = _nil
SetFogOfWarMaskAtlas = _nil
SetFogOfWarMaskTexture = _nil
SetMaskScalar = _nil
SetUiMapID = _nil
`;
