// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:158b2b0497b81bc90833eb61f26b71285238967d6d1b89af084337b3c8ab72ee
// @sig-hash: sha256:e5e726ddbfab6f61
// Source: Blizzard_APIDocumentationGenerated/frameapitabardmodeldocumentation.lua
export const _FrameAPITabardModel = `
GetLowerBackgroundFileName = _nil("GetLowerBackgroundFileName")
GetLowerBorderFile = _nil("GetLowerBorderFile")
GetLowerEmblemFile = _nil("GetLowerEmblemFile")
GetUpperBackgroundFileName = _nil("GetUpperBackgroundFileName")
GetUpperBorderFile = _nil("GetUpperBorderFile")
GetUpperEmblemFile = _nil("GetUpperEmblemFile")
`;
