// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:aa89ae21f009960787f21734f0a084e0f9d54a1dbb180225a03f3120c531f939
// @sig-hash: sha256:4e00e5c2f3a48be0
// Source: Blizzard_APIDocumentationGenerated/gamecursordocumentation.lua
export const _GameCursor = `
ClearCursor = _nil
ClearCursorHoveredItem = _nil
CursorHasItem = _nil
CursorHasMacro = _nil
CursorHasMoney = _nil
CursorHasSpell = _nil
DeleteCursorItem = _nil
DropCursorMoney = _nil
EquipCursorItem = _nil
GetCursorInfo = _nil
GetCursorMoney = _nil
PickupPlayerMoney = _nil
ResetCursor = _nil
SellCursorItem = _nil
SetCursor = _nil
SetCursorByMode = _nil
SetCursorHoveredItem = _nil
SetCursorHoveredItemTradeItem = _nil
SetCursorVirtualItem = _nil
`;
