// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6f1d7d9ea23e1556dd63c27465fe53f8cc22108a040ac56f403fcbb18650af4b
// @sig-hash: sha256:e12c7c3371854c2c
// Source: Blizzard_APIDocumentationGenerated/gamecursordocumentation.lua
export const _GameCursor = `
ClearCursor = _nil("ClearCursor")
ClearCursorHoveredItem = _nil("ClearCursorHoveredItem")
CursorHasItem = _bool("CursorHasItem")
CursorHasMacro = _bool("CursorHasMacro")
CursorHasMoney = _bool("CursorHasMoney")
CursorHasSpell = _bool("CursorHasSpell")
DeleteCursorItem = _nil("DeleteCursorItem")
DropCursorMoney = _nil("DropCursorMoney")
EquipCursorItem = _nil("EquipCursorItem")
GetCursorInfo = _nil("GetCursorInfo")
GetCursorMoney = _num("GetCursorMoney")
PickupPlayerMoney = _nil("PickupPlayerMoney")
ResetCursor = _nil("ResetCursor")
SellCursorItem = _nil("SellCursorItem")
SetCursor = _bool("SetCursor")
SetCursorByMode = _bool("SetCursorByMode")
SetCursorHoveredItem = _nil("SetCursorHoveredItem")
SetCursorHoveredItemTradeItem = _nil("SetCursorHoveredItemTradeItem")
SetCursorVirtualItem = _nil("SetCursorVirtualItem")
`;
