// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5bca0ff4bbfbd4c8ac4180fda84574eb8fdb6660c9998c51d09c6a06d698d96f
// @sig-hash: sha256:6605a74ef9fa337d
// Source: Blizzard_APIDocumentationGenerated/gameuidocumentation.lua
export const _GameUI = `
SetInWorldUIVisibility = _nil
SetUIVisibility = _nil
`;
