// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5d04c117430dcc005c6bd5ae66a747545a365880754f176900e85968e543f382
// @sig-hash: sha256:5221de28055f6c08
// Source: Blizzard_APIDocumentationGenerated/gameuidocumentation.lua
export const _GameUI = `
SetInWorldUIVisibility = _nil("SetInWorldUIVisibility")
SetUIVisibility = _nil("SetUIVisibility")
`;
