// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:852cfe36026a082ac5d9255a8ed56e4bde6e933a061eb8a90432ec6222964563
// @sig-hash: sha256:658cbdc1aca0a988
// Source: Blizzard_APIDocumentationGenerated/gameerrordocumentation.lua
export const _GameError = `
GetGameMessageInfo = _nil
NotWhileDeadError = _nil
`;
