// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:357c79c43930f65e8cfba92fd5c39217925ab9556840bd0e854f70bf3ba2e232
// @sig-hash: sha256:186e72b469beb730
// Source: Blizzard_APIDocumentationGenerated/housingfixturepointframeapidocumentation.lua
export const _HousingFixturePointFrameAPI = `
HasAttachedFixture = _bool("HasAttachedFixture")
IsSelected = _bool("IsSelected")
IsValid = _bool("IsValid")
Select = _nil("Select")
SetUpdateCallback = _nil("SetUpdateCallback")
`;
