// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6e44d5bc37a76d72dcfbb26f497adafbb92bb89ecdbe2c818bfc4ddb98faf326
// @sig-hash: sha256:9d4693b983b24bba
// Source: Blizzard_APIDocumentationGenerated/housingfixturepointframeapidocumentation.lua
export const _HousingFixturePointFrameAPI = `
HasAttachedFixture = _nil
IsSelected = _nil
IsValid = _nil
Select = _nil
SetUpdateCallback = _nil
`;
