// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fa2919f39bf3cabf686819f39c5fab1c45d2f4c3cca6cfcddfb6a06af9057dcb
// @sig-hash: sha256:abfa9cb30dc61dfe
// Source: Blizzard_APIDocumentationGenerated/housinglayoutpinframeapidocumentation.lua
export const _HousingLayoutPinFrameAPI = `
CanMove = _nil
CanRemove = _nil
CanRotate = _nil
Drag = _nil
GetDoorConnectionInfo = _nil
GetPinType = _nil
GetRoomGUID = _nil
GetRoomName = _nil
IsAnyPartOfRoomSelected = _nil
IsOccupiedDoor = _nil
IsSelected = _nil
IsValid = _nil
IsValidForSelectedFloorplan = _nil
Select = _nil
SetUpdateCallback = _nil
`;
