// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:445ed1a27d5ee81d25e9bec028ac92764d7872bd0f58786376f2f05f1bd9a2e2
// @sig-hash: sha256:e3d0d7c5bf5f1c89
// Source: Blizzard_APIDocumentationGenerated/inputdocumentation.lua
export const _Input = `
GetCursorDelta = _num
GetCursorPosition = _num
GetMouseButtonClicked = _str
GetMouseButtonName = _str
GetMouseFoci = _tbl
IsAltKeyDown = _bool
IsControlKeyDown = _bool
IsKeyDown = _nil
IsLeftAltKeyDown = _bool
IsLeftControlKeyDown = _bool
IsLeftMetaKeyDown = _bool
IsLeftShiftKeyDown = _bool
IsMetaKeyDown = _bool
IsModifierKeyDown = _bool
IsMouseButtonDown = _bool
IsRightAltKeyDown = _bool
IsRightControlKeyDown = _bool
IsRightMetaKeyDown = _bool
IsRightShiftKeyDown = _bool
IsShiftKeyDown = _bool
IsUsingGamepad = _bool
IsUsingMouse = _bool
SetCursorPosition = _nil
SimulateMouseClick = _nil
SimulateMouseDown = _nil
SimulateMouseUp = _nil
SimulateMouseWheel = _nil
`;
