// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d46c53dce113ca372105809db0cf42d36ad3fb5d752629fe339c09064d336918
// @sig-hash: sha256:07bcb296cdf899de
// Source: Blizzard_APIDocumentationGenerated/instancedocumentation.lua
export const _Instance = `
CanChangePlayerDifficulty = _nil
CanMapChangeDifficulty = _nil
CanShowResetInstances = _nil
GetDifficultyInfo = _nil
GetDungeonDifficultyID = _nil
GetInstanceBootTimeRemaining = _nil
GetInstanceInfo = _nil
GetInstanceLockTimeRemaining = _nil
GetInstanceLockTimeRemainingEncounter = _nil
GetLegacyRaidDifficultyID = _nil
GetRaidDifficultyID = _nil
IsInInstance = _nil
IsLegacyDifficulty = _nil
ResetInstances = _nil
SetDungeonDifficultyID = _nil
SetLegacyRaidDifficultyID = _nil
SetRaidDifficultyID = _nil
`;
