// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7f3898b49ec50cd47be90a17c4e0a52fc76fe9b76c9c0ce6b85565541df6910e
// @sig-hash: sha256:6d8a3100343e9538
// Source: Blizzard_APIDocumentationGenerated/localedocumentation.lua
export const _Locale = `
GetAvailableLocaleInfo = _tbl
GetAvailableLocales = _str
GetCurrentRegion = _num
GetLocale = _str
GetOSLocale = _str
`;
