// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c86cb76d9534b76cf8b31a2841e0f912afc1f74a4383593e38a17a7007aed102
// @sig-hash: sha256:f4ea4adfc665073e
// Source: Blizzard_APIDocumentationGenerated/localizationdocumentation.lua
export const _Localization = `
AbbreviateLargeNumbers = _nil
AbbreviateNumbers = _nil
BreakUpLargeNumbers = _nil
CaseAccentInsensitiveParse = _nil
CreateAbbreviateConfig = _nil
DeclineName = _nil
GetDefaultAbbreviationBreakpoints = _tbl
GetNumDeclensionSets = _nil
IsEuropeanNumbers = _nil
LocalizedClassList = _nil
SetEuropeanNumbers = _nil
`;
