// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:afa645ba096138c451cea0fc0fd579bc9c2688df60a168bc89a97566ad837522
// @sig-hash: sha256:918c80872d5276c7
// Source: Blizzard_APIDocumentationGenerated/localedocumentation.lua
export const _Locale = `
GetAvailableLocaleInfo = _tbl("GetAvailableLocaleInfo")
GetAvailableLocales = _str("GetAvailableLocales")
GetCurrentRegion = _num("GetCurrentRegion")
GetLocale = _str("GetLocale")
GetOSLocale = _str("GetOSLocale")
`;
