// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ed98b35825e9bac448bad0a1c146e6b2fe3d037a7f7bc859694eed717569477b
// @sig-hash: sha256:976b10a12eee8170
// Source: Blizzard_APIDocumentationGenerated/luacurveobjectapidocumentation.lua
export const _LuaCurveObjectAPI = `
AddPoint = _nil("AddPoint")
ClearPoints = _nil("ClearPoints")
Copy = _nil("Copy")
Evaluate = _num("Evaluate")
GetPoint = _nil("GetPoint")
GetPointCount = _nil("GetPointCount")
GetPoints = _tbl("GetPoints")
RemovePoint = _nil("RemovePoint")
SetPoints = _nil("SetPoints")
SetToDefaults = _nil("SetToDefaults")
`;
