// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fc3335fe5cfb570a8a34eae64695c3ce52ea5bb22afb55fe7c54ca6be087d492
// @sig-hash: sha256:3cf0e74f4e67f54f
// Source: Blizzard_APIDocumentationGenerated/luacolorcurveobjectapidocumentation.lua
export const _LuaColorCurveObjectAPI = `
AddPoint = _nil("AddPoint")
ClearPoints = _nil("ClearPoints")
Copy = _nil("Copy")
Evaluate = _nil("Evaluate")
EvaluateUnpacked = _num("EvaluateUnpacked")
GetPoint = _nil("GetPoint")
GetPointCount = _nil("GetPointCount")
GetPoints = _tbl("GetPoints")
RemovePoint = _nil("RemovePoint")
SetPoints = _nil("SetPoints")
SetToDefaults = _nil("SetToDefaults")
`;
