// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3617c538021d66412eb5b8130436b3f4ae8041893c86edf85fd8e99e97b8bc86
// @sig-hash: sha256:0e29a903d837080d
// Source: Blizzard_APIDocumentationGenerated/luacurveobjectbaseapidocumentation.lua
export const _LuaCurveObjectBaseAPI = `
GetType = _nil
HasSecretValues = _nil
SetType = _nil
`;
