// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6332ac51d7383e4050c8b82489b672db6c45fa595385b8721c53d573f9cd8615
// @sig-hash: sha256:c77230cb187a47e0
// Source: Blizzard_APIDocumentationGenerated/luacurveobjectapidocumentation.lua
export const _LuaCurveObjectAPI = `
AddPoint = _nil
ClearPoints = _nil
Copy = _nil
Evaluate = _nil
GetPoint = _nil
GetPointCount = _nil
GetPoints = _tbl
RemovePoint = _nil
SetPoints = _nil
SetToDefaults = _nil
`;
