// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d6504482aaa76737c258c8b84232d91bbcffee891cbfd45b8cffe884452ac3e0
// @sig-hash: sha256:78d1184024511216
// Source: Blizzard_APIDocumentationGenerated/luacolorcurveobjectapidocumentation.lua
export const _LuaColorCurveObjectAPI = `
AddPoint = _nil
ClearPoints = _nil
Copy = _nil
Evaluate = _nil
EvaluateUnpacked = _nil
GetPoint = _nil
GetPointCount = _nil
GetPoints = _tbl
RemovePoint = _nil
SetPoints = _nil
SetToDefaults = _nil
`;
