// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2a363bbca85219d5398660356b5d4793df2c8f6de12fc186742db80fe66e3ee1
// @sig-hash: sha256:0349bca5ccde383b
// Source: Blizzard_APIDocumentationGenerated/mirrortimerdocumentation.lua
export const _MirrorTimer = `
GetMirrorTimerInfo = _nil
GetMirrorTimerProgress = _nil
`;
