// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:26a6453760d523cecfd78beeda9046f7371d971a0432d07d8857807675f34a2a
// @sig-hash: sha256:a341dfa50ecfb830
// Source: Blizzard_APIDocumentationGenerated/mirrortimerdocumentation.lua
export const _MirrorTimer = `
GetMirrorTimerInfo = _str("GetMirrorTimerInfo")
GetMirrorTimerProgress = _nil("GetMirrorTimerProgress")
`;
