// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:60dbdd093e80232664fb656ae7ef74f4ce7def0b0bc8da927809218c3e1210de
// @sig-hash: sha256:13b958ec0b79ab2d
// Source: Blizzard_APIDocumentationGenerated/moviedocumentation.lua
export const _Movie = `
CancelPreloadingMovie = _nil
GetMovieDownloadProgress = _nil
IsMovieLocal = _nil
IsMoviePlayable = _nil
IsMovieReadable = _nil
PreloadMovie = _nil
`;
