// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:92d1900ad638cc92b23ae7960826d02a348d331f1dbc00e6aecb7a5ee442cf8c
// @sig-hash: sha256:b82954b6af03b059
// Source: Blizzard_APIDocumentationGenerated/moviedocumentation.lua
export const _Movie = `
CancelPreloadingMovie = _nil("CancelPreloadingMovie")
GetMovieDownloadProgress = _bool("GetMovieDownloadProgress")
IsMovieLocal = _bool("IsMovieLocal")
IsMoviePlayable = _bool("IsMoviePlayable")
IsMovieReadable = _bool("IsMovieReadable")
PreloadMovie = _nil("PreloadMovie")
`;
