// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:aa7130c95e27f46e037d2f761b736f7ec8e74e9e61b5094f9f712b2f380eb54c
// @sig-hash: sha256:6c0f741362101a11
// Source: Blizzard_APIDocumentationGenerated/numericformatterapidocumentation.lua
export const _NumericFormatterAPI = `
FormatNumber = _str("FormatNumber")
`;
