// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:648bd3b9c2ec3d57e2accb0a79a70e2310595e45fc4692c1bc35957c59634c11
// @sig-hash: sha256:f9b3eded99c5175e
// Source: Blizzard_APIDocumentationGenerated/parentalcontrolsdocumentation.lua
export const _ParentalControls = `
GetSecondsUntilParentalControlsKick = _nil
`;
