// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e0a3e9d35877105681b3f4191e0b3265beb8bfc5ef7456f09d170db4c4ac0103
// @sig-hash: sha256:a5fd76552703b1e2
// Source: Blizzard_APIDocumentationGenerated/performancedocumentation.lua
export const _PerformanceScript = `
GetAddOnCPUUsage = _nil
GetAddOnMemoryUsage = _nil
GetFrameCPUUsage = _nil
ResetCPUUsage = _nil
UpdateAddOnCPUUsage = _nil
UpdateAddOnMemoryUsage = _nil
`;
