// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e9f01d05bdfcee534d7be1b142e900da7d9800b8805973a6586c39b90042d26d
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/pingpinframeapidocumentation.lua
export const _PingPinFrameAPI = `

`;
