// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8b117f3ec655fb688b7f3496ecf2267d52ba662d1f7c7305bce26d16e3a59c98
// @sig-hash: sha256:f3da9f7fca2a18ac
// Source: Blizzard_APIDocumentationGenerated/raidmarkersdocumentation.lua
export const _RaidMarkers = `
CanBeRaidTarget = _bool("CanBeRaidTarget")
ClearRaidMarker = _nil("ClearRaidMarker")
GetRaidTargetIndex = _nil("GetRaidTargetIndex")
IsRaidMarkerActive = _bool("IsRaidMarkerActive")
IsRaidMarkerSystemEnabled = _bool("IsRaidMarkerSystemEnabled")
PlaceRaidMarker = _nil("PlaceRaidMarker")
RemoveRaidTargets = _nil("RemoveRaidTargets")
SetRaidTarget = _nil("SetRaidTarget")
`;
