// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:864903aaf47cb8683860c83247d99ef9a69b231de36a5378a0ac9d9896fb3485
// @sig-hash: sha256:4e71c7eaab904867
// Source: Blizzard_APIDocumentationGenerated/screendocumentation.lua
export const _Screen = `
GetDefaultScale = _num("GetDefaultScale")
GetPhysicalScreenSize = _num("GetPhysicalScreenSize")
GetScreenDPIScale = _num("GetScreenDPIScale")
GetScreenHeight = _num("GetScreenHeight")
GetScreenWidth = _num("GetScreenWidth")
`;
