// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:12b457cd6db3ee8bb1118e5c2a273e9a0de3463e7c288f719fd51e66d13c9599
// @sig-hash: sha256:be87875e0d59db9f
// Source: Blizzard_APIDocumentationGenerated/simpleanimalphaapidocumentation.lua
export const _SimpleAnimAlphaAPI = `
GetFromAlpha = _nil
GetToAlpha = _nil
SetFromAlpha = _nil
SetToAlpha = _nil
`;
