// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:03a615746f705b18b7c9ed6eeb3ad0707f5157e5cf310f55a233e382cf032652
// @sig-hash: sha256:fd8beec7c1ff21d3
// Source: Blizzard_APIDocumentationGenerated/simplemovieapidocumentation.lua
export const _SimpleMovieAPI = `
EnableSubtitles = _nil("EnableSubtitles")
StartMovie = _bool("StartMovie")
StartMovieByName = _bool("StartMovieByName")
StopMovie = _nil("StopMovie")
`;
