// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:37a587d1b1c8d12162350e1c7b9fbde458d07074a2619e752502b4d21e24f6f5
// @sig-hash: sha256:38abcda630c3b1ed
// Source: Blizzard_APIDocumentationGenerated/simplecontrolpointapidocumentation.lua
export const _SimpleControlPointAPI = `
GetOffset = _nil
GetOrder = _nil
SetOffset = _nil
SetOrder = _nil
SetParent = _nil
`;
