// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fb59d3627cbb1976a56605972f52d33cb6368b79fb198cee039834ec20672b56
// @sig-hash: sha256:8afbcfde95996581
// Source: Blizzard_APIDocumentationGenerated/simpleanimvertexcolorapidocumentation.lua
export const _SimpleAnimVertexColorAPI = `
GetEndColor = _nil
GetStartColor = _nil
SetEndColor = _nil
SetStartColor = _nil
`;
