// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:28f57a2056f3b800571063a29a6fa763ce58f3df6ab35d455876b3701d059d44
// @sig-hash: sha256:0e89404ab0b2636e
// Source: Blizzard_APIDocumentationGenerated/simpleanimtexturecoordtranslationapidocumentation.lua
export const _SimpleAnimTextureCoordTranslationAPI = `
GetOffset = _num("GetOffset")
SetOffset = _nil("SetOffset")
`;
