// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fd7ef3be3e4da523b84d97652b79d1fdf053abf87390f3a0af4eb655f7d4019b
// @sig-hash: sha256:996392f6eafbc94a
// Source: Blizzard_APIDocumentationGenerated/simpleanimtexturecoordtranslationapidocumentation.lua
export const _SimpleAnimTextureCoordTranslationAPI = `
GetOffset = _nil
SetOffset = _nil
`;
