// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3e0030e409a2f8b4262e70ee44044b111c8a4a7424d8deeaf8c0375825aab3c3
// @sig-hash: sha256:ed90c04e331bb241
// Source: Blizzard_APIDocumentationGenerated/simplebrowserapidocumentation.lua
export const _SimpleBrowserAPI = `
ClearFocus = _nil
CopyExternalLink = _nil
DeleteCookies = _nil
NavigateBack = _nil
NavigateForward = _nil
NavigateHome = _nil
NavigateReload = _nil
NavigateStop = _nil
OpenExternalLink = _nil
OpenTicket = _nil
SetFocus = _nil
SetZoom = _nil
`;
