// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:95a990a44559251e6d76c183ce6d5bb4aec37a918a55d6a7feda78447e62b346
// @sig-hash: sha256:bef601bffdadc2f9
// Source: Blizzard_APIDocumentationGenerated/simpleanimalphaapidocumentation.lua
export const _SimpleAnimAlphaAPI = `
GetFromAlpha = _num("GetFromAlpha")
GetToAlpha = _num("GetToAlpha")
SetFromAlpha = _nil("SetFromAlpha")
SetToAlpha = _nil("SetToAlpha")
`;
