// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3070224a340a3abd1605cf3a24b5b206105f513add7aace90977b96b2d94c983
// @sig-hash: sha256:7b6c078b8555e6a3
// Source: Blizzard_APIDocumentationGenerated/simplecontrolpointapidocumentation.lua
export const _SimpleControlPointAPI = `
GetOffset = _nil("GetOffset")
GetOrder = _num("GetOrder")
SetOffset = _nil("SetOffset")
SetOrder = _nil("SetOrder")
SetParent = _nil("SetParent")
`;
