// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2c0477d5f9640d152337584258606d79e0a9f80b4d7611d9ba1e4f25a0526fb3
// @sig-hash: sha256:476c5ffecfb73a16
// Source: Blizzard_APIDocumentationGenerated/simpleanimatableobjectapidocumentation.lua
export const _SimpleAnimatableObjectAPI = `
CreateAnimationGroup = _nil
GetAnimationGroups = _nil
StopAnimating = _nil
`;
