// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:032bfd68c4a7b9c486635d0ed377992935bbab2c0ec1990405de40a624737a27
// @sig-hash: sha256:8e3bea86b1d2ffd3
// Source: Blizzard_APIDocumentationGenerated/simpleanimatableobjectapidocumentation.lua
export const _SimpleAnimatableObjectAPI = `
CreateAnimationGroup = _nil("CreateAnimationGroup")
GetAnimationGroups = _nil("GetAnimationGroups")
StopAnimating = _nil("StopAnimating")
`;
