// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:50f97102726ddb15dd3af8ed140e8e1a09d11ed328ca4d96697d2b5ea9356209
// @sig-hash: sha256:6b76e49b859cb8c5
// Source: Blizzard_APIDocumentationGenerated/simpleobjectapidocumentation.lua
export const _SimpleObjectAPI = `
ClearParentKey = _nil("ClearParentKey")
GetDebugName = _str("GetDebugName")
GetParent = _nil("GetParent")
GetParentKey = _str("GetParentKey")
SetParentKey = _nil("SetParentKey")
`;
