// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ea5377de1c3209dc24b6be41ab63bcb79e8c9d5f6d8ec78172cd726bf013e71d
// @sig-hash: sha256:14f9e8eb2fac6b4c
// Source: Blizzard_APIDocumentationGenerated/simplelineapidocumentation.lua
export const _SimpleLineAPI = `
ClearAllPoints = _nil
GetEndPoint = _nil
GetHitRectThickness = _nil
GetStartPoint = _nil
GetThickness = _nil
SetEndPoint = _nil
SetHitRectThickness = _nil
SetStartPoint = _nil
SetThickness = _nil
`;
