// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7d45a61c8d2b1f053fcfabbe68ec8a9e092235f88c333c70b3c12779eb606ef0
// @sig-hash: sha256:ef9b85d0a8c712cf
// Source: Blizzard_APIDocumentationGenerated/simplecheckboxapidocumentation.lua
export const _SimpleCheckboxAPI = `
GetChecked = _nil
GetCheckedTexture = _nil
GetDisabledCheckedTexture = _nil
SetChecked = _nil
SetCheckedTexture = _nil
SetDisabledCheckedTexture = _nil
`;
