// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f638d30706ea6a4d2cf9a4061a0aa7818081f154defe046358ff5c31991fb030
// @sig-hash: sha256:a7e410e997c437c6
// Source: Blizzard_APIDocumentationGenerated/simpleanimflipbookapidocumentation.lua
export const _SimpleAnimFlipBookAPI = `
GetFlipBookColumns = _num("GetFlipBookColumns")
GetFlipBookFrameHeight = _num("GetFlipBookFrameHeight")
GetFlipBookFrameWidth = _num("GetFlipBookFrameWidth")
GetFlipBookFrames = _num("GetFlipBookFrames")
GetFlipBookRows = _num("GetFlipBookRows")
SetFlipBookColumns = _nil("SetFlipBookColumns")
SetFlipBookFrameHeight = _nil("SetFlipBookFrameHeight")
SetFlipBookFrameWidth = _nil("SetFlipBookFrameWidth")
SetFlipBookFrames = _nil("SetFlipBookFrames")
SetFlipBookRows = _nil("SetFlipBookRows")
`;
