// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e6cc6a7b0fb2f325dfec6ffd5ead81b9d9963d66da9dc5b6696b29edbf8a4257
// @sig-hash: sha256:10d8ebc52566339d
// Source: Blizzard_APIDocumentationGenerated/simplefontapidocumentation.lua
export const _SimpleFontAPI = `
CopyFontObject = _nil
GetAlpha = _nil
GetFont = _nil
GetFontHeight = _nil
GetFontObject = _nil
GetFontObjectForAlphabet = _nil
GetIndentedWordWrap = _nil
GetJustifyH = _nil
GetJustifyV = _nil
GetShadowColor = _nil
GetShadowOffset = _nil
GetSpacing = _nil
GetTextColor = _nil
SetAlpha = _nil
SetFont = _nil
SetFontHeight = _nil
SetFontObject = _nil
SetIndentedWordWrap = _nil
SetJustifyH = _nil
SetJustifyV = _nil
SetShadowColor = _nil
SetShadowOffset = _nil
SetSpacing = _nil
SetTextColor = _nil
`;
