// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:deec8722b1ad4e7d8e0fad5d26b85498b2cc95ed85ce5ccf573dbaa3811ec30b
// @sig-hash: sha256:563f9806ba68e57a
// Source: Blizzard_APIDocumentationGenerated/simplemapsceneapidocumentation.lua
export const _SimpleMapSceneAPI = `
GetMaxCharacterSlotCount = _num("GetMaxCharacterSlotCount")
GetModelDrawLayer = _nil("GetModelDrawLayer")
GetViewInsets = _nil("GetViewInsets")
SetModelDrawLayer = _nil("SetModelDrawLayer")
SetViewInsets = _nil("SetViewInsets")
`;
