// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7a62baac1efe47800ed41e7e7eff0897ed4c29c914177388a18bc8c637d40ab6
// @sig-hash: sha256:33b334b0ed85ceee
// Source: Blizzard_APIDocumentationGenerated/simplescriptregionresizingapidocumentation.lua
export const _SimpleScriptRegionResizingAPI = `
AdjustPointsOffset = _nil
ClearAllPoints = _nil
ClearPoint = _nil
ClearPointsOffset = _nil
GetNumPoints = _nil
GetPoint = _nil
GetPointByName = _nil
SetAllPoints = _nil
SetHeight = _nil
SetPoint = _nil
SetPointsOffset = _nil
SetSize = _nil
SetWidth = _nil
`;
