// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3786dd60d1498a18f64fb647b09aa55e162aa2e0e2a2c90187a9f9f0c1563f8a
// @sig-hash: sha256:e44175f01b7903eb
// Source: Blizzard_APIDocumentationGenerated/simplestatusbarapidocumentation.lua
export const _SimpleStatusBarAPI = `
GetFillStyle = _nil("GetFillStyle")
GetInterpolatedValue = _num("GetInterpolatedValue")
GetMinMaxValues = _num("GetMinMaxValues")
GetOrientation = _nil("GetOrientation")
GetReverseFill = _bool("GetReverseFill")
GetRotatesTexture = _bool("GetRotatesTexture")
GetStatusBarColor = _num("GetStatusBarColor")
GetStatusBarDesaturation = _nil("GetStatusBarDesaturation")
GetStatusBarTexture = _nil("GetStatusBarTexture")
GetTimerDuration = _nil("GetTimerDuration")
GetValue = _num("GetValue")
IsInterpolating = _bool("IsInterpolating")
IsStatusBarDesaturated = _bool("IsStatusBarDesaturated")
SetColorFill = _nil("SetColorFill")
SetFillStyle = _nil("SetFillStyle")
SetMinMaxValues = _nil("SetMinMaxValues")
SetOrientation = _nil("SetOrientation")
SetReverseFill = _nil("SetReverseFill")
SetRotatesTexture = _nil("SetRotatesTexture")
SetStatusBarColor = _nil("SetStatusBarColor")
SetStatusBarDesaturated = _nil("SetStatusBarDesaturated")
SetStatusBarDesaturation = _nil("SetStatusBarDesaturation")
SetStatusBarTexture = _bool("SetStatusBarTexture")
SetTimerDuration = _nil("SetTimerDuration")
SetToTargetValue = _nil("SetToTargetValue")
SetValue = _nil("SetValue")
`;
