// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:902507b5498860474e81aae0111a32b65be6bc2ad3dff996aa23a51fc6f38ec0
// @sig-hash: sha256:e32873b6adcb8aba
// Source: Blizzard_APIDocumentationGenerated/simplesliderapidocumentation.lua
export const _SimpleSliderAPI = `
Disable = _nil
Enable = _nil
GetMinMaxValues = _nil
GetObeyStepOnDrag = _nil
GetOrientation = _nil
GetStepsPerPage = _nil
GetThumbTexture = _nil
GetValue = _nil
GetValueStep = _nil
IsDraggingThumb = _nil
IsEnabled = _nil
SetEnabled = _nil
SetMinMaxValues = _nil
SetObeyStepOnDrag = _nil
SetOrientation = _nil
SetStepsPerPage = _nil
SetThumbTexture = _nil
SetValue = _nil
SetValueStep = _nil
`;
