// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9991a4f56000ec7047ff869220339069d5b386b1061033b852b5a6a5732f88b7
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/simplemasktextureapidocumentation.lua
export const _SimpleMaskTextureAPI = `

`;
