// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ba6fdafece3c752fed66b05106b8047c1c3640deca9adc86f2c717f8ad29e090
// @sig-hash: sha256:8b911426ce467e53
// Source: Blizzard_APIDocumentationGenerated/simplemovieapidocumentation.lua
export const _SimpleMovieAPI = `
EnableSubtitles = _nil
StartMovie = _nil
StartMovieByName = _nil
StopMovie = _nil
`;
