// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8078798fc02133da003b7c47b58f6d7f22bcbcf0f39d5cee94b2c29ea4d8aded
// @sig-hash: sha256:69f9e530fce64a4a
// Source: Blizzard_APIDocumentationGenerated/simpleoffscreenframeapidocumentation.lua
export const _SimpleOffScreenFrameAPI = `
ApplySnapshot = _nil
Flush = _nil
GetMaxSnapshots = _nil
IsSnapshotValid = _nil
SetMaxSnapshots = _nil
TakeSnapshot = _nil
TestPrintToFile = _nil
UsesNPOT = _nil
`;
