// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7e4bedbfd28e445cb271df40dae69db0578aae05887960d53d7f755af855d245
// @sig-hash: sha256:244b2ccdaec2768e
// Source: Blizzard_APIDocumentationGenerated/simplemodelffxapidocumentation.lua
export const _SimpleModelFFXAPI = `
AddCharacterLight = _nil
AddLight = _nil
AddPetLight = _nil
ResetLights = _nil
`;
