// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:37b5985b6074c6c7f1dd0eb1461fddbca1d58bcf3568635359a89d5bb06943c7
// @sig-hash: sha256:422875d782f894e9
// Source: Blizzard_APIDocumentationGenerated/simplemapsceneapidocumentation.lua
export const _SimpleMapSceneAPI = `
GetMaxCharacterSlotCount = _nil
GetModelDrawLayer = _nil
GetViewInsets = _nil
SetModelDrawLayer = _nil
SetViewInsets = _nil
`;
