// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:dfa8a009e77d3273503322183376a27cbad77b699af271db546bbb823bbe48c3
// @sig-hash: sha256:88bec2cab2f330c4
// Source: Blizzard_APIDocumentationGenerated/simpleanimscaleapidocumentation.lua
export const _SimpleAnimScaleAPI = `
GetOrigin = _nil("GetOrigin")
GetScale = _num("GetScale")
GetScaleFrom = _num("GetScaleFrom")
GetScaleTo = _num("GetScaleTo")
SetOrigin = _nil("SetOrigin")
SetScale = _nil("SetScale")
SetScaleFrom = _nil("SetScaleFrom")
SetScaleTo = _nil("SetScaleTo")
`;
