// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7691d39a6bcff06c0e376370937c3fe6daab4ae077c4db87d473ef6ea5617ab5
// @sig-hash: sha256:8c08590b1623ed26
// Source: Blizzard_APIDocumentationGenerated/simpleanimpathapidocumentation.lua
export const _SimpleAnimPathAPI = `
CreateControlPoint = _nil("CreateControlPoint")
GetControlPoints = _nil("GetControlPoints")
GetCurveType = _nil("GetCurveType")
GetMaxControlPointOrder = _num("GetMaxControlPointOrder")
SetCurveType = _nil("SetCurveType")
`;
