// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:00d112c0771c8aff9609d6515c1743c98aa52b3e0b849e1f256241fd5dd03fa0
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/simpleanimscalelineapidocumentation.lua
export const _SimpleAnimScaleLineAPI = `

`;
