// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ae1888aa8f9e91798c8121011d0d2c5c236028ab9b20bdcf75849168844f412c
// @sig-hash: sha256:7a6eb38f217de089
// Source: Blizzard_APIDocumentationGenerated/simpleframescriptobjectapidocumentation.lua
export const _SimpleFrameScriptObjectAPI = `
GetName = _str("GetName")
GetObjectType = _str("GetObjectType")
HasAnySecretAspect = _bool("HasAnySecretAspect")
HasSecretAspect = _bool("HasSecretAspect")
HasSecretValues = _bool("HasSecretValues")
IsForbidden = _bool("IsForbidden")
IsObjectType = _bool("IsObjectType")
IsPreventingSecretValues = _bool("IsPreventingSecretValues")
SetForbidden = _nil("SetForbidden")
SetToDefaults = _nil("SetToDefaults")
`;
