// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:36c66c54ae8d804ec9e50cc8f2c9f49b025f7e9cc8ec4185e6ad0fa82e4764d2
// @sig-hash: sha256:ef53571091eacaf8
// Source: Blizzard_APIDocumentationGenerated/simpleanimrotationapidocumentation.lua
export const _SimpleAnimRotationAPI = `
GetDegrees = _nil
GetOrigin = _nil
GetRadians = _nil
SetDegrees = _nil
SetOrigin = _nil
SetRadians = _nil
`;
