// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f2c24f8e12c00980c447907c90f9d582eb6eebe2254ff32ccb66653d60a4f0d6
// @sig-hash: sha256:5c00435537c738a2
// Source: Blizzard_APIDocumentationGenerated/simplecheckboxapidocumentation.lua
export const _SimpleCheckboxAPI = `
GetChecked = _bool("GetChecked")
GetCheckedTexture = _nil("GetCheckedTexture")
GetDisabledCheckedTexture = _nil("GetDisabledCheckedTexture")
SetChecked = _nil("SetChecked")
SetCheckedTexture = _nil("SetCheckedTexture")
SetDisabledCheckedTexture = _nil("SetDisabledCheckedTexture")
`;
