// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:697a3eeb4193f2b04e8d69008106c1d71e8ca886350c145ca93f18c899270e34
// @sig-hash: sha256:17814f7fa1a2cbc2
// Source: Blizzard_APIDocumentationGenerated/simplehtmlapidocumentation.lua
export const _SimpleHTMLAPI = `
GetContentHeight = _nil("GetContentHeight")
GetFont = _str("GetFont")
GetFontObject = _nil("GetFontObject")
GetHyperlinkFormat = _str("GetHyperlinkFormat")
GetIndentedWordWrap = _bool("GetIndentedWordWrap")
GetJustifyH = _nil("GetJustifyH")
GetJustifyV = _nil("GetJustifyV")
GetShadowColor = _num("GetShadowColor")
GetShadowOffset = _num("GetShadowOffset")
GetSpacing = _nil("GetSpacing")
GetTextColor = _num("GetTextColor")
GetTextData = _tbl("GetTextData")
SetFont = _nil("SetFont")
SetFontObject = _nil("SetFontObject")
SetHyperlinkFormat = _nil("SetHyperlinkFormat")
SetIndentedWordWrap = _nil("SetIndentedWordWrap")
SetJustifyH = _nil("SetJustifyH")
SetJustifyV = _nil("SetJustifyV")
SetShadowColor = _nil("SetShadowColor")
SetShadowOffset = _nil("SetShadowOffset")
SetSpacing = _nil("SetSpacing")
SetText = _nil("SetText")
SetTextColor = _nil("SetTextColor")
`;
