// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:69db715181520b66b3cbfe2783fb58766edaba1d14c221a9efa9eecc0c05c898
// @sig-hash: sha256:ed05dd89f57bae57
// Source: Blizzard_APIDocumentationGenerated/simpleanimtranslationapidocumentation.lua
export const _SimpleAnimTranslationAPI = `
GetOffset = _nil("GetOffset")
SetOffset = _nil("SetOffset")
`;
