// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:79817943812a83eba15ba9e2be31c37ac0d666e5627b7e27934e23f3b854425d
// @sig-hash: sha256:8db5f5ed92648c5d
// Source: Blizzard_APIDocumentationGenerated/simplecolorselectapidocumentation.lua
export const _SimpleColorSelectAPI = `
ClearColorWheelTexture = _nil
GetColorAlpha = _nil
GetColorAlphaTexture = _nil
GetColorAlphaThumbTexture = _nil
GetColorHSV = _nil
GetColorRGB = _nil
GetColorValueTexture = _nil
GetColorValueThumbTexture = _nil
GetColorWheelTexture = _nil
GetColorWheelThumbTexture = _nil
SetColorAlpha = _nil
SetColorAlphaTexture = _nil
SetColorAlphaThumbTexture = _nil
SetColorHSV = _nil
SetColorRGB = _nil
SetColorValueTexture = _nil
SetColorValueThumbTexture = _nil
SetColorWheelTexture = _nil
SetColorWheelThumbTexture = _nil
`;
