// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f72024431d58d1181b163562a9061fd7ed976dc9955d1cf57ff71e98b2ba33d9
// @sig-hash: sha256:299cd04ad63bb55a
// Source: Blizzard_APIDocumentationGenerated/simpletextureapidocumentation.lua
export const _SimpleTextureAPI = `
AddMaskTexture = _nil
GetMaskTexture = _nil
GetNumMaskTextures = _nil
RemoveMaskTexture = _nil
`;
