// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c249da75395b2a2ee3267e1b5e242175a6f9e527667b9e68b18dc83cd3aa2c79
// @sig-hash: sha256:9f81508b64e01761
// Source: Blizzard_APIDocumentationGenerated/simpleframescriptobjectapidocumentation.lua
export const _SimpleFrameScriptObjectAPI = `
GetName = _nil
GetObjectType = _nil
HasAnySecretAspect = _nil
HasSecretAspect = _nil
HasSecretValues = _nil
IsForbidden = _nil
IsObjectType = _nil
IsPreventingSecretValues = _nil
SetForbidden = _nil
SetToDefaults = _nil
`;
