// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c0a9f6fe2f58b05f07760a5e99b72fe3253f23dce1cc05db58fec12590d3e540
// @sig-hash: sha256:25e9888b67ba1771
// Source: Blizzard_APIDocumentationGenerated/simplefontapidocumentation.lua
export const _SimpleFontAPI = `
CopyFontObject = _nil("CopyFontObject")
GetAlpha = _nil("GetAlpha")
GetFont = _str("GetFont")
GetFontHeight = _num("GetFontHeight")
GetFontObject = _nil("GetFontObject")
GetFontObjectForAlphabet = _nil("GetFontObjectForAlphabet")
GetIndentedWordWrap = _bool("GetIndentedWordWrap")
GetJustifyH = _nil("GetJustifyH")
GetJustifyV = _nil("GetJustifyV")
GetShadowColor = _num("GetShadowColor")
GetShadowOffset = _num("GetShadowOffset")
GetSpacing = _nil("GetSpacing")
GetTextColor = _num("GetTextColor")
SetAlpha = _nil("SetAlpha")
SetFont = _nil("SetFont")
SetFontHeight = _nil("SetFontHeight")
SetFontObject = _nil("SetFontObject")
SetIndentedWordWrap = _nil("SetIndentedWordWrap")
SetJustifyH = _nil("SetJustifyH")
SetJustifyV = _nil("SetJustifyV")
SetShadowColor = _nil("SetShadowColor")
SetShadowOffset = _nil("SetShadowOffset")
SetSpacing = _nil("SetSpacing")
SetTextColor = _nil("SetTextColor")
`;
