// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f5a5c85df6a4e22d9d3c70c88d6e3602013df62af98a848f28a6a817fc59dfe8
// @sig-hash: sha256:4420cc797eb0f6bf
// Source: Blizzard_APIDocumentationGenerated/simpleoffscreenframeapidocumentation.lua
export const _SimpleOffScreenFrameAPI = `
ApplySnapshot = _bool("ApplySnapshot")
Flush = _nil("Flush")
GetMaxSnapshots = _num("GetMaxSnapshots")
IsSnapshotValid = _bool("IsSnapshotValid")
SetMaxSnapshots = _nil("SetMaxSnapshots")
TakeSnapshot = _nil("TakeSnapshot")
TestPrintToFile = _bool("TestPrintToFile")
UsesNPOT = _nil("UsesNPOT")
`;
