// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e03219fa2b80bbb5661140762ff379cd6777e4ad51d63f9f0b166c8e4333d0e4
// @sig-hash: sha256:b9783ca92dd7f487
// Source: Blizzard_APIDocumentationGenerated/simpleanimflipbookapidocumentation.lua
export const _SimpleAnimFlipBookAPI = `
GetFlipBookColumns = _nil
GetFlipBookFrameHeight = _nil
GetFlipBookFrameWidth = _nil
GetFlipBookFrames = _nil
GetFlipBookRows = _nil
SetFlipBookColumns = _nil
SetFlipBookFrameHeight = _nil
SetFlipBookFrameWidth = _nil
SetFlipBookFrames = _nil
SetFlipBookRows = _nil
`;
