// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:63d65a351cdf3d8bf44cc679c39bfe6641fe456cf96eb4761d8c20fd9a96f3fa
// @sig-hash: sha256:a0571c20a0db4772
// Source: Blizzard_APIDocumentationGenerated/simplescriptregionresizingapidocumentation.lua
export const _SimpleScriptRegionResizingAPI = `
AdjustPointsOffset = _nil("AdjustPointsOffset")
ClearAllPoints = _nil("ClearAllPoints")
ClearPoint = _nil("ClearPoint")
ClearPointsOffset = _nil("ClearPointsOffset")
GetNumPoints = _num("GetNumPoints")
GetPoint = _nil("GetPoint")
GetPointByName = _nil("GetPointByName")
SetAllPoints = _nil("SetAllPoints")
SetHeight = _nil("SetHeight")
SetPoint = _nil("SetPoint")
SetPointsOffset = _nil("SetPointsOffset")
SetSize = _nil("SetSize")
SetWidth = _nil("SetWidth")
`;
