// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1792cdd98b3dc40502594d36153eb2f843c358face91c39cf731328c39905e35
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/simpleanimtranslationlineapidocumentation.lua
export const _SimpleAnimTranslationLineAPI = `

`;
