// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6c33eeb6654a6592c66ed510bab27c7fa7a67b97e9ed5d0410e3a273988c06eb
// @sig-hash: sha256:5f0d3380e140117f
// Source: Blizzard_APIDocumentationGenerated/simpleregionapidocumentation.lua
export const _SimpleRegionAPI = `
GetAlpha = _nil("GetAlpha")
GetDrawLayer = _nil("GetDrawLayer")
GetEffectiveScale = _num("GetEffectiveScale")
GetScale = _num("GetScale")
GetVertexColor = _num("GetVertexColor")
IsIgnoringParentAlpha = _bool("IsIgnoringParentAlpha")
IsIgnoringParentScale = _bool("IsIgnoringParentScale")
IsObjectLoaded = _bool("IsObjectLoaded")
SetAlpha = _nil("SetAlpha")
SetAlphaFromBoolean = _nil("SetAlphaFromBoolean")
SetDrawLayer = _nil("SetDrawLayer")
SetIgnoreParentAlpha = _nil("SetIgnoreParentAlpha")
SetIgnoreParentScale = _nil("SetIgnoreParentScale")
SetScale = _nil("SetScale")
SetVertexColor = _nil("SetVertexColor")
SetVertexColorFromBoolean = _nil("SetVertexColorFromBoolean")
`;
