// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d9efaed077e358c10b05dafca1b98d5ec47629ffbdb0860111d712373608ef20
// @sig-hash: sha256:435a66f424f47269
// Source: Blizzard_APIDocumentationGenerated/slashcommanddocumentation.lua
export const _SlashCommand = `
AreDangerousScriptsAllowed = _bool("AreDangerousScriptsAllowed")
SetAllowDangerousScripts = _nil("SetAllowDangerousScripts")
`;
