// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:341dade8e1ad7329ec5b4fcfc95a67b63d05cd93ad5101a84c7cd333e9396adf
// @sig-hash: sha256:58f4e05f9bc9beaa
// Source: Blizzard_APIDocumentationGenerated/slashcommanddocumentation.lua
export const _SlashCommand = `
AreDangerousScriptsAllowed = _nil
SetAllowDangerousScripts = _nil
`;
