// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0088b46f3c8c3e4bca6a652da1a5798989b1c3611451e0b9b89ed67a05d93730
// @sig-hash: sha256:196ebe4376ff7407
// Source: Blizzard_APIDocumentationGenerated/specializationshareddocumentation.lua
export const _SpecializationShared = `
GetSpecializationInfoForClassID = _num("GetSpecializationInfoForClassID")
GetSpecializationInfoForSpecID = _num("GetSpecializationInfoForSpecID")
GetSpecializationNameForSpecID = _nil("GetSpecializationNameForSpecID")
HasLootSpecializations = _bool("HasLootSpecializations")
`;
