// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9a82286e3e127a8cf22ed074e952d1061831775208001ded227532e6b1562219
// @sig-hash: sha256:6f80ca9ffa1be7c6
// Source: Blizzard_APIDocumentationGenerated/streamingdocumentation.lua
export const _Streaming = `
GetAvailableBandwidth = _num("GetAvailableBandwidth")
GetBackgroundLoadingStatus = _num("GetBackgroundLoadingStatus")
GetDownloadedPercentage = _num("GetDownloadedPercentage")
GetFileStreamingStatus = _num("GetFileStreamingStatus")
`;
