// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1cc0cadfecc1626c8b6c9db21edd011be81ec575b0ae3447f65356f42d0643a9
// @sig-hash: sha256:5bde8c29c17a1ac3
// Source: Blizzard_APIDocumentationGenerated/systemtimedocumentation.lua
export const _SystemTime = `
GetGameTime = _num("GetGameTime")
GetLocalGameTime = _num("GetLocalGameTime")
GetServerTime = _num("GetServerTime")
GetSessionTime = _num("GetSessionTime")
GetTickTime = _num("GetTickTime")
GetTime = _num("GetTime")
IsUsingFixedTimeStep = _bool("IsUsingFixedTimeStep")
`;
