// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b0f6a65338eba5ab554ffa32bff791ff0912e3ea9f4a2e32093102729fc23adf
// @sig-hash: sha256:3dd28a91248269cd
// Source: Blizzard_APIDocumentationGenerated/systemtimedocumentation.lua
export const _SystemTime = `
GetGameTime = _num
GetLocalGameTime = _num
GetServerTime = _num
GetSessionTime = _num
GetTickTime = _num
GetTime = _num
IsUsingFixedTimeStep = _bool
`;
