// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:eb594302bf31a6c6b1a8e51dd591ad0e32cc027cffefc5c455758696e61b29b8
// @sig-hash: sha256:a8c5fd82ba88c445
// Source: Blizzard_APIDocumentationGenerated/targetscriptdocumentation.lua
export const _TargetScript = `
AssistUnit = _nil("AssistUnit")
AttackTarget = _nil("AttackTarget")
ClearFocus = _nil("ClearFocus")
ClearTarget = _bool("ClearTarget")
FocusUnit = _nil("FocusUnit")
IsTargetLoose = _bool("IsTargetLoose")
TargetDirectionEnemy = _nil("TargetDirectionEnemy")
TargetDirectionFinished = _nil("TargetDirectionFinished")
TargetDirectionFriend = _nil("TargetDirectionFriend")
TargetLastEnemy = _nil("TargetLastEnemy")
TargetLastFriend = _nil("TargetLastFriend")
TargetLastTarget = _nil("TargetLastTarget")
TargetNearest = _nil("TargetNearest")
TargetNearestEnemy = _nil("TargetNearestEnemy")
TargetNearestEnemyPlayer = _nil("TargetNearestEnemyPlayer")
TargetNearestFriend = _nil("TargetNearestFriend")
TargetNearestFriendPlayer = _nil("TargetNearestFriendPlayer")
TargetNearestPartyMember = _nil("TargetNearestPartyMember")
TargetNearestRaidMember = _nil("TargetNearestRaidMember")
TargetPriorityHighlightEnd = _nil("TargetPriorityHighlightEnd")
TargetPriorityHighlightStart = _nil("TargetPriorityHighlightStart")
TargetToggle = _nil("TargetToggle")
TargetUnit = _nil("TargetUnit")
`;
