// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:50784e3cb1a8106e406e98213b95406d45b7819dc33eddb2493d9d6049fe4282
// @sig-hash: sha256:f61a6b5ea1dc5adf
// Source: Blizzard_APIDocumentationGenerated/titledocumentation.lua
export const _Title = `
GetCurrentTitle = _nil
GetNumTitles = _nil
GetTitleName = _nil
IsTitleKnown = _nil
SetCurrentTitle = _nil
`;
