// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ec7f4f9e58e5c1a4bfdc4edcd0a4dac6cd4a9744101a5d7016151bdab0333ae6
// @sig-hash: sha256:f9cd27c6947efc03
// Source: Blizzard_APIDocumentationGenerated/titledocumentation.lua
export const _Title = `
GetCurrentTitle = _num("GetCurrentTitle")
GetNumTitles = _num("GetNumTitles")
GetTitleName = _str("GetTitleName")
IsTitleKnown = _bool("IsTitleKnown")
SetCurrentTitle = _nil("SetCurrentTitle")
`;
