// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:037302989caa64e44a005ada164454c89c9c0dcbf82e80ff42254a4cf16550de
// @sig-hash: sha256:a5f14af523b82604
// Source: Blizzard_APIDocumentationGenerated/totemdocumentation.lua
export const _Totem = `
DestroyTotem = _nil("DestroyTotem")
GetNumTotemSlots = _num("GetNumTotemSlots")
GetTotemCannotDismiss = _nil("GetTotemCannotDismiss")
GetTotemDuration = _nil("GetTotemDuration")
GetTotemInfo = _bool("GetTotemInfo")
GetTotemTimeLeft = _nil("GetTotemTimeLeft")
TargetTotem = _nil("TargetTotem")
`;
