// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:990ebad303e03e4cdeb58a6b5e5f1d969e973b4301271789e522edc2fa1042b5
// @sig-hash: sha256:bc1eaecfe229b5a4
// Source: Blizzard_APIDocumentationGenerated/unitroledocumentation.lua
export const _UnitRole = `
AreClassRolesSoftSuggestions = _bool("AreClassRolesSoftSuggestions")
CanShowSetRoleButton = _bool("CanShowSetRoleButton")
InitiateRolePoll = _bool("InitiateRolePoll")
UnitGetAvailableRoles = _bool("UnitGetAvailableRoles")
UnitSetRole = _bool("UnitSetRole")
UnitSetRoleEnum = _bool("UnitSetRoleEnum")
-- Events: ROLE_CHANGED_INFORM, ROLE_POLL_BEGIN
`;
