// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7ba4e75dd1c50f42941dd8f015a4d1b57f1bf22d24d28f9458311d7770d6f9aa
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/wowsurveyconstantsdocumentation.lua
export const _Unknown = `

`;
