// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d8a4718e596f52d7ea97726fcde49d9f75ea0b7269848f5b261a3209e377d5eb
// @sig-hash: sha256:1041ed2505698e7c
// Source: Blizzard_APIDocumentationGenerated/urldocumentation.lua
export const _URL = `
LaunchURL = _nil("LaunchURL")
LoadURLIndex = _nil("LoadURLIndex")
`;
