// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:25619fc0795507860831f1c3670f5171f9134747753c64c4d6324558f3e8016b
// @sig-hash: sha256:9468264a2f0ac997
// Source: Blizzard_APIDocumentationGenerated/zonescriptdocumentation.lua
export const _ZoneScript = `
GetAreaText = _str
GetMinimapZoneText = _str
GetRealZoneText = _str
GetSubZoneText = _str
GetZoneText = _str
`;
