// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1d3265adf4a089ce086e8334926418e9e673e913a233270ae1cd6e014af8cf42
// @sig-hash: sha256:9595b7736370d781
// Source: Blizzard_APIDocumentationGenerated/zonescriptdocumentation.lua
export const _ZoneScript = `
GetAreaText = _str("GetAreaText")
GetMinimapZoneText = _str("GetMinimapZoneText")
GetRealZoneText = _str("GetRealZoneText")
GetSubZoneText = _str("GetSubZoneText")
GetZoneText = _str("GetZoneText")
`;
