// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9c61c232ecff64fc771c457394b5584c0ffb25899a0ea57d116f72762ce08add
// @sig-hash: sha256:388f2cd23c859c31
// Source: Blizzard_APIDocumentationGenerated/achievementinfodocumentation.lua
export const C_AchievementInfo = `
if C_AchievementInfo == nil then C_AchievementInfo = {} end
C_AchievementInfo.AreGuildAchievementsEnabled = _bool("C_AchievementInfo.AreGuildAchievementsEnabled")
C_AchievementInfo.GetRewardItemID = _nil("C_AchievementInfo.GetRewardItemID")
C_AchievementInfo.GetSupercedingAchievements = _tbl("C_AchievementInfo.GetSupercedingAchievements")
C_AchievementInfo.IsGuildAchievement = _bool("C_AchievementInfo.IsGuildAchievement")
C_AchievementInfo.IsValidAchievement = _bool("C_AchievementInfo.IsValidAchievement")
C_AchievementInfo.SetPortraitTexture = _nil("C_AchievementInfo.SetPortraitTexture")
-- Events: ACHIEVEMENT_EARNED, ACHIEVEMENT_PLAYER_NAME, ACHIEVEMENT_SEARCH_UPDATED, CRITERIA_COMPLETE, CRITERIA_EARNED, CRITERIA_UPDATE, INSPECT_ACHIEVEMENT_READY, RECEIVED_ACHIEVEMENT_LIST, RECEIVED_ACHIEVEMENT_MEMBER_LIST, TRACKED_ACHIEVEMENT_LIST_CHANGED, TRACKED_ACHIEVEMENT_UPDATE
`;
