// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ce7e7e86cf491987c2ee07646514c5794b70783637f0dd20bb46de6c8ce937c8
// @sig-hash: sha256:dd730f0bee732f75
// Source: Blizzard_APIDocumentationGenerated/achievementtelemetrydocumentation.lua
export const C_AchievementTelemetry = `
if C_AchievementTelemetry == nil then C_AchievementTelemetry = {} end
C_AchievementTelemetry.LinkAchievementInClub = _nil
C_AchievementTelemetry.LinkAchievementInWhisper = _nil
C_AchievementTelemetry.ShowAchievements = _nil
`;
