// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9b1096f13120b17709b05b21eacdb99e291e008d95860e103788568916381a72
// @sig-hash: sha256:a2bf351d5a570f0b
// Source: Blizzard_APIDocumentationGenerated/accountinfodocumentation.lua
export const C_AccountInfo = `
if C_AccountInfo == nil then C_AccountInfo = {} end
C_AccountInfo.GetIDFromBattleNetAccountGUID = _nil
C_AccountInfo.IsGUIDBattleNetAccountType = _nil
C_AccountInfo.IsGUIDRelatedToLocalAccount = _nil
`;
