// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:815e53a60bdbcc9e962e1ef57a9e98c223f78701d7e185eefa2878c5bbac5fdb
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/accessibilityoptionsdocumentation.lua
export const C_AccessibilityOptions = `
if C_AccessibilityOptions == nil then C_AccessibilityOptions = {} end
`;
