// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b311cc67fcec33ab5d6343811a0fda3c3e057aa79d6ee89f6618f6d9fa07e24b
// @sig-hash: sha256:49ff44efd7571168
// Source: Blizzard_APIDocumentationGenerated/achievementtelemetrydocumentation.lua
export const C_AchievementTelemetry = `
if C_AchievementTelemetry == nil then C_AchievementTelemetry = {} end
C_AchievementTelemetry.LinkAchievementInClub = _nil("C_AchievementTelemetry.LinkAchievementInClub")
C_AchievementTelemetry.LinkAchievementInWhisper = _nil("C_AchievementTelemetry.LinkAchievementInWhisper")
C_AchievementTelemetry.ShowAchievements = _nil("C_AchievementTelemetry.ShowAchievements")
`;
