// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b57240447ab3d0961300a166eb652103d8be761757357d4193247f1edc676490
// @sig-hash: sha256:91fca630885eeeed
// Source: Blizzard_APIDocumentationGenerated/accountinfodocumentation.lua
export const C_AccountInfo = `
if C_AccountInfo == nil then C_AccountInfo = {} end
C_AccountInfo.GetIDFromBattleNetAccountGUID = _num("C_AccountInfo.GetIDFromBattleNetAccountGUID")
C_AccountInfo.IsGUIDBattleNetAccountType = _bool("C_AccountInfo.IsGUIDBattleNetAccountType")
C_AccountInfo.IsGUIDRelatedToLocalAccount = _bool("C_AccountInfo.IsGUIDRelatedToLocalAccount")
`;
