// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:761c7fc5811f71acc2c45d4d26831955673f5b27d49c6494a05cb0590a0c9b7e
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/accessibilityoptionsdocumentation.lua
export const C_AccessibilityOptions = `
if C_AccessibilityOptions == nil then C_AccessibilityOptions = {} end
`;
