// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d075b59a6c491e9cce4dec8316be13f928a491f3ba42d876b4351b138add586e
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/adventurejournaldocumentation.lua
export const C_AdventureJournal = `
if C_AdventureJournal == nil then C_AdventureJournal = {} end
-- Events: AJ_DUNGEON_ACTION, AJ_OPEN, AJ_OPEN_COLLECTIONS_ACTION, AJ_PVE_LFG_ACTION, AJ_PVP_ACTION, AJ_PVP_LFG_ACTION, AJ_PVP_RBG_ACTION, AJ_PVP_SKIRMISH_ACTION, AJ_PVP_SPECIAL_BG_ACTION, AJ_PVP_TRAINING_GROUNDS_ACTION, AJ_QUEST_LOG_OPEN, AJ_RAID_ACTION, AJ_REFRESH_DISPLAY, AJ_REWARD_DATA_RECEIVED
`;
