// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8ec7b6ce07137cf322a9c2b848dbbfdba2ee7ba795367c52d0c3ac22a084c6bd
// @sig-hash: sha256:128c347a16197650
// Source: Blizzard_APIDocumentationGenerated/adventuremapdocumentation.lua
export const C_AdventureMap = `
if C_AdventureMap == nil then C_AdventureMap = {} end
C_AdventureMap.GetAdventureMapTextureKit = _nil
C_AdventureMap.GetQuestPortraitInfo = _tbl
-- Events: ADVENTURE_MAP_CLOSE, ADVENTURE_MAP_OPEN, ADVENTURE_MAP_QUEST_UPDATE, ADVENTURE_MAP_UPDATE_INSETS, ADVENTURE_MAP_UPDATE_POIS
`;
