// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fc633341c70580b4ce5821efb6b2381b844bb8c89da8828cc8fa872ac7457611
// @sig-hash: sha256:61be1f9ca7e77dfe
// Source: Blizzard_APIDocumentationGenerated/addonsdocumentation.lua
export const C_AddOns = `
if C_AddOns == nil then C_AddOns = {} end
C_AddOns.DisableAddOn = _nil
C_AddOns.DisableAllAddOns = _nil
C_AddOns.DoesAddOnExist = _nil
C_AddOns.DoesAddOnHaveLoadError = _nil
C_AddOns.EnableAddOn = _nil
C_AddOns.EnableAllAddOns = _nil
C_AddOns.GetAddOnDependencies = _nil
C_AddOns.GetAddOnEnableState = _nil
C_AddOns.GetAddOnInfo = _nil
C_AddOns.GetAddOnInterfaceVersion = _nil
C_AddOns.GetAddOnLocalTable = _nil
C_AddOns.GetAddOnMetadata = _nil
C_AddOns.GetAddOnName = _nil
C_AddOns.GetAddOnNotes = _nil
C_AddOns.GetAddOnOptionalDependencies = _nil
C_AddOns.GetAddOnSecurity = _nil
C_AddOns.GetAddOnTitle = _nil
C_AddOns.GetNumAddOns = _nil
C_AddOns.GetScriptsDisallowedForBeta = _nil
C_AddOns.IsAddOnDefaultEnabled = _nil
C_AddOns.IsAddOnLoadOnDemand = _nil
C_AddOns.IsAddOnLoadable = _nil
C_AddOns.IsAddOnLoaded = _nil
C_AddOns.IsAddonVersionCheckEnabled = _nil
C_AddOns.LoadAddOn = _nil
C_AddOns.ResetAddOns = _nil
C_AddOns.ResetDisabledAddOns = _nil
C_AddOns.SaveAddOns = _nil
C_AddOns.SetAddonVersionCheck = _nil
-- Events: ADDON_LOADED, ADDONS_UNLOADING, SAVED_VARIABLES_TOO_LARGE
`;
