// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:78532c1d1162a327e288522bc9bd130d4789157d463b83ad50b73273bb0ee112
// @sig-hash: sha256:167a9dcab27e4c17
// Source: Blizzard_APIDocumentationGenerated/addonprofilerdocumentation.lua
export const C_AddOnProfiler = `
if C_AddOnProfiler == nil then C_AddOnProfiler = {} end
C_AddOnProfiler.AddMeasuredCallEvent = _nil
C_AddOnProfiler.AddPerformanceMessageShown = _nil
C_AddOnProfiler.CheckForPerformanceMessage = _tbl
C_AddOnProfiler.GetAddOnMetric = _num
C_AddOnProfiler.GetApplicationMetric = _num
C_AddOnProfiler.GetOverallMetric = _num
C_AddOnProfiler.GetTicksPerSecond = _nil
C_AddOnProfiler.GetTopKAddOnsForMetric = _tbl
C_AddOnProfiler.IsEnabled = _bool
C_AddOnProfiler.MeasureCall = _tbl
`;
