// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2082c3721922a7e5b6f9e1ce59749712a9bc5728fade0531e1144df02570b369
// @sig-hash: sha256:35e5b052d7547fc5
// Source: Blizzard_APIDocumentationGenerated/adventuremapdocumentation.lua
export const C_AdventureMap = `
if C_AdventureMap == nil then C_AdventureMap = {} end
C_AdventureMap.GetAdventureMapTextureKit = _nil("C_AdventureMap.GetAdventureMapTextureKit")
C_AdventureMap.GetQuestPortraitInfo = _tbl("C_AdventureMap.GetQuestPortraitInfo")
-- Events: ADVENTURE_MAP_CLOSE, ADVENTURE_MAP_OPEN, ADVENTURE_MAP_QUEST_UPDATE, ADVENTURE_MAP_UPDATE_INSETS, ADVENTURE_MAP_UPDATE_POIS
`;
