// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b30b9a88f54c078356bd873422094742d8cbd231fc5a990b3079247920cdc687
// @sig-hash: sha256:46372c4041215eb7
// Source: Blizzard_APIDocumentationGenerated/alliedracesframedocumentation.lua
export const C_AlliedRaces = `
if C_AlliedRaces == nil then C_AlliedRaces = {} end
C_AlliedRaces.GetAllRacialAbilitiesFromID = _tbl("C_AlliedRaces.GetAllRacialAbilitiesFromID")
C_AlliedRaces.GetRaceInfoByID = _tbl("C_AlliedRaces.GetRaceInfoByID")
-- Events: ALLIED_RACE_CLOSE, ALLIED_RACE_OPEN
`;
