// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:02be03b8ead07bc5773712cff721ade99f43659c0bd5901dc289d2b857421092
// @sig-hash: sha256:96a11a0a6ba3b253
// Source: Blizzard_APIDocumentationGenerated/alliedracesframedocumentation.lua
export const C_AlliedRaces = `
if C_AlliedRaces == nil then C_AlliedRaces = {} end
C_AlliedRaces.GetAllRacialAbilitiesFromID = _tbl
C_AlliedRaces.GetRaceInfoByID = _tbl
-- Events: ALLIED_RACE_CLOSE, ALLIED_RACE_OPEN
`;
