// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:be30a163bb892621231a90cc59a21436cac5e44b776d466d91f1f337c7ee9584
// @sig-hash: sha256:4b7bd00b5810a698
// Source: Blizzard_APIDocumentationGenerated/animadiversionuidocumentation.lua
export const C_AnimaDiversion = `
if C_AnimaDiversion == nil then C_AnimaDiversion = {} end
C_AnimaDiversion.CloseUI = _nil
C_AnimaDiversion.GetAnimaDiversionNodes = _tbl
C_AnimaDiversion.GetOriginPosition = _nil
C_AnimaDiversion.GetReinforceProgress = _nil
C_AnimaDiversion.GetTextureKit = _nil
C_AnimaDiversion.OpenAnimaDiversionUI = _nil
C_AnimaDiversion.SelectAnimaNode = _nil
-- Events: ANIMA_DIVERSION_CLOSE, ANIMA_DIVERSION_OPEN, ANIMA_DIVERSION_TALENT_UPDATED
`;
