// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f78812d208181d117bd63bc1b50a17a81e4d68bc6ec6d8b1b706b6830112eed7
// @sig-hash: sha256:739171eb1ed665ff
// Source: Blizzard_APIDocumentationGenerated/ardenwealdgardeningdocumentation.lua
export const C_ArdenwealdGardening = `
if C_ArdenwealdGardening == nil then C_ArdenwealdGardening = {} end
C_ArdenwealdGardening.GetGardenData = _tbl
C_ArdenwealdGardening.IsGardenAccessible = _nil
`;
