// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a93c92329b1a4e8d86632d7a1d954c48c74d867e33fa1f811acd47b2e5135d1b
// @sig-hash: sha256:f297888b1150c082
// Source: Blizzard_APIDocumentationGenerated/areapoiinfodocumentation.lua
export const C_AreaPoiInfo = `
if C_AreaPoiInfo == nil then C_AreaPoiInfo = {} end
C_AreaPoiInfo.GetAreaPOIForMap = _tbl
C_AreaPoiInfo.GetAreaPOIInfo = _tbl
C_AreaPoiInfo.GetAreaPOISecondsLeft = _num
C_AreaPoiInfo.GetDelvesForMap = _tbl
C_AreaPoiInfo.GetDragonridingRacesForMap = _tbl
C_AreaPoiInfo.GetEventsForMap = _tbl
C_AreaPoiInfo.GetQuestHubsForMap = _tbl
C_AreaPoiInfo.IsAreaPOITimed = _bool
-- Events: AREA_POIS_UPDATED
`;
