// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5135013277423354c4907090acd520173e3d7f740bede068bdbbbc96ed6987ce
// @sig-hash: sha256:ac0eeb2718078b35
// Source: Blizzard_APIDocumentationGenerated/ardenwealdgardeningdocumentation.lua
export const C_ArdenwealdGardening = `
if C_ArdenwealdGardening == nil then C_ArdenwealdGardening = {} end
C_ArdenwealdGardening.GetGardenData = _tbl("C_ArdenwealdGardening.GetGardenData")
C_ArdenwealdGardening.IsGardenAccessible = _bool("C_ArdenwealdGardening.IsGardenAccessible")
`;
