// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b31fc84185d0b8aa59de954c92d48da33e619fdd2d4ca875318a1b84b8cc808e
// @sig-hash: sha256:783e1790852fae2d
// Source: Blizzard_APIDocumentationGenerated/areapoiinfodocumentation.lua
export const C_AreaPoiInfo = `
if C_AreaPoiInfo == nil then C_AreaPoiInfo = {} end
C_AreaPoiInfo.GetAreaPOIForMap = _tbl("C_AreaPoiInfo.GetAreaPOIForMap")
C_AreaPoiInfo.GetAreaPOIInfo = _tbl("C_AreaPoiInfo.GetAreaPOIInfo")
C_AreaPoiInfo.GetAreaPOISecondsLeft = _num("C_AreaPoiInfo.GetAreaPOISecondsLeft")
C_AreaPoiInfo.GetDelvesForMap = _tbl("C_AreaPoiInfo.GetDelvesForMap")
C_AreaPoiInfo.GetDragonridingRacesForMap = _tbl("C_AreaPoiInfo.GetDragonridingRacesForMap")
C_AreaPoiInfo.GetEventsForMap = _tbl("C_AreaPoiInfo.GetEventsForMap")
C_AreaPoiInfo.GetQuestHubsForMap = _tbl("C_AreaPoiInfo.GetQuestHubsForMap")
C_AreaPoiInfo.IsAreaPOITimed = _bool("C_AreaPoiInfo.IsAreaPOITimed")
-- Events: AREA_POIS_UPDATED
`;
