// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3350e263eac76f257b52a3601499c5bc426ad09a222a08930583f68b1c885b93
// @sig-hash: sha256:fffdf5a827ed874f
// Source: Blizzard_APIDocumentationGenerated/assistedcombatdocumentation.lua
export const C_AssistedCombat = `
if C_AssistedCombat == nil then C_AssistedCombat = {} end
C_AssistedCombat.GetActionSpell = _nil("C_AssistedCombat.GetActionSpell")
C_AssistedCombat.GetNextCastSpell = _nil("C_AssistedCombat.GetNextCastSpell")
C_AssistedCombat.GetRotationSpells = _tbl("C_AssistedCombat.GetRotationSpells")
C_AssistedCombat.IsAvailable = _bool("C_AssistedCombat.IsAvailable")
-- Events: ASSISTED_COMBAT_ACTION_SPELL_CAST
`;
