// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5e7ff2e8070d23c986ef9dcb5afa7e4ab3f6aa1dde006ff994816341e1f67164
// @sig-hash: sha256:3cc46e047d7c9d72
// Source: Blizzard_APIDocumentationGenerated/assistedcombatdocumentation.lua
export const C_AssistedCombat = `
if C_AssistedCombat == nil then C_AssistedCombat = {} end
C_AssistedCombat.GetActionSpell = _nil
C_AssistedCombat.GetNextCastSpell = _nil
C_AssistedCombat.GetRotationSpells = _tbl
C_AssistedCombat.IsAvailable = _nil
-- Events: ASSISTED_COMBAT_ACTION_SPELL_CAST
`;
