// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:074e565a138bca398da1e6ea75fc48ec67a70309826f6503e12a0b1a0f48a555
// @sig-hash: sha256:63e3d71747770519
// Source: Blizzard_APIDocumentationGenerated/autocompletedocumentation.lua
export const C_AutoComplete = `
if C_AutoComplete == nil then C_AutoComplete = {} end
C_AutoComplete.GetAutoCompletePresenceID = _nil
C_AutoComplete.GetAutoCompleteRealms = _tbl
C_AutoComplete.GetAutoCompleteResults = _tbl
C_AutoComplete.IsRecognizedName = _bool
`;
