// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b45a3b98ebad30182c8b64d1a1abb5418b86bd146dde20cd3d23510677ef9b57
// @sig-hash: sha256:2a88e4a2a88baa91
// Source: Blizzard_APIDocumentationGenerated/autocompletedocumentation.lua
export const C_AutoComplete = `
if C_AutoComplete == nil then C_AutoComplete = {} end
C_AutoComplete.GetAutoCompletePresenceID = _nil("C_AutoComplete.GetAutoCompletePresenceID")
C_AutoComplete.GetAutoCompleteRealms = _tbl("C_AutoComplete.GetAutoCompleteRealms")
C_AutoComplete.GetAutoCompleteResults = _tbl("C_AutoComplete.GetAutoCompleteResults")
C_AutoComplete.IsRecognizedName = _bool("C_AutoComplete.IsRecognizedName")
`;
