// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:42c215ab034254d1f5f4e5f0514c73a49d224f16bac9da076e8c44c2d6076845
// @sig-hash: sha256:da47cd980dab1adb
// Source: Blizzard_APIDocumentationGenerated/azeriteitemdocumentation.lua
export const C_AzeriteItem = `
if C_AzeriteItem == nil then C_AzeriteItem = {} end
C_AzeriteItem.FindActiveAzeriteItem = _nil
C_AzeriteItem.GetAzeriteItemXPInfo = _num
C_AzeriteItem.GetPowerLevel = _num
C_AzeriteItem.GetUnlimitedPowerLevel = _num
C_AzeriteItem.HasActiveAzeriteItem = _bool
C_AzeriteItem.IsAzeriteItem = _bool
C_AzeriteItem.IsAzeriteItemAtMaxLevel = _bool
C_AzeriteItem.IsAzeriteItemByID = _bool
C_AzeriteItem.IsAzeriteItemEnabled = _bool
C_AzeriteItem.IsUnlimitedLevelingUnlocked = _bool
-- Events: AZERITE_ITEM_ENABLED_STATE_CHANGED, AZERITE_ITEM_EXPERIENCE_CHANGED, AZERITE_ITEM_POWER_LEVEL_CHANGED
`;
