// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:33cc49c5f6e2e3a0cbfc3d3b6b7882665f3046985d639bce18b11b09537d9e01
// @sig-hash: sha256:0d04a3bde215c17c
// Source: Blizzard_APIDocumentationGenerated/azeriteitemdocumentation.lua
export const C_AzeriteItem = `
if C_AzeriteItem == nil then C_AzeriteItem = {} end
C_AzeriteItem.FindActiveAzeriteItem = _nil("C_AzeriteItem.FindActiveAzeriteItem")
C_AzeriteItem.GetAzeriteItemXPInfo = _num("C_AzeriteItem.GetAzeriteItemXPInfo")
C_AzeriteItem.GetPowerLevel = _num("C_AzeriteItem.GetPowerLevel")
C_AzeriteItem.GetUnlimitedPowerLevel = _num("C_AzeriteItem.GetUnlimitedPowerLevel")
C_AzeriteItem.HasActiveAzeriteItem = _bool("C_AzeriteItem.HasActiveAzeriteItem")
C_AzeriteItem.IsAzeriteItem = _bool("C_AzeriteItem.IsAzeriteItem")
C_AzeriteItem.IsAzeriteItemAtMaxLevel = _bool("C_AzeriteItem.IsAzeriteItemAtMaxLevel")
C_AzeriteItem.IsAzeriteItemByID = _bool("C_AzeriteItem.IsAzeriteItemByID")
C_AzeriteItem.IsAzeriteItemEnabled = _bool("C_AzeriteItem.IsAzeriteItemEnabled")
C_AzeriteItem.IsUnlimitedLevelingUnlocked = _bool("C_AzeriteItem.IsUnlimitedLevelingUnlocked")
-- Events: AZERITE_ITEM_ENABLED_STATE_CHANGED, AZERITE_ITEM_EXPERIENCE_CHANGED, AZERITE_ITEM_POWER_LEVEL_CHANGED
`;
