// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:cb5fbbf598b27475dc124e4322c72dd1abaf40e363e0d34120925a069190e348
// @sig-hash: sha256:23f2ffb193f98b62
// Source: Blizzard_APIDocumentationGenerated/azeriteempowereditemdocumentation.lua
export const C_AzeriteEmpoweredItem = `
if C_AzeriteEmpoweredItem == nil then C_AzeriteEmpoweredItem = {} end
C_AzeriteEmpoweredItem.CanSelectPower = _nil
C_AzeriteEmpoweredItem.ConfirmAzeriteEmpoweredItemRespec = _nil
C_AzeriteEmpoweredItem.GetAllTierInfo = _tbl
C_AzeriteEmpoweredItem.GetAllTierInfoByItemID = _tbl
C_AzeriteEmpoweredItem.GetAzeriteEmpoweredItemRespecCost = _nil
C_AzeriteEmpoweredItem.GetPowerInfo = _tbl
C_AzeriteEmpoweredItem.GetPowerText = _tbl
C_AzeriteEmpoweredItem.GetSpecsForPower = _tbl
C_AzeriteEmpoweredItem.HasAnyUnselectedPowers = _nil
C_AzeriteEmpoweredItem.HasBeenViewed = _nil
C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItem = _nil
C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID = _nil
C_AzeriteEmpoweredItem.IsAzeritePreviewSourceDisplayable = _nil
C_AzeriteEmpoweredItem.IsHeartOfAzerothEquipped = _nil
C_AzeriteEmpoweredItem.IsPowerAvailableForSpec = _nil
C_AzeriteEmpoweredItem.IsPowerSelected = _nil
C_AzeriteEmpoweredItem.SelectPower = _nil
C_AzeriteEmpoweredItem.SetHasBeenViewed = _nil
-- Events: AZERITE_EMPOWERED_ITEM_EQUIPPED_STATUS_CHANGED, AZERITE_EMPOWERED_ITEM_SELECTION_UPDATED
`;
