// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fef95d32650fcbe05c6f7d5132ef819962202ec9915c905d98d04c695f8d4299
// @sig-hash: sha256:a334772033eea11f
// Source: Blizzard_APIDocumentationGenerated/bankdocumentation.lua
export const C_Bank = `
if C_Bank == nil then C_Bank = {} end
C_Bank.AreAnyBankTypesViewable = _bool("C_Bank.AreAnyBankTypesViewable")
C_Bank.AutoDepositItemsIntoBank = _nil("C_Bank.AutoDepositItemsIntoBank")
C_Bank.CanDepositMoney = _bool("C_Bank.CanDepositMoney")
C_Bank.CanPurchaseBankTab = _bool("C_Bank.CanPurchaseBankTab")
C_Bank.CanUseBank = _bool("C_Bank.CanUseBank")
C_Bank.CanViewBank = _bool("C_Bank.CanViewBank")
C_Bank.CanWithdrawMoney = _bool("C_Bank.CanWithdrawMoney")
C_Bank.CloseBankFrame = _nil("C_Bank.CloseBankFrame")
C_Bank.DepositMoney = _nil("C_Bank.DepositMoney")
C_Bank.DoesBankTypeSupportAutoDeposit = _bool("C_Bank.DoesBankTypeSupportAutoDeposit")
C_Bank.DoesBankTypeSupportMoneyTransfer = _bool("C_Bank.DoesBankTypeSupportMoneyTransfer")
C_Bank.FetchBankLockedReason = _nil("C_Bank.FetchBankLockedReason")
C_Bank.FetchDepositedMoney = _nil("C_Bank.FetchDepositedMoney")
C_Bank.FetchNextPurchasableBankTabData = _nil("C_Bank.FetchNextPurchasableBankTabData")
C_Bank.FetchNumPurchasedBankTabs = _num("C_Bank.FetchNumPurchasedBankTabs")
C_Bank.FetchPurchasedBankTabData = _tbl("C_Bank.FetchPurchasedBankTabData")
C_Bank.FetchPurchasedBankTabIDs = _tbl("C_Bank.FetchPurchasedBankTabIDs")
C_Bank.FetchViewableBankTypes = _tbl("C_Bank.FetchViewableBankTypes")
C_Bank.HasMaxBankTabs = _bool("C_Bank.HasMaxBankTabs")
C_Bank.IsItemAllowedInBankType = _bool("C_Bank.IsItemAllowedInBankType")
C_Bank.PurchaseBankTab = _nil("C_Bank.PurchaseBankTab")
C_Bank.UpdateBankTabSettings = _nil("C_Bank.UpdateBankTabSettings")
C_Bank.WithdrawMoney = _nil("C_Bank.WithdrawMoney")
-- Events: BANK_BAG_SLOT_FLAGS_UPDATED, BANK_TAB_SETTINGS_UPDATED, BANK_TABS_CHANGED, BANKFRAME_CLOSED, BANKFRAME_OPENED, PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED, PLAYERBANKSLOTS_CHANGED
`;
