// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:69da9bcd2ac666ccc9149661f12c65675d911872e69c8c3588826179cad3d9ca
// @sig-hash: sha256:827535f5b05896d6
// Source: Blizzard_APIDocumentationGenerated/barbershopdocumentation.lua
export const C_BarberShop = `
if C_BarberShop == nil then C_BarberShop = {} end
C_BarberShop.ApplyCustomizationChoices = _bool("C_BarberShop.ApplyCustomizationChoices")
C_BarberShop.Cancel = _nil("C_BarberShop.Cancel")
C_BarberShop.ClearPreviewChoices = _nil("C_BarberShop.ClearPreviewChoices")
C_BarberShop.GetAvailableCustomizations = _tbl("C_BarberShop.GetAvailableCustomizations")
C_BarberShop.GetCurrentCameraZoom = _num("C_BarberShop.GetCurrentCameraZoom")
C_BarberShop.GetCurrentCharacterData = _tbl("C_BarberShop.GetCurrentCharacterData")
C_BarberShop.GetCurrentCost = _num("C_BarberShop.GetCurrentCost")
C_BarberShop.GetViewingChrModel = _nil("C_BarberShop.GetViewingChrModel")
C_BarberShop.HasAlteredForm = _bool("C_BarberShop.HasAlteredForm")
C_BarberShop.HasAnyChanges = _bool("C_BarberShop.HasAnyChanges")
C_BarberShop.HasCustomizationFeature = _bool("C_BarberShop.HasCustomizationFeature")
C_BarberShop.IsViewingAlteredForm = _bool("C_BarberShop.IsViewingAlteredForm")
C_BarberShop.MarkCustomizationChoiceAsSeen = _nil("C_BarberShop.MarkCustomizationChoiceAsSeen")
C_BarberShop.MarkCustomizationOptionAsSeen = _nil("C_BarberShop.MarkCustomizationOptionAsSeen")
C_BarberShop.PreviewCustomizationChoice = _nil("C_BarberShop.PreviewCustomizationChoice")
C_BarberShop.RandomizeCustomizationChoices = _nil("C_BarberShop.RandomizeCustomizationChoices")
C_BarberShop.ResetCameraRotation = _nil("C_BarberShop.ResetCameraRotation")
C_BarberShop.ResetCustomizationChoices = _nil("C_BarberShop.ResetCustomizationChoices")
C_BarberShop.RotateCamera = _nil("C_BarberShop.RotateCamera")
C_BarberShop.SaveSeenChoices = _nil("C_BarberShop.SaveSeenChoices")
C_BarberShop.SetCameraDistanceOffset = _nil("C_BarberShop.SetCameraDistanceOffset")
C_BarberShop.SetCameraZoomLevel = _nil("C_BarberShop.SetCameraZoomLevel")
C_BarberShop.SetCustomizationChoice = _nil("C_BarberShop.SetCustomizationChoice")
C_BarberShop.SetModelDressState = _nil("C_BarberShop.SetModelDressState")
C_BarberShop.SetSelectedSex = _nil("C_BarberShop.SetSelectedSex")
C_BarberShop.SetViewingAlteredForm = _nil("C_BarberShop.SetViewingAlteredForm")
C_BarberShop.SetViewingChrModel = _nil("C_BarberShop.SetViewingChrModel")
C_BarberShop.SetViewingShapeshiftForm = _nil("C_BarberShop.SetViewingShapeshiftForm")
C_BarberShop.ZoomCamera = _nil("C_BarberShop.ZoomCamera")
-- Events: BARBER_SHOP_APPEARANCE_APPLIED, BARBER_SHOP_CAMERA_VALUES_UPDATED, BARBER_SHOP_CLOSE, BARBER_SHOP_COST_UPDATE, BARBER_SHOP_FORCE_CUSTOMIZATIONS_UPDATE, BARBER_SHOP_OPEN, BARBER_SHOP_RESULT
`;
