// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b289dfaeca92283902a9b246c42fd04a29c710abd05f841602d7a72b8e3fe311
// @sig-hash: sha256:7a86b1f2feb53cca
// Source: Blizzard_APIDocumentationGenerated/barbershopinternaldocumentation.lua
export const C_BarberShopInternal = `
if C_BarberShopInternal == nil then C_BarberShopInternal = {} end
C_BarberShopInternal.SetQAMode = _nil("C_BarberShopInternal.SetQAMode")
`;
