// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3556ecfef5047c7097723bf14631f579a8c7d02031c583b8e342fea6036e1851
// @sig-hash: sha256:4828015b6899750d
// Source: Blizzard_APIDocumentationGenerated/barbershopdocumentation.lua
export const C_BarberShop = `
if C_BarberShop == nil then C_BarberShop = {} end
C_BarberShop.ApplyCustomizationChoices = _bool
C_BarberShop.Cancel = _nil
C_BarberShop.ClearPreviewChoices = _nil
C_BarberShop.GetAvailableCustomizations = _tbl
C_BarberShop.GetCurrentCameraZoom = _num
C_BarberShop.GetCurrentCharacterData = _tbl
C_BarberShop.GetCurrentCost = _num
C_BarberShop.GetViewingChrModel = _nil
C_BarberShop.HasAlteredForm = _bool
C_BarberShop.HasAnyChanges = _bool
C_BarberShop.HasCustomizationFeature = _bool
C_BarberShop.IsViewingAlteredForm = _bool
C_BarberShop.MarkCustomizationChoiceAsSeen = _nil
C_BarberShop.MarkCustomizationOptionAsSeen = _nil
C_BarberShop.PreviewCustomizationChoice = _nil
C_BarberShop.RandomizeCustomizationChoices = _nil
C_BarberShop.ResetCameraRotation = _nil
C_BarberShop.ResetCustomizationChoices = _nil
C_BarberShop.RotateCamera = _nil
C_BarberShop.SaveSeenChoices = _nil
C_BarberShop.SetCameraDistanceOffset = _nil
C_BarberShop.SetCameraZoomLevel = _nil
C_BarberShop.SetCustomizationChoice = _nil
C_BarberShop.SetModelDressState = _nil
C_BarberShop.SetSelectedSex = _nil
C_BarberShop.SetViewingAlteredForm = _nil
C_BarberShop.SetViewingChrModel = _nil
C_BarberShop.SetViewingShapeshiftForm = _nil
C_BarberShop.ZoomCamera = _nil
-- Events: BARBER_SHOP_APPEARANCE_APPLIED, BARBER_SHOP_CAMERA_VALUES_UPDATED, BARBER_SHOP_CLOSE, BARBER_SHOP_COST_UPDATE, BARBER_SHOP_FORCE_CUSTOMIZATIONS_UPDATE, BARBER_SHOP_OPEN, BARBER_SHOP_RESULT
`;
