// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f26ee88d26f4d5503f7b419047c0cfa855e2c2a86e9bebbfca3f838984024ff0
// @sig-hash: sha256:5995ae2bad67d325
// Source: Blizzard_APIDocumentationGenerated/barbershopinternaldocumentation.lua
export const C_BarberShopInternal = `
if C_BarberShopInternal == nil then C_BarberShopInternal = {} end
C_BarberShopInternal.SetQAMode = _nil
`;
