// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7ea13b13cca4d4aa5110fb2d38d9fc3a3189c9c1820cd22d7dda0d5768f38dd3
// @sig-hash: sha256:2bd0da95a1d53898
// Source: Blizzard_APIDocumentationGenerated/behavioralmessagingdocumentation.lua
export const C_BehavioralMessaging = `
if C_BehavioralMessaging == nil then C_BehavioralMessaging = {} end
C_BehavioralMessaging.SendNotificationReceipt = _nil
-- Events: BEHAVIORAL_NOTIFICATION
`;
