// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:34a3d1af184b75f5eefb2c511f1a39e7fe9dc074d92e6bbcdbfdb5d5dd89dba7
// @sig-hash: sha256:a3113b0b6355cdcf
// Source: Blizzard_APIDocumentationGenerated/behavioralmessagingdocumentation.lua
export const C_BehavioralMessaging = `
if C_BehavioralMessaging == nil then C_BehavioralMessaging = {} end
C_BehavioralMessaging.SendNotificationReceipt = _nil("C_BehavioralMessaging.SendNotificationReceipt")
-- Events: BEHAVIORAL_NOTIFICATION
`;
