// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2c7ee2bb656925de4f494c5e977c28328ed00564cb73fd8b22f1e40404e8a08e
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/blackmarketinfodocumentation.lua
export const C_BlackMarketInfo = `
if C_BlackMarketInfo == nil then C_BlackMarketInfo = {} end
-- Events: BLACK_MARKET_BID_RESULT, BLACK_MARKET_CLOSE, BLACK_MARKET_ITEM_UPDATE, BLACK_MARKET_OPEN, BLACK_MARKET_OUTBID, BLACK_MARKET_UNAVAILABLE, BLACK_MARKET_WON
`;
