// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a92a81f71c02995744027278b01550a0b7d931d7dacade527b75818b685c0c8d
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/browserdocumentation.lua
export const C_Browser = `
if C_Browser == nil then C_Browser = {} end
-- Events: SIMPLE_BROWSER_POPUP, SIMPLE_BROWSER_SOCIAL_CALLBACK_INVOKED, SIMPLE_BROWSER_WEB_ERROR, SIMPLE_BROWSER_WEB_PROXY_FAILED, SIMPLE_CHECKOUT_CLOSED
`;
