// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8f2952b1983fb3b9312fbb23073d2b458b027f1ed2f5b076b34d60ec27c006c7
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/browserdocumentation.lua
export const C_Browser = `
if C_Browser == nil then C_Browser = {} end
-- Events: SIMPLE_BROWSER_POPUP, SIMPLE_BROWSER_SOCIAL_CALLBACK_INVOKED, SIMPLE_BROWSER_WEB_ERROR, SIMPLE_BROWSER_WEB_PROXY_FAILED, SIMPLE_CHECKOUT_CLOSED
`;
