// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:244caaf823239426728e09311e55d6d0bb189239c7f334a69087be41f1ed9feb
// @sig-hash: sha256:47097640d113812e
// Source: Blizzard_APIDocumentationGenerated/warcampaigndocumentation.lua
export const C_CampaignInfo = `
if C_CampaignInfo == nil then C_CampaignInfo = {} end
C_CampaignInfo.GetAvailableCampaigns = _tbl
C_CampaignInfo.GetCampaignChapterInfo = _nil
C_CampaignInfo.GetCampaignID = _nil
C_CampaignInfo.GetCampaignInfo = _nil
C_CampaignInfo.GetChapterIDs = _tbl
C_CampaignInfo.GetCurrentChapterID = _nil
C_CampaignInfo.GetFailureReason = _nil
C_CampaignInfo.GetState = _nil
C_CampaignInfo.IsCampaignQuest = _nil
C_CampaignInfo.SortAsNormalQuest = _nil
`;
