// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3821b07f76b643a02ead99bc3ad2d8c1f189d4dc2c68352e268cf967ed07a9aa
// @sig-hash: sha256:6130d6291facbd0d
// Source: Blizzard_APIDocumentationGenerated/warcampaigndocumentation.lua
export const C_CampaignInfo = `
if C_CampaignInfo == nil then C_CampaignInfo = {} end
C_CampaignInfo.GetAvailableCampaigns = _tbl("C_CampaignInfo.GetAvailableCampaigns")
C_CampaignInfo.GetCampaignChapterInfo = _nil("C_CampaignInfo.GetCampaignChapterInfo")
C_CampaignInfo.GetCampaignID = _num("C_CampaignInfo.GetCampaignID")
C_CampaignInfo.GetCampaignInfo = _nil("C_CampaignInfo.GetCampaignInfo")
C_CampaignInfo.GetChapterIDs = _tbl("C_CampaignInfo.GetChapterIDs")
C_CampaignInfo.GetCurrentChapterID = _nil("C_CampaignInfo.GetCurrentChapterID")
C_CampaignInfo.GetFailureReason = _nil("C_CampaignInfo.GetFailureReason")
C_CampaignInfo.GetState = _nil("C_CampaignInfo.GetState")
C_CampaignInfo.IsCampaignQuest = _bool("C_CampaignInfo.IsCampaignQuest")
C_CampaignInfo.SortAsNormalQuest = _bool("C_CampaignInfo.SortAsNormalQuest")
`;
