// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:62726e6c24f52ffe0dd14f86ba01c84f35466b5e311f2da7413b7b67154f0be3
// @sig-hash: sha256:318d8e07ab81a2aa
// Source: Blizzard_APIDocumentationGenerated/chromietimeuidocumentation.lua
export const C_ChromieTime = `
if C_ChromieTime == nil then C_ChromieTime = {} end
C_ChromieTime.CloseUI = _nil("C_ChromieTime.CloseUI")
C_ChromieTime.GetChromieTimeExpansionOption = _nil("C_ChromieTime.GetChromieTimeExpansionOption")
C_ChromieTime.GetChromieTimeExpansionOptions = _tbl("C_ChromieTime.GetChromieTimeExpansionOptions")
C_ChromieTime.SelectChromieTimeOption = _nil("C_ChromieTime.SelectChromieTimeOption")
`;
