// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:884adf6ecb67d5adaf247e7c38b83665c5664c133ce79cea2c2a3c56bac8ef69
// @sig-hash: sha256:e71ff982d3214734
// Source: Blizzard_APIDocumentationGenerated/chromietimeuidocumentation.lua
export const C_ChromieTime = `
if C_ChromieTime == nil then C_ChromieTime = {} end
C_ChromieTime.CloseUI = _nil
C_ChromieTime.GetChromieTimeExpansionOption = _nil
C_ChromieTime.GetChromieTimeExpansionOptions = _tbl
C_ChromieTime.SelectChromieTimeOption = _nil
`;
