// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0fa8cf54c6281778d844e37c268b899102d4f2828184e671a459b3c4a89b37be
// @sig-hash: sha256:85e7dcaf9a5dbf05
// Source: Blizzard_APIDocumentationGenerated/chatbubblesdocumentation.lua
export const C_ChatBubbles = `
if C_ChatBubbles == nil then C_ChatBubbles = {} end
C_ChatBubbles.GetAllChatBubbles = _tbl("C_ChatBubbles.GetAllChatBubbles")
`;
