// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4ba61152c11168f2b86dd2ae145795b32883947dc0d69de6dd66f90989801a44
// @sig-hash: sha256:7d86aba97a1ecffa
// Source: Blizzard_APIDocumentationGenerated/chatbubblesdocumentation.lua
export const C_ChatBubbles = `
if C_ChatBubbles == nil then C_ChatBubbles = {} end
C_ChatBubbles.GetAllChatBubbles = _tbl
`;
