// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a32b486bc5eb6df189062262c6c193eb9835c9fc0b46c18dbc86c7a9f33c4ddc
// @sig-hash: sha256:95f2bec8c4a53865
// Source: Blizzard_APIDocumentationGenerated/cinematiclistdocumentation.lua
export const C_CinematicList = `
if C_CinematicList == nil then C_CinematicList = {} end
C_CinematicList.GetUICinematicList = _tbl
`;
