// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0daba827732eca9542b01c4a860636d06af80a99250985e7d540e10b9f0017cf
// @sig-hash: sha256:b4cf846b741cad39
// Source: Blizzard_APIDocumentationGenerated/cinematiclistdocumentation.lua
export const C_CinematicList = `
if C_CinematicList == nil then C_CinematicList = {} end
C_CinematicList.GetUICinematicList = _tbl("C_CinematicList.GetUICinematicList")
`;
