// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:de1bac7b84243510e2dc5315a4b8f8715783dc2f8d1a8d5ee856106e4e8aad67
// @sig-hash: sha256:03f3521abda53cb4
// Source: Blizzard_APIDocumentationGenerated/clickbindingsdocumentation.lua
export const C_ClickBindings = `
if C_ClickBindings == nil then C_ClickBindings = {} end
C_ClickBindings.CanSpellBeClickBound = _bool("C_ClickBindings.CanSpellBeClickBound")
C_ClickBindings.ExecuteBinding = _nil("C_ClickBindings.ExecuteBinding")
C_ClickBindings.GetBindingType = _nil("C_ClickBindings.GetBindingType")
C_ClickBindings.GetEffectiveInteractionButton = _str("C_ClickBindings.GetEffectiveInteractionButton")
C_ClickBindings.GetProfileInfo = _tbl("C_ClickBindings.GetProfileInfo")
C_ClickBindings.GetStringFromModifiers = _str("C_ClickBindings.GetStringFromModifiers")
C_ClickBindings.GetTutorialShown = _bool("C_ClickBindings.GetTutorialShown")
C_ClickBindings.MakeModifiers = _num("C_ClickBindings.MakeModifiers")
C_ClickBindings.ResetCurrentProfile = _nil("C_ClickBindings.ResetCurrentProfile")
C_ClickBindings.SetProfileByInfo = _nil("C_ClickBindings.SetProfileByInfo")
C_ClickBindings.SetTutorialShown = _nil("C_ClickBindings.SetTutorialShown")
-- Events: CLICKBINDINGS_SET_HIGHLIGHTS_SHOWN
`;
