// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fa9d0047c04aedc40e75002c79941c7be7d8f78530d46150207a16e1d6df0f1f
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/classtrialdocumentation.lua
export const C_ClassTrial = `
if C_ClassTrial == nil then C_ClassTrial = {} end
-- Events: CLASS_TRIAL_TIMER_START, CLASS_TRIAL_UPGRADE_COMPLETE
`;
