// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:40bd4c8a4bb3ecda4737f15865d38ca0faf01a024737a08584ef57f44a436098
// @sig-hash: sha256:dad04faee8c96413
// Source: Blizzard_APIDocumentationGenerated/classtalentsdocumentation.lua
export const C_ClassTalents = `
if C_ClassTalents == nil then C_ClassTalents = {} end
C_ClassTalents.CanChangeTalents = _bool("C_ClassTalents.CanChangeTalents")
C_ClassTalents.CanCreateNewConfig = _bool("C_ClassTalents.CanCreateNewConfig")
C_ClassTalents.CanEditTalents = _bool("C_ClassTalents.CanEditTalents")
C_ClassTalents.CommitConfig = _bool("C_ClassTalents.CommitConfig")
C_ClassTalents.DeleteConfig = _bool("C_ClassTalents.DeleteConfig")
C_ClassTalents.GetActiveConfigID = _nil("C_ClassTalents.GetActiveConfigID")
C_ClassTalents.GetActiveHeroTalentSpec = _nil("C_ClassTalents.GetActiveHeroTalentSpec")
C_ClassTalents.GetConfigIDsBySpecID = _tbl("C_ClassTalents.GetConfigIDsBySpecID")
C_ClassTalents.GetHasStarterBuild = _bool("C_ClassTalents.GetHasStarterBuild")
C_ClassTalents.GetHeroTalentSpecsForClassSpec = _tbl("C_ClassTalents.GetHeroTalentSpecsForClassSpec")
C_ClassTalents.GetLastSelectedSavedConfigID = _nil("C_ClassTalents.GetLastSelectedSavedConfigID")
C_ClassTalents.GetNextStarterBuildPurchase = _nil("C_ClassTalents.GetNextStarterBuildPurchase")
C_ClassTalents.GetStarterBuildActive = _bool("C_ClassTalents.GetStarterBuildActive")
C_ClassTalents.GetTraitTreeForSpec = _nil("C_ClassTalents.GetTraitTreeForSpec")
C_ClassTalents.HasUnspentHeroTalentPoints = _bool("C_ClassTalents.HasUnspentHeroTalentPoints")
C_ClassTalents.HasUnspentTalentPoints = _bool("C_ClassTalents.HasUnspentTalentPoints")
C_ClassTalents.ImportLoadout = _bool("C_ClassTalents.ImportLoadout")
C_ClassTalents.InitializeViewLoadout = _nil("C_ClassTalents.InitializeViewLoadout")
C_ClassTalents.IsConfigPopulated = _bool("C_ClassTalents.IsConfigPopulated")
C_ClassTalents.LoadConfig = _tbl("C_ClassTalents.LoadConfig")
C_ClassTalents.RenameConfig = _bool("C_ClassTalents.RenameConfig")
C_ClassTalents.RequestNewConfig = _bool("C_ClassTalents.RequestNewConfig")
C_ClassTalents.SaveConfig = _bool("C_ClassTalents.SaveConfig")
C_ClassTalents.SetStarterBuildActive = _nil("C_ClassTalents.SetStarterBuildActive")
C_ClassTalents.SetUsesSharedActionBars = _nil("C_ClassTalents.SetUsesSharedActionBars")
C_ClassTalents.SwitchToLoadoutByIndex = _nil("C_ClassTalents.SwitchToLoadoutByIndex")
C_ClassTalents.SwitchToLoadoutByName = _nil("C_ClassTalents.SwitchToLoadoutByName")
C_ClassTalents.SwitchToSpecializationByIndex = _nil("C_ClassTalents.SwitchToSpecializationByIndex")
C_ClassTalents.SwitchToSpecializationByName = _nil("C_ClassTalents.SwitchToSpecializationByName")
C_ClassTalents.UpdateLastSelectedSavedConfigID = _nil("C_ClassTalents.UpdateLastSelectedSavedConfigID")
C_ClassTalents.ViewLoadout = _bool("C_ClassTalents.ViewLoadout")
-- Events: ACTIVE_COMBAT_CONFIG_CHANGED, CLASS_TALENTS_SWITCH_TO_LOADOUT_BY_INDEX, CLASS_TALENTS_SWITCH_TO_LOADOUT_BY_NAME, CLASS_TALENTS_SWITCH_TO_SPECIALIZATION_BY_INDEX, CLASS_TALENTS_SWITCH_TO_SPECIALIZATION_BY_NAME, SELECTED_LOADOUT_CHANGED, SPECIALIZATION_CHANGE_CAST_FAILED, STARTER_BUILD_ACTIVATION_FAILED
`;
