// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f78a3c8af0b812a6f705c078f18a70a763687cb9217b09f8aaf20e5c45510358
// @sig-hash: sha256:8db412b76cc2d4fc
// Source: Blizzard_APIDocumentationGenerated/classtalentsdocumentation.lua
export const C_ClassTalents = `
if C_ClassTalents == nil then C_ClassTalents = {} end
C_ClassTalents.CanChangeTalents = _bool
C_ClassTalents.CanCreateNewConfig = _bool
C_ClassTalents.CanEditTalents = _bool
C_ClassTalents.CommitConfig = _bool
C_ClassTalents.DeleteConfig = _bool
C_ClassTalents.GetActiveConfigID = _nil
C_ClassTalents.GetActiveHeroTalentSpec = _nil
C_ClassTalents.GetConfigIDsBySpecID = _tbl
C_ClassTalents.GetHasStarterBuild = _bool
C_ClassTalents.GetHeroTalentSpecsForClassSpec = _tbl
C_ClassTalents.GetLastSelectedSavedConfigID = _nil
C_ClassTalents.GetNextStarterBuildPurchase = _nil
C_ClassTalents.GetStarterBuildActive = _bool
C_ClassTalents.GetTraitTreeForSpec = _nil
C_ClassTalents.HasUnspentHeroTalentPoints = _bool
C_ClassTalents.HasUnspentTalentPoints = _bool
C_ClassTalents.ImportLoadout = _bool
C_ClassTalents.InitializeViewLoadout = _nil
C_ClassTalents.IsConfigPopulated = _bool
C_ClassTalents.LoadConfig = _tbl
C_ClassTalents.RenameConfig = _bool
C_ClassTalents.RequestNewConfig = _bool
C_ClassTalents.SaveConfig = _bool
C_ClassTalents.SetStarterBuildActive = _nil
C_ClassTalents.SetUsesSharedActionBars = _nil
C_ClassTalents.SwitchToLoadoutByIndex = _nil
C_ClassTalents.SwitchToLoadoutByName = _nil
C_ClassTalents.SwitchToSpecializationByIndex = _nil
C_ClassTalents.SwitchToSpecializationByName = _nil
C_ClassTalents.UpdateLastSelectedSavedConfigID = _nil
C_ClassTalents.ViewLoadout = _bool
-- Events: ACTIVE_COMBAT_CONFIG_CHANGED, CLASS_TALENTS_SWITCH_TO_LOADOUT_BY_INDEX, CLASS_TALENTS_SWITCH_TO_LOADOUT_BY_NAME, CLASS_TALENTS_SWITCH_TO_SPECIALIZATION_BY_INDEX, CLASS_TALENTS_SWITCH_TO_SPECIALIZATION_BY_NAME, SELECTED_LOADOUT_CHANGED, SPECIALIZATION_CHANGE_CAST_FAILED, STARTER_BUILD_ACTIVATION_FAILED
`;
