// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:28e4909d2b1af5ba686cd8b8d5ac0e3cb269a377fb982b3fe3a635fc7ba90cfa
// @sig-hash: sha256:919eb708e0baef6b
// Source: Blizzard_APIDocumentationGenerated/classcolordocumentation.lua
export const C_ClassColor = `
if C_ClassColor == nil then C_ClassColor = {} end
C_ClassColor.GetClassColor = _nil("C_ClassColor.GetClassColor")
`;
