// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a4de11fe274d68dd18d1807c9776f21f8dac5b2f559b48104b15ac44d3c02460
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/classtrialdocumentation.lua
export const C_ClassTrial = `
if C_ClassTrial == nil then C_ClassTrial = {} end
-- Events: CLASS_TRIAL_TIMER_START, CLASS_TRIAL_UPGRADE_COMPLETE
`;
