// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:46e58427bf6fc8a4bcc793811874e941476098c57ed92ab7a8f9d783d224f295
// @sig-hash: sha256:fdde12d47a742f4e
// Source: Blizzard_APIDocumentationGenerated/classcolordocumentation.lua
export const C_ClassColor = `
if C_ClassColor == nil then C_ClassColor = {} end
C_ClassColor.GetClassColor = _nil
`;
