// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:584b3b4b70e52c3fb63c7f52182786c4bd9aa6577f256974ca5983c1a80e79c7
// @sig-hash: sha256:ba75cc9119cd2e14
// Source: Blizzard_APIDocumentationGenerated/combatlogdocumentation.lua
export const C_CombatLog = `
if C_CombatLog == nil then C_CombatLog = {} end
C_CombatLog.ApplyFilterSettings = _nil("C_CombatLog.ApplyFilterSettings")
C_CombatLog.AreFilteredEventsEnabled = _bool("C_CombatLog.AreFilteredEventsEnabled")
C_CombatLog.ClearEntries = _nil("C_CombatLog.ClearEntries")
C_CombatLog.DoesObjectMatchFilter = _bool("C_CombatLog.DoesObjectMatchFilter")
C_CombatLog.GetEntryRetentionTime = _num("C_CombatLog.GetEntryRetentionTime")
C_CombatLog.GetMessageLimit = _num("C_CombatLog.GetMessageLimit")
C_CombatLog.IsCombatLogRestricted = _bool("C_CombatLog.IsCombatLogRestricted")
C_CombatLog.RefilterEntries = _nil("C_CombatLog.RefilterEntries")
C_CombatLog.SetEntryRetentionTime = _nil("C_CombatLog.SetEntryRetentionTime")
C_CombatLog.SetFilteredEventsEnabled = _nil("C_CombatLog.SetFilteredEventsEnabled")
C_CombatLog.SetMessageLimit = _nil("C_CombatLog.SetMessageLimit")
-- Events: COMBAT_LOG_ENTRIES_CLEARED, COMBAT_LOG_EVENT, COMBAT_LOG_EVENT_UNFILTERED, COMBAT_LOG_MESSAGE_LIMIT_CHANGED
`;
