// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:182eed3c4a12dd47e0fa8191b5bcebffa63cfb5159930041241cb34a41a288ba
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/compactunitframesdocumentation.lua
export const C_CompactUnitFrames = `
if C_CompactUnitFrames == nil then C_CompactUnitFrames = {} end
-- Events: COMPACT_UNIT_FRAME_PROFILES_LOADED
`;
