// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8b2810bb03f1334517f7041bf8903ceb9b9d94333fa42c8f7c434b0599ca0c66
// @sig-hash: sha256:32b22b40a4eaff34
// Source: Blizzard_APIDocumentationGenerated/consolescriptcollectiondocumentation.lua
export const C_ConsoleScriptCollection = `
if C_ConsoleScriptCollection == nil then C_ConsoleScriptCollection = {} end
C_ConsoleScriptCollection.GetCollectionDataByID = _nil
C_ConsoleScriptCollection.GetCollectionDataByTag = _nil
C_ConsoleScriptCollection.GetElements = _tbl
C_ConsoleScriptCollection.GetScriptData = _tbl
`;
