// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e50d8a1558969d6de74c3adbc8b8fd0c57c445889bed0a8fbbf1a05478e063d0
// @sig-hash: sha256:5f76b5a1f872a01c
// Source: Blizzard_APIDocumentationGenerated/configurationwarningsdocumentation.lua
export const C_ConfigurationWarnings = `
if C_ConfigurationWarnings == nil then C_ConfigurationWarnings = {} end
C_ConfigurationWarnings.GetConfigurationWarningSeen = _nil
C_ConfigurationWarnings.GetConfigurationWarningString = _nil
C_ConfigurationWarnings.GetConfigurationWarnings = _tbl
C_ConfigurationWarnings.SetConfigurationWarningSeen = _nil
`;
