// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2efffa8291488e5367e60d89c25c4ea5d68021a52d8a6e21578048f1a055ea24
// @sig-hash: sha256:5560babbbbe1c8c1
// Source: Blizzard_APIDocumentationGenerated/contributioncollectordocumentation.lua
export const C_ContributionCollector = `
if C_ContributionCollector == nil then C_ContributionCollector = {} end
C_ContributionCollector.Close = _nil("C_ContributionCollector.Close")
C_ContributionCollector.Contribute = _nil("C_ContributionCollector.Contribute")
C_ContributionCollector.GetActive = _num("C_ContributionCollector.GetActive")
C_ContributionCollector.GetAtlases = _tbl("C_ContributionCollector.GetAtlases")
C_ContributionCollector.GetBuffs = _num("C_ContributionCollector.GetBuffs")
C_ContributionCollector.GetContributionAppearance = _nil("C_ContributionCollector.GetContributionAppearance")
C_ContributionCollector.GetContributionCollectorsForMap = _tbl("C_ContributionCollector.GetContributionCollectorsForMap")
C_ContributionCollector.GetContributionResult = _nil("C_ContributionCollector.GetContributionResult")
C_ContributionCollector.GetDescription = _str("C_ContributionCollector.GetDescription")
C_ContributionCollector.GetManagedContributionsForCreatureID = _num("C_ContributionCollector.GetManagedContributionsForCreatureID")
C_ContributionCollector.GetName = _str("C_ContributionCollector.GetName")
C_ContributionCollector.GetOrderIndex = _num("C_ContributionCollector.GetOrderIndex")
C_ContributionCollector.GetRequiredContributionCurrency = _num("C_ContributionCollector.GetRequiredContributionCurrency")
C_ContributionCollector.GetRequiredContributionItem = _num("C_ContributionCollector.GetRequiredContributionItem")
C_ContributionCollector.GetRewardQuestID = _num("C_ContributionCollector.GetRewardQuestID")
C_ContributionCollector.GetState = _nil("C_ContributionCollector.GetState")
C_ContributionCollector.HasPendingContribution = _bool("C_ContributionCollector.HasPendingContribution")
C_ContributionCollector.IsAwaitingRewardQuestData = _bool("C_ContributionCollector.IsAwaitingRewardQuestData")
-- Events: CONTRIBUTION_CHANGED, CONTRIBUTION_COLLECTOR_PENDING, CONTRIBUTION_COLLECTOR_UPDATE, CONTRIBUTION_COLLECTOR_UPDATE_SINGLE
`;
