// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:23afe9c8419650442f421110312786fb8e47fafb237252acff19611a81450ae2
// @sig-hash: sha256:fc1facc2df531f2a
// Source: Blizzard_APIDocumentationGenerated/containerdocumentation.lua
export const C_Container = `
if C_Container == nil then C_Container = {} end
C_Container.ContainerIDToInventoryID = _num
C_Container.ContainerRefundItemPurchase = _nil
C_Container.GetBackpackAutosortDisabled = _bool
C_Container.GetBackpackSellJunkDisabled = _bool
C_Container.GetBagName = _str
C_Container.GetBagSlotFlag = _bool
C_Container.GetBankAutosortDisabled = _bool
C_Container.GetContainerFreeSlots = _tbl
C_Container.GetContainerItemCooldown = _num
C_Container.GetContainerItemDurability = _num
C_Container.GetContainerItemEquipmentSetInfo = _bool
C_Container.GetContainerItemID = _num
C_Container.GetContainerItemInfo = _tbl
C_Container.GetContainerItemLink = _str
C_Container.GetContainerItemPurchaseCurrency = _tbl
C_Container.GetContainerItemPurchaseInfo = _tbl
C_Container.GetContainerItemPurchaseItem = _tbl
C_Container.GetContainerItemQuestInfo = _tbl
C_Container.GetContainerNumFreeSlots = _num
C_Container.GetContainerNumSlots = _num
C_Container.GetInsertItemsLeftToRight = _bool
C_Container.GetItemCooldown = _num
C_Container.GetMaxArenaCurrency = _num
C_Container.GetSortBagsRightToLeft = _bool
C_Container.HasContainerItem = _bool
C_Container.IsBattlePayItem = _bool
C_Container.IsContainerFiltered = _bool
C_Container.PickupContainerItem = _nil
C_Container.PlayerHasHearthstone = _nil
C_Container.SetBackpackAutosortDisabled = _nil
C_Container.SetBackpackSellJunkDisabled = _nil
C_Container.SetBagPortraitTexture = _nil
C_Container.SetBagSlotFlag = _nil
C_Container.SetBankAutosortDisabled = _nil
C_Container.SetInsertItemsLeftToRight = _nil
C_Container.SetItemSearch = _nil
C_Container.SetSortBagsRightToLeft = _nil
C_Container.ShowContainerSellCursor = _nil
C_Container.SocketContainerItem = _bool
C_Container.SortAccountBankBags = _nil
C_Container.SortBags = _nil
C_Container.SortBank = _nil
C_Container.SortBankBags = _nil
C_Container.SplitContainerItem = _nil
C_Container.UseContainerItem = _nil
C_Container.UseHearthstone = _bool
-- Events: BAG_CLOSED, BAG_CONTAINER_UPDATE, BAG_NEW_ITEMS_UPDATED, BAG_OPEN, BAG_OVERFLOW_WITH_FULL_INVENTORY, BAG_SLOT_FLAGS_UPDATED, BAG_UPDATE, BAG_UPDATE_COOLDOWN, BAG_UPDATE_DELAYED, EQUIP_BIND_REFUNDABLE_CONFIRM, EQUIP_BIND_TRADEABLE_CONFIRM, EXPAND_BAG_BAR_CHANGED, INVENTORY_SEARCH_UPDATE, ITEM_LOCK_CHANGED, ITEM_LOCKED, ITEM_UNLOCKED, USE_COMBINED_BAGS_CHANGED
`;
