// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b2634cbb94ea6b047e6c1c70d91c0347bddaeb0ba3ea6c57c34b4beb7487a634
// @sig-hash: sha256:2a18c7978c4574b6
// Source: Blizzard_APIDocumentationGenerated/combataudioalertdocumentation.lua
export const C_CombatAudioAlert = `
if C_CombatAudioAlert == nil then C_CombatAudioAlert = {} end
C_CombatAudioAlert.AddToKnownTargetingList = _bool
C_CombatAudioAlert.GetCategoryVoice = _num
C_CombatAudioAlert.GetCategoryVolume = _num
C_CombatAudioAlert.GetFormatSetting = _num
C_CombatAudioAlert.GetSpeakerSpeed = _num
C_CombatAudioAlert.GetSpecSetting = _num
C_CombatAudioAlert.GetThrottle = _num
C_CombatAudioAlert.IsEnabled = _bool
C_CombatAudioAlert.RemoveFromKnownTargetingList = _bool
C_CombatAudioAlert.SetCategoryVoice = _bool
C_CombatAudioAlert.SetCategoryVolume = _bool
C_CombatAudioAlert.SetFormatSetting = _bool
C_CombatAudioAlert.SetSpeakerSpeed = _bool
C_CombatAudioAlert.SetSpecSetting = _bool
C_CombatAudioAlert.SetThrottle = _bool
C_CombatAudioAlert.SpeakText = _nil
`;
