// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:40ce9ece492f816bfe86ac2ddcd9fd8aa7d5aaeefef0711639d9bb37ecfbc4a2
// @sig-hash: sha256:526846230cb4d1a3
// Source: Blizzard_APIDocumentationGenerated/cooldownviewerdocumentation.lua
export const C_CooldownViewer = `
if C_CooldownViewer == nil then C_CooldownViewer = {} end
C_CooldownViewer.GetCooldownViewerCategorySet = _tbl("C_CooldownViewer.GetCooldownViewerCategorySet")
C_CooldownViewer.GetCooldownViewerCooldownInfo = _tbl("C_CooldownViewer.GetCooldownViewerCooldownInfo")
C_CooldownViewer.GetLayoutData = _str("C_CooldownViewer.GetLayoutData")
C_CooldownViewer.GetValidAlertTypes = _tbl("C_CooldownViewer.GetValidAlertTypes")
C_CooldownViewer.IsCooldownViewerAvailable = _bool("C_CooldownViewer.IsCooldownViewerAvailable")
C_CooldownViewer.SetLayoutData = _nil("C_CooldownViewer.SetLayoutData")
-- Events: COOLDOWN_VIEWER_DATA_LOADED, COOLDOWN_VIEWER_SPELL_OVERRIDE_UPDATED, COOLDOWN_VIEWER_TABLE_HOTFIXED
`;
