// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:734249e9702ee4666297bbddbaeca9fcd79109251502803fb0523fff99ef97be
// @sig-hash: sha256:35248581192aa770
// Source: Blizzard_APIDocumentationGenerated/combatlogsecuredocumentation.lua
export const C_CombatLogSecure = `
if C_CombatLogSecure == nil then C_CombatLogSecure = {} end
C_CombatLogSecure.AddEventFilter = _nil
C_CombatLogSecure.ClearEventFilters = _nil
C_CombatLogSecure.CreateCombatLogMessage = _nil
C_CombatLogSecure.GetCurrentEntryInfo = _nil
C_CombatLogSecure.GetCurrentEventInfo = _nil
C_CombatLogSecure.GetEntryCount = _nil
C_CombatLogSecure.SeekToNewestEntry = _nil
C_CombatLogSecure.SeekToPreviousEntry = _nil
C_CombatLogSecure.ShouldShowCurrentEntry = _nil
-- Events: COMBAT_LOG_APPLY_FILTER_SETTINGS, COMBAT_LOG_MESSAGE, COMBAT_LOG_REFILTER_ENTRIES
`;
