// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d2a26683d08874ed591bca216e8a3cb06419f3c463d36d64b7ddb8098bf438da
// @sig-hash: sha256:f58a77312e1f44eb
// Source: Blizzard_APIDocumentationGenerated/cooldownviewerdocumentation.lua
export const C_CooldownViewer = `
if C_CooldownViewer == nil then C_CooldownViewer = {} end
C_CooldownViewer.GetCooldownViewerCategorySet = _tbl
C_CooldownViewer.GetCooldownViewerCooldownInfo = _tbl
C_CooldownViewer.GetLayoutData = _str
C_CooldownViewer.GetValidAlertTypes = _tbl
C_CooldownViewer.IsCooldownViewerAvailable = _bool
C_CooldownViewer.SetLayoutData = _nil
-- Events: COOLDOWN_VIEWER_DATA_LOADED, COOLDOWN_VIEWER_SPELL_OVERRIDE_UPDATED, COOLDOWN_VIEWER_TABLE_HOTFIXED
`;
