// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b4fd2facd8b5f9cf7f05b3e0609344065df7a9ffb5bd82944675a0290e89f0e0
// @sig-hash: sha256:ff992c472dc06c45
// Source: Blizzard_APIDocumentationGenerated/covenantsanctumdocumentation.lua
export const C_CovenantSanctumUI = `
if C_CovenantSanctumUI == nil then C_CovenantSanctumUI = {} end
C_CovenantSanctumUI.CanAccessReservoir = _bool("C_CovenantSanctumUI.CanAccessReservoir")
C_CovenantSanctumUI.CanDepositAnima = _bool("C_CovenantSanctumUI.CanDepositAnima")
C_CovenantSanctumUI.DepositAnima = _nil("C_CovenantSanctumUI.DepositAnima")
C_CovenantSanctumUI.EndInteraction = _nil("C_CovenantSanctumUI.EndInteraction")
C_CovenantSanctumUI.GetAnimaInfo = _num("C_CovenantSanctumUI.GetAnimaInfo")
C_CovenantSanctumUI.GetCurrentTalentTreeID = _nil("C_CovenantSanctumUI.GetCurrentTalentTreeID")
C_CovenantSanctumUI.GetFeatures = _tbl("C_CovenantSanctumUI.GetFeatures")
C_CovenantSanctumUI.GetRenownLevel = _num("C_CovenantSanctumUI.GetRenownLevel")
C_CovenantSanctumUI.GetRenownLevels = _tbl("C_CovenantSanctumUI.GetRenownLevels")
C_CovenantSanctumUI.GetRenownRewardsForLevel = _tbl("C_CovenantSanctumUI.GetRenownRewardsForLevel")
C_CovenantSanctumUI.GetSanctumType = _nil("C_CovenantSanctumUI.GetSanctumType")
C_CovenantSanctumUI.GetSoulCurrencies = _tbl("C_CovenantSanctumUI.GetSoulCurrencies")
C_CovenantSanctumUI.HasMaximumRenown = _bool("C_CovenantSanctumUI.HasMaximumRenown")
C_CovenantSanctumUI.IsPlayerInRenownCatchUpMode = _bool("C_CovenantSanctumUI.IsPlayerInRenownCatchUpMode")
C_CovenantSanctumUI.IsWeeklyRenownCapped = _bool("C_CovenantSanctumUI.IsWeeklyRenownCapped")
C_CovenantSanctumUI.RequestCatchUpState = _nil("C_CovenantSanctumUI.RequestCatchUpState")
-- Events: COVENANT_RENOWN_CATCH_UP_STATE_UPDATE, COVENANT_SANCTUM_RENOWN_LEVEL_CHANGED
`;
