// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:54ce2ac4ed30b9f0ebaca739e6790d5b1e1c534802079e8a0273aa3c4655f32b
// @sig-hash: sha256:c485512a59540174
// Source: Blizzard_APIDocumentationGenerated/combataudioalertdocumentation.lua
export const C_CombatAudioAlert = `
if C_CombatAudioAlert == nil then C_CombatAudioAlert = {} end
C_CombatAudioAlert.AddToKnownTargetingList = _bool("C_CombatAudioAlert.AddToKnownTargetingList")
C_CombatAudioAlert.GetCategoryVoice = _num("C_CombatAudioAlert.GetCategoryVoice")
C_CombatAudioAlert.GetCategoryVolume = _num("C_CombatAudioAlert.GetCategoryVolume")
C_CombatAudioAlert.GetFormatSetting = _num("C_CombatAudioAlert.GetFormatSetting")
C_CombatAudioAlert.GetSpeakerSpeed = _num("C_CombatAudioAlert.GetSpeakerSpeed")
C_CombatAudioAlert.GetSpecSetting = _num("C_CombatAudioAlert.GetSpecSetting")
C_CombatAudioAlert.GetThrottle = _num("C_CombatAudioAlert.GetThrottle")
C_CombatAudioAlert.IsEnabled = _bool("C_CombatAudioAlert.IsEnabled")
C_CombatAudioAlert.RemoveFromKnownTargetingList = _bool("C_CombatAudioAlert.RemoveFromKnownTargetingList")
C_CombatAudioAlert.SetCategoryVoice = _bool("C_CombatAudioAlert.SetCategoryVoice")
C_CombatAudioAlert.SetCategoryVolume = _bool("C_CombatAudioAlert.SetCategoryVolume")
C_CombatAudioAlert.SetFormatSetting = _bool("C_CombatAudioAlert.SetFormatSetting")
C_CombatAudioAlert.SetSpeakerSpeed = _bool("C_CombatAudioAlert.SetSpeakerSpeed")
C_CombatAudioAlert.SetSpecSetting = _bool("C_CombatAudioAlert.SetSpecSetting")
C_CombatAudioAlert.SetThrottle = _bool("C_CombatAudioAlert.SetThrottle")
C_CombatAudioAlert.SpeakText = _nil("C_CombatAudioAlert.SpeakText")
`;
