// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0963a70a844ede8b691c4c9673ad15760efdb4762312a25416cb1892d100638e
// @sig-hash: sha256:ad97c160df4f1782
// Source: Blizzard_APIDocumentationGenerated/coloroverridesdocumentation.lua
export const C_ColorOverrides = `
if C_ColorOverrides == nil then C_ColorOverrides = {} end
C_ColorOverrides.ClearColorOverrides = _nil
C_ColorOverrides.GetColorForQuality = _nil
C_ColorOverrides.GetColorOverrideInfo = _nil
C_ColorOverrides.GetDefaultColorForQuality = _nil
C_ColorOverrides.RemoveColorOverride = _nil
C_ColorOverrides.SetColorOverride = _nil
-- Events: COLOR_OVERRIDE_UPDATED, COLOR_OVERRIDES_RESET
`;
