// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a7252d9299d2d3886112d0dccc8481070ca2e08d2b0454435423ea46658dd1b7
// @sig-hash: sha256:6cbf7f26be515fc3
// Source: Blizzard_APIDocumentationGenerated/covenantpreviewdocumentation.lua
export const C_CovenantPreview = `
if C_CovenantPreview == nil then C_CovenantPreview = {} end
C_CovenantPreview.CloseFromUI = _nil
C_CovenantPreview.GetCovenantInfoForPlayerChoiceResponseID = _tbl
-- Events: COVENANT_PREVIEW_CLOSE, COVENANT_PREVIEW_OPEN
`;
