// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:660ba8035acbb1b5b1675228820920b3edb27ed1f547aa798378776c4dcf9dc2
// @sig-hash: sha256:35da2cefd733be50
// Source: Blizzard_APIDocumentationGenerated/colorutildocumentation.lua
export const C_ColorUtil = `
if C_ColorUtil == nil then C_ColorUtil = {} end
C_ColorUtil.ConvertHSLToHSV = _num
C_ColorUtil.ConvertHSVToHSL = _num
C_ColorUtil.ConvertHSVToRGB = _num
C_ColorUtil.ConvertRGBToHSV = _num
C_ColorUtil.GenerateTextColorCode = _str
C_ColorUtil.WrapTextInColor = _str
C_ColorUtil.WrapTextInColorCode = _str
`;
