// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a3afb05630b9df07314247a9334cb98ab3000132e3e48a4d33029b2860659176
// @sig-hash: sha256:8fb146161c3752f3
// Source: Blizzard_APIDocumentationGenerated/consolescriptcollectiondocumentation.lua
export const C_ConsoleScriptCollection = `
if C_ConsoleScriptCollection == nil then C_ConsoleScriptCollection = {} end
C_ConsoleScriptCollection.GetCollectionDataByID = _nil("C_ConsoleScriptCollection.GetCollectionDataByID")
C_ConsoleScriptCollection.GetCollectionDataByTag = _nil("C_ConsoleScriptCollection.GetCollectionDataByTag")
C_ConsoleScriptCollection.GetElements = _tbl("C_ConsoleScriptCollection.GetElements")
C_ConsoleScriptCollection.GetScriptData = _tbl("C_ConsoleScriptCollection.GetScriptData")
`;
