// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a415624ddba27a3dd8cae6bd1948c8cf93fe8b168cf2f1227d89bbd8c744cd9b
// @sig-hash: sha256:28de47420f85a3e2
// Source: Blizzard_APIDocumentationGenerated/colorutildocumentation.lua
export const C_ColorUtil = `
if C_ColorUtil == nil then C_ColorUtil = {} end
C_ColorUtil.ConvertHSLToHSV = _num("C_ColorUtil.ConvertHSLToHSV")
C_ColorUtil.ConvertHSVToHSL = _num("C_ColorUtil.ConvertHSVToHSL")
C_ColorUtil.ConvertHSVToRGB = _num("C_ColorUtil.ConvertHSVToRGB")
C_ColorUtil.ConvertRGBToHSV = _num("C_ColorUtil.ConvertRGBToHSV")
C_ColorUtil.GenerateTextColorCode = _str("C_ColorUtil.GenerateTextColorCode")
C_ColorUtil.WrapTextInColor = _str("C_ColorUtil.WrapTextInColor")
C_ColorUtil.WrapTextInColorCode = _str("C_ColorUtil.WrapTextInColorCode")
`;
