// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4c6f7cac03c16475f79984cc606201ba2fa13e5d8a75b7918251584239493684
// @sig-hash: sha256:e5eb8f6c30b538a4
// Source: Blizzard_APIDocumentationGenerated/configurationwarningsdocumentation.lua
export const C_ConfigurationWarnings = `
if C_ConfigurationWarnings == nil then C_ConfigurationWarnings = {} end
C_ConfigurationWarnings.GetConfigurationWarningSeen = _bool("C_ConfigurationWarnings.GetConfigurationWarningSeen")
C_ConfigurationWarnings.GetConfigurationWarningString = _str("C_ConfigurationWarnings.GetConfigurationWarningString")
C_ConfigurationWarnings.GetConfigurationWarnings = _tbl("C_ConfigurationWarnings.GetConfigurationWarnings")
C_ConfigurationWarnings.SetConfigurationWarningSeen = _nil("C_ConfigurationWarnings.SetConfigurationWarningSeen")
`;
