// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b067ccbad64e1b477c48769bfddab9afa0fc41766d0f36268955eea21e7ed73b
// @sig-hash: sha256:1c61435c197ad00e
// Source: Blizzard_APIDocumentationGenerated/combattextdocumentation.lua
export const C_CombatText = `
if C_CombatText == nil then C_CombatText = {} end
C_CombatText.GetActiveUnit = _nil
C_CombatText.GetCurrentEventInfo = _nil
C_CombatText.SetActiveUnit = _nil
-- Events: COMBAT_TEXT_UPDATE
`;
