// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5745abecc9e767af85599e328e74db995c73a4e3d8f2f428e6cd00febcc70a16
// @sig-hash: sha256:ecf68d9e9f0917c0
// Source: Blizzard_APIDocumentationGenerated/covenantsdocumentation.lua
export const C_Covenants = `
if C_Covenants == nil then C_Covenants = {} end
C_Covenants.GetActiveCovenantID = _num
C_Covenants.GetCovenantData = _nil
C_Covenants.GetCovenantIDs = _tbl
-- Events: COVENANT_CHOSEN
`;
