// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8dd12f87668be706d338d01efe66a1967a94d924cbf988aaf5388f02389ea7fe
// @sig-hash: sha256:65e62e7b775a1b0b
// Source: Blizzard_APIDocumentationGenerated/combatlogsecuredocumentation.lua
export const C_CombatLogSecure = `
if C_CombatLogSecure == nil then C_CombatLogSecure = {} end
C_CombatLogSecure.AddEventFilter = _nil("C_CombatLogSecure.AddEventFilter")
C_CombatLogSecure.ClearEventFilters = _nil("C_CombatLogSecure.ClearEventFilters")
C_CombatLogSecure.CreateCombatLogMessage = _nil("C_CombatLogSecure.CreateCombatLogMessage")
C_CombatLogSecure.GetCurrentEntryInfo = _nil("C_CombatLogSecure.GetCurrentEntryInfo")
C_CombatLogSecure.GetCurrentEventInfo = _nil("C_CombatLogSecure.GetCurrentEventInfo")
C_CombatLogSecure.GetEntryCount = _num("C_CombatLogSecure.GetEntryCount")
C_CombatLogSecure.SeekToNewestEntry = _bool("C_CombatLogSecure.SeekToNewestEntry")
C_CombatLogSecure.SeekToPreviousEntry = _bool("C_CombatLogSecure.SeekToPreviousEntry")
C_CombatLogSecure.ShouldShowCurrentEntry = _bool("C_CombatLogSecure.ShouldShowCurrentEntry")
-- Events: COMBAT_LOG_APPLY_FILTER_SETTINGS, COMBAT_LOG_MESSAGE, COMBAT_LOG_REFILTER_ENTRIES
`;
