// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:32159d16c65b2d2c3fb2dcb6f09caef1edb48b7188e28590d1d8de06628e762c
// @sig-hash: sha256:86634fd145a37341
// Source: Blizzard_APIDocumentationGenerated/combatloginternaldocumentation.lua
export const C_CombatLogInternal = `
if C_CombatLogInternal == nil then C_CombatLogInternal = {} end
C_CombatLogInternal.GetCurrentEventInfo = _nil("C_CombatLogInternal.GetCurrentEventInfo")
-- Events: COMBAT_LOG_EVENT_INTERNAL_UNFILTERED
`;
