// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:24efdc1359b750ba410a64102a6fed19f98c018623d879234e829df08c6e1919
// @sig-hash: sha256:e1b0e307b0b48ea2
// Source: Blizzard_APIDocumentationGenerated/combatloginternaldocumentation.lua
export const C_CombatLogInternal = `
if C_CombatLogInternal == nil then C_CombatLogInternal = {} end
C_CombatLogInternal.GetCurrentEventInfo = _nil
-- Events: COMBAT_LOG_EVENT_INTERNAL_UNFILTERED
`;
