// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fb489bcbc903d39afebd3743f06052eb4a1e1415d916d14184fb4a20935f153c
// @sig-hash: sha256:23bc30310b8610b5
// Source: Blizzard_APIDocumentationGenerated/creatureinfodocumentation.lua
export const C_CreatureInfo = `
if C_CreatureInfo == nil then C_CreatureInfo = {} end
C_CreatureInfo.GetClassInfo = _nil("C_CreatureInfo.GetClassInfo")
C_CreatureInfo.GetCreatureFamilyIDs = _tbl("C_CreatureInfo.GetCreatureFamilyIDs")
C_CreatureInfo.GetCreatureFamilyInfo = _nil("C_CreatureInfo.GetCreatureFamilyInfo")
C_CreatureInfo.GetCreatureID = _nil("C_CreatureInfo.GetCreatureID")
C_CreatureInfo.GetCreatureTypeIDs = _tbl("C_CreatureInfo.GetCreatureTypeIDs")
C_CreatureInfo.GetCreatureTypeInfo = _nil("C_CreatureInfo.GetCreatureTypeInfo")
C_CreatureInfo.GetFactionInfo = _nil("C_CreatureInfo.GetFactionInfo")
C_CreatureInfo.GetRaceInfo = _nil("C_CreatureInfo.GetRaceInfo")
`;
