// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:74ab6521b83ad8f06b8f609f33bde97fe2fecd65bec690c728aef1c3316a4233
// @sig-hash: sha256:7077269249fb87e4
// Source: Blizzard_APIDocumentationGenerated/craftingorderuidocumentation.lua
export const C_CraftingOrders = `
if C_CraftingOrders == nil then C_CraftingOrders = {} end
C_CraftingOrders.AreOrderNotesDisabled = _bool("C_CraftingOrders.AreOrderNotesDisabled")
C_CraftingOrders.CalculateCraftingOrderPostingFee = _nil("C_CraftingOrders.CalculateCraftingOrderPostingFee")
C_CraftingOrders.CanOrderSkillAbility = _bool("C_CraftingOrders.CanOrderSkillAbility")
C_CraftingOrders.CancelOrder = _nil("C_CraftingOrders.CancelOrder")
C_CraftingOrders.ClaimOrder = _nil("C_CraftingOrders.ClaimOrder")
C_CraftingOrders.CloseCrafterCraftingOrders = _nil("C_CraftingOrders.CloseCrafterCraftingOrders")
C_CraftingOrders.CloseCustomerCraftingOrders = _nil("C_CraftingOrders.CloseCustomerCraftingOrders")
C_CraftingOrders.FulfillOrder = _nil("C_CraftingOrders.FulfillOrder")
C_CraftingOrders.GetClaimedOrder = _nil("C_CraftingOrders.GetClaimedOrder")
C_CraftingOrders.GetCrafterBuckets = _tbl("C_CraftingOrders.GetCrafterBuckets")
C_CraftingOrders.GetCrafterOrders = _tbl("C_CraftingOrders.GetCrafterOrders")
C_CraftingOrders.GetCraftingOrderTime = _nil("C_CraftingOrders.GetCraftingOrderTime")
C_CraftingOrders.GetCustomerCategories = _tbl("C_CraftingOrders.GetCustomerCategories")
C_CraftingOrders.GetCustomerOptions = _tbl("C_CraftingOrders.GetCustomerOptions")
C_CraftingOrders.GetCustomerOrders = _tbl("C_CraftingOrders.GetCustomerOrders")
C_CraftingOrders.GetDefaultOrdersSkillLine = _nil("C_CraftingOrders.GetDefaultOrdersSkillLine")
C_CraftingOrders.GetMyOrders = _tbl("C_CraftingOrders.GetMyOrders")
C_CraftingOrders.GetNumFavoriteCustomerOptions = _nil("C_CraftingOrders.GetNumFavoriteCustomerOptions")
C_CraftingOrders.GetOrderClaimInfo = _tbl("C_CraftingOrders.GetOrderClaimInfo")
C_CraftingOrders.GetPersonalOrdersInfo = _tbl("C_CraftingOrders.GetPersonalOrdersInfo")
C_CraftingOrders.HasFavoriteCustomerOptions = _bool("C_CraftingOrders.HasFavoriteCustomerOptions")
C_CraftingOrders.IsCustomerOptionFavorited = _bool("C_CraftingOrders.IsCustomerOptionFavorited")
C_CraftingOrders.ListMyOrders = _nil("C_CraftingOrders.ListMyOrders")
C_CraftingOrders.OpenCrafterCraftingOrders = _nil("C_CraftingOrders.OpenCrafterCraftingOrders")
C_CraftingOrders.OpenCustomerCraftingOrders = _nil("C_CraftingOrders.OpenCustomerCraftingOrders")
C_CraftingOrders.OrderCanBeRecrafted = _bool("C_CraftingOrders.OrderCanBeRecrafted")
C_CraftingOrders.ParseCustomerOptions = _nil("C_CraftingOrders.ParseCustomerOptions")
C_CraftingOrders.PlaceNewOrder = _nil("C_CraftingOrders.PlaceNewOrder")
C_CraftingOrders.RejectOrder = _nil("C_CraftingOrders.RejectOrder")
C_CraftingOrders.ReleaseOrder = _nil("C_CraftingOrders.ReleaseOrder")
C_CraftingOrders.RequestCrafterOrders = _nil("C_CraftingOrders.RequestCrafterOrders")
C_CraftingOrders.RequestCustomerOrders = _nil("C_CraftingOrders.RequestCustomerOrders")
C_CraftingOrders.SetCustomerOptionFavorited = _nil("C_CraftingOrders.SetCustomerOptionFavorited")
C_CraftingOrders.ShouldShowCraftingOrderTab = _bool("C_CraftingOrders.ShouldShowCraftingOrderTab")
C_CraftingOrders.SkillLineHasOrders = _bool("C_CraftingOrders.SkillLineHasOrders")
C_CraftingOrders.UpdateIgnoreList = _nil("C_CraftingOrders.UpdateIgnoreList")
-- Events: CRAFTING_HOUSE_DISABLED, CRAFTINGORDERS_CAN_REQUEST, CRAFTINGORDERS_CLAIM_ORDER_RESPONSE, CRAFTINGORDERS_CLAIMED_ORDER_ADDED, CRAFTINGORDERS_CLAIMED_ORDER_REMOVED, CRAFTINGORDERS_CLAIMED_ORDER_UPDATED, CRAFTINGORDERS_CRAFT_ORDER_RESPONSE, CRAFTINGORDERS_CUSTOMER_FAVORITES_CHANGED, CRAFTINGORDERS_CUSTOMER_OPTIONS_PARSED, CRAFTINGORDERS_DISPLAY_CRAFTER_FULFILLED_MSG, CRAFTINGORDERS_FULFILL_ORDER_RESPONSE, CRAFTINGORDERS_HIDE_CRAFTER, CRAFTINGORDERS_HIDE_CUSTOMER, CRAFTINGORDERS_ORDER_CANCEL_RESPONSE, CRAFTINGORDERS_ORDER_PLACEMENT_RESPONSE, CRAFTINGORDERS_REJECT_ORDER_RESPONSE, CRAFTINGORDERS_RELEASE_ORDER_RESPONSE, CRAFTINGORDERS_SHOW_CRAFTER, CRAFTINGORDERS_SHOW_CUSTOMER, CRAFTINGORDERS_UNEXPECTED_ERROR, CRAFTINGORDERS_UPDATE_CUSTOMER_NAME, CRAFTINGORDERS_UPDATE_ORDER_COUNT, CRAFTINGORDERS_UPDATE_PERSONAL_ORDER_COUNTS, CRAFTINGORDERS_UPDATE_REWARDS
`;
