// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fdd9d58b0c718b45fac07e3437e832f86f26587559001e3cad3a203d4fef2c74
// @sig-hash: sha256:8a81eec7845f0e3c
// Source: Blizzard_APIDocumentationGenerated/cursordocumentation.lua
export const C_Cursor = `
if C_Cursor == nil then C_Cursor = {} end
C_Cursor.GetCursorItem = _nil("C_Cursor.GetCursorItem")
-- Events: BATTLE_PET_CURSOR_CLEAR, CURSOR_CHANGED, MOUNT_CURSOR_CLEAR, WORLD_CURSOR_TOOLTIP_UPDATE
`;
