// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:70f53f6cd9ade0693f8abb0260fe19c6a0b4c611d73d39eba5cddc1151262a4e
// @sig-hash: sha256:8b4d91677c3b38e7
// Source: Blizzard_APIDocumentationGenerated/curveutildocumentation.lua
export const C_CurveUtil = `
if C_CurveUtil == nil then C_CurveUtil = {} end
C_CurveUtil.CreateColorCurve = _nil
C_CurveUtil.CreateCurve = _nil
C_CurveUtil.EvaluateColorFromBoolean = _nil
C_CurveUtil.EvaluateColorValueFromBoolean = _nil
C_CurveUtil.EvaluateGameCurve = _nil
`;
