// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f7feddcd3f76014e0f888773e94ace12234f1b58fab0adcae74227691c24e665
// @sig-hash: sha256:066e935b72f67fdb
// Source: Blizzard_APIDocumentationGenerated/currencyinfodocumentation.lua
export const C_CurrencyInfo = `
if C_CurrencyInfo == nil then C_CurrencyInfo = {} end
C_CurrencyInfo.CanTransferCurrency = _nil
C_CurrencyInfo.DoesCurrentFilterRequireAccountCurrencyData = _nil
C_CurrencyInfo.DoesWarModeBonusApply = _nil
C_CurrencyInfo.ExpandCurrencyList = _nil
C_CurrencyInfo.FetchCurrencyDataFromAccountCharacters = _tbl
C_CurrencyInfo.FetchCurrencyTransferTransactions = _tbl
C_CurrencyInfo.GetAzeriteCurrencyID = _nil
C_CurrencyInfo.GetBackpackCurrencyInfo = _tbl
C_CurrencyInfo.GetBasicCurrencyInfo = _tbl
C_CurrencyInfo.GetCoinIcon = _nil
C_CurrencyInfo.GetCoinText = _nil
C_CurrencyInfo.GetCoinTextureString = _nil
C_CurrencyInfo.GetCostToTransferCurrency = _nil
C_CurrencyInfo.GetCurrencyContainerInfo = _tbl
C_CurrencyInfo.GetCurrencyDescription = _nil
C_CurrencyInfo.GetCurrencyFilter = _nil
C_CurrencyInfo.GetCurrencyIDFromLink = _nil
C_CurrencyInfo.GetCurrencyInfo = _tbl
C_CurrencyInfo.GetCurrencyInfoFromLink = _tbl
C_CurrencyInfo.GetCurrencyLink = _nil
C_CurrencyInfo.GetCurrencyListInfo = _tbl
C_CurrencyInfo.GetCurrencyListLink = _nil
C_CurrencyInfo.GetCurrencyListSize = _nil
C_CurrencyInfo.GetDragonIslesSuppliesCurrencyID = _nil
C_CurrencyInfo.GetFactionGrantedByCurrency = _nil
C_CurrencyInfo.GetMaxTransferableAmountFromQuantity = _nil
C_CurrencyInfo.GetPlayerCurrencyCategoryInfo = _tbl
C_CurrencyInfo.GetWarResourcesCurrencyID = _nil
C_CurrencyInfo.IsAccountCharacterCurrencyDataReady = _nil
C_CurrencyInfo.IsAccountTransferableCurrency = _nil
C_CurrencyInfo.IsAccountWideCurrency = _nil
C_CurrencyInfo.IsCurrencyContainer = _nil
C_CurrencyInfo.IsCurrencyTransferInProgress = _nil
C_CurrencyInfo.IsCurrencyTransferTransactionDataReady = _nil
C_CurrencyInfo.PickupCurrency = _nil
C_CurrencyInfo.PlayerHasMaxQuantity = _nil
C_CurrencyInfo.PlayerHasMaxWeeklyQuantity = _nil
C_CurrencyInfo.RequestCurrencyDataForAccountCharacters = _nil
C_CurrencyInfo.RequestCurrencyFromAccountCharacter = _nil
C_CurrencyInfo.SetCurrencyBackpack = _nil
C_CurrencyInfo.SetCurrencyBackpackByID = _nil
C_CurrencyInfo.SetCurrencyFilter = _nil
C_CurrencyInfo.SetCurrencyUnused = _nil
-- Events: ACCOUNT_CHARACTER_CURRENCY_DATA_RECEIVED, ACCOUNT_MONEY, CURRENCY_DISPLAY_UPDATE, CURRENCY_TRANSFER_FAILED, CURRENCY_TRANSFER_INITIATED, CURRENCY_TRANSFER_LOG_UPDATE, CURRENCY_TRANSFER_SUCCESS, PLAYER_MONEY
`;
