// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:91ad1499ded4b9e522fa5ce0dc3622dad483b9ccd64f2f51d14a9311332469e0
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/cursorutildocumentation.lua
export const C_CursorUtil = `
if C_CursorUtil == nil then C_CursorUtil = {} end
`;
