// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6f16d744f89c3ef026df2cebe907fff79aef3af8b1223b6969c49a6071b2090b
// @sig-hash: sha256:080c4749ecf7b89e
// Source: Blizzard_APIDocumentationGenerated/curveutildocumentation.lua
export const C_CurveUtil = `
if C_CurveUtil == nil then C_CurveUtil = {} end
C_CurveUtil.CreateColorCurve = _nil("C_CurveUtil.CreateColorCurve")
C_CurveUtil.CreateCurve = _nil("C_CurveUtil.CreateCurve")
C_CurveUtil.EvaluateColorFromBoolean = _nil("C_CurveUtil.EvaluateColorFromBoolean")
C_CurveUtil.EvaluateColorValueFromBoolean = _nil("C_CurveUtil.EvaluateColorValueFromBoolean")
C_CurveUtil.EvaluateGameCurve = _num("C_CurveUtil.EvaluateGameCurve")
`;
