// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5248329d20895f55974de61675f0ff53e4d9c65b2deee1ddf4257b98cc045a42
// @sig-hash: sha256:41628b829f1d8aba
// Source: Blizzard_APIDocumentationGenerated/cursordocumentation.lua
export const C_Cursor = `
if C_Cursor == nil then C_Cursor = {} end
C_Cursor.GetCursorItem = _nil
-- Events: BATTLE_PET_CURSOR_CLEAR, CURSOR_CHANGED, MOUNT_CURSOR_CLEAR, WORLD_CURSOR_TOOLTIP_UPDATE
`;
