// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5e9529026699105b09edbed8eb0e48db257981bffd4e3dd40351210b924a0e6e
// @sig-hash: sha256:e799e03703c8153b
// Source: Blizzard_APIDocumentationGenerated/cvardocumentation.lua
export const C_CVar = `
if C_CVar == nil then C_CVar = {} end
C_CVar.GetCVar = _nil("C_CVar.GetCVar")
C_CVar.GetCVarBitfield = _nil("C_CVar.GetCVarBitfield")
C_CVar.GetCVarBool = _nil("C_CVar.GetCVarBool")
C_CVar.GetCVarDefault = _nil("C_CVar.GetCVarDefault")
C_CVar.GetCVarInfo = _str("C_CVar.GetCVarInfo")
C_CVar.RegisterCVar = _nil("C_CVar.RegisterCVar")
C_CVar.ResetTestCVars = _nil("C_CVar.ResetTestCVars")
C_CVar.SetCVar = _bool("C_CVar.SetCVar")
C_CVar.SetCVarBitfield = _bool("C_CVar.SetCVarBitfield")
`;
