// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6102e44a3d05b6a3ddd5e815fd1f14b77db6f794a2ffc742fe747e46fafac077
// @sig-hash: sha256:b6151e3ea0ab8964
// Source: Blizzard_APIDocumentationGenerated/cvardocumentation.lua
export const C_CVar = `
if C_CVar == nil then C_CVar = {} end
C_CVar.GetCVar = _nil
C_CVar.GetCVarBitfield = _nil
C_CVar.GetCVarBool = _nil
C_CVar.GetCVarDefault = _nil
C_CVar.GetCVarInfo = _nil
C_CVar.RegisterCVar = _nil
C_CVar.ResetTestCVars = _nil
C_CVar.SetCVar = _nil
C_CVar.SetCVarBitfield = _nil
`;
