// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6ba57a3bfb8e989f9347aa13e167af4d5fed43dc2828a749047db962b8db1746
// @sig-hash: sha256:5667ea11fde6912e
// Source: Blizzard_APIDocumentationGenerated/dateandtimedocumentation.lua
export const C_DateAndTime = `
if C_DateAndTime == nil then C_DateAndTime = {} end
C_DateAndTime.AdjustTimeByDays = _tbl
C_DateAndTime.AdjustTimeByMinutes = _tbl
C_DateAndTime.AdjustTimeByMonths = _tbl
C_DateAndTime.CompareCalendarTime = _nil
C_DateAndTime.GetCalendarTimeFromEpoch = _tbl
C_DateAndTime.GetCurrentCalendarTime = _tbl
C_DateAndTime.GetSecondsUntilDailyReset = _nil
C_DateAndTime.GetSecondsUntilWeeklyReset = _nil
C_DateAndTime.GetServerTimeLocal = _nil
C_DateAndTime.GetWeeklyResetStartTime = _nil
`;
