// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5ce96407db78f703d9825b71e5da8db2517102943d00d6b207af1d1fed3d2264
// @sig-hash: sha256:a15aaefa592b21f3
// Source: Blizzard_APIDocumentationGenerated/damagemeterdocumentation.lua
export const C_DamageMeter = `
if C_DamageMeter == nil then C_DamageMeter = {} end
C_DamageMeter.GetAvailableCombatSessions = _tbl
C_DamageMeter.GetCombatSessionFromID = _tbl
C_DamageMeter.GetCombatSessionFromType = _tbl
C_DamageMeter.GetCombatSessionSourceFromID = _tbl
C_DamageMeter.GetCombatSessionSourceFromType = _tbl
C_DamageMeter.GetSessionDurationSeconds = _nil
C_DamageMeter.IsDamageMeterAvailable = _nil
C_DamageMeter.ResetAllCombatSessions = _nil
-- Events: DAMAGE_METER_COMBAT_SESSION_UPDATED, DAMAGE_METER_CURRENT_SESSION_UPDATED, DAMAGE_METER_RESET
`;
