// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:77889762bc9a48bf74a9b73f55ba26b51b1dc7d3868f55432f61ec3822d97569
// @sig-hash: sha256:60f47a1cf6ed24f8
// Source: Blizzard_APIDocumentationGenerated/deathinfodocumentation.lua
export const C_DeathInfo = `
if C_DeathInfo == nil then C_DeathInfo = {} end
C_DeathInfo.GetCorpseMapPosition = _nil
C_DeathInfo.GetDeathReleasePosition = _nil
C_DeathInfo.GetGraveyardsForMap = _tbl
C_DeathInfo.GetSelfResurrectOptions = _tbl
C_DeathInfo.UseSelfResurrectOption = _nil
-- Events: AREA_SPIRIT_HEALER_IN_RANGE, AREA_SPIRIT_HEALER_OUT_OF_RANGE, CEMETERY_PREFERENCE_UPDATED, CONFIRM_XP_LOSS, CORPSE_IN_INSTANCE, CORPSE_IN_RANGE, CORPSE_OUT_OF_RANGE, PLAYER_ALIVE, PLAYER_DEAD, PLAYER_SKINNED, PLAYER_UNGHOST, REQUEST_CEMETERY_LIST_RESPONSE, RESURRECT_REQUEST, SELF_RES_SPELL_CHANGED
`;
