// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1afd91b876998142268b214fcf404fde8329dfd570c8e5bd12bcbfda12843da9
// @sig-hash: sha256:9a7c34659afa7cd3
// Source: Blizzard_APIDocumentationGenerated/deathinfodocumentation.lua
export const C_DeathInfo = `
if C_DeathInfo == nil then C_DeathInfo = {} end
C_DeathInfo.GetCorpseMapPosition = _nil("C_DeathInfo.GetCorpseMapPosition")
C_DeathInfo.GetDeathReleasePosition = _nil("C_DeathInfo.GetDeathReleasePosition")
C_DeathInfo.GetGraveyardsForMap = _tbl("C_DeathInfo.GetGraveyardsForMap")
C_DeathInfo.GetSelfResurrectOptions = _tbl("C_DeathInfo.GetSelfResurrectOptions")
C_DeathInfo.UseSelfResurrectOption = _nil("C_DeathInfo.UseSelfResurrectOption")
-- Events: AREA_SPIRIT_HEALER_IN_RANGE, AREA_SPIRIT_HEALER_OUT_OF_RANGE, CEMETERY_PREFERENCE_UPDATED, CONFIRM_XP_LOSS, CORPSE_IN_INSTANCE, CORPSE_IN_RANGE, CORPSE_OUT_OF_RANGE, PLAYER_ALIVE, PLAYER_DEAD, PLAYER_SKINNED, PLAYER_UNGHOST, REQUEST_CEMETERY_LIST_RESPONSE, RESURRECT_REQUEST, SELF_RES_SPELL_CHANGED
`;
