// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b843718d0707e5a555851f63072035a14c81cb05f65798d4f0f8a9dba4433252
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/deathalertdocumentation.lua
export const C_DeathAlert = `
if C_DeathAlert == nil then C_DeathAlert = {} end
-- Events: HARDCORE_DEATHS
`;
