// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:28f836bb411515fe39005b19e030b894914c46168782313187104e3d912f9669
// @sig-hash: sha256:662b240b9f30c803
// Source: Blizzard_APIDocumentationGenerated/delvesuidocumentation.lua
export const C_DelvesUI = `
if C_DelvesUI == nil then C_DelvesUI = {} end
C_DelvesUI.GetActiveDelveTier = _tbl
C_DelvesUI.GetCompanionInfoForActivePlayer = _num
C_DelvesUI.GetCreatureDisplayInfoForCompanion = _num
C_DelvesUI.GetCurioLink = _str
C_DelvesUI.GetCurioNodeForCompanion = _num
C_DelvesUI.GetCurioRarityByTraitCondAccountElementID = _nil
C_DelvesUI.GetCurrentDelvesSeasonNumber = _num
C_DelvesUI.GetDelveEntranceBackgroundWidgetSetID = _num
C_DelvesUI.GetDelveEntranceDescriptionString = _nil
C_DelvesUI.GetDelveEntranceHeaderString = _nil
C_DelvesUI.GetDelveEntranceMapID = _num
C_DelvesUI.GetDelveEntranceTiers = _tbl
C_DelvesUI.GetDelvesAffixSpellsForSeason = _tbl
C_DelvesUI.GetDelvesFactionForSeason = _num
C_DelvesUI.GetDelvesMinRequiredLevel = _nil
C_DelvesUI.GetFactionForCompanion = _num
C_DelvesUI.GetLockedTextForCompanion = _str
C_DelvesUI.GetModelSceneForCompanion = _num
C_DelvesUI.GetPlayerCompanionPDEID = _num
C_DelvesUI.GetRoleNodeForCompanion = _num
C_DelvesUI.GetRoleSubtreeForCompanion = _num
C_DelvesUI.GetTieredEntranceOptionalAffixTraitTreeID = _nil
C_DelvesUI.GetTieredEntrancePDEID = _num
C_DelvesUI.GetTieredEntranceType = _num
C_DelvesUI.GetTraitTreeForCompanion = _num
C_DelvesUI.GetUnseenCuriosBySlotType = _tbl
C_DelvesUI.HasActiveDelve = _bool
C_DelvesUI.IsDelveEntranceTierEnabled = _bool
C_DelvesUI.IsEligibleForActiveDelveRewards = _bool
C_DelvesUI.IsTraitTreeForCompanion = _bool
C_DelvesUI.RequestPartyEligibilityForDelveTiers = _nil
C_DelvesUI.SaveSeenCuriosBySlotType = _nil
C_DelvesUI.SelectDelveEntranceTier = _nil
-- Events: ACTIVE_DELVE_DATA_UPDATE, DELVE_ASSIST_ACTION, DELVES_ACCOUNT_DATA_ELEMENT_CHANGED, PARTY_ELIGIBILITY_FOR_DELVE_TIERS_CHANGED, SHOW_DELVES_COMPANION_CONFIGURATION_UI, WALK_IN_DATA_UPDATE
`;
