// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:50ea02be232e3ff7b38a38c074619c98f3aa85b94e66884527d0afb3da83996d
// @sig-hash: sha256:f57bcd13d1929eb1
// Source: Blizzard_APIDocumentationGenerated/durationutildocumentation.lua
export const C_DurationUtil = `
if C_DurationUtil == nil then C_DurationUtil = {} end
C_DurationUtil.CreateDuration = _nil
C_DurationUtil.GetCurrentTime = _nil
`;
