// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f2bc98b53d3184ff1d8a079a3eb798e1580adc992fab701d36cdb245990036f9
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/duelinfodocumentation.lua
export const C_DuelInfo = `
if C_DuelInfo == nil then C_DuelInfo = {} end
-- Events: DUEL_FINISHED, DUEL_INBOUNDS, DUEL_OUTOFBOUNDS, DUEL_REQUESTED, DUEL_TO_THE_DEATH_REQUESTED
`;
