// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2c1f6a3368c9daea6921938c23c8f7a045032b3bb5cd9592b0a239baaccfeb76
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/duelinfodocumentation.lua
export const C_DuelInfo = `
if C_DuelInfo == nil then C_DuelInfo = {} end
-- Events: DUEL_FINISHED, DUEL_INBOUNDS, DUEL_OUTOFBOUNDS, DUEL_REQUESTED, DUEL_TO_THE_DEATH_REQUESTED
`;
