// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:81c7909e862309ef1764a27ea2b792402ec1a0d45071a18158809fe0f3ac7285
// @sig-hash: sha256:4719f598cc4a97f4
// Source: Blizzard_APIDocumentationGenerated/dyecolorinfodocumentation.lua
export const C_DyeColor = `
if C_DyeColor == nil then C_DyeColor = {} end
C_DyeColor.GetAllDyeColorCategories = _tbl
C_DyeColor.GetAllDyeColors = _tbl
C_DyeColor.GetDyeColorCategoryInfo = _nil
C_DyeColor.GetDyeColorForItem = _nil
C_DyeColor.GetDyeColorForItemLocation = _nil
C_DyeColor.GetDyeColorInfo = _nil
C_DyeColor.GetDyeColorsInCategory = _tbl
C_DyeColor.IsDyeColorOwned = _nil
-- Events: DYE_COLOR_CATEGORY_UPDATED, DYE_COLOR_UPDATED
`;
