// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8cf7ba92a7794dfc486e71318ed8de3c841f90ccf80fd0426f13458ccc5332e7
// @sig-hash: sha256:0e969665fc63ea4a
// Source: Blizzard_APIDocumentationGenerated/editmodemanagerdocumentation.lua
export const C_EditMode = `
if C_EditMode == nil then C_EditMode = {} end
C_EditMode.ConvertLayoutInfoToString = _str("C_EditMode.ConvertLayoutInfoToString")
C_EditMode.ConvertStringToLayoutInfo = _tbl("C_EditMode.ConvertStringToLayoutInfo")
C_EditMode.GetAccountSettings = _tbl("C_EditMode.GetAccountSettings")
C_EditMode.GetLayouts = _tbl("C_EditMode.GetLayouts")
C_EditMode.IsValidLayoutName = _bool("C_EditMode.IsValidLayoutName")
C_EditMode.OnEditModeExit = _nil("C_EditMode.OnEditModeExit")
C_EditMode.OnLayoutAdded = _nil("C_EditMode.OnLayoutAdded")
C_EditMode.OnLayoutDeleted = _nil("C_EditMode.OnLayoutDeleted")
C_EditMode.SaveLayouts = _nil("C_EditMode.SaveLayouts")
C_EditMode.SetAccountSetting = _nil("C_EditMode.SetAccountSetting")
C_EditMode.SetActiveLayout = _nil("C_EditMode.SetActiveLayout")
-- Events: EDIT_MODE_LAYOUTS_UPDATED
`;
