// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3f937c16f0bea205a03b3816f5679f952a64ad8ce593df2c03d3b382cb569fca
// @sig-hash: sha256:57a81bcc9e5594f9
// Source: Blizzard_APIDocumentationGenerated/editmodemanagerdocumentation.lua
export const C_EditMode = `
if C_EditMode == nil then C_EditMode = {} end
C_EditMode.ConvertLayoutInfoToString = _str
C_EditMode.ConvertStringToLayoutInfo = _tbl
C_EditMode.GetAccountSettings = _tbl
C_EditMode.GetLayouts = _tbl
C_EditMode.IsValidLayoutName = _bool
C_EditMode.OnEditModeExit = _nil
C_EditMode.OnLayoutAdded = _nil
C_EditMode.OnLayoutDeleted = _nil
C_EditMode.SaveLayouts = _nil
C_EditMode.SetAccountSetting = _nil
C_EditMode.SetActiveLayout = _nil
-- Events: EDIT_MODE_LAYOUTS_UPDATED
`;
