// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9199fd7fcd8ca7ef0f03062b999b12e2e5a3b07cdf15a7dff0af46120ddf4b7c
// @sig-hash: sha256:133846b24881d245
// Source: Blizzard_APIDocumentationGenerated/encountereventsdocumentation.lua
export const C_EncounterEvents = `
if C_EncounterEvents == nil then C_EncounterEvents = {} end
C_EncounterEvents.GetEventColor = _nil("C_EncounterEvents.GetEventColor")
C_EncounterEvents.GetEventInfo = _tbl("C_EncounterEvents.GetEventInfo")
C_EncounterEvents.GetEventList = _tbl("C_EncounterEvents.GetEventList")
C_EncounterEvents.GetEventSound = _tbl("C_EncounterEvents.GetEventSound")
C_EncounterEvents.HasEventInfo = _bool("C_EncounterEvents.HasEventInfo")
C_EncounterEvents.PlayEventSound = _nil("C_EncounterEvents.PlayEventSound")
C_EncounterEvents.SetEventColor = _nil("C_EncounterEvents.SetEventColor")
C_EncounterEvents.SetEventSound = _nil("C_EncounterEvents.SetEventSound")
`;
