// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:049c6f056ea0c59f4679a97655464ebb0b6002ec613cea324a0ab6c6d387b1cc
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/encounterinfodocumentation.lua
export const C_EncounterInfo = `
if C_EncounterInfo == nil then C_EncounterInfo = {} end
-- Events: BOSS_KILL, DISABLE_LOW_LEVEL_RAID, ENABLE_LOW_LEVEL_RAID, ENCOUNTER_END, ENCOUNTER_START, INSTANCE_LOCK_START, INSTANCE_LOCK_STOP, INSTANCE_LOCK_WARNING, RAID_TARGET_UPDATE, UPDATE_INSTANCE_INFO
`;
