// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:43bc9e8bba9650d966159ee5656b56f50363da343b732be7e56bacb15f84cc95
// @sig-hash: sha256:d18d8878db1c5695
// Source: Blizzard_APIDocumentationGenerated/encounterwarningsdocumentation.lua
export const C_EncounterWarnings = `
if C_EncounterWarnings == nil then C_EncounterWarnings = {} end
C_EncounterWarnings.GetColorForSeverity = _nil
C_EncounterWarnings.GetEditModeWarningInfo = _tbl
C_EncounterWarnings.GetPlayCustomSoundsWhenHidden = _nil
C_EncounterWarnings.GetSoundKitForSeverity = _nil
C_EncounterWarnings.GetWarningsShown = _nil
C_EncounterWarnings.IsFeatureAvailable = _nil
C_EncounterWarnings.IsFeatureEnabled = _nil
C_EncounterWarnings.PlaySound = _nil
C_EncounterWarnings.SetPlayCustomSoundsWhenHidden = _nil
C_EncounterWarnings.SetWarningsShown = _nil
-- Events: ENCOUNTER_WARNING
`;
