// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:82d225e29b5bc2ec8b67ee56b361293a1ea318ea157d2dc489087e54d2f2b6c0
// @sig-hash: sha256:f9943d053efae714
// Source: Blizzard_APIDocumentationGenerated/encounterjournaldocumentation.lua
export const C_EncounterJournal = `
if C_EncounterJournal == nil then C_EncounterJournal = {} end
C_EncounterJournal.GetDungeonEntrancesForMap = _tbl("C_EncounterJournal.GetDungeonEntrancesForMap")
C_EncounterJournal.GetEncounterJournalLink = _str("C_EncounterJournal.GetEncounterJournalLink")
C_EncounterJournal.GetEncountersOnMap = _tbl("C_EncounterJournal.GetEncountersOnMap")
C_EncounterJournal.GetInstanceForGameMap = _nil("C_EncounterJournal.GetInstanceForGameMap")
C_EncounterJournal.GetLootInfo = _tbl("C_EncounterJournal.GetLootInfo")
C_EncounterJournal.GetLootInfoByIndex = _tbl("C_EncounterJournal.GetLootInfoByIndex")
C_EncounterJournal.GetSectionIconFlags = _tbl("C_EncounterJournal.GetSectionIconFlags")
C_EncounterJournal.GetSectionInfo = _tbl("C_EncounterJournal.GetSectionInfo")
C_EncounterJournal.GetSlotFilter = _nil("C_EncounterJournal.GetSlotFilter")
C_EncounterJournal.InitalizeSelectedTier = _nil("C_EncounterJournal.InitalizeSelectedTier")
C_EncounterJournal.InstanceHasLoot = _bool("C_EncounterJournal.InstanceHasLoot")
C_EncounterJournal.IsEncounterComplete = _bool("C_EncounterJournal.IsEncounterComplete")
C_EncounterJournal.OnClose = _nil("C_EncounterJournal.OnClose")
C_EncounterJournal.OnOpen = _nil("C_EncounterJournal.OnOpen")
C_EncounterJournal.ResetSlotFilter = _nil("C_EncounterJournal.ResetSlotFilter")
C_EncounterJournal.SetPreviewMythicPlusLevel = _nil("C_EncounterJournal.SetPreviewMythicPlusLevel")
C_EncounterJournal.SetPreviewPvpTier = _nil("C_EncounterJournal.SetPreviewPvpTier")
C_EncounterJournal.SetSlotFilter = _nil("C_EncounterJournal.SetSlotFilter")
C_EncounterJournal.SetTab = _nil("C_EncounterJournal.SetTab")
C_EncounterJournal.StartArathiRPE = _nil("C_EncounterJournal.StartArathiRPE")
-- Events: EJ_DIFFICULTY_UPDATE, EJ_LOOT_DATA_RECIEVED, SHOW_JOURNEYS_UI
`;
