// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c2cf4266286295df15f4e1e9030ee1be114e19060c1cb698e14cce6dd9d1bf6b
// @sig-hash: sha256:2bff5fc49717e56a
// Source: Blizzard_APIDocumentationGenerated/encounterwarningsdocumentation.lua
export const C_EncounterWarnings = `
if C_EncounterWarnings == nil then C_EncounterWarnings = {} end
C_EncounterWarnings.GetColorForSeverity = _nil("C_EncounterWarnings.GetColorForSeverity")
C_EncounterWarnings.GetEditModeWarningInfo = _tbl("C_EncounterWarnings.GetEditModeWarningInfo")
C_EncounterWarnings.GetPlayCustomSoundsWhenHidden = _bool("C_EncounterWarnings.GetPlayCustomSoundsWhenHidden")
C_EncounterWarnings.GetSoundKitForSeverity = _num("C_EncounterWarnings.GetSoundKitForSeverity")
C_EncounterWarnings.GetWarningsShown = _bool("C_EncounterWarnings.GetWarningsShown")
C_EncounterWarnings.IsFeatureAvailable = _bool("C_EncounterWarnings.IsFeatureAvailable")
C_EncounterWarnings.IsFeatureEnabled = _bool("C_EncounterWarnings.IsFeatureEnabled")
C_EncounterWarnings.PlaySound = _num("C_EncounterWarnings.PlaySound")
C_EncounterWarnings.SetPlayCustomSoundsWhenHidden = _nil("C_EncounterWarnings.SetPlayCustomSoundsWhenHidden")
C_EncounterWarnings.SetWarningsShown = _nil("C_EncounterWarnings.SetWarningsShown")
-- Events: ENCOUNTER_WARNING
`;
