// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:378865a06a40cbfc471330a5ac05a84773b7db66d8036378ae77ac5406ccad5a
// @sig-hash: sha256:99bb473cb543b09b
// Source: Blizzard_APIDocumentationGenerated/encountereventsdocumentation.lua
export const C_EncounterEvents = `
if C_EncounterEvents == nil then C_EncounterEvents = {} end
C_EncounterEvents.GetEventColor = _nil
C_EncounterEvents.GetEventInfo = _tbl
C_EncounterEvents.GetEventList = _tbl
C_EncounterEvents.GetEventSound = _tbl
C_EncounterEvents.HasEventInfo = _bool
C_EncounterEvents.PlayEventSound = _nil
C_EncounterEvents.SetEventColor = _nil
C_EncounterEvents.SetEventSound = _nil
`;
