// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3b3dc98367254686b5fc899189bd5a35adc56c6a7bfa6ce31ab7d1cf5282ac80
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/encounterinfodocumentation.lua
export const C_EncounterInfo = `
if C_EncounterInfo == nil then C_EncounterInfo = {} end
-- Events: BOSS_KILL, DISABLE_LOW_LEVEL_RAID, ENABLE_LOW_LEVEL_RAID, ENCOUNTER_END, ENCOUNTER_START, INSTANCE_LOCK_START, INSTANCE_LOCK_STOP, INSTANCE_LOCK_WARNING, RAID_TARGET_UPDATE, UPDATE_INSTANCE_INFO
`;
