// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ef1461561560761e40664664ad4a9a45b1a05498444b198e6142ce731b8529a9
// @sig-hash: sha256:ec1a77d52d9d41ef
// Source: Blizzard_APIDocumentationGenerated/encodingutildocumentation.lua
export const C_EncodingUtil = `
if C_EncodingUtil == nil then C_EncodingUtil = {} end
C_EncodingUtil.CompressString = _nil
C_EncodingUtil.DecodeBase64 = _nil
C_EncodingUtil.DecodeHex = _nil
C_EncodingUtil.DecompressString = _nil
C_EncodingUtil.DeserializeCBOR = _nil
C_EncodingUtil.DeserializeJSON = _nil
C_EncodingUtil.EncodeBase64 = _nil
C_EncodingUtil.EncodeHex = _nil
C_EncodingUtil.SerializeCBOR = _nil
C_EncodingUtil.SerializeJSON = _nil
`;
