// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:44aa319b1e887cc6ab52c88e698ed6cad427849db4fc58306ebd45538d629fad
// @sig-hash: sha256:bcb9c7512bc8330b
// Source: Blizzard_APIDocumentationGenerated/encounterjournaldocumentation.lua
export const C_EncounterJournal = `
if C_EncounterJournal == nil then C_EncounterJournal = {} end
C_EncounterJournal.GetDungeonEntrancesForMap = _tbl
C_EncounterJournal.GetEncounterJournalLink = _nil
C_EncounterJournal.GetEncountersOnMap = _tbl
C_EncounterJournal.GetInstanceForGameMap = _nil
C_EncounterJournal.GetLootInfo = _tbl
C_EncounterJournal.GetLootInfoByIndex = _tbl
C_EncounterJournal.GetSectionIconFlags = _tbl
C_EncounterJournal.GetSectionInfo = _tbl
C_EncounterJournal.GetSlotFilter = _nil
C_EncounterJournal.InitalizeSelectedTier = _nil
C_EncounterJournal.InstanceHasLoot = _nil
C_EncounterJournal.IsEncounterComplete = _nil
C_EncounterJournal.OnClose = _nil
C_EncounterJournal.OnOpen = _nil
C_EncounterJournal.ResetSlotFilter = _nil
C_EncounterJournal.SetPreviewMythicPlusLevel = _nil
C_EncounterJournal.SetPreviewPvpTier = _nil
C_EncounterJournal.SetSlotFilter = _nil
C_EncounterJournal.SetTab = _nil
C_EncounterJournal.StartArathiRPE = _nil
-- Events: EJ_DIFFICULTY_UPDATE, EJ_LOOT_DATA_RECIEVED, SHOW_JOURNEYS_UI
`;
