// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:10828e73576748fc7f6f95fb195005245bf246f61b80118ef1defcba431bbf9e
// @sig-hash: sha256:b28ae960bff7efec
// Source: Blizzard_APIDocumentationGenerated/encountertimelinedocumentation.lua
export const C_EncounterTimeline = `
if C_EncounterTimeline == nil then C_EncounterTimeline = {} end
C_EncounterTimeline.AddEditModeEvents = _nil("C_EncounterTimeline.AddEditModeEvents")
C_EncounterTimeline.AddScriptEvent = _nil("C_EncounterTimeline.AddScriptEvent")
C_EncounterTimeline.CancelAllScriptEvents = _nil("C_EncounterTimeline.CancelAllScriptEvents")
C_EncounterTimeline.CancelEditModeEvents = _nil("C_EncounterTimeline.CancelEditModeEvents")
C_EncounterTimeline.CancelScriptEvent = _nil("C_EncounterTimeline.CancelScriptEvent")
C_EncounterTimeline.FinishScriptEvent = _nil("C_EncounterTimeline.FinishScriptEvent")
C_EncounterTimeline.GetCurrentTime = _nil("C_EncounterTimeline.GetCurrentTime")
C_EncounterTimeline.GetEventCountBySource = _num("C_EncounterTimeline.GetEventCountBySource")
C_EncounterTimeline.GetEventHighlightTime = _nil("C_EncounterTimeline.GetEventHighlightTime")
C_EncounterTimeline.GetEventInfo = _tbl("C_EncounterTimeline.GetEventInfo")
C_EncounterTimeline.GetEventList = _tbl("C_EncounterTimeline.GetEventList")
C_EncounterTimeline.GetEventState = _nil("C_EncounterTimeline.GetEventState")
C_EncounterTimeline.GetEventTimeElapsed = _nil("C_EncounterTimeline.GetEventTimeElapsed")
C_EncounterTimeline.GetEventTimeRemaining = _nil("C_EncounterTimeline.GetEventTimeRemaining")
C_EncounterTimeline.GetEventTimer = _nil("C_EncounterTimeline.GetEventTimer")
C_EncounterTimeline.GetEventTrack = _nil("C_EncounterTimeline.GetEventTrack")
C_EncounterTimeline.GetSortedEventList = _tbl("C_EncounterTimeline.GetSortedEventList")
C_EncounterTimeline.GetTrackInfo = _tbl("C_EncounterTimeline.GetTrackInfo")
C_EncounterTimeline.GetTrackList = _tbl("C_EncounterTimeline.GetTrackList")
C_EncounterTimeline.GetTrackMaxEventDuration = _nil("C_EncounterTimeline.GetTrackMaxEventDuration")
C_EncounterTimeline.GetTrackType = _nil("C_EncounterTimeline.GetTrackType")
C_EncounterTimeline.GetViewType = _nil("C_EncounterTimeline.GetViewType")
C_EncounterTimeline.HasActiveEvents = _bool("C_EncounterTimeline.HasActiveEvents")
C_EncounterTimeline.HasAnyEvents = _bool("C_EncounterTimeline.HasAnyEvents")
C_EncounterTimeline.HasPausedEvents = _bool("C_EncounterTimeline.HasPausedEvents")
C_EncounterTimeline.HasVisibleEvents = _bool("C_EncounterTimeline.HasVisibleEvents")
C_EncounterTimeline.IsEventBlocked = _bool("C_EncounterTimeline.IsEventBlocked")
C_EncounterTimeline.IsFeatureAvailable = _bool("C_EncounterTimeline.IsFeatureAvailable")
C_EncounterTimeline.IsFeatureEnabled = _bool("C_EncounterTimeline.IsFeatureEnabled")
C_EncounterTimeline.PauseScriptEvent = _nil("C_EncounterTimeline.PauseScriptEvent")
C_EncounterTimeline.ResumeScriptEvent = _nil("C_EncounterTimeline.ResumeScriptEvent")
C_EncounterTimeline.SetEventIconTextures = _nil("C_EncounterTimeline.SetEventIconTextures")
C_EncounterTimeline.SetViewType = _nil("C_EncounterTimeline.SetViewType")
-- Events: ENCOUNTER_TIMELINE_EVENT_ADDED, ENCOUNTER_TIMELINE_EVENT_BLOCK_STATE_CHANGED, ENCOUNTER_TIMELINE_EVENT_HIGHLIGHT, ENCOUNTER_TIMELINE_EVENT_REMOVED, ENCOUNTER_TIMELINE_EVENT_STATE_CHANGED, ENCOUNTER_TIMELINE_EVENT_TRACK_CHANGED, ENCOUNTER_TIMELINE_LAYOUT_UPDATED, ENCOUNTER_TIMELINE_STATE_UPDATED, ENCOUNTER_TIMELINE_VIEW_ACTIVATED, ENCOUNTER_TIMELINE_VIEW_DEACTIVATED
`;
