// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b4eaadf8f2143627749631fc157ee3212fb95e46e410b8b376d397eeb22be706
// @sig-hash: sha256:bce46e1df5660455
// Source: Blizzard_APIDocumentationGenerated/equipmentmanagerdocumentation.lua
export const C_EquipmentSet = `
if C_EquipmentSet == nil then C_EquipmentSet = {} end
C_EquipmentSet.AssignSpecToEquipmentSet = _nil
C_EquipmentSet.CanUseEquipmentSets = _nil
C_EquipmentSet.ClearIgnoredSlotsForSave = _nil
C_EquipmentSet.CreateEquipmentSet = _nil
C_EquipmentSet.DeleteEquipmentSet = _nil
C_EquipmentSet.EquipmentSetContainsLockedItems = _nil
C_EquipmentSet.GetEquipmentSetAssignedSpec = _nil
C_EquipmentSet.GetEquipmentSetForSpec = _nil
C_EquipmentSet.GetEquipmentSetID = _nil
C_EquipmentSet.GetEquipmentSetIDs = _tbl
C_EquipmentSet.GetEquipmentSetInfo = _nil
C_EquipmentSet.GetIgnoredSlots = _tbl
C_EquipmentSet.GetItemIDs = _tbl
C_EquipmentSet.GetItemLocations = _tbl
C_EquipmentSet.GetNumEquipmentSets = _nil
C_EquipmentSet.IgnoreSlotForSave = _nil
C_EquipmentSet.IsSlotIgnoredForSave = _nil
C_EquipmentSet.ModifyEquipmentSet = _nil
C_EquipmentSet.PickupEquipmentSet = _nil
C_EquipmentSet.SaveEquipmentSet = _nil
C_EquipmentSet.UnassignEquipmentSetSpec = _nil
C_EquipmentSet.UnignoreSlotForSave = _nil
C_EquipmentSet.UseEquipmentSet = _nil
-- Events: EQUIPMENT_SETS_CHANGED, EQUIPMENT_SWAP_FINISHED, EQUIPMENT_SWAP_PENDING, TRANSMOG_CUSTOM_SETS_CHANGED
`;
