// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6ba9679bf985a77cae8a1cde784a181c7d6a8ce844046c6a93fb2fa4044c4f7e
// @sig-hash: sha256:7409210909dd75a9
// Source: Blizzard_APIDocumentationGenerated/uieventtoastmanagerdocumentation.lua
export const C_EventToastManager = `
if C_EventToastManager == nil then C_EventToastManager = {} end
C_EventToastManager.GetLevelUpDisplayToastsFromLevel = _tbl("C_EventToastManager.GetLevelUpDisplayToastsFromLevel")
C_EventToastManager.GetNextToastToDisplay = _tbl("C_EventToastManager.GetNextToastToDisplay")
C_EventToastManager.RemoveCurrentToast = _nil("C_EventToastManager.RemoveCurrentToast")
-- Events: DISPLAY_EVENT_TOAST_LINK, DISPLAY_EVENT_TOASTS
`;
