// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:388a0d46c772123d19977875a2f89c99eb6819053525f3bab0b887e10321898c
// @sig-hash: sha256:bf1b8bd94c96da02
// Source: Blizzard_APIDocumentationGenerated/eventscheduleruidocumentation.lua
export const C_EventScheduler = `
if C_EventScheduler == nil then C_EventScheduler = {} end
C_EventScheduler.CanShowEvents = _bool
C_EventScheduler.ClearReminder = _nil
C_EventScheduler.GetActiveContinentName = _str
C_EventScheduler.GetEventUiMapID = _nil
C_EventScheduler.GetEventZoneName = _nil
C_EventScheduler.GetOngoingEvents = _tbl
C_EventScheduler.GetScheduledEvents = _tbl
C_EventScheduler.HasData = _bool
C_EventScheduler.HasSavedReminders = _bool
C_EventScheduler.RequestEvents = _nil
C_EventScheduler.SetReminder = _nil
-- Events: EVENT_SCHEDULER_UPDATE
`;
