// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:770cca45377534d1b3c9fefbd3d006189acde1c1e4890d856583700cee190c1c
// @sig-hash: sha256:6017c4874b1812ed
// Source: Blizzard_APIDocumentationGenerated/eventscheduleruidocumentation.lua
export const C_EventScheduler = `
if C_EventScheduler == nil then C_EventScheduler = {} end
C_EventScheduler.CanShowEvents = _bool("C_EventScheduler.CanShowEvents")
C_EventScheduler.ClearReminder = _nil("C_EventScheduler.ClearReminder")
C_EventScheduler.GetActiveContinentName = _str("C_EventScheduler.GetActiveContinentName")
C_EventScheduler.GetEventUiMapID = _nil("C_EventScheduler.GetEventUiMapID")
C_EventScheduler.GetEventZoneName = _nil("C_EventScheduler.GetEventZoneName")
C_EventScheduler.GetOngoingEvents = _tbl("C_EventScheduler.GetOngoingEvents")
C_EventScheduler.GetScheduledEvents = _tbl("C_EventScheduler.GetScheduledEvents")
C_EventScheduler.HasData = _bool("C_EventScheduler.HasData")
C_EventScheduler.HasSavedReminders = _bool("C_EventScheduler.HasSavedReminders")
C_EventScheduler.RequestEvents = _nil("C_EventScheduler.RequestEvents")
C_EventScheduler.SetReminder = _nil("C_EventScheduler.SetReminder")
-- Events: EVENT_SCHEDULER_UPDATE
`;
