// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fc6d05eb22d0dee77ca06a77468f1dbabeac4247ce514dd67a46bc919506aa7a
// @sig-hash: sha256:6f47e40afff66fd8
// Source: Blizzard_APIDocumentationGenerated/uieventtoastmanagerdocumentation.lua
export const C_EventToastManager = `
if C_EventToastManager == nil then C_EventToastManager = {} end
C_EventToastManager.GetLevelUpDisplayToastsFromLevel = _tbl
C_EventToastManager.GetNextToastToDisplay = _tbl
C_EventToastManager.RemoveCurrentToast = _nil
-- Events: DISPLAY_EVENT_TOAST_LINK, DISPLAY_EVENT_TOASTS
`;
