// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:117a0f7f5ebec6da772f068666654587a658f5c3050bda12e5930962cf8391ef
// @sig-hash: sha256:9cce36861df0413f
// Source: Blizzard_APIDocumentationGenerated/externaleventurldocumentation.lua
export const C_ExternalEventURL = `
if C_ExternalEventURL == nil then C_ExternalEventURL = {} end
C_ExternalEventURL.HasURL = _bool("C_ExternalEventURL.HasURL")
C_ExternalEventURL.IsNew = _bool("C_ExternalEventURL.IsNew")
C_ExternalEventURL.LaunchURL = _nil("C_ExternalEventURL.LaunchURL")
`;
