// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1898f67b6993829b0b421c9e7124a5e8b87a20f1a1f992be809d1b1f6ccff5ff
// @sig-hash: sha256:519f2badc5c3b12a
// Source: Blizzard_APIDocumentationGenerated/expansiontrialdocumentation.lua
export const C_ExpansionTrial = `
if C_ExpansionTrial == nil then C_ExpansionTrial = {} end
C_ExpansionTrial.OnTrialLevelUpDialogClicked = _nil
C_ExpansionTrial.OnTrialLevelUpDialogShown = _nil
`;
