// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f5275fd13c00ed0e3fe908d8f320b7c1914215eba2eef87d4d207ba0c9b71476
// @sig-hash: sha256:34e9d657e70acb2d
// Source: Blizzard_APIDocumentationGenerated/expansiontrialdocumentation.lua
export const C_ExpansionTrial = `
if C_ExpansionTrial == nil then C_ExpansionTrial = {} end
C_ExpansionTrial.OnTrialLevelUpDialogClicked = _nil("C_ExpansionTrial.OnTrialLevelUpDialogClicked")
C_ExpansionTrial.OnTrialLevelUpDialogShown = _nil("C_ExpansionTrial.OnTrialLevelUpDialogShown")
`;
