// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b21fbbf601d1cdd92d76747fdc6c6162b1c90a5f27f708e01e9ecd583bef194c
// @sig-hash: sha256:740db541d71334dd
// Source: Blizzard_APIDocumentationGenerated/externaleventurldocumentation.lua
export const C_ExternalEventURL = `
if C_ExternalEventURL == nil then C_ExternalEventURL = {} end
C_ExternalEventURL.HasURL = _bool
C_ExternalEventURL.IsNew = _bool
C_ExternalEventURL.LaunchURL = _nil
`;
