// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2ea78c85b7d5c5a42cfa5ac312f4a1daf2c64307d515f1d7442ad731596fec77
// @sig-hash: sha256:a441e81d74ce7d15
// Source: Blizzard_APIDocumentationGenerated/fogofwardocumentation.lua
export const C_FogOfWar = `
if C_FogOfWar == nil then C_FogOfWar = {} end
C_FogOfWar.GetFogOfWarForMap = _nil("C_FogOfWar.GetFogOfWarForMap")
C_FogOfWar.GetFogOfWarInfo = _nil("C_FogOfWar.GetFogOfWarInfo")
-- Events: FOG_OF_WAR_UPDATED
`;
