// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:69a2797fbabf361f1aaaa4ea3a89858685212eadd79fc4297d44d8d1f6011bbe
// @sig-hash: sha256:4c7899a2cbd50296
// Source: Blizzard_APIDocumentationGenerated/fogofwardocumentation.lua
export const C_FogOfWar = `
if C_FogOfWar == nil then C_FogOfWar = {} end
C_FogOfWar.GetFogOfWarForMap = _nil
C_FogOfWar.GetFogOfWarInfo = _nil
-- Events: FOG_OF_WAR_UPDATED
`;
