// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d8db38c5b09d1f58a295ba7ae013bba812d4af5774fc37196570fa17e5ab2a51
// @sig-hash: sha256:a3cfe8133ce1c4d2
// Source: Blizzard_APIDocumentationGenerated/uiframemanagerdocumentation.lua
export const C_FrameManager = `
if C_FrameManager == nil then C_FrameManager = {} end
C_FrameManager.GetFrameVisibilityState = _bool("C_FrameManager.GetFrameVisibilityState")
-- Events: FRAME_MANAGER_UPDATE_ALL, FRAME_MANAGER_UPDATE_FRAME
`;
