// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:88902867b2b7de6d0c46acdff57adecf22fc17e01bdcf99012119ff75392951d
// @sig-hash: sha256:5d47720fdc325303
// Source: Blizzard_APIDocumentationGenerated/uiframemanagerdocumentation.lua
export const C_FrameManager = `
if C_FrameManager == nil then C_FrameManager = {} end
C_FrameManager.GetFrameVisibilityState = _nil
-- Events: FRAME_MANAGER_UPDATE_ALL, FRAME_MANAGER_UPDATE_FRAME
`;
