// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:dfb5ffbe4f18fcdbc9ce5eedb1742d8f76248b5380849b0f8ef8c733011402ac
// @sig-hash: sha256:744fdf623ec90a39
// Source: Blizzard_APIDocumentationGenerated/friendlistdocumentation.lua
export const C_FriendList = `
if C_FriendList == nil then C_FriendList = {} end
C_FriendList.AddFriend = _nil
C_FriendList.AddIgnore = _nil
C_FriendList.AddOrDelIgnore = _nil
C_FriendList.AddOrRemoveFriend = _nil
C_FriendList.DelIgnore = _nil
C_FriendList.DelIgnoreByIndex = _nil
C_FriendList.GetFriendInfo = _tbl
C_FriendList.GetFriendInfoByIndex = _tbl
C_FriendList.GetIgnoreName = _nil
C_FriendList.GetNumFriends = _nil
C_FriendList.GetNumIgnores = _nil
C_FriendList.GetNumOnlineFriends = _nil
C_FriendList.GetNumWhoResults = _nil
C_FriendList.GetSelectedFriend = _nil
C_FriendList.GetSelectedIgnore = _nil
C_FriendList.GetWhoInfo = _tbl
C_FriendList.IsFriend = _nil
C_FriendList.IsIgnored = _nil
C_FriendList.IsIgnoredByGuid = _nil
C_FriendList.IsOnIgnoredList = _nil
C_FriendList.RemoveFriend = _nil
C_FriendList.RemoveFriendByIndex = _nil
C_FriendList.SendWho = _nil
C_FriendList.SetFriendNotes = _nil
C_FriendList.SetFriendNotesByIndex = _nil
C_FriendList.SetSelectedFriend = _nil
C_FriendList.SetSelectedIgnore = _nil
C_FriendList.SetWhoToUi = _nil
C_FriendList.ShowFriends = _nil
C_FriendList.SortWho = _nil
-- Events: BATTLETAG_INVITE_SHOW, BN_BLOCK_FAILED_TOO_MANY, BN_BLOCK_LIST_UPDATED, BN_CHAT_WHISPER_UNDELIVERABLE, BN_CONNECTED, BN_CUSTOM_MESSAGE_CHANGED, BN_CUSTOM_MESSAGE_LOADED, BN_DISCONNECTED, BN_FRIEND_ACCOUNT_OFFLINE, BN_FRIEND_ACCOUNT_ONLINE, BN_FRIEND_INFO_CHANGED, BN_FRIEND_INVITE_ADDED, BN_FRIEND_INVITE_LIST_INITIALIZED, BN_FRIEND_INVITE_REMOVED, BN_FRIEND_LIST_SIZE_CHANGED, BN_INFO_CHANGED, BN_REQUEST_FOF_SUCCEEDED, FRIENDLIST_UPDATE, IGNORELIST_UPDATE, MUTELIST_UPDATE, NEW_MATCHMAKING_PARTY_INVITE, REJECTED_MATCHMAKING_PARTY_INVITE, WHO_LIST_UPDATE
`;
