// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2edd962e7044068c77f2c442c9789fe0b7b26ea3866c593b06b0683ff3fd6af5
// @sig-hash: sha256:15e20c4ed1498f61
// Source: Blizzard_APIDocumentationGenerated/friendlistdocumentation.lua
export const C_FriendList = `
if C_FriendList == nil then C_FriendList = {} end
C_FriendList.AddFriend = _nil("C_FriendList.AddFriend")
C_FriendList.AddIgnore = _bool("C_FriendList.AddIgnore")
C_FriendList.AddOrDelIgnore = _nil("C_FriendList.AddOrDelIgnore")
C_FriendList.AddOrRemoveFriend = _nil("C_FriendList.AddOrRemoveFriend")
C_FriendList.DelIgnore = _bool("C_FriendList.DelIgnore")
C_FriendList.DelIgnoreByIndex = _nil("C_FriendList.DelIgnoreByIndex")
C_FriendList.GetFriendInfo = _tbl("C_FriendList.GetFriendInfo")
C_FriendList.GetFriendInfoByIndex = _tbl("C_FriendList.GetFriendInfoByIndex")
C_FriendList.GetIgnoreName = _nil("C_FriendList.GetIgnoreName")
C_FriendList.GetNumFriends = _num("C_FriendList.GetNumFriends")
C_FriendList.GetNumIgnores = _num("C_FriendList.GetNumIgnores")
C_FriendList.GetNumOnlineFriends = _num("C_FriendList.GetNumOnlineFriends")
C_FriendList.GetNumWhoResults = _num("C_FriendList.GetNumWhoResults")
C_FriendList.GetSelectedFriend = _nil("C_FriendList.GetSelectedFriend")
C_FriendList.GetSelectedIgnore = _nil("C_FriendList.GetSelectedIgnore")
C_FriendList.GetWhoInfo = _tbl("C_FriendList.GetWhoInfo")
C_FriendList.IsFriend = _bool("C_FriendList.IsFriend")
C_FriendList.IsIgnored = _bool("C_FriendList.IsIgnored")
C_FriendList.IsIgnoredByGuid = _bool("C_FriendList.IsIgnoredByGuid")
C_FriendList.IsOnIgnoredList = _bool("C_FriendList.IsOnIgnoredList")
C_FriendList.RemoveFriend = _bool("C_FriendList.RemoveFriend")
C_FriendList.RemoveFriendByIndex = _nil("C_FriendList.RemoveFriendByIndex")
C_FriendList.SendWho = _nil("C_FriendList.SendWho")
C_FriendList.SetFriendNotes = _bool("C_FriendList.SetFriendNotes")
C_FriendList.SetFriendNotesByIndex = _nil("C_FriendList.SetFriendNotesByIndex")
C_FriendList.SetSelectedFriend = _nil("C_FriendList.SetSelectedFriend")
C_FriendList.SetSelectedIgnore = _nil("C_FriendList.SetSelectedIgnore")
C_FriendList.SetWhoToUi = _nil("C_FriendList.SetWhoToUi")
C_FriendList.ShowFriends = _nil("C_FriendList.ShowFriends")
C_FriendList.SortWho = _nil("C_FriendList.SortWho")
-- Events: BATTLETAG_INVITE_SHOW, BN_BLOCK_FAILED_TOO_MANY, BN_BLOCK_LIST_UPDATED, BN_CHAT_WHISPER_UNDELIVERABLE, BN_CONNECTED, BN_CUSTOM_MESSAGE_CHANGED, BN_CUSTOM_MESSAGE_LOADED, BN_DISCONNECTED, BN_FRIEND_ACCOUNT_OFFLINE, BN_FRIEND_ACCOUNT_ONLINE, BN_FRIEND_INFO_CHANGED, BN_FRIEND_INVITE_ADDED, BN_FRIEND_INVITE_LIST_INITIALIZED, BN_FRIEND_INVITE_REMOVED, BN_FRIEND_LIST_SIZE_CHANGED, BN_INFO_CHANGED, BN_REQUEST_FOF_SUCCEEDED, FRIENDLIST_UPDATE, IGNORELIST_UPDATE, MUTELIST_UPDATE, NEW_MATCHMAKING_PARTY_INVITE, REJECTED_MATCHMAKING_PARTY_INVITE, WHO_LIST_UPDATE
`;
