// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c3a93a3b1be0a1bcc1d768045f5d4ac29ea433d0a76578b47f659a51fab9bf91
// @sig-hash: sha256:17f715377d33c5d8
// Source: Blizzard_APIDocumentationGenerated/gamerulesdocumentation.lua
export const C_GameRules = `
if C_GameRules == nil then C_GameRules = {} end
C_GameRules.AutoConnectToGameModeRealm = _nil
C_GameRules.DoesGameModeHavePromo = _nil
C_GameRules.GetActiveGameMode = _nil
C_GameRules.GetCurrentEventRealmQueues = _nil
C_GameRules.GetCurrentGameModeDisplayInfo = _nil
C_GameRules.GetCurrentGameModeRecordID = _nil
C_GameRules.GetDisplayedGameModeRecordIDAtIndex = _nil
C_GameRules.GetGameModeDisplayInfoByRecordID = _nil
C_GameRules.GetGameModeGlueScreenName = _nil
C_GameRules.GetGameModePromoGlobalString = _nil
C_GameRules.GetGameRuleAsFloat = _nil
C_GameRules.GetGameRuleAsFrameStrata = _nil
C_GameRules.GetNumDisplayedGameModes = _nil
C_GameRules.IsCharacterlessLoginActive = _nil
C_GameRules.IsClassAllowedForGameMode = _nil
C_GameRules.IsGameModeEnabled = _nil
C_GameRules.IsGameRuleActive = _nil
C_GameRules.IsMultiActionBarVisibilityForced = _nil
C_GameRules.IsPersonalResourceDisplayEnabled = _nil
C_GameRules.IsPlunderstorm = _nil
C_GameRules.IsStandard = _nil
C_GameRules.IsWoWHack = _nil
-- Events: ACTIVE_GAME_MODE_UPDATED, AVAILABLE_GAME_MODES_UPDATED, EVENT_REALM_QUEUES_UPDATED, GAME_MODE_DISPLAY_INFO_UPDATED, GAME_MODE_DISPLAY_MODE_TOGGLE_DISABLED
`;
