// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1d562c32c89440a3a03bb08d803c8ad1b687be82de8774ee29b734f4e6267a67
// @sig-hash: sha256:24d78863380b43be
// Source: Blizzard_APIDocumentationGenerated/gamepaddocumentation.lua
export const C_GamePad = `
if C_GamePad == nil then C_GamePad = {} end
C_GamePad.AddSDLMapping = _bool("C_GamePad.AddSDLMapping")
C_GamePad.ApplyConfigs = _nil("C_GamePad.ApplyConfigs")
C_GamePad.AxisIndexToConfigName = _nil("C_GamePad.AxisIndexToConfigName")
C_GamePad.ButtonBindingToIndex = _nil("C_GamePad.ButtonBindingToIndex")
C_GamePad.ButtonIndexToBinding = _nil("C_GamePad.ButtonIndexToBinding")
C_GamePad.ButtonIndexToConfigName = _nil("C_GamePad.ButtonIndexToConfigName")
C_GamePad.ClearLedColor = _nil("C_GamePad.ClearLedColor")
C_GamePad.DeleteConfig = _nil("C_GamePad.DeleteConfig")
C_GamePad.GetActiveDeviceID = _num("C_GamePad.GetActiveDeviceID")
C_GamePad.GetAllConfigIDs = _tbl("C_GamePad.GetAllConfigIDs")
C_GamePad.GetAllDeviceIDs = _tbl("C_GamePad.GetAllDeviceIDs")
C_GamePad.GetCombinedDeviceID = _num("C_GamePad.GetCombinedDeviceID")
C_GamePad.GetConfig = _nil("C_GamePad.GetConfig")
C_GamePad.GetDeviceMappedState = _nil("C_GamePad.GetDeviceMappedState")
C_GamePad.GetDeviceRawState = _nil("C_GamePad.GetDeviceRawState")
C_GamePad.GetLedColor = _nil("C_GamePad.GetLedColor")
C_GamePad.GetPowerLevel = _nil("C_GamePad.GetPowerLevel")
C_GamePad.IsEnabled = _bool("C_GamePad.IsEnabled")
C_GamePad.SetConfig = _nil("C_GamePad.SetConfig")
C_GamePad.SetLedColor = _nil("C_GamePad.SetLedColor")
C_GamePad.SetVibration = _nil("C_GamePad.SetVibration")
C_GamePad.StickIndexToConfigName = _nil("C_GamePad.StickIndexToConfigName")
C_GamePad.StopVibration = _nil("C_GamePad.StopVibration")
-- Events: GAME_PAD_ACTIVE_CHANGED, GAME_PAD_CONFIGS_CHANGED, GAME_PAD_CONNECTED, GAME_PAD_DISCONNECTED, GAME_PAD_POWER_CHANGED
`;
