// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8d8c630ef269fbe9b80cb2cbbb98a52e925e6fa8ac2f75898381476277ed5c64
// @sig-hash: sha256:1f90018dcac93493
// Source: Blizzard_APIDocumentationGenerated/gamerulesdocumentation.lua
export const C_GameRules = `
if C_GameRules == nil then C_GameRules = {} end
C_GameRules.AutoConnectToGameModeRealm = _nil("C_GameRules.AutoConnectToGameModeRealm")
C_GameRules.DoesGameModeHavePromo = _bool("C_GameRules.DoesGameModeHavePromo")
C_GameRules.GetActiveGameMode = _nil("C_GameRules.GetActiveGameMode")
C_GameRules.GetCurrentEventRealmQueues = _nil("C_GameRules.GetCurrentEventRealmQueues")
C_GameRules.GetCurrentGameModeDisplayInfo = _nil("C_GameRules.GetCurrentGameModeDisplayInfo")
C_GameRules.GetCurrentGameModeRecordID = _num("C_GameRules.GetCurrentGameModeRecordID")
C_GameRules.GetDisplayedGameModeRecordIDAtIndex = _num("C_GameRules.GetDisplayedGameModeRecordIDAtIndex")
C_GameRules.GetGameModeDisplayInfoByRecordID = _nil("C_GameRules.GetGameModeDisplayInfoByRecordID")
C_GameRules.GetGameModeGlueScreenName = _str("C_GameRules.GetGameModeGlueScreenName")
C_GameRules.GetGameModePromoGlobalString = _str("C_GameRules.GetGameModePromoGlobalString")
C_GameRules.GetGameRuleAsFloat = _num("C_GameRules.GetGameRuleAsFloat")
C_GameRules.GetGameRuleAsFrameStrata = _str("C_GameRules.GetGameRuleAsFrameStrata")
C_GameRules.GetNumDisplayedGameModes = _num("C_GameRules.GetNumDisplayedGameModes")
C_GameRules.IsCharacterlessLoginActive = _bool("C_GameRules.IsCharacterlessLoginActive")
C_GameRules.IsClassAllowedForGameMode = _bool("C_GameRules.IsClassAllowedForGameMode")
C_GameRules.IsGameModeEnabled = _bool("C_GameRules.IsGameModeEnabled")
C_GameRules.IsGameRuleActive = _bool("C_GameRules.IsGameRuleActive")
C_GameRules.IsMultiActionBarVisibilityForced = _bool("C_GameRules.IsMultiActionBarVisibilityForced")
C_GameRules.IsPersonalResourceDisplayEnabled = _bool("C_GameRules.IsPersonalResourceDisplayEnabled")
C_GameRules.IsPlunderstorm = _bool("C_GameRules.IsPlunderstorm")
C_GameRules.IsStandard = _bool("C_GameRules.IsStandard")
C_GameRules.IsWoWHack = _bool("C_GameRules.IsWoWHack")
-- Events: ACTIVE_GAME_MODE_UPDATED, AVAILABLE_GAME_MODES_UPDATED, EVENT_REALM_QUEUES_UPDATED, GAME_MODE_DISPLAY_INFO_UPDATED, GAME_MODE_DISPLAY_MODE_TOGGLE_DISABLED
`;
