// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6b63e7e0f7db4bc1ba2cf1f47072f552db6218c4aee08b02c93aa64536f74490
// @sig-hash: sha256:ae341ad326f2b4b2
// Source: Blizzard_APIDocumentationGenerated/gamepaddocumentation.lua
export const C_GamePad = `
if C_GamePad == nil then C_GamePad = {} end
C_GamePad.AddSDLMapping = _nil
C_GamePad.ApplyConfigs = _nil
C_GamePad.AxisIndexToConfigName = _nil
C_GamePad.ButtonBindingToIndex = _nil
C_GamePad.ButtonIndexToBinding = _nil
C_GamePad.ButtonIndexToConfigName = _nil
C_GamePad.ClearLedColor = _nil
C_GamePad.DeleteConfig = _nil
C_GamePad.GetActiveDeviceID = _nil
C_GamePad.GetAllConfigIDs = _tbl
C_GamePad.GetAllDeviceIDs = _tbl
C_GamePad.GetCombinedDeviceID = _nil
C_GamePad.GetConfig = _nil
C_GamePad.GetDeviceMappedState = _nil
C_GamePad.GetDeviceRawState = _nil
C_GamePad.GetLedColor = _nil
C_GamePad.GetPowerLevel = _nil
C_GamePad.IsEnabled = _nil
C_GamePad.SetConfig = _nil
C_GamePad.SetLedColor = _nil
C_GamePad.SetVibration = _nil
C_GamePad.StickIndexToConfigName = _nil
C_GamePad.StopVibration = _nil
-- Events: GAME_PAD_ACTIVE_CHANGED, GAME_PAD_CONFIGS_CHANGED, GAME_PAD_CONNECTED, GAME_PAD_DISCONNECTED, GAME_PAD_POWER_CHANGED
`;
