// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c3a93a3b1be0a1bcc1d768045f5d4ac29ea433d0a76578b47f659a51fab9bf91
// @sig-hash: sha256:17f715377d33c5d8
// Source: Blizzard_APIDocumentationGenerated/gamerulesdocumentation.lua
export const C_GameRules = `
if C_GameRules == nil then C_GameRules = {} end
C_GameRules.AutoConnectToGameModeRealm = _nil
C_GameRules.DoesGameModeHavePromo = _bool
C_GameRules.GetActiveGameMode = _nil
C_GameRules.GetCurrentEventRealmQueues = _nil
C_GameRules.GetCurrentGameModeDisplayInfo = _nil
C_GameRules.GetCurrentGameModeRecordID = _num
C_GameRules.GetDisplayedGameModeRecordIDAtIndex = _num
C_GameRules.GetGameModeDisplayInfoByRecordID = _nil
C_GameRules.GetGameModeGlueScreenName = _str
C_GameRules.GetGameModePromoGlobalString = _str
C_GameRules.GetGameRuleAsFloat = _num
C_GameRules.GetGameRuleAsFrameStrata = _str
C_GameRules.GetNumDisplayedGameModes = _num
C_GameRules.IsCharacterlessLoginActive = _bool
C_GameRules.IsClassAllowedForGameMode = _bool
C_GameRules.IsGameModeEnabled = _bool
C_GameRules.IsGameRuleActive = _bool
C_GameRules.IsMultiActionBarVisibilityForced = _bool
C_GameRules.IsPersonalResourceDisplayEnabled = _bool
C_GameRules.IsPlunderstorm = _bool
C_GameRules.IsStandard = _bool
C_GameRules.IsWoWHack = _bool
-- Events: ACTIVE_GAME_MODE_UPDATED, AVAILABLE_GAME_MODES_UPDATED, EVENT_REALM_QUEUES_UPDATED, GAME_MODE_DISPLAY_INFO_UPDATED, GAME_MODE_DISPLAY_MODE_TOGGLE_DISABLED
`;
