// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:80c621aa86272acf8f2512d4bfec50bb9435bdfcf8c35bdb6a5971bb649d5cd2
// @sig-hash: sha256:7396897d4cd5fc0f
// Source: Blizzard_APIDocumentationGenerated/uigenericwidgetdisplaydocumentation.lua
export const C_GenericWidgetDisplay = `
if C_GenericWidgetDisplay == nil then C_GenericWidgetDisplay = {} end
C_GenericWidgetDisplay.Acknowledge = _nil("C_GenericWidgetDisplay.Acknowledge")
C_GenericWidgetDisplay.Close = _nil("C_GenericWidgetDisplay.Close")
-- Events: GENERIC_WIDGET_DISPLAY_SHOW
`;
