// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b24e69187e2300308e1cd0d321fc68afe5c89cfec10f4667837f3bd140dc516e
// @sig-hash: sha256:f33ae601d0006faa
// Source: Blizzard_APIDocumentationGenerated/uigenericwidgetdisplaydocumentation.lua
export const C_GenericWidgetDisplay = `
if C_GenericWidgetDisplay == nil then C_GenericWidgetDisplay = {} end
C_GenericWidgetDisplay.Acknowledge = _nil
C_GenericWidgetDisplay.Close = _nil
-- Events: GENERIC_WIDGET_DISPLAY_SHOW
`;
