// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:05dcd45b10831d3fc8bea31624c200ccaa0aac211d3298dc8d59a1af0c2e84cd
// @sig-hash: sha256:b4df865acc2d0956
// Source: Blizzard_APIDocumentationGenerated/gluedocumentation.lua
export const C_Glue = `
if C_Glue == nil then C_Glue = {} end
C_Glue.IsFirstLoadThisSession = _nil
C_Glue.IsOnGlueScreen = _nil
-- Events: ACCOUNT_CVARS_LOADED
`;
