// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a1f06615af1311c1936bb5d40021c03a054b85108f3eb6f974c6290d051d082f
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/gmticketinfodocumentation.lua
export const C_GMTicketInfo = `
if C_GMTicketInfo == nil then C_GMTicketInfo = {} end
-- Events: GM_PLAYER_INFO, ITEM_RESTORATION_BUTTON_STATUS, PETITION_CLOSED, PETITION_SHOW, PLAYER_REPORT_SUBMITTED, QUICK_TICKET_SYSTEM_STATUS, QUICK_TICKET_THROTTLE_CHANGED, UPDATE_WEB_TICKET
`;
