// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b2a8cf1823651f72e2d0b7de31b465309a4deb753f87a4383b1fb299b1d20868
// @sig-hash: sha256:ce542b5ef4a035d9
// Source: Blizzard_APIDocumentationGenerated/guildbankdocumentation.lua
export const C_GuildBank = `
if C_GuildBank == nil then C_GuildBank = {} end
C_GuildBank.IsGuildBankEnabled = _bool("C_GuildBank.IsGuildBankEnabled")
-- Events: GUILDBANK_ITEM_LOCK_CHANGED, GUILDBANK_TEXT_CHANGED, GUILDBANK_UPDATE_MONEY, GUILDBANK_UPDATE_TABS, GUILDBANK_UPDATE_TEXT, GUILDBANK_UPDATE_WITHDRAWMONEY, GUILDBANKBAGSLOTS_CHANGED, GUILDBANKFRAME_CLOSED, GUILDBANKFRAME_OPENED, GUILDBANKLOG_UPDATE
`;
