// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:54b0969eb6da9307978f4a4d3c2840b4adae6486a9066e2feb4ffd6746d666de
// @sig-hash: sha256:ee1e9ff9a7fa2875
// Source: Blizzard_APIDocumentationGenerated/guildinfodocumentation.lua
export const C_GuildInfo = `
if C_GuildInfo == nil then C_GuildInfo = {} end
C_GuildInfo.AreGuildEventsEnabled = _nil
C_GuildInfo.CanEditOfficerNote = _nil
C_GuildInfo.CanSpeakInGuildChat = _nil
C_GuildInfo.CanViewOfficerNote = _nil
C_GuildInfo.Demote = _nil
C_GuildInfo.Disband = _nil
C_GuildInfo.GetGuildNewsInfo = _tbl
C_GuildInfo.GetGuildRankOrder = _nil
C_GuildInfo.GetGuildTabardInfo = _nil
C_GuildInfo.GetInfoText = _nil
C_GuildInfo.GetMOTD = _nil
C_GuildInfo.GuildControlGetRankFlags = _tbl
C_GuildInfo.GuildRoster = _nil
C_GuildInfo.Invite = _nil
C_GuildInfo.IsEncounterGuildNewsEnabled = _nil
C_GuildInfo.IsGuildOfficer = _nil
C_GuildInfo.IsGuildRankAssignmentAllowed = _nil
C_GuildInfo.IsGuildReputationEnabled = _nil
C_GuildInfo.Leave = _nil
C_GuildInfo.MemberExistsByName = _nil
C_GuildInfo.Promote = _nil
C_GuildInfo.QueryGuildMemberRecipes = _nil
C_GuildInfo.QueryGuildMembersForRecipe = _nil
C_GuildInfo.RemoveFromGuild = _nil
C_GuildInfo.RequestGuildRename = _nil
C_GuildInfo.RequestGuildRenameRefund = _nil
C_GuildInfo.RequestRenameNameCheck = _nil
C_GuildInfo.RequestRenameStatus = _nil
C_GuildInfo.SetGuildRankOrder = _nil
C_GuildInfo.SetInfoText = _nil
C_GuildInfo.SetLeader = _nil
C_GuildInfo.SetMOTD = _nil
C_GuildInfo.SetNote = _nil
C_GuildInfo.Uninvite = _nil
-- Events: CLOSE_TABARD_FRAME, DISABLE_DECLINE_GUILD_INVITE, ENABLE_DECLINE_GUILD_INVITE, GUILD_CHALLENGE_COMPLETED, GUILD_CHALLENGE_UPDATED, GUILD_EVENT_LOG_UPDATE, GUILD_INVITE_CANCEL, GUILD_INVITE_REQUEST, GUILD_MOTD, GUILD_NEWS_UPDATE, GUILD_PARTY_STATE_UPDATED, GUILD_RANKS_UPDATE, GUILD_RECIPE_KNOWN_BY_MEMBERS, GUILD_REGISTRAR_CLOSED, GUILD_REGISTRAR_SHOW, GUILD_RENAME_NAME_CHECK, GUILD_RENAME_REFUND_RESULT, GUILD_RENAME_REQUIRED, GUILD_RENAME_STATUS_UPDATE, GUILD_REWARDS_LIST, GUILD_REWARDS_LIST_UPDATE, GUILD_ROSTER_UPDATE, GUILD_TRADESKILL_UPDATE, GUILDTABARD_UPDATE, OPEN_TABARD_FRAME, PLAYER_GUILD_UPDATE, REQUESTED_GUILD_RENAME_RESULT, REQUIRED_GUILD_RENAME_RESULT, TABARD_CANSAVE_CHANGED, TABARD_SAVE_PENDING, UNIT_GUILD_LEVEL
`;
