// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:889ec6bf62f60928b2c63367270033641b04b30d1637bc2a4331384533b5d446
// @sig-hash: sha256:73cbd5d16e37ab24
// Source: Blizzard_APIDocumentationGenerated/guildinfodocumentation.lua
export const C_GuildInfo = `
if C_GuildInfo == nil then C_GuildInfo = {} end
C_GuildInfo.AreGuildEventsEnabled = _bool("C_GuildInfo.AreGuildEventsEnabled")
C_GuildInfo.CanEditOfficerNote = _bool("C_GuildInfo.CanEditOfficerNote")
C_GuildInfo.CanSpeakInGuildChat = _bool("C_GuildInfo.CanSpeakInGuildChat")
C_GuildInfo.CanViewOfficerNote = _bool("C_GuildInfo.CanViewOfficerNote")
C_GuildInfo.Demote = _nil("C_GuildInfo.Demote")
C_GuildInfo.Disband = _nil("C_GuildInfo.Disband")
C_GuildInfo.GetGuildNewsInfo = _tbl("C_GuildInfo.GetGuildNewsInfo")
C_GuildInfo.GetGuildRankOrder = _nil("C_GuildInfo.GetGuildRankOrder")
C_GuildInfo.GetGuildTabardInfo = _nil("C_GuildInfo.GetGuildTabardInfo")
C_GuildInfo.GetInfoText = _str("C_GuildInfo.GetInfoText")
C_GuildInfo.GetMOTD = _str("C_GuildInfo.GetMOTD")
C_GuildInfo.GuildControlGetRankFlags = _tbl("C_GuildInfo.GuildControlGetRankFlags")
C_GuildInfo.GuildRoster = _nil("C_GuildInfo.GuildRoster")
C_GuildInfo.Invite = _nil("C_GuildInfo.Invite")
C_GuildInfo.IsEncounterGuildNewsEnabled = _bool("C_GuildInfo.IsEncounterGuildNewsEnabled")
C_GuildInfo.IsGuildOfficer = _bool("C_GuildInfo.IsGuildOfficer")
C_GuildInfo.IsGuildRankAssignmentAllowed = _bool("C_GuildInfo.IsGuildRankAssignmentAllowed")
C_GuildInfo.IsGuildReputationEnabled = _bool("C_GuildInfo.IsGuildReputationEnabled")
C_GuildInfo.Leave = _nil("C_GuildInfo.Leave")
C_GuildInfo.MemberExistsByName = _bool("C_GuildInfo.MemberExistsByName")
C_GuildInfo.Promote = _nil("C_GuildInfo.Promote")
C_GuildInfo.QueryGuildMemberRecipes = _nil("C_GuildInfo.QueryGuildMemberRecipes")
C_GuildInfo.QueryGuildMembersForRecipe = _num("C_GuildInfo.QueryGuildMembersForRecipe")
C_GuildInfo.RemoveFromGuild = _nil("C_GuildInfo.RemoveFromGuild")
C_GuildInfo.RequestGuildRename = _nil("C_GuildInfo.RequestGuildRename")
C_GuildInfo.RequestGuildRenameRefund = _nil("C_GuildInfo.RequestGuildRenameRefund")
C_GuildInfo.RequestRenameNameCheck = _nil("C_GuildInfo.RequestRenameNameCheck")
C_GuildInfo.RequestRenameStatus = _bool("C_GuildInfo.RequestRenameStatus")
C_GuildInfo.SetGuildRankOrder = _nil("C_GuildInfo.SetGuildRankOrder")
C_GuildInfo.SetInfoText = _nil("C_GuildInfo.SetInfoText")
C_GuildInfo.SetLeader = _nil("C_GuildInfo.SetLeader")
C_GuildInfo.SetMOTD = _nil("C_GuildInfo.SetMOTD")
C_GuildInfo.SetNote = _nil("C_GuildInfo.SetNote")
C_GuildInfo.Uninvite = _nil("C_GuildInfo.Uninvite")
-- Events: CLOSE_TABARD_FRAME, DISABLE_DECLINE_GUILD_INVITE, ENABLE_DECLINE_GUILD_INVITE, GUILD_CHALLENGE_COMPLETED, GUILD_CHALLENGE_UPDATED, GUILD_EVENT_LOG_UPDATE, GUILD_INVITE_CANCEL, GUILD_INVITE_REQUEST, GUILD_MOTD, GUILD_NEWS_UPDATE, GUILD_PARTY_STATE_UPDATED, GUILD_RANKS_UPDATE, GUILD_RECIPE_KNOWN_BY_MEMBERS, GUILD_REGISTRAR_CLOSED, GUILD_REGISTRAR_SHOW, GUILD_RENAME_NAME_CHECK, GUILD_RENAME_REFUND_RESULT, GUILD_RENAME_REQUIRED, GUILD_RENAME_STATUS_UPDATE, GUILD_REWARDS_LIST, GUILD_REWARDS_LIST_UPDATE, GUILD_ROSTER_UPDATE, GUILD_TRADESKILL_UPDATE, GUILDTABARD_UPDATE, OPEN_TABARD_FRAME, PLAYER_GUILD_UPDATE, REQUESTED_GUILD_RENAME_RESULT, REQUIRED_GUILD_RENAME_RESULT, TABARD_CANSAVE_CHANGED, TABARD_SAVE_PENDING, UNIT_GUILD_LEVEL
`;
