// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2297a5959e4ed5b7319d42f4b4bb99a330584c96a1363fee006b07a22ab2b483
// @sig-hash: sha256:c91a6f6abf3fc3a9
// Source: Blizzard_APIDocumentationGenerated/heirloominfodocumentation.lua
export const C_HeirloomInfo = `
if C_HeirloomInfo == nil then C_HeirloomInfo = {} end
C_HeirloomInfo.AreAllCollectionFiltersChecked = _nil
C_HeirloomInfo.AreAllSourceFiltersChecked = _nil
C_HeirloomInfo.IsHeirloomSourceValid = _nil
C_HeirloomInfo.IsUsingDefaultFilters = _nil
C_HeirloomInfo.SetAllCollectionFilters = _nil
C_HeirloomInfo.SetAllSourceFilters = _nil
C_HeirloomInfo.SetDefaultFilters = _nil
-- Events: HEIRLOOM_UPGRADE_TARGETING_CHANGED, HEIRLOOMS_UPDATED
`;
