// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:200f05f2cb58611699bc777e4b28151ba9d6b98393120d57e451d8e6379619c5
// @sig-hash: sha256:5d673e5069e55f40
// Source: Blizzard_APIDocumentationGenerated/housingcataloguidocumentation.lua
export const C_HousingCatalog = `
if C_HousingCatalog == nil then C_HousingCatalog = {} end
C_HousingCatalog.CreateCatalogSearcher = _nil("C_HousingCatalog.CreateCatalogSearcher")
C_HousingCatalog.DeletePreviewCartDecor = _nil("C_HousingCatalog.DeletePreviewCartDecor")
C_HousingCatalog.DestroyEntry = _nil("C_HousingCatalog.DestroyEntry")
C_HousingCatalog.GetAllFilterTagGroups = _tbl("C_HousingCatalog.GetAllFilterTagGroups")
C_HousingCatalog.GetAllVariantInfosForEntry = _tbl("C_HousingCatalog.GetAllVariantInfosForEntry")
C_HousingCatalog.GetBundleInfo = _nil("C_HousingCatalog.GetBundleInfo")
C_HousingCatalog.GetCartSizeLimit = _num("C_HousingCatalog.GetCartSizeLimit")
C_HousingCatalog.GetCatalogCategoryInfo = _nil("C_HousingCatalog.GetCatalogCategoryInfo")
C_HousingCatalog.GetCatalogEntryInfo = _nil("C_HousingCatalog.GetCatalogEntryInfo")
C_HousingCatalog.GetCatalogEntryInfoByItem = _nil("C_HousingCatalog.GetCatalogEntryInfoByItem")
C_HousingCatalog.GetCatalogEntryInfoByRecordID = _nil("C_HousingCatalog.GetCatalogEntryInfoByRecordID")
C_HousingCatalog.GetCatalogEntryRefundTimeStampByRecordID = _nil("C_HousingCatalog.GetCatalogEntryRefundTimeStampByRecordID")
C_HousingCatalog.GetCatalogEntryVariantInfo = _nil("C_HousingCatalog.GetCatalogEntryVariantInfo")
C_HousingCatalog.GetCatalogSubcategoryInfo = _nil("C_HousingCatalog.GetCatalogSubcategoryInfo")
C_HousingCatalog.GetDecorMaxOwnedCount = _num("C_HousingCatalog.GetDecorMaxOwnedCount")
C_HousingCatalog.GetDecorTotalOwnedCount = _num("C_HousingCatalog.GetDecorTotalOwnedCount")
C_HousingCatalog.GetDestroyableInstanceCount = _num("C_HousingCatalog.GetDestroyableInstanceCount")
C_HousingCatalog.GetFeaturedBundles = _tbl("C_HousingCatalog.GetFeaturedBundles")
C_HousingCatalog.GetFeaturedSmallProducts = _tbl("C_HousingCatalog.GetFeaturedSmallProducts")
C_HousingCatalog.GetMarketInfoForDecor = _nil("C_HousingCatalog.GetMarketInfoForDecor")
C_HousingCatalog.HasFeaturedEntries = _bool("C_HousingCatalog.HasFeaturedEntries")
C_HousingCatalog.HousingMarketActionAddToCart = _nil("C_HousingCatalog.HousingMarketActionAddToCart")
C_HousingCatalog.HousingMarketActionClearCart = _nil("C_HousingCatalog.HousingMarketActionClearCart")
C_HousingCatalog.HousingMarketActionRemoveFromCart = _nil("C_HousingCatalog.HousingMarketActionRemoveFromCart")
C_HousingCatalog.HousingMarketActionViewBundle = _nil("C_HousingCatalog.HousingMarketActionViewBundle")
C_HousingCatalog.HousingMarketActionViewInStore = _nil("C_HousingCatalog.HousingMarketActionViewInStore")
C_HousingCatalog.IsPreviewCartItemShown = _bool("C_HousingCatalog.IsPreviewCartItemShown")
C_HousingCatalog.PromotePreviewDecor = _bool("C_HousingCatalog.PromotePreviewDecor")
C_HousingCatalog.RequestHousingMarketInfoRefresh = _nil("C_HousingCatalog.RequestHousingMarketInfoRefresh")
C_HousingCatalog.RequestHousingMarketRefundInfo = _nil("C_HousingCatalog.RequestHousingMarketRefundInfo")
C_HousingCatalog.SearchCatalogCategories = _tbl("C_HousingCatalog.SearchCatalogCategories")
C_HousingCatalog.SearchCatalogSubcategories = _tbl("C_HousingCatalog.SearchCatalogSubcategories")
C_HousingCatalog.SetPreviewCartItemShown = _nil("C_HousingCatalog.SetPreviewCartItemShown")
-- Events: HOUSING_CATALOG_CATEGORY_UPDATED, HOUSING_CATALOG_SUBCATEGORY_UPDATED, HOUSING_DECOR_ADD_TO_PREVIEW_LIST, HOUSING_DECOR_PREVIEW_LIST_REMOVE_FROM_WORLD, HOUSING_DECOR_PREVIEW_LIST_UPDATED, HOUSING_REFUND_LIST_UPDATED, HOUSING_STORAGE_ENTRY_UPDATED, HOUSING_STORAGE_UPDATED
`;
