// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fb390af82d2e394d13d2498c6f7d2549501a43f5b4a4b16125ac98006ec7a833
// @sig-hash: sha256:644b9b5400fc5b57
// Source: Blizzard_APIDocumentationGenerated/housingneighborhooduidocumentation.lua
export const C_HousingNeighborhood = `
if C_HousingNeighborhood == nil then C_HousingNeighborhood = {} end
C_HousingNeighborhood.CanReturnAfterVisitingHouse = _nil
C_HousingNeighborhood.CancelInviteToNeighborhood = _nil
C_HousingNeighborhood.DemoteToResident = _nil
C_HousingNeighborhood.GetCornerstoneHouseInfo = _tbl
C_HousingNeighborhood.GetCornerstoneNeighborhoodInfo = _tbl
C_HousingNeighborhood.GetCornerstonePurchaseMode = _nil
C_HousingNeighborhood.GetCurrentNeighborhoodTextureSuffix = _nil
C_HousingNeighborhood.GetDiscountedMovePrice = _nil
C_HousingNeighborhood.GetMoveCooldownTime = _nil
C_HousingNeighborhood.GetNeighborhoodMapData = _tbl
C_HousingNeighborhood.GetNeighborhoodName = _nil
C_HousingNeighborhood.GetNeighborhoodPlotName = _nil
C_HousingNeighborhood.GetPreviousHouseIdentifier = _nil
C_HousingNeighborhood.HasPermissionToPurchase = _nil
C_HousingNeighborhood.InvitePlayerToNeighborhood = _nil
C_HousingNeighborhood.IsNeighborhoodManager = _nil
C_HousingNeighborhood.IsNeighborhoodOwner = _nil
C_HousingNeighborhood.IsPlayerInOtherPlayersPlot = _nil
C_HousingNeighborhood.IsPlotAvailableForPurchase = _nil
C_HousingNeighborhood.IsPlotOwnedByPlayer = _nil
C_HousingNeighborhood.OnBulletinBoardClosed = _nil
C_HousingNeighborhood.OnCornerstoneClosed = _nil
C_HousingNeighborhood.PromoteToManager = _nil
C_HousingNeighborhood.RequestNeighborhoodInfo = _nil
C_HousingNeighborhood.RequestNeighborhoodRoster = _nil
C_HousingNeighborhood.RequestPendingNeighborhoodInvites = _nil
C_HousingNeighborhood.TransferNeighborhoodOwnership = _nil
C_HousingNeighborhood.TryEvictPlayer = _nil
C_HousingNeighborhood.TryMoveHouse = _nil
C_HousingNeighborhood.TryPurchasePlot = _nil
-- Events: CANCEL_NEIGHBORHOOD_INVITE_RESPONSE, CLOSE_PLOT_CORNERSTONE, NEIGHBORHOOD_INFO_UPDATED, NEIGHBORHOOD_INVITE_RESPONSE, NEIGHBORHOOD_MAP_DATA_UPDATED, NEIGHBORHOOD_NAME_UPDATED, OPEN_PLOT_CORNERSTONE, PENDING_NEIGHBORHOOD_INVITES_RECIEVED, PURCHASE_PLOT_RESULT, SHOW_PLAYER_EVICTED_DIALOG, UPDATE_BULLETIN_BOARD_MEMBER_TYPE, UPDATE_BULLETIN_BOARD_ROSTER, UPDATE_BULLETIN_BOARD_ROSTER_STATUSES
`;
