// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ce25e01c6524b1f3bf835dc9d49c63efcd78e4f654e010d6fd33fa2bbc97bf74
// @sig-hash: sha256:ab3996a16446d8f9
// Source: Blizzard_APIDocumentationGenerated/houseeditoruidocumentation.lua
export const C_HouseEditor = `
if C_HouseEditor == nil then C_HouseEditor = {} end
C_HouseEditor.ActivateHouseEditorMode = _nil("C_HouseEditor.ActivateHouseEditorMode")
C_HouseEditor.EnterHouseEditor = _nil("C_HouseEditor.EnterHouseEditor")
C_HouseEditor.GetActiveHouseEditorMode = _nil("C_HouseEditor.GetActiveHouseEditorMode")
C_HouseEditor.GetHouseEditorAvailability = _nil("C_HouseEditor.GetHouseEditorAvailability")
C_HouseEditor.GetHouseEditorModeAvailability = _nil("C_HouseEditor.GetHouseEditorModeAvailability")
C_HouseEditor.IsHouseEditorActive = _bool("C_HouseEditor.IsHouseEditorActive")
C_HouseEditor.IsHouseEditorModeActive = _bool("C_HouseEditor.IsHouseEditorModeActive")
C_HouseEditor.IsHouseEditorStatusAvailable = _bool("C_HouseEditor.IsHouseEditorStatusAvailable")
C_HouseEditor.LeaveHouseEditor = _nil("C_HouseEditor.LeaveHouseEditor")
-- Events: HOUSE_EDITOR_AVAILABILITY_CHANGED, HOUSE_EDITOR_MODE_CHANGE_FAILURE, HOUSE_EDITOR_MODE_CHANGED
`;
