// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c1b76071b3e9f60be63f0ee746d38f1578d4e855232492ce5ad1ba33d11860a8
// @sig-hash: sha256:d9d97ab8cc8bed56
// Source: Blizzard_APIDocumentationGenerated/housingexpertmodeuidocumentation.lua
export const C_HousingExpertMode = `
if C_HousingExpertMode == nil then C_HousingExpertMode = {} end
C_HousingExpertMode.CancelActiveEditing = _nil("C_HousingExpertMode.CancelActiveEditing")
C_HousingExpertMode.CommitDecorMovement = _nil("C_HousingExpertMode.CommitDecorMovement")
C_HousingExpertMode.CommitHouseExteriorPosition = _nil("C_HousingExpertMode.CommitHouseExteriorPosition")
C_HousingExpertMode.GetHoveredDecorInfo = _nil("C_HousingExpertMode.GetHoveredDecorInfo")
C_HousingExpertMode.GetPrecisionSubmode = _nil("C_HousingExpertMode.GetPrecisionSubmode")
C_HousingExpertMode.GetPrecisionSubmodeRestriction = _nil("C_HousingExpertMode.GetPrecisionSubmodeRestriction")
C_HousingExpertMode.GetSelectedDecorInfo = _nil("C_HousingExpertMode.GetSelectedDecorInfo")
C_HousingExpertMode.IsDecorSelected = _bool("C_HousingExpertMode.IsDecorSelected")
C_HousingExpertMode.IsGridVisible = _bool("C_HousingExpertMode.IsGridVisible")
C_HousingExpertMode.IsHouseExteriorHovered = _bool("C_HousingExpertMode.IsHouseExteriorHovered")
C_HousingExpertMode.IsHouseExteriorSelected = _bool("C_HousingExpertMode.IsHouseExteriorSelected")
C_HousingExpertMode.IsHoveringDecor = _bool("C_HousingExpertMode.IsHoveringDecor")
C_HousingExpertMode.RemoveSelectedDecor = _nil("C_HousingExpertMode.RemoveSelectedDecor")
C_HousingExpertMode.ResetPrecisionChanges = _nil("C_HousingExpertMode.ResetPrecisionChanges")
C_HousingExpertMode.SelectNextRotationAxis = _nil("C_HousingExpertMode.SelectNextRotationAxis")
C_HousingExpertMode.SetGridVisible = _nil("C_HousingExpertMode.SetGridVisible")
C_HousingExpertMode.SetPrecisionIncrementingActive = _nil("C_HousingExpertMode.SetPrecisionIncrementingActive")
C_HousingExpertMode.SetPrecisionSubmode = _nil("C_HousingExpertMode.SetPrecisionSubmode")
-- Events: HOUSING_DECOR_PRECISION_MANIPULATION_EVENT, HOUSING_DECOR_PRECISION_MANIPULATION_STATUS_CHANGED, HOUSING_DECOR_PRECISION_SUBMODE_CHANGED, HOUSING_EXPERT_MODE_HOVERED_TARGET_CHANGED, HOUSING_EXPERT_MODE_PLACEMENT_FLAGS_UPDATED, HOUSING_EXPERT_MODE_SELECTED_TARGET_CHANGED
`;
