// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6c3d7acbc450dc69ca533914153915e31f01644448397efab71ee111e8168f67
// @sig-hash: sha256:705f30202b7aa66b
// Source: Blizzard_APIDocumentationGenerated/housinginspectmodeuidocumentation.lua
export const C_HousingInspectMode = `
if C_HousingInspectMode == nil then C_HousingInspectMode = {} end
C_HousingInspectMode.EnterInspectMode = _nil("C_HousingInspectMode.EnterInspectMode")
C_HousingInspectMode.ExitInspectMode = _nil("C_HousingInspectMode.ExitInspectMode")
C_HousingInspectMode.GetHoveredDecorGUID = _nil("C_HousingInspectMode.GetHoveredDecorGUID")
C_HousingInspectMode.IsHoveringDecor = _bool("C_HousingInspectMode.IsHoveringDecor")
C_HousingInspectMode.IsInInspectMode = _bool("C_HousingInspectMode.IsInInspectMode")
-- Events: HOUSING_INSPECT_MODE_DECOR_HOVERED_CHANGED, HOUSING_INSPECT_MODE_STATE_UPDATED
`;
