// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7016638e090eee88001e40942c4b37b0eebea9e24da49f4f394a398e692b656a
// @sig-hash: sha256:cb2ffaa78c7bfff7
// Source: Blizzard_APIDocumentationGenerated/housinglayoutuidocumentation.lua
export const C_HousingLayout = `
if C_HousingLayout == nil then C_HousingLayout = {} end
C_HousingLayout.AnyRoomsOnFloor = _nil
C_HousingLayout.CancelActiveLayoutEditing = _nil
C_HousingLayout.ConfirmStairChoice = _nil
C_HousingLayout.DeselectFloorplan = _nil
C_HousingLayout.DeselectRoomOrDoor = _nil
C_HousingLayout.GetNumActiveRooms = _nil
C_HousingLayout.GetNumFloors = _nil
C_HousingLayout.GetRoomPlacementBudget = _nil
C_HousingLayout.GetSelectedDoor = _nil
C_HousingLayout.GetSelectedFloorplan = _nil
C_HousingLayout.GetSelectedRoom = _nil
C_HousingLayout.GetSelectedStairwellRoomCount = _nil
C_HousingLayout.GetSpentPlacementBudget = _nil
C_HousingLayout.GetViewedFloor = _nil
C_HousingLayout.HasAnySelections = _nil
C_HousingLayout.HasRoomPlacementBudget = _nil
C_HousingLayout.HasSelectedDoor = _nil
C_HousingLayout.HasSelectedFloorplan = _nil
C_HousingLayout.HasSelectedRoom = _nil
C_HousingLayout.HasStairs = _nil
C_HousingLayout.HasValidConnection = _nil
C_HousingLayout.IsBaseRoom = _nil
C_HousingLayout.IsDraggingRoom = _nil
C_HousingLayout.IsDraggingStairwell = _nil
C_HousingLayout.MoveDraggedRoom = _nil
C_HousingLayout.MoveLayoutCamera = _nil
C_HousingLayout.RemoveRoom = _nil
C_HousingLayout.RotateFocusedRoom = _nil
C_HousingLayout.RotateRoom = _nil
C_HousingLayout.SelectFloorplan = _nil
C_HousingLayout.SetViewedFloor = _nil
C_HousingLayout.StartDrag = _nil
C_HousingLayout.StopDrag = _nil
C_HousingLayout.StopDraggingRoom = _nil
C_HousingLayout.ZoomLayoutCamera = _nil
-- Events: HOUSING_LAYOUT_DOOR_SELECTED, HOUSING_LAYOUT_DOOR_SELECTION_CHANGED, HOUSING_LAYOUT_DRAG_TARGET_CHANGED, HOUSING_LAYOUT_FLOORPLAN_SELECTION_CHANGED, HOUSING_LAYOUT_NUM_FLOORS_CHANGED, HOUSING_LAYOUT_PIN_FRAME_ADDED, HOUSING_LAYOUT_PIN_FRAME_RELEASED, HOUSING_LAYOUT_PIN_FRAMES_RELEASED, HOUSING_LAYOUT_ROOM_COMPONENT_THEME_SET_CHANGED, HOUSING_LAYOUT_ROOM_MOVE_INVALID, HOUSING_LAYOUT_ROOM_MOVED, HOUSING_LAYOUT_ROOM_RECEIVED, HOUSING_LAYOUT_ROOM_REMOVED, HOUSING_LAYOUT_ROOM_RETURNED, HOUSING_LAYOUT_ROOM_SELECTION_CHANGED, HOUSING_LAYOUT_ROOM_SNAPPED, HOUSING_LAYOUT_VIEWED_FLOOR_CHANGED, SHOW_STAIR_DIRECTION_CONFIRMATION
`;
