// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:173fc6bef299cbdc0052a320ec9ec0c74256a6f82302d3bc45b74fc8094e4150
// @sig-hash: sha256:38befe0c354b2ebc
// Source: Blizzard_APIDocumentationGenerated/housingcustomizemodeuidocumentation.lua
export const C_HousingCustomizeMode = `
if C_HousingCustomizeMode == nil then C_HousingCustomizeMode = {} end
C_HousingCustomizeMode.ApplyDyeToSelectedDecor = _nil
C_HousingCustomizeMode.ApplyThemeToRoom = _nil
C_HousingCustomizeMode.ApplyThemeToSelectedRoomComponent = _nil
C_HousingCustomizeMode.ApplyWallpaperToAllWalls = _nil
C_HousingCustomizeMode.ApplyWallpaperToSelectedRoomComponent = _nil
C_HousingCustomizeMode.CancelActiveEditing = _nil
C_HousingCustomizeMode.ClearDyesForSelectedDecor = _nil
C_HousingCustomizeMode.ClearTargetRoomComponent = _nil
C_HousingCustomizeMode.CommitDyesForSelectedDecor = _nil
C_HousingCustomizeMode.GetHoveredDecorInfo = _nil
C_HousingCustomizeMode.GetHoveredRoomComponentInfo = _nil
C_HousingCustomizeMode.GetNumDyesToRemoveOnSelectedDecor = _nil
C_HousingCustomizeMode.GetNumDyesToSpendOnSelectedDecor = _nil
C_HousingCustomizeMode.GetPreviewDyesOnSelectedDecor = _tbl
C_HousingCustomizeMode.GetRecentlyUsedDyes = _tbl
C_HousingCustomizeMode.GetRecentlyUsedThemeSets = _tbl
C_HousingCustomizeMode.GetRecentlyUsedWallpapers = _tbl
C_HousingCustomizeMode.GetSelectedDecorInfo = _nil
C_HousingCustomizeMode.GetSelectedRoomComponentInfo = _nil
C_HousingCustomizeMode.GetThemeSetInfo = _nil
C_HousingCustomizeMode.GetWallpapersForRoomComponentType = _tbl
C_HousingCustomizeMode.IsDecorSelected = _nil
C_HousingCustomizeMode.IsHouseExteriorDoorHovered = _nil
C_HousingCustomizeMode.IsHoveringDecor = _nil
C_HousingCustomizeMode.IsHoveringRoomComponent = _nil
C_HousingCustomizeMode.IsRoomComponentSelected = _nil
C_HousingCustomizeMode.RoomComponentSupportsVariant = _nil
C_HousingCustomizeMode.SetRoomComponentCeilingType = _nil
C_HousingCustomizeMode.SetRoomComponentDoorType = _nil
-- Events: HOUSING_CUSTOMIZE_MODE_HOVERED_TARGET_CHANGED, HOUSING_CUSTOMIZE_MODE_SELECTED_TARGET_CHANGED, HOUSING_DECOR_CUSTOMIZATION_CHANGED, HOUSING_DECOR_DYE_FAILURE, HOUSING_ROOM_COMPONENT_CUSTOMIZATION_CHANGE_FAILED, HOUSING_ROOM_COMPONENT_CUSTOMIZATION_CHANGED
`;
