// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b96dfbe3777a219f5c75b16ae9ffa8f40372702f60bb96c52f5fdc9ad2f6f41d
// @sig-hash: sha256:4715a9a5b557a115
// Source: Blizzard_APIDocumentationGenerated/housingdecoruidocumentation.lua
export const C_HousingDecor = `
if C_HousingDecor == nil then C_HousingDecor = {} end
C_HousingDecor.CancelActiveEditing = _nil
C_HousingDecor.CommitDecorMovement = _nil
C_HousingDecor.EnterPreviewState = _nil
C_HousingDecor.ExitPreviewState = _nil
C_HousingDecor.GetAllPlacedDecor = _tbl
C_HousingDecor.GetDecorHyperlink = _nil
C_HousingDecor.GetDecorIcon = _nil
C_HousingDecor.GetDecorInstanceInfoForGUID = _nil
C_HousingDecor.GetDecorName = _nil
C_HousingDecor.GetHoveredDecorInfo = _nil
C_HousingDecor.GetMaxPlacementBudget = _nil
C_HousingDecor.GetNumDecorPlaced = _nil
C_HousingDecor.GetNumPreviewDecor = _nil
C_HousingDecor.GetSelectedDecorInfo = _nil
C_HousingDecor.GetSpentPlacementBudget = _nil
C_HousingDecor.HasMaxPlacementBudget = _nil
C_HousingDecor.IsDecorSelected = _nil
C_HousingDecor.IsGridVisible = _nil
C_HousingDecor.IsHouseExteriorDoorHovered = _nil
C_HousingDecor.IsHouseExteriorHovered = _nil
C_HousingDecor.IsHoveringDecor = _nil
C_HousingDecor.IsModeDisabledForPreviewState = _nil
C_HousingDecor.IsPreviewState = _nil
C_HousingDecor.RemovePlacedDecorEntry = _nil
C_HousingDecor.RemoveSelectedDecor = _nil
C_HousingDecor.SetGridVisible = _nil
C_HousingDecor.SetPlacedDecorEntryHovered = _nil
C_HousingDecor.SetPlacedDecorEntrySelected = _nil
-- Events: HOUSE_DECOR_ADDED_TO_CHEST, HOUSE_EXTERIOR_POSITION_FAILURE, HOUSE_EXTERIOR_POSITION_SUCCESS, HOUSING_DECOR_GRID_VISIBILITY_STATUS_CHANGED, HOUSING_DECOR_PLACE_FAILURE, HOUSING_DECOR_PLACE_SUCCESS, HOUSING_DECOR_PREVIEW_STATE_CHANGED, HOUSING_DECOR_REMOVED, HOUSING_DECOR_SELECT_RESPONSE, HOUSING_NUM_DECOR_PLACED_CHANGED
`;
