// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7e7b5a5b0bd477b24ffba357ef3398f909b06b25e2f89a7e38af8bc733176ddb
// @sig-hash: sha256:4ba9c3e5cb6d2462
// Source: Blizzard_APIDocumentationGenerated/housingexpertmodeuidocumentation.lua
export const C_HousingExpertMode = `
if C_HousingExpertMode == nil then C_HousingExpertMode = {} end
C_HousingExpertMode.CancelActiveEditing = _nil
C_HousingExpertMode.CommitDecorMovement = _nil
C_HousingExpertMode.CommitHouseExteriorPosition = _nil
C_HousingExpertMode.GetHoveredDecorInfo = _nil
C_HousingExpertMode.GetPrecisionSubmode = _nil
C_HousingExpertMode.GetPrecisionSubmodeRestriction = _nil
C_HousingExpertMode.GetSelectedDecorInfo = _nil
C_HousingExpertMode.IsDecorSelected = _bool
C_HousingExpertMode.IsGridVisible = _bool
C_HousingExpertMode.IsHouseExteriorHovered = _bool
C_HousingExpertMode.IsHouseExteriorSelected = _bool
C_HousingExpertMode.IsHoveringDecor = _bool
C_HousingExpertMode.RemoveSelectedDecor = _nil
C_HousingExpertMode.ResetPrecisionChanges = _nil
C_HousingExpertMode.SelectNextRotationAxis = _nil
C_HousingExpertMode.SetGridVisible = _nil
C_HousingExpertMode.SetPrecisionIncrementingActive = _nil
C_HousingExpertMode.SetPrecisionSubmode = _nil
-- Events: HOUSING_DECOR_PRECISION_MANIPULATION_EVENT, HOUSING_DECOR_PRECISION_MANIPULATION_STATUS_CHANGED, HOUSING_DECOR_PRECISION_SUBMODE_CHANGED, HOUSING_EXPERT_MODE_HOVERED_TARGET_CHANGED, HOUSING_EXPERT_MODE_PLACEMENT_FLAGS_UPDATED, HOUSING_EXPERT_MODE_SELECTED_TARGET_CHANGED
`;
