// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c564fde9516ae680bd350a6f0f4b9e8f4123051f673f5708757740ffd7511b82
// @sig-hash: sha256:51481f65ae45adc7
// Source: Blizzard_APIDocumentationGenerated/housingdecoruidocumentation.lua
export const C_HousingDecor = `
if C_HousingDecor == nil then C_HousingDecor = {} end
C_HousingDecor.CancelActiveEditing = _nil("C_HousingDecor.CancelActiveEditing")
C_HousingDecor.CommitDecorMovement = _nil("C_HousingDecor.CommitDecorMovement")
C_HousingDecor.EnterPreviewState = _nil("C_HousingDecor.EnterPreviewState")
C_HousingDecor.ExitPreviewState = _nil("C_HousingDecor.ExitPreviewState")
C_HousingDecor.GetAllPlacedDecor = _tbl("C_HousingDecor.GetAllPlacedDecor")
C_HousingDecor.GetDecorHyperlink = _str("C_HousingDecor.GetDecorHyperlink")
C_HousingDecor.GetDecorIcon = _nil("C_HousingDecor.GetDecorIcon")
C_HousingDecor.GetDecorInstanceInfoForGUID = _nil("C_HousingDecor.GetDecorInstanceInfoForGUID")
C_HousingDecor.GetDecorName = _str("C_HousingDecor.GetDecorName")
C_HousingDecor.GetHoveredDecorInfo = _nil("C_HousingDecor.GetHoveredDecorInfo")
C_HousingDecor.GetMaxPlacementBudget = _num("C_HousingDecor.GetMaxPlacementBudget")
C_HousingDecor.GetNumDecorPlaced = _num("C_HousingDecor.GetNumDecorPlaced")
C_HousingDecor.GetNumPreviewDecor = _num("C_HousingDecor.GetNumPreviewDecor")
C_HousingDecor.GetSelectedDecorInfo = _nil("C_HousingDecor.GetSelectedDecorInfo")
C_HousingDecor.GetSpentPlacementBudget = _num("C_HousingDecor.GetSpentPlacementBudget")
C_HousingDecor.HasMaxPlacementBudget = _bool("C_HousingDecor.HasMaxPlacementBudget")
C_HousingDecor.IsDecorSelected = _bool("C_HousingDecor.IsDecorSelected")
C_HousingDecor.IsGridVisible = _bool("C_HousingDecor.IsGridVisible")
C_HousingDecor.IsHouseExteriorDoorHovered = _bool("C_HousingDecor.IsHouseExteriorDoorHovered")
C_HousingDecor.IsHouseExteriorHovered = _bool("C_HousingDecor.IsHouseExteriorHovered")
C_HousingDecor.IsHoveringDecor = _bool("C_HousingDecor.IsHoveringDecor")
C_HousingDecor.IsModeDisabledForPreviewState = _bool("C_HousingDecor.IsModeDisabledForPreviewState")
C_HousingDecor.IsPreviewState = _bool("C_HousingDecor.IsPreviewState")
C_HousingDecor.RemovePlacedDecorEntry = _nil("C_HousingDecor.RemovePlacedDecorEntry")
C_HousingDecor.RemoveSelectedDecor = _nil("C_HousingDecor.RemoveSelectedDecor")
C_HousingDecor.SetGridVisible = _nil("C_HousingDecor.SetGridVisible")
C_HousingDecor.SetPlacedDecorEntryHovered = _nil("C_HousingDecor.SetPlacedDecorEntryHovered")
C_HousingDecor.SetPlacedDecorEntrySelected = _nil("C_HousingDecor.SetPlacedDecorEntrySelected")
-- Events: HOUSE_DECOR_ADDED_TO_CHEST, HOUSE_EXTERIOR_POSITION_FAILURE, HOUSE_EXTERIOR_POSITION_SUCCESS, HOUSING_DECOR_GRID_VISIBILITY_STATUS_CHANGED, HOUSING_DECOR_PLACE_FAILURE, HOUSING_DECOR_PLACE_SUCCESS, HOUSING_DECOR_PREVIEW_STATE_CHANGED, HOUSING_DECOR_REMOVED, HOUSING_DECOR_SELECT_RESPONSE, HOUSING_NUM_DECOR_PLACED_CHANGED
`;
