// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:98705eb28ec1391e4177d8555cc8ef204738d9c5a7a7c10c70220a96234dcc44
// @sig-hash: sha256:148d8820347a6924
// Source: Blizzard_APIDocumentationGenerated/housingcataloguidocumentation.lua
export const C_HousingCatalog = `
if C_HousingCatalog == nil then C_HousingCatalog = {} end
C_HousingCatalog.CreateCatalogSearcher = _nil
C_HousingCatalog.DeletePreviewCartDecor = _nil
C_HousingCatalog.DestroyEntry = _nil
C_HousingCatalog.GetAllFilterTagGroups = _tbl
C_HousingCatalog.GetAllVariantInfosForEntry = _tbl
C_HousingCatalog.GetBundleInfo = _nil
C_HousingCatalog.GetCartSizeLimit = _nil
C_HousingCatalog.GetCatalogCategoryInfo = _nil
C_HousingCatalog.GetCatalogEntryInfo = _nil
C_HousingCatalog.GetCatalogEntryInfoByItem = _nil
C_HousingCatalog.GetCatalogEntryInfoByRecordID = _nil
C_HousingCatalog.GetCatalogEntryRefundTimeStampByRecordID = _nil
C_HousingCatalog.GetCatalogEntryVariantInfo = _nil
C_HousingCatalog.GetCatalogSubcategoryInfo = _nil
C_HousingCatalog.GetDecorMaxOwnedCount = _nil
C_HousingCatalog.GetDecorTotalOwnedCount = _nil
C_HousingCatalog.GetDestroyableInstanceCount = _nil
C_HousingCatalog.GetFeaturedBundles = _tbl
C_HousingCatalog.GetFeaturedSmallProducts = _tbl
C_HousingCatalog.GetMarketInfoForDecor = _nil
C_HousingCatalog.HasFeaturedEntries = _nil
C_HousingCatalog.HousingMarketActionAddToCart = _nil
C_HousingCatalog.HousingMarketActionClearCart = _nil
C_HousingCatalog.HousingMarketActionRemoveFromCart = _nil
C_HousingCatalog.HousingMarketActionViewBundle = _nil
C_HousingCatalog.HousingMarketActionViewInStore = _nil
C_HousingCatalog.IsPreviewCartItemShown = _nil
C_HousingCatalog.PromotePreviewDecor = _nil
C_HousingCatalog.RequestHousingMarketInfoRefresh = _nil
C_HousingCatalog.RequestHousingMarketRefundInfo = _nil
C_HousingCatalog.SearchCatalogCategories = _tbl
C_HousingCatalog.SearchCatalogSubcategories = _tbl
C_HousingCatalog.SetPreviewCartItemShown = _nil
-- Events: HOUSING_CATALOG_CATEGORY_UPDATED, HOUSING_CATALOG_SUBCATEGORY_UPDATED, HOUSING_DECOR_ADD_TO_PREVIEW_LIST, HOUSING_DECOR_PREVIEW_LIST_REMOVE_FROM_WORLD, HOUSING_DECOR_PREVIEW_LIST_UPDATED, HOUSING_REFUND_LIST_UPDATED, HOUSING_STORAGE_ENTRY_UPDATED, HOUSING_STORAGE_UPDATED
`;
