// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:da9cd262e181e2aab95672c0d58b159ac315f20f5c5d1f4f2eb3ba6b279da5cd
// @sig-hash: sha256:f4a35e1fa77b28c2
// Source: Blizzard_APIDocumentationGenerated/housinglayoutuidocumentation.lua
export const C_HousingLayout = `
if C_HousingLayout == nil then C_HousingLayout = {} end
C_HousingLayout.AnyRoomsOnFloor = _bool("C_HousingLayout.AnyRoomsOnFloor")
C_HousingLayout.CancelActiveLayoutEditing = _nil("C_HousingLayout.CancelActiveLayoutEditing")
C_HousingLayout.ConfirmStairChoice = _nil("C_HousingLayout.ConfirmStairChoice")
C_HousingLayout.DeselectFloorplan = _nil("C_HousingLayout.DeselectFloorplan")
C_HousingLayout.DeselectRoomOrDoor = _nil("C_HousingLayout.DeselectRoomOrDoor")
C_HousingLayout.GetNumActiveRooms = _num("C_HousingLayout.GetNumActiveRooms")
C_HousingLayout.GetNumFloors = _num("C_HousingLayout.GetNumFloors")
C_HousingLayout.GetRoomPlacementBudget = _num("C_HousingLayout.GetRoomPlacementBudget")
C_HousingLayout.GetSelectedDoor = _num("C_HousingLayout.GetSelectedDoor")
C_HousingLayout.GetSelectedFloorplan = _nil("C_HousingLayout.GetSelectedFloorplan")
C_HousingLayout.GetSelectedRoom = _nil("C_HousingLayout.GetSelectedRoom")
C_HousingLayout.GetSelectedStairwellRoomCount = _num("C_HousingLayout.GetSelectedStairwellRoomCount")
C_HousingLayout.GetSpentPlacementBudget = _num("C_HousingLayout.GetSpentPlacementBudget")
C_HousingLayout.GetViewedFloor = _num("C_HousingLayout.GetViewedFloor")
C_HousingLayout.HasAnySelections = _bool("C_HousingLayout.HasAnySelections")
C_HousingLayout.HasRoomPlacementBudget = _bool("C_HousingLayout.HasRoomPlacementBudget")
C_HousingLayout.HasSelectedDoor = _bool("C_HousingLayout.HasSelectedDoor")
C_HousingLayout.HasSelectedFloorplan = _bool("C_HousingLayout.HasSelectedFloorplan")
C_HousingLayout.HasSelectedRoom = _bool("C_HousingLayout.HasSelectedRoom")
C_HousingLayout.HasStairs = _bool("C_HousingLayout.HasStairs")
C_HousingLayout.HasValidConnection = _bool("C_HousingLayout.HasValidConnection")
C_HousingLayout.IsBaseRoom = _bool("C_HousingLayout.IsBaseRoom")
C_HousingLayout.IsDraggingRoom = _bool("C_HousingLayout.IsDraggingRoom")
C_HousingLayout.IsDraggingStairwell = _bool("C_HousingLayout.IsDraggingStairwell")
C_HousingLayout.MoveDraggedRoom = _nil("C_HousingLayout.MoveDraggedRoom")
C_HousingLayout.MoveLayoutCamera = _nil("C_HousingLayout.MoveLayoutCamera")
C_HousingLayout.RemoveRoom = _nil("C_HousingLayout.RemoveRoom")
C_HousingLayout.RotateFocusedRoom = _nil("C_HousingLayout.RotateFocusedRoom")
C_HousingLayout.RotateRoom = _nil("C_HousingLayout.RotateRoom")
C_HousingLayout.SelectFloorplan = _nil("C_HousingLayout.SelectFloorplan")
C_HousingLayout.SetViewedFloor = _nil("C_HousingLayout.SetViewedFloor")
C_HousingLayout.StartDrag = _nil("C_HousingLayout.StartDrag")
C_HousingLayout.StopDrag = _nil("C_HousingLayout.StopDrag")
C_HousingLayout.StopDraggingRoom = _nil("C_HousingLayout.StopDraggingRoom")
C_HousingLayout.ZoomLayoutCamera = _bool("C_HousingLayout.ZoomLayoutCamera")
-- Events: HOUSING_LAYOUT_DOOR_SELECTED, HOUSING_LAYOUT_DOOR_SELECTION_CHANGED, HOUSING_LAYOUT_DRAG_TARGET_CHANGED, HOUSING_LAYOUT_FLOORPLAN_SELECTION_CHANGED, HOUSING_LAYOUT_NUM_FLOORS_CHANGED, HOUSING_LAYOUT_PIN_FRAME_ADDED, HOUSING_LAYOUT_PIN_FRAME_RELEASED, HOUSING_LAYOUT_PIN_FRAMES_RELEASED, HOUSING_LAYOUT_ROOM_COMPONENT_THEME_SET_CHANGED, HOUSING_LAYOUT_ROOM_MOVE_INVALID, HOUSING_LAYOUT_ROOM_MOVED, HOUSING_LAYOUT_ROOM_RECEIVED, HOUSING_LAYOUT_ROOM_REMOVED, HOUSING_LAYOUT_ROOM_RETURNED, HOUSING_LAYOUT_ROOM_SELECTION_CHANGED, HOUSING_LAYOUT_ROOM_SNAPPED, HOUSING_LAYOUT_VIEWED_FLOOR_CHANGED, SHOW_STAIR_DIRECTION_CONFIRMATION
`;
