// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:122651731973d66ce596e8f6745e2ac26f4a3defc0193f0d849f67021064dbf7
// @sig-hash: sha256:752368906f5e3280
// Source: Blizzard_APIDocumentationGenerated/houseexterioruidocumentation.lua
export const C_HouseExterior = `
if C_HouseExterior == nil then C_HouseExterior = {} end
C_HouseExterior.CancelActiveExteriorEditing = _nil("C_HouseExterior.CancelActiveExteriorEditing")
C_HouseExterior.GetCoreFixtureOptionsInfo = _nil("C_HouseExterior.GetCoreFixtureOptionsInfo")
C_HouseExterior.GetCurrentHouseExteriorSize = _nil("C_HouseExterior.GetCurrentHouseExteriorSize")
C_HouseExterior.GetCurrentHouseExteriorType = _nil("C_HouseExterior.GetCurrentHouseExteriorType")
C_HouseExterior.GetHouseExteriorSizeOptions = _nil("C_HouseExterior.GetHouseExteriorSizeOptions")
C_HouseExterior.GetHouseExteriorTypeOptions = _nil("C_HouseExterior.GetHouseExteriorTypeOptions")
C_HouseExterior.GetSelectedFixturePointInfo = _nil("C_HouseExterior.GetSelectedFixturePointInfo")
C_HouseExterior.HasHoveredFixture = _bool("C_HouseExterior.HasHoveredFixture")
C_HouseExterior.HasSelectedFixturePoint = _bool("C_HouseExterior.HasSelectedFixturePoint")
C_HouseExterior.IsAnyDecorAttachedToCoreFixture = _bool("C_HouseExterior.IsAnyDecorAttachedToCoreFixture")
C_HouseExterior.IsAnyDecorAttachedToDoor = _bool("C_HouseExterior.IsAnyDecorAttachedToDoor")
C_HouseExterior.IsAnyDecorAttachedToHouseExterior = _bool("C_HouseExterior.IsAnyDecorAttachedToHouseExterior")
C_HouseExterior.IsAnyDecorAttachedToSelectedFixturePoint = _bool("C_HouseExterior.IsAnyDecorAttachedToSelectedFixturePoint")
C_HouseExterior.IsExteriorDecorHidden = _bool("C_HouseExterior.IsExteriorDecorHidden")
C_HouseExterior.RemoveFixtureFromSelectedPoint = _nil("C_HouseExterior.RemoveFixtureFromSelectedPoint")
C_HouseExterior.SelectCoreFixtureOption = _nil("C_HouseExterior.SelectCoreFixtureOption")
C_HouseExterior.SelectFixtureOption = _nil("C_HouseExterior.SelectFixtureOption")
C_HouseExterior.SetExteriorDecorHidden = _nil("C_HouseExterior.SetExteriorDecorHidden")
C_HouseExterior.SetHouseExteriorSize = _nil("C_HouseExterior.SetHouseExteriorSize")
C_HouseExterior.SetHouseExteriorType = _nil("C_HouseExterior.SetHouseExteriorType")
-- Events: HOUSE_EXTERIOR_DECOR_HIDDEN_CHANGED, HOUSE_EXTERIOR_TYPE_UNLOCKED, HOUSING_CORE_FIXTURE_CHANGED, HOUSING_FIXTURE_HOVER_CHANGED, HOUSING_FIXTURE_POINT_FRAME_ADDED, HOUSING_FIXTURE_POINT_FRAME_RELEASED, HOUSING_FIXTURE_POINT_FRAMES_RELEASED, HOUSING_FIXTURE_POINT_SELECTION_CHANGED, HOUSING_FIXTURE_UNLOCKED, HOUSING_SET_EXTERIOR_HOUSE_SIZE_RESPONSE, HOUSING_SET_EXTERIOR_HOUSE_TYPE_RESPONSE, HOUSING_SET_FIXTURE_RESPONSE
`;
