// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e508c6be520690531c9ad0e231bf9fc63be22186a007924afa1db8a88be5af40
// @sig-hash: sha256:efa32ee2c41efb38
// Source: Blizzard_APIDocumentationGenerated/housingcleanupmodeuidocumentation.lua
export const C_HousingCleanupMode = `
if C_HousingCleanupMode == nil then C_HousingCleanupMode = {} end
C_HousingCleanupMode.GetHoveredDecorInfo = _nil
C_HousingCleanupMode.IsHoveringDecor = _bool
C_HousingCleanupMode.RemoveSelectedDecor = _nil
-- Events: HOUSING_CLEANUP_MODE_HOVERED_TARGET_CHANGED, HOUSING_CLEANUP_MODE_TARGET_SELECTED
`;
