// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5d990eeb36f232e2a7de3a50ccba7eefd01cf312d79984a6250e923afd302a59
// @sig-hash: sha256:20bce85e7b6cc612
// Source: Blizzard_APIDocumentationGenerated/immersiveinteractionmanagerdocumentation.lua
export const C_ImmersiveInteraction = `
if C_ImmersiveInteraction == nil then C_ImmersiveInteraction = {} end
C_ImmersiveInteraction.HasImmersiveInteraction = _bool
-- Events: IMMERSIVE_INTERACTION_BEGIN, IMMERSIVE_INTERACTION_END
`;
