// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:51a6d78096940fce5b15b01f861f2c0f8c92957aca6a5572249cfea7f378d493
// @sig-hash: sha256:3534529d3779df3a
// Source: Blizzard_APIDocumentationGenerated/immersiveinteractionmanagerdocumentation.lua
export const C_ImmersiveInteraction = `
if C_ImmersiveInteraction == nil then C_ImmersiveInteraction = {} end
C_ImmersiveInteraction.HasImmersiveInteraction = _bool("C_ImmersiveInteraction.HasImmersiveInteraction")
-- Events: IMMERSIVE_INTERACTION_BEGIN, IMMERSIVE_INTERACTION_END
`;
