// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:89b614b7d79a88956b6220fdcd204ab4a6e514e9dabfbb10218cb4b6358c9607
// @sig-hash: sha256:843b5f1255bf916e
// Source: Blizzard_APIDocumentationGenerated/instanceleaverinfodocumentation.lua
export const C_InstanceLeaver = `
if C_InstanceLeaver == nil then C_InstanceLeaver = {} end
C_InstanceLeaver.IsPlayerLeaver = _bool("C_InstanceLeaver.IsPlayerLeaver")
-- Events: INSTANCE_LEAVER_STATUS_CHANGED
`;
