// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:76563c1793a43115cfd69fe95147f00145f13788c8a589d9022984d9a8a2ce8e
// @sig-hash: sha256:b5315fcc80011d0a
// Source: Blizzard_APIDocumentationGenerated/invasioninfodocumentation.lua
export const C_InvasionInfo = `
if C_InvasionInfo == nil then C_InvasionInfo = {} end
C_InvasionInfo.AreInvasionsAvailable = _bool
C_InvasionInfo.GetInvasionForUiMapID = _nil
C_InvasionInfo.GetInvasionInfo = _tbl
C_InvasionInfo.GetInvasionTimeLeft = _nil
`;
