// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a9b99c9e4ec4b8621c4dc9c241595c86a2f53d78af4a47a805c0a7ee45291aea
// @sig-hash: sha256:815731c9d5ac76d9
// Source: Blizzard_APIDocumentationGenerated/invasioninfodocumentation.lua
export const C_InvasionInfo = `
if C_InvasionInfo == nil then C_InvasionInfo = {} end
C_InvasionInfo.AreInvasionsAvailable = _bool("C_InvasionInfo.AreInvasionsAvailable")
C_InvasionInfo.GetInvasionForUiMapID = _nil("C_InvasionInfo.GetInvasionForUiMapID")
C_InvasionInfo.GetInvasionInfo = _tbl("C_InvasionInfo.GetInvasionInfo")
C_InvasionInfo.GetInvasionTimeLeft = _nil("C_InvasionInfo.GetInvasionTimeLeft")
`;
