// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9188d518e7f60248cada1aa2f63e25c6c9186de0113f9c606064d339901e0841
// @sig-hash: sha256:03e6aece78a297eb
// Source: Blizzard_APIDocumentationGenerated/incomingsummondocumentation.lua
export const C_IncomingSummon = `
if C_IncomingSummon == nil then C_IncomingSummon = {} end
C_IncomingSummon.HasIncomingSummon = _nil
C_IncomingSummon.IncomingSummonStatus = _nil
`;
