// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7c75d3bcea3545c43e10aadceed4928e27a9e893bafc51e3a4029240d7167e16
// @sig-hash: sha256:6db46161b825bad5
// Source: Blizzard_APIDocumentationGenerated/instanceencounterdocumentation.lua
export const C_InstanceEncounter = `
if C_InstanceEncounter == nil then C_InstanceEncounter = {} end
C_InstanceEncounter.IsEncounterInProgress = _bool
C_InstanceEncounter.IsEncounterLimitingResurrections = _bool
C_InstanceEncounter.IsEncounterSuppressingRelease = _bool
C_InstanceEncounter.ShouldShowTimelineForEncounter = _bool
-- Events: ENCOUNTER_STATE_CHANGED, INSTANCE_ENCOUNTER_ADD_TIMER, INSTANCE_ENCOUNTER_ENGAGE_UNIT, INSTANCE_ENCOUNTER_OBJECTIVE_COMPLETE, INSTANCE_ENCOUNTER_OBJECTIVE_START, INSTANCE_ENCOUNTER_OBJECTIVE_UPDATE
`;
