// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5b77d54f3e32faab17e8df315a091168a9d55287ba5f81ca2d1a93c9103ecd08
// @sig-hash: sha256:c7353c1da57ac79a
// Source: Blizzard_APIDocumentationGenerated/instanceencounterdocumentation.lua
export const C_InstanceEncounter = `
if C_InstanceEncounter == nil then C_InstanceEncounter = {} end
C_InstanceEncounter.IsEncounterInProgress = _bool("C_InstanceEncounter.IsEncounterInProgress")
C_InstanceEncounter.IsEncounterLimitingResurrections = _bool("C_InstanceEncounter.IsEncounterLimitingResurrections")
C_InstanceEncounter.IsEncounterSuppressingRelease = _bool("C_InstanceEncounter.IsEncounterSuppressingRelease")
C_InstanceEncounter.ShouldShowTimelineForEncounter = _bool("C_InstanceEncounter.ShouldShowTimelineForEncounter")
-- Events: ENCOUNTER_STATE_CHANGED, INSTANCE_ENCOUNTER_ADD_TIMER, INSTANCE_ENCOUNTER_ENGAGE_UNIT, INSTANCE_ENCOUNTER_OBJECTIVE_COMPLETE, INSTANCE_ENCOUNTER_OBJECTIVE_START, INSTANCE_ENCOUNTER_OBJECTIVE_UPDATE
`;
