// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4718fc216293276e21127cf62d65dbda5d0a9f8869ef813887dc7fc143520eda
// @sig-hash: sha256:5b20048e8ad514f3
// Source: Blizzard_APIDocumentationGenerated/islandsqueueuidocumentation.lua
export const C_IslandsQueue = `
if C_IslandsQueue == nil then C_IslandsQueue = {} end
C_IslandsQueue.CloseIslandsQueueScreen = _nil
C_IslandsQueue.GetIslandDifficultyInfo = _tbl
C_IslandsQueue.GetIslandsMaxGroupSize = _nil
C_IslandsQueue.GetIslandsWeeklyQuestID = _nil
C_IslandsQueue.QueueForIsland = _nil
C_IslandsQueue.RequestPreloadRewardData = _nil
-- Events: ISLANDS_QUEUE_CLOSE, ISLANDS_QUEUE_OPEN
`;
