// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2f091131930cff6581899e76e73fd8732e52b960fff750de3ec0104b074c5f22
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/islandsinfodocumentation.lua
export const C_IslandsInfo = `
if C_IslandsInfo == nil then C_IslandsInfo = {} end
-- Events: ISLAND_AZERITE_GAIN
`;
