// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9004c6f5bfb7569e04a52ba528b8c4e9869524d9c2e5ce19c1e2c6c3e308a74d
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/islandsinfodocumentation.lua
export const C_IslandsInfo = `
if C_IslandsInfo == nil then C_IslandsInfo = {} end
-- Events: ISLAND_AZERITE_GAIN
`;
