// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e4f1a30cd1622cd0b777d35ad24ac316735a50e44798c36aae6520fa814b1e0b
// @sig-hash: sha256:a474782b19d9636b
// Source: Blizzard_APIDocumentationGenerated/itemsocketinfodocumentation.lua
export const C_ItemSocketInfo = `
if C_ItemSocketInfo == nil then C_ItemSocketInfo = {} end
C_ItemSocketInfo.AcceptSockets = _nil
C_ItemSocketInfo.ClickSocketButton = _nil
C_ItemSocketInfo.CloseSocketInfo = _nil
C_ItemSocketInfo.CompleteSocketing = _nil
C_ItemSocketInfo.GetCurrUIType = _nil
C_ItemSocketInfo.GetExistingSocketInfo = _nil
C_ItemSocketInfo.GetExistingSocketLink = _nil
C_ItemSocketInfo.GetNewSocketInfo = _nil
C_ItemSocketInfo.GetNewSocketLink = _nil
C_ItemSocketInfo.GetNumSockets = _nil
C_ItemSocketInfo.GetSocketItemBoundTradeable = _nil
C_ItemSocketInfo.GetSocketItemInfo = _nil
C_ItemSocketInfo.GetSocketItemRefundable = _nil
C_ItemSocketInfo.GetSocketTypes = _nil
C_ItemSocketInfo.HasBoundGemProposed = _nil
C_ItemSocketInfo.IsArtifactRelicItem = _nil
-- Events: SOCKET_INFO_ACCEPT, SOCKET_INFO_BIND_CONFIRM, SOCKET_INFO_CLOSE, SOCKET_INFO_FAILURE, SOCKET_INFO_REFUNDABLE_CONFIRM, SOCKET_INFO_SUCCESS, SOCKET_INFO_UI_EVENT_REGISTRATION_UPDATE, SOCKET_INFO_UPDATE
`;
