// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f2583e2c3952b87bd1fbf610d994840bed15a199c1f59fbfbbaea96164f7323c
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/itemtextdocumentation.lua
export const C_ItemText = `
if C_ItemText == nil then C_ItemText = {} end
-- Events: ITEM_TEXT_BEGIN, ITEM_TEXT_CLOSED, ITEM_TEXT_READY, ITEM_TEXT_TRANSLATION
`;
