// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e325ca873f1c9597001ee100f80683cdbe793f2fbca7bff4cf606e530cb2139e
// @sig-hash: sha256:a3c41d593f5bea69
// Source: Blizzard_APIDocumentationGenerated/iteminteractionuidocumentation.lua
export const C_ItemInteraction = `
if C_ItemInteraction == nil then C_ItemInteraction = {} end
C_ItemInteraction.ClearPendingItem = _nil
C_ItemInteraction.CloseUI = _nil
C_ItemInteraction.GetChargeInfo = _tbl
C_ItemInteraction.GetItemConversionCurrencyCost = _tbl
C_ItemInteraction.GetItemInteractionInfo = _nil
C_ItemInteraction.GetItemInteractionSpellId = _num
C_ItemInteraction.InitializeFrame = _nil
C_ItemInteraction.PerformItemInteraction = _nil
C_ItemInteraction.Reset = _nil
C_ItemInteraction.SetPendingItem = _bool
-- Events: ITEM_INTERACTION_CHARGE_INFO_UPDATED, ITEM_INTERACTION_ITEM_SELECTION_UPDATED
`;
