// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a4f3ada8ba3267e0ce79c9e26e193d53a6daa71b68a691572db8f7f7ca0af5bc
// @sig-hash: sha256:9e710e69000975ab
// Source: Blizzard_APIDocumentationGenerated/itemupgradedocumentation.lua
export const C_ItemUpgrade = `
if C_ItemUpgrade == nil then C_ItemUpgrade = {} end
C_ItemUpgrade.CanUpgradeItem = _nil
C_ItemUpgrade.ClearItemUpgrade = _nil
C_ItemUpgrade.CloseItemUpgrade = _nil
C_ItemUpgrade.GetHighWatermarkForItem = _nil
C_ItemUpgrade.GetHighWatermarkForSlot = _nil
C_ItemUpgrade.GetHighWatermarkSlotForItem = _nil
C_ItemUpgrade.GetItemHyperlink = _nil
C_ItemUpgrade.GetItemUpgradeCurrentLevel = _nil
C_ItemUpgrade.GetItemUpgradeEffect = _nil
C_ItemUpgrade.GetItemUpgradeItemInfo = _tbl
C_ItemUpgrade.GetItemUpgradePvpItemLevelDeltaValues = _nil
C_ItemUpgrade.GetNumItemUpgradeEffects = _nil
C_ItemUpgrade.IsItemBound = _nil
C_ItemUpgrade.SetItemUpgradeFromCursorItem = _nil
C_ItemUpgrade.SetItemUpgradeFromLocation = _nil
C_ItemUpgrade.UpgradeItem = _nil
-- Events: ITEM_UPGRADE_FAILED, ITEM_UPGRADE_MASTER_SET_ITEM, ITEM_UPGRADE_MASTER_UPDATE
`;
