// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a7b16b2074133398cbe880d681e17ed4f23809e34277acb7522cde12496a0cc4
// @sig-hash: sha256:0b9f72feedc7ba65
// Source: Blizzard_APIDocumentationGenerated/itemsocketinfodocumentation.lua
export const C_ItemSocketInfo = `
if C_ItemSocketInfo == nil then C_ItemSocketInfo = {} end
C_ItemSocketInfo.AcceptSockets = _nil("C_ItemSocketInfo.AcceptSockets")
C_ItemSocketInfo.ClickSocketButton = _nil("C_ItemSocketInfo.ClickSocketButton")
C_ItemSocketInfo.CloseSocketInfo = _nil("C_ItemSocketInfo.CloseSocketInfo")
C_ItemSocketInfo.CompleteSocketing = _nil("C_ItemSocketInfo.CompleteSocketing")
C_ItemSocketInfo.GetCurrUIType = _nil("C_ItemSocketInfo.GetCurrUIType")
C_ItemSocketInfo.GetExistingSocketInfo = _nil("C_ItemSocketInfo.GetExistingSocketInfo")
C_ItemSocketInfo.GetExistingSocketLink = _nil("C_ItemSocketInfo.GetExistingSocketLink")
C_ItemSocketInfo.GetNewSocketInfo = _nil("C_ItemSocketInfo.GetNewSocketInfo")
C_ItemSocketInfo.GetNewSocketLink = _nil("C_ItemSocketInfo.GetNewSocketLink")
C_ItemSocketInfo.GetNumSockets = _num("C_ItemSocketInfo.GetNumSockets")
C_ItemSocketInfo.GetSocketItemBoundTradeable = _bool("C_ItemSocketInfo.GetSocketItemBoundTradeable")
C_ItemSocketInfo.GetSocketItemInfo = _nil("C_ItemSocketInfo.GetSocketItemInfo")
C_ItemSocketInfo.GetSocketItemRefundable = _bool("C_ItemSocketInfo.GetSocketItemRefundable")
C_ItemSocketInfo.GetSocketTypes = _nil("C_ItemSocketInfo.GetSocketTypes")
C_ItemSocketInfo.HasBoundGemProposed = _bool("C_ItemSocketInfo.HasBoundGemProposed")
C_ItemSocketInfo.IsArtifactRelicItem = _bool("C_ItemSocketInfo.IsArtifactRelicItem")
-- Events: SOCKET_INFO_ACCEPT, SOCKET_INFO_BIND_CONFIRM, SOCKET_INFO_CLOSE, SOCKET_INFO_FAILURE, SOCKET_INFO_REFUNDABLE_CONFIRM, SOCKET_INFO_SUCCESS, SOCKET_INFO_UI_EVENT_REGISTRATION_UPDATE, SOCKET_INFO_UPDATE
`;
