// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:60446449a7d1f4bd03bef3738037e58019c0cedec439f12886111ad31ba53198
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/itemtextdocumentation.lua
export const C_ItemText = `
if C_ItemText == nil then C_ItemText = {} end
-- Events: ITEM_TEXT_BEGIN, ITEM_TEXT_CLOSED, ITEM_TEXT_READY, ITEM_TEXT_TRANSLATION
`;
