// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:eac1c61df7594bf211aa47b75798a7379e6b17bc1c0bb95b6e137c8444cccba9
// @sig-hash: sha256:8e3fdfbaf48bcd8a
// Source: Blizzard_APIDocumentationGenerated/keybindingsdocumentation.lua
export const C_KeyBindings = `
if C_KeyBindings == nil then C_KeyBindings = {} end
C_KeyBindings.ActivateBindingContext = _nil("C_KeyBindings.ActivateBindingContext")
C_KeyBindings.DeactivateBindingContext = _nil("C_KeyBindings.DeactivateBindingContext")
C_KeyBindings.GetBindingByKey = _str("C_KeyBindings.GetBindingByKey")
C_KeyBindings.GetBindingContextForAction = _nil("C_KeyBindings.GetBindingContextForAction")
C_KeyBindings.GetBindingIndex = _nil("C_KeyBindings.GetBindingIndex")
C_KeyBindings.GetCustomBindingType = _nil("C_KeyBindings.GetCustomBindingType")
C_KeyBindings.GetSearchTagsForAction = _tbl("C_KeyBindings.GetSearchTagsForAction")
C_KeyBindings.GetTurnStrafeStyle = _nil("C_KeyBindings.GetTurnStrafeStyle")
C_KeyBindings.IsBindingContextActive = _bool("C_KeyBindings.IsBindingContextActive")
C_KeyBindings.SetTurnStrafeStyle = _nil("C_KeyBindings.SetTurnStrafeStyle")
C_KeyBindings.UpdateTurnStrafeBindingsForCharacter = _nil("C_KeyBindings.UpdateTurnStrafeBindingsForCharacter")
-- Events: BINDINGS_LOADED, MODIFIER_STATE_CHANGED, NOTIFY_TURN_STRAFE_CHANGE, UPDATE_BINDINGS
`;
