// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b7786de49af809bbb33b63fa8f14f27fa509d63759c131a48cb876849fca0b66
// @sig-hash: sha256:65542bfa3bba2282
// Source: Blizzard_APIDocumentationGenerated/levellinkdocumentation.lua
export const C_LevelLink = `
if C_LevelLink == nil then C_LevelLink = {} end
C_LevelLink.IsActionLocked = _bool("C_LevelLink.IsActionLocked")
C_LevelLink.IsSpellLocked = _bool("C_LevelLink.IsSpellLocked")
`;
