// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f66ca03ba49903aed1ec27134814e6cb017552cc8860545d89edcd66e73596c5
// @sig-hash: sha256:cbfaf2202940b49e
// Source: Blizzard_APIDocumentationGenerated/levelsquishdocumentation.lua
export const C_LevelSquish = `
if C_LevelSquish == nil then C_LevelSquish = {} end
C_LevelSquish.ConvertFollowerLevel = _nil
C_LevelSquish.ConvertPlayerLevel = _nil
`;
