// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:658b327fac3939744095a7ffa7bd2fcddf712a48ca6264031157c7c50e766445
// @sig-hash: sha256:1155b14d23d28aeb
// Source: Blizzard_APIDocumentationGenerated/levellinkdocumentation.lua
export const C_LevelLink = `
if C_LevelLink == nil then C_LevelLink = {} end
C_LevelLink.IsActionLocked = _nil
C_LevelLink.IsSpellLocked = _nil
`;
