// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:530d104bac94ca940450b3d32e12bb42aea2059860ee6e513959cca8a62e15ae
// @sig-hash: sha256:960817b46c7c9964
// Source: Blizzard_APIDocumentationGenerated/legendarycraftingdocumentation.lua
export const C_LegendaryCrafting = `
if C_LegendaryCrafting == nil then C_LegendaryCrafting = {} end
C_LegendaryCrafting.CloseRuneforgeInteraction = _nil
C_LegendaryCrafting.CraftRuneforgeLegendary = _nil
C_LegendaryCrafting.GetRuneforgeItemPreviewInfo = _nil
C_LegendaryCrafting.GetRuneforgeLegendaryComponentInfo = _tbl
C_LegendaryCrafting.GetRuneforgeLegendaryCost = _tbl
C_LegendaryCrafting.GetRuneforgeLegendaryCraftSpellID = _nil
C_LegendaryCrafting.GetRuneforgeLegendaryCurrencies = _tbl
C_LegendaryCrafting.GetRuneforgeLegendaryUpgradeCost = _tbl
C_LegendaryCrafting.GetRuneforgeModifierInfo = _tbl
C_LegendaryCrafting.GetRuneforgeModifiers = _tbl
C_LegendaryCrafting.GetRuneforgePowerInfo = _tbl
C_LegendaryCrafting.GetRuneforgePowerSlots = _tbl
C_LegendaryCrafting.GetRuneforgePowers = _tbl
C_LegendaryCrafting.GetRuneforgePowersByClassSpecAndCovenant = _tbl
C_LegendaryCrafting.IsRuneforgeLegendary = _nil
C_LegendaryCrafting.IsRuneforgeLegendaryMaxLevel = _nil
C_LegendaryCrafting.IsUpgradeItemValidForRuneforgeLegendary = _nil
C_LegendaryCrafting.IsValidRuneforgeBaseItem = _nil
C_LegendaryCrafting.MakeRuneforgeCraftDescription = _tbl
C_LegendaryCrafting.UpgradeRuneforgeLegendary = _nil
-- Events: NEW_RUNEFORGE_POWER_ADDED, RUNEFORGE_LEGENDARY_CRAFTING_CLOSED, RUNEFORGE_LEGENDARY_CRAFTING_OPENED, RUNEFORGE_POWER_INFO_UPDATED
`;
