// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c4d6811ef787a9e75931b1781cf4c39064ea78474cec1c4b1fde471c713b64c1
// @sig-hash: sha256:48913adfe0669b0f
// Source: Blizzard_APIDocumentationGenerated/levelsquishdocumentation.lua
export const C_LevelSquish = `
if C_LevelSquish == nil then C_LevelSquish = {} end
C_LevelSquish.ConvertFollowerLevel = _num("C_LevelSquish.ConvertFollowerLevel")
C_LevelSquish.ConvertPlayerLevel = _num("C_LevelSquish.ConvertPlayerLevel")
`;
