// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:40919f96088a564363b845a942b89f70c604f84c74a037b3d428647b8c1c6e34
// @sig-hash: sha256:0e49add66cf8f95e
// Source: Blizzard_APIDocumentationGenerated/lfglistinfodocumentation.lua
export const C_LFGList = `
if C_LFGList == nil then C_LFGList = {} end
C_LFGList.CanActiveEntryUseAutoAccept = _bool
C_LFGList.CanCreateQuestGroup = _bool
C_LFGList.CanCreateScenarioGroup = _bool
C_LFGList.ClearApplicationTextFields = _nil
C_LFGList.ClearCreationTextFields = _nil
C_LFGList.ClearSearchTextFields = _nil
C_LFGList.CopyActiveEntryInfoToCreationFields = _nil
C_LFGList.CreateListing = _bool
C_LFGList.CreateScenarioListing = _bool
C_LFGList.DoesEntryTitleMatchPrebuiltTitle = _bool
C_LFGList.GetActiveEntryInfo = _tbl
C_LFGList.GetActivityFullName = _str
C_LFGList.GetActivityGroupInfo = _str
C_LFGList.GetActivityInfoTable = _tbl
C_LFGList.GetAdvancedFilter = _tbl
C_LFGList.GetApplicantBestDungeonScore = _tbl
C_LFGList.GetApplicantDungeonScoreForListing = _tbl
C_LFGList.GetApplicantInfo = _tbl
C_LFGList.GetApplicantPvpRatingInfoForListing = _tbl
C_LFGList.GetAvailableActivityGroups = _tbl
C_LFGList.GetFilteredSearchResults = _tbl
C_LFGList.GetGroupLeaverCountsByRole = _num
C_LFGList.GetKeystoneForActivity = _num
C_LFGList.GetLfgCategoryInfo = _tbl
C_LFGList.GetOwnedKeystoneActivityAndGroupAndLevel = _num
C_LFGList.GetPlaystyleString = _str
C_LFGList.GetPremadeGroupFinderStyle = _nil
C_LFGList.GetSearchResultInfo = _tbl
C_LFGList.GetSearchResultLeaderInfo = _tbl
C_LFGList.GetSearchResultPlayerInfo = _tbl
C_LFGList.GetSearchResults = _tbl
C_LFGList.HasActiveEntryInfo = _bool
C_LFGList.HasSearchResultInfo = _bool
C_LFGList.IsPlayerAuthenticatedForLFG = _bool
C_LFGList.IsPlayerValidForEndgameFieldEdits = _bool
C_LFGList.IsPremadeGroupFinderEnabled = _bool
C_LFGList.ListingUsesEndgameEditRestrictions = _bool
C_LFGList.ReportGroupAsAdvertisement = _nil
C_LFGList.SaveAdvancedFilter = _nil
C_LFGList.Search = _nil
C_LFGList.SetEntryTitle = _nil
C_LFGList.SetSearchToActivity = _nil
C_LFGList.SetSearchToQuestID = _nil
C_LFGList.SetSearchToScenarioID = _nil
C_LFGList.UpdateListing = _bool
C_LFGList.ValidateRequiredDungeonScore = _bool
C_LFGList.ValidateRequiredPvpRatingForActivity = _bool
-- Events: LFG_GROUP_DELISTED_LEADERSHIP_CHANGE, LFG_LIST_ACTIVE_ENTRY_UPDATE, LFG_LIST_APPLICANT_LIST_UPDATED, LFG_LIST_APPLICANT_UPDATED, LFG_LIST_APPLICATION_STATUS_UPDATED, LFG_LIST_AVAILABILITY_UPDATE, LFG_LIST_ENTRY_CREATION_FAILED, LFG_LIST_ENTRY_EXPIRED_TIMEOUT, LFG_LIST_ENTRY_EXPIRED_TOO_MANY_PLAYERS, LFG_LIST_JOINED_GROUP, LFG_LIST_SEARCH_FAILED, LFG_LIST_SEARCH_RESULT_UPDATED, LFG_LIST_SEARCH_RESULTS_RECEIVED, LFG_LIST_UPDATE_SEARCH_RESULTS
`;
