// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:45081fc53a10a7485bbfc224f0881a10d2fbf369a83dbcc22510d1833b74dad2
// @sig-hash: sha256:60d7872cea63be7c
// Source: Blizzard_APIDocumentationGenerated/liveeventdocumentation.lua
export const C_LiveEvent = `
if C_LiveEvent == nil then C_LiveEvent = {} end
C_LiveEvent.OnLiveEventBannerClicked = _nil
C_LiveEvent.OnLiveEventPopupClicked = _nil
`;
