// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9815425e4a96352e188ce6e0c59a1f93add6fd35f0b31023a188c90188d63db5
// @sig-hash: sha256:5f96189ec946c902
// Source: Blizzard_APIDocumentationGenerated/limitedinputdocumentation.lua
export const C_LimitedInput = `
if C_LimitedInput == nil then C_LimitedInput = {} end
C_LimitedInput.LimitedInputAllowed = _nil
`;
