// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:33f3e95b0567054d122903b657b80156ae9e6cebb1b24987a2556f47b6961f25
// @sig-hash: sha256:0dec68dcdbe21f2b
// Source: Blizzard_APIDocumentationGenerated/limitedinputdocumentation.lua
export const C_LimitedInput = `
if C_LimitedInput == nil then C_LimitedInput = {} end
C_LimitedInput.LimitedInputAllowed = _bool("C_LimitedInput.LimitedInputAllowed")
`;
