// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:40b02d01032927ab5ca5daae24a53900eda3d1b9d1f7692969d23de0f8a8d9c7
// @sig-hash: sha256:7a0ceac7882628b3
// Source: Blizzard_APIDocumentationGenerated/loretextdocumentation.lua
export const C_LoreText = `
if C_LoreText == nil then C_LoreText = {} end
C_LoreText.RequestLoreTextForCampaignID = _nil("C_LoreText.RequestLoreTextForCampaignID")
-- Events: LORE_TEXT_UPDATED_CAMPAIGN
`;
