// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:aab8043d568466767b7abdf872cba828e33a7a93cf7fe5c2a90db3e18869958b
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/loadingscreendocumentation.lua
export const C_LoadingScreen = `
if C_LoadingScreen == nil then C_LoadingScreen = {} end
-- Events: LOADING_SCREEN_DISABLED, LOADING_SCREEN_ENABLED
`;
