// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e56828fe5c3b2c71ad7ba5523a5ac0bbd2822d415de8533c063092e5a510f4af
// @sig-hash: sha256:5f8e8695652f89b0
// Source: Blizzard_APIDocumentationGenerated/lossofcontroldocumentation.lua
export const C_LossOfControl = `
if C_LossOfControl == nil then C_LossOfControl = {} end
C_LossOfControl.GetActiveLossOfControlData = _nil("C_LossOfControl.GetActiveLossOfControlData")
C_LossOfControl.GetActiveLossOfControlDataByUnit = _nil("C_LossOfControl.GetActiveLossOfControlDataByUnit")
C_LossOfControl.GetActiveLossOfControlDataCount = _num("C_LossOfControl.GetActiveLossOfControlDataCount")
C_LossOfControl.GetActiveLossOfControlDataCountByUnit = _num("C_LossOfControl.GetActiveLossOfControlDataCountByUnit")
C_LossOfControl.GetActiveLossOfControlDuration = _nil("C_LossOfControl.GetActiveLossOfControlDuration")
-- Events: LOSS_OF_CONTROL_ADDED, LOSS_OF_CONTROL_COMMENTATOR_ADDED, LOSS_OF_CONTROL_COMMENTATOR_UPDATE, LOSS_OF_CONTROL_UPDATE, PLAYER_CONTROL_GAINED, PLAYER_CONTROL_LOST
`;
