// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:df4baec09311110d0fa23f7f3586d8fe218c143ae9a04ba02013bca89983a09f
// @sig-hash: sha256:15e3b37a06b2570e
// Source: Blizzard_APIDocumentationGenerated/lootjournaldocumentation.lua
export const C_LootJournal = `
if C_LootJournal == nil then C_LootJournal = {} end
C_LootJournal.GetItemSetItems = _tbl("C_LootJournal.GetItemSetItems")
C_LootJournal.GetItemSets = _tbl("C_LootJournal.GetItemSets")
-- Events: LOOT_JOURNAL_ITEM_UPDATE
`;
