// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:95485e0ea8e11c5d7d8dabbbb8fef8f83a36260c98d4a01a6e1eb2e6dab6a901
// @sig-hash: sha256:d9210909b833d13b
// Source: Blizzard_APIDocumentationGenerated/lobbymatchmakerinfodocumentation.lua
export const C_LobbyMatchmakerInfo = `
if C_LobbyMatchmakerInfo == nil then C_LobbyMatchmakerInfo = {} end
C_LobbyMatchmakerInfo.AbandonQueue = _nil
C_LobbyMatchmakerInfo.EnterQueue = _nil
C_LobbyMatchmakerInfo.GetCurrQueuePlaylistEntry = _nil
C_LobbyMatchmakerInfo.GetCurrQueueState = _nil
C_LobbyMatchmakerInfo.GetQueueFromMainlineEnabled = _nil
C_LobbyMatchmakerInfo.GetQueueStartTime = _nil
C_LobbyMatchmakerInfo.IsInQueue = _nil
C_LobbyMatchmakerInfo.RespondToQueuePop = _nil
-- Events: LOBBY_MATCHMAKER_QUEUE_ABANDONED, LOBBY_MATCHMAKER_QUEUE_ERROR, LOBBY_MATCHMAKER_QUEUE_EXPIRED, LOBBY_MATCHMAKER_QUEUE_POPPED, LOBBY_MATCHMAKER_QUEUE_STATUS_UPDATE
`;
