// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d7f622ff95b7e1c01da25ceaadf672eb2a920a2b1ae8daf66dc1e9fae0f5fc93
// @sig-hash: sha256:ba8c06faadcf9538
// Source: Blizzard_APIDocumentationGenerated/lossofcontroldocumentation.lua
export const C_LossOfControl = `
if C_LossOfControl == nil then C_LossOfControl = {} end
C_LossOfControl.GetActiveLossOfControlData = _nil
C_LossOfControl.GetActiveLossOfControlDataByUnit = _nil
C_LossOfControl.GetActiveLossOfControlDataCount = _num
C_LossOfControl.GetActiveLossOfControlDataCountByUnit = _num
C_LossOfControl.GetActiveLossOfControlDuration = _nil
-- Events: LOSS_OF_CONTROL_ADDED, LOSS_OF_CONTROL_COMMENTATOR_ADDED, LOSS_OF_CONTROL_COMMENTATOR_UPDATE, LOSS_OF_CONTROL_UPDATE, PLAYER_CONTROL_GAINED, PLAYER_CONTROL_LOST
`;
