// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4827390bc9053e2fb49bce691f75a3e646f7d8bf07add2fb1241b22482ceae02
// @sig-hash: sha256:fe45dbc4768a5518
// Source: Blizzard_APIDocumentationGenerated/logdocumentation.lua
export const C_Log = `
if C_Log == nil then C_Log = {} end
C_Log.LogErrorMessage = _nil("C_Log.LogErrorMessage")
C_Log.LogMessage = _nil("C_Log.LogMessage")
C_Log.LogMessageWithPriority = _nil("C_Log.LogMessageWithPriority")
C_Log.LogWarningMessage = _nil("C_Log.LogWarningMessage")
`;
