// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:843b5f5435be54a526f95068354a5a3e23c4999fbd6d709e973696f78c5916fe
// @sig-hash: sha256:dfc7444266ab4cf6
// Source: Blizzard_APIDocumentationGenerated/lobbymatchmakerinfodocumentation.lua
export const C_LobbyMatchmakerInfo = `
if C_LobbyMatchmakerInfo == nil then C_LobbyMatchmakerInfo = {} end
C_LobbyMatchmakerInfo.AbandonQueue = _nil("C_LobbyMatchmakerInfo.AbandonQueue")
C_LobbyMatchmakerInfo.EnterQueue = _nil("C_LobbyMatchmakerInfo.EnterQueue")
C_LobbyMatchmakerInfo.GetCurrQueuePlaylistEntry = _nil("C_LobbyMatchmakerInfo.GetCurrQueuePlaylistEntry")
C_LobbyMatchmakerInfo.GetCurrQueueState = _nil("C_LobbyMatchmakerInfo.GetCurrQueueState")
C_LobbyMatchmakerInfo.GetQueueFromMainlineEnabled = _bool("C_LobbyMatchmakerInfo.GetQueueFromMainlineEnabled")
C_LobbyMatchmakerInfo.GetQueueStartTime = _num("C_LobbyMatchmakerInfo.GetQueueStartTime")
C_LobbyMatchmakerInfo.IsInQueue = _bool("C_LobbyMatchmakerInfo.IsInQueue")
C_LobbyMatchmakerInfo.RespondToQueuePop = _nil("C_LobbyMatchmakerInfo.RespondToQueuePop")
-- Events: LOBBY_MATCHMAKER_QUEUE_ABANDONED, LOBBY_MATCHMAKER_QUEUE_ERROR, LOBBY_MATCHMAKER_QUEUE_EXPIRED, LOBBY_MATCHMAKER_QUEUE_POPPED, LOBBY_MATCHMAKER_QUEUE_STATUS_UPDATE
`;
