// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f01e7a422ce6256719e40eb60df53f2584ed785d023659dc76829d94dd67c3e2
// @sig-hash: sha256:a2a8f3bf46e92c55
// Source: Blizzard_APIDocumentationGenerated/loothistorydocumentation.lua
export const C_LootHistory = `
if C_LootHistory == nil then C_LootHistory = {} end
C_LootHistory.GetAllEncounterInfos = _tbl
C_LootHistory.GetInfoForEncounter = _nil
C_LootHistory.GetLootHistoryTime = _num
C_LootHistory.GetSortedDropsForEncounter = _tbl
C_LootHistory.GetSortedInfoForDrop = _nil
-- Events: LOOT_HISTORY_CLEAR_HISTORY, LOOT_HISTORY_GO_TO_ENCOUNTER, LOOT_HISTORY_ONE_HUNDRED_ROLL, LOOT_HISTORY_UPDATE_DROP, LOOT_HISTORY_UPDATE_ENCOUNTER
`;
