// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d19c645a1e3e51ac982882fc78f4243bb4c5ab97794f10c58c887ea474e8a6cc
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/loadingscreendocumentation.lua
export const C_LoadingScreen = `
if C_LoadingScreen == nil then C_LoadingScreen = {} end
-- Events: LOADING_SCREEN_DISABLED, LOADING_SCREEN_ENABLED
`;
