// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2a25c0d8b1fa840181b84644bde0632281abc8b1a02d55b441370959239a2ece
// @sig-hash: sha256:f6fc0556284869bd
// Source: Blizzard_APIDocumentationGenerated/mapexplorationdocumentation.lua
export const C_MapExplorationInfo = `
if C_MapExplorationInfo == nil then C_MapExplorationInfo = {} end
C_MapExplorationInfo.GetExploredAreaIDsAtPosition = _tbl
C_MapExplorationInfo.GetExploredMapTextures = _tbl
-- Events: MAP_EXPLORATION_UPDATED
`;
