// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7b65cc65670eba1431c3b4566329de7302b345c02b2d231b828e28a808f38b95
// @sig-hash: sha256:05e5355e5412589a
// Source: Blizzard_APIDocumentationGenerated/mailinfodocumentation.lua
export const C_Mail = `
if C_Mail == nil then C_Mail = {} end
C_Mail.CanCheckInbox = _bool("C_Mail.CanCheckInbox")
C_Mail.GetCraftingOrderMailInfo = _nil("C_Mail.GetCraftingOrderMailInfo")
C_Mail.HasInboxMoney = _bool("C_Mail.HasInboxMoney")
C_Mail.IsCommandPending = _bool("C_Mail.IsCommandPending")
C_Mail.SetOpeningAll = _nil("C_Mail.SetOpeningAll")
-- Events: CLOSE_INBOX_ITEM, MAIL_CLOSED, MAIL_FAILED, MAIL_INBOX_UPDATE, MAIL_LOCK_SEND_ITEMS, MAIL_SEND_INFO_UPDATE, MAIL_SEND_SUCCESS, MAIL_SHOW, MAIL_SUCCESS, MAIL_UNLOCK_SEND_ITEMS, SEND_MAIL_COD_CHANGED, SEND_MAIL_MONEY_CHANGED, UPDATE_PENDING_MAIL
`;
