// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:bd13607800523f3ea085ece94cbdbe85988b7d3bcedc2413a81c37e6d6d8445b
// @sig-hash: sha256:58dec5eacfd01600
// Source: Blizzard_APIDocumentationGenerated/uimacrosdocumentation.lua
export const C_Macro = `
if C_Macro == nil then C_Macro = {} end
C_Macro.GetMacroName = _nil("C_Macro.GetMacroName")
C_Macro.GetSelectedMacroIcon = _nil("C_Macro.GetSelectedMacroIcon")
C_Macro.RunMacroText = _nil("C_Macro.RunMacroText")
C_Macro.SetMacroExecuteLineCallback = _nil("C_Macro.SetMacroExecuteLineCallback")
-- Events: UPDATE_MACROS
`;
