// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5afb1f3495d61803a815dc36a97d17531fed1182e7eac1ce1e0bd02cc5b74a15
// @sig-hash: sha256:16cdaeb46a035727
// Source: Blizzard_APIDocumentationGenerated/majorfactionsdocumentation.lua
export const C_MajorFactions = `
if C_MajorFactions == nil then C_MajorFactions = {} end
C_MajorFactions.GetCurrentRenownLevel = _num("C_MajorFactions.GetCurrentRenownLevel")
C_MajorFactions.GetMajorFactionData = _nil("C_MajorFactions.GetMajorFactionData")
C_MajorFactions.GetMajorFactionIDs = _tbl("C_MajorFactions.GetMajorFactionIDs")
C_MajorFactions.GetMajorFactionRenownInfo = _nil("C_MajorFactions.GetMajorFactionRenownInfo")
C_MajorFactions.GetRenownLevels = _tbl("C_MajorFactions.GetRenownLevels")
C_MajorFactions.GetRenownNPCFactionID = _num("C_MajorFactions.GetRenownNPCFactionID")
C_MajorFactions.GetRenownRewardsForLevel = _tbl("C_MajorFactions.GetRenownRewardsForLevel")
C_MajorFactions.HasMaximumRenown = _bool("C_MajorFactions.HasMaximumRenown")
C_MajorFactions.IsMajorFactionHiddenFromExpansionPage = _bool("C_MajorFactions.IsMajorFactionHiddenFromExpansionPage")
C_MajorFactions.IsWeeklyRenownCapped = _bool("C_MajorFactions.IsWeeklyRenownCapped")
C_MajorFactions.ShouldDisplayMajorFactionAsJourney = _bool("C_MajorFactions.ShouldDisplayMajorFactionAsJourney")
C_MajorFactions.ShouldUseJourneyRewardTrack = _bool("C_MajorFactions.ShouldUseJourneyRewardTrack")
-- Events: MAJOR_FACTION_INTERACTION_ENDED, MAJOR_FACTION_INTERACTION_STARTED, MAJOR_FACTION_RENOWN_LEVEL_CHANGED, MAJOR_FACTION_UNLOCKED
`;
