// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7d71f3c6cb86083f1945ac16e5f7a5d291c619e138fe0bed4d25292f88c49aad
// @sig-hash: sha256:e00e7edb79c9c077
// Source: Blizzard_APIDocumentationGenerated/mapdocumentation.lua
export const C_Map = `
if C_Map == nil then C_Map = {} end
C_Map.CanSetUserWaypointOnMap = _bool
C_Map.ClearUserWaypoint = _nil
C_Map.CloseWorldMapInteraction = _nil
C_Map.GetAreaInfo = _str
C_Map.GetBestMapForUnit = _nil
C_Map.GetBountySetMaps = _tbl
C_Map.GetFallbackWorldMapID = _num
C_Map.GetMapArtBackgroundAtlas = _nil
C_Map.GetMapArtHelpTextPosition = _nil
C_Map.GetMapArtID = _num
C_Map.GetMapArtLayerTextures = _tbl
C_Map.GetMapArtLayers = _tbl
C_Map.GetMapArtZoneTextPosition = _nil
C_Map.GetMapBannersForMap = _tbl
C_Map.GetMapChildrenInfo = _tbl
C_Map.GetMapDisplayInfo = _bool
C_Map.GetMapGroupID = _num
C_Map.GetMapGroupMembersInfo = _tbl
C_Map.GetMapHighlightInfoAtPosition = _nil
C_Map.GetMapHighlightPulseInfo = _nil
C_Map.GetMapInfo = _tbl
C_Map.GetMapInfoAtPosition = _tbl
C_Map.GetMapLevels = _num
C_Map.GetMapLinksForMap = _tbl
C_Map.GetMapPosFromWorldPos = _num
C_Map.GetMapRectOnMap = _num
C_Map.GetMapWorldSize = _num
C_Map.GetPlayerMapPosition = _nil
C_Map.GetUserWaypoint = _nil
C_Map.GetUserWaypointFromHyperlink = _nil
C_Map.GetUserWaypointHyperlink = _str
C_Map.GetUserWaypointPositionForMap = _nil
C_Map.GetWorldPosFromMapPos = _num
C_Map.HasUserWaypoint = _bool
C_Map.IsCityMap = _bool
C_Map.IsMapValidForNavBarDropdown = _bool
C_Map.MapHasArt = _bool
C_Map.OpenWorldMap = _nil
C_Map.RequestPreloadMap = _nil
C_Map.SetUserWaypoint = _nil
-- Events: NEW_WMO_CHUNK, PLAYER_MAP_CHANGED, USER_WAYPOINT_UPDATED, WORLD_MAP_OPEN, ZONE_CHANGED, ZONE_CHANGED_INDOORS, ZONE_CHANGED_NEW_AREA
`;
