// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4fa68a1a3630cf9ad0eb1876ca0654690214ad4cc84eeed27fbc8aaef218490c
// @sig-hash: sha256:2ae1bb5e41509950
// Source: Blizzard_APIDocumentationGenerated/mapexplorationdocumentation.lua
export const C_MapExplorationInfo = `
if C_MapExplorationInfo == nil then C_MapExplorationInfo = {} end
C_MapExplorationInfo.GetExploredAreaIDsAtPosition = _tbl("C_MapExplorationInfo.GetExploredAreaIDsAtPosition")
C_MapExplorationInfo.GetExploredMapTextures = _tbl("C_MapExplorationInfo.GetExploredMapTextures")
-- Events: MAP_EXPLORATION_UPDATED
`;
