// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4e81bf1e0bf7eb453c14bfaa0207e05940c06ff3e43f123a2c5b5b78fa957fed
// @sig-hash: sha256:6ac41fc92c7abae6
// Source: Blizzard_APIDocumentationGenerated/macoptionsdocumentation.lua
export const C_MacOptions = `
if C_MacOptions == nil then C_MacOptions = {} end
C_MacOptions.AreOSShortcutsDisabled = _nil
C_MacOptions.GetGameBundleName = _str
C_MacOptions.HasNewStyleInputMonitoring = _bool
C_MacOptions.IsInputMonitoringEnabled = _bool
C_MacOptions.IsMicrophoneEnabled = _bool
C_MacOptions.IsUniversalAccessEnabled = _bool
C_MacOptions.OpenInputMonitoring = _nil
C_MacOptions.OpenMicrophoneRequestDialogue = _nil
C_MacOptions.OpenUniversalAccess = _nil
C_MacOptions.SetOSShortcutsDisabled = _nil
`;
