// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4cb05a48b102655da070af52a1158f19c0f0e9bb128d3947e019bcf93fd92709
// @sig-hash: sha256:3aedea90e0e85d53
// Source: Blizzard_APIDocumentationGenerated/merchantframedocumentation.lua
export const C_MerchantFrame = `
if C_MerchantFrame == nil then C_MerchantFrame = {} end
C_MerchantFrame.GetBuybackItemID = _num("C_MerchantFrame.GetBuybackItemID")
C_MerchantFrame.GetItemInfo = _tbl("C_MerchantFrame.GetItemInfo")
C_MerchantFrame.GetNumJunkItems = _num("C_MerchantFrame.GetNumJunkItems")
C_MerchantFrame.IsMerchantItemRefundable = _bool("C_MerchantFrame.IsMerchantItemRefundable")
C_MerchantFrame.IsSellAllJunkEnabled = _bool("C_MerchantFrame.IsSellAllJunkEnabled")
C_MerchantFrame.SellAllJunkItems = _nil("C_MerchantFrame.SellAllJunkItems")
-- Events: MERCHANT_CLOSED, MERCHANT_FILTER_ITEM_UPDATE, MERCHANT_SHOW, MERCHANT_UPDATE
`;
