// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6565d564c71b451645379247370cb3dd1565d53989ec3354702799fbbf60d026
// @sig-hash: sha256:4cb9a9ebfb0068e6
// Source: Blizzard_APIDocumentationGenerated/minimapdocumentation.lua
export const C_Minimap = `
if C_Minimap == nil then C_Minimap = {} end
C_Minimap.CanTrackBattlePets = _bool("C_Minimap.CanTrackBattlePets")
C_Minimap.ClearAllTracking = _nil("C_Minimap.ClearAllTracking")
C_Minimap.ClearMinimapInsetInfo = _nil("C_Minimap.ClearMinimapInsetInfo")
C_Minimap.GetDefaultTrackingValue = _bool("C_Minimap.GetDefaultTrackingValue")
C_Minimap.GetDrawGroundTextures = _bool("C_Minimap.GetDrawGroundTextures")
C_Minimap.GetNumQuestPOIWorldEffects = _num("C_Minimap.GetNumQuestPOIWorldEffects")
C_Minimap.GetNumTrackingTypes = _num("C_Minimap.GetNumTrackingTypes")
C_Minimap.GetObjectIconTextureCoords = _num("C_Minimap.GetObjectIconTextureCoords")
C_Minimap.GetPOITextureCoords = _num("C_Minimap.GetPOITextureCoords")
C_Minimap.GetTrackingFilter = _tbl("C_Minimap.GetTrackingFilter")
C_Minimap.GetTrackingInfo = _nil("C_Minimap.GetTrackingInfo")
C_Minimap.GetUiMapID = _nil("C_Minimap.GetUiMapID")
C_Minimap.GetViewRadius = _num("C_Minimap.GetViewRadius")
C_Minimap.IsFilteredOut = _bool("C_Minimap.IsFilteredOut")
C_Minimap.IsInsideQuestBlob = _bool("C_Minimap.IsInsideQuestBlob")
C_Minimap.IsRotateMinimapIgnored = _bool("C_Minimap.IsRotateMinimapIgnored")
C_Minimap.IsTrackingAccountCompletedQuests = _bool("C_Minimap.IsTrackingAccountCompletedQuests")
C_Minimap.IsTrackingBattlePets = _bool("C_Minimap.IsTrackingBattlePets")
C_Minimap.IsTrackingHiddenQuests = _bool("C_Minimap.IsTrackingHiddenQuests")
C_Minimap.SetDrawGroundTextures = _nil("C_Minimap.SetDrawGroundTextures")
C_Minimap.SetIgnoreRotateMinimap = _nil("C_Minimap.SetIgnoreRotateMinimap")
C_Minimap.SetMinimapInsetInfo = _nil("C_Minimap.SetMinimapInsetInfo")
C_Minimap.SetTracking = _nil("C_Minimap.SetTracking")
C_Minimap.ShouldUseHybridMinimap = _bool("C_Minimap.ShouldUseHybridMinimap")
-- Events: MINIMAP_PING, MINIMAP_UPDATE_TRACKING, MINIMAP_UPDATE_ZOOM, PLAYER_INSIDE_QUEST_BLOB_STATE_CHANGED
`;
