// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:df65e97ed0418dacd8b9897440db8cddd12494fd83df6f2f3213a973ab3dd255
// @sig-hash: sha256:886db4cc5ce08106
// Source: Blizzard_APIDocumentationGenerated/uimodelinfodocumentation.lua
export const C_ModelInfo = `
if C_ModelInfo == nil then C_ModelInfo = {} end
C_ModelInfo.AddActiveModelScene = _nil("C_ModelInfo.AddActiveModelScene")
C_ModelInfo.AddActiveModelSceneActor = _nil("C_ModelInfo.AddActiveModelSceneActor")
C_ModelInfo.ClearActiveModelScene = _nil("C_ModelInfo.ClearActiveModelScene")
C_ModelInfo.ClearActiveModelSceneActor = _nil("C_ModelInfo.ClearActiveModelSceneActor")
C_ModelInfo.GetModelSceneActorDisplayInfoByID = _tbl("C_ModelInfo.GetModelSceneActorDisplayInfoByID")
C_ModelInfo.GetModelSceneActorInfoByID = _tbl("C_ModelInfo.GetModelSceneActorInfoByID")
C_ModelInfo.GetModelSceneCameraInfoByID = _tbl("C_ModelInfo.GetModelSceneCameraInfoByID")
C_ModelInfo.GetModelSceneInfoByID = _tbl("C_ModelInfo.GetModelSceneInfoByID")
-- Events: UI_MODEL_SCENE_INFO_UPDATED
`;
