// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9cd336e962215fa0f7dcd4e4d894f3515fbe3909cd05e106d47e1a7f90423ea3
// @sig-hash: sha256:f06debe9132e87a2
// Source: Blizzard_APIDocumentationGenerated/mountjournaldocumentation.lua
export const C_MountJournal = `
if C_MountJournal == nil then C_MountJournal = {} end
C_MountJournal.ApplyMountEquipment = _bool
C_MountJournal.AreMountEquipmentEffectsSuppressed = _bool
C_MountJournal.ClearFanfare = _nil
C_MountJournal.ClearRecentFanfares = _nil
C_MountJournal.Dismiss = _nil
C_MountJournal.GetAllCreatureDisplayIDsForMountID = _tbl
C_MountJournal.GetAppliedMountEquipmentID = _nil
C_MountJournal.GetCollectedDragonridingMounts = _tbl
C_MountJournal.GetCollectedFilterSetting = _bool
C_MountJournal.GetDisplayedMountAllCreatureDisplayInfo = _tbl
C_MountJournal.GetDisplayedMountID = _num
C_MountJournal.GetDisplayedMountInfo = _str
C_MountJournal.GetDisplayedMountInfoExtra = _nil
C_MountJournal.GetDynamicFlightModeSpellID = _num
C_MountJournal.GetIsFavorite = _bool
C_MountJournal.GetMountAllCreatureDisplayInfoByID = _tbl
C_MountJournal.GetMountEquipmentUnlockLevel = _num
C_MountJournal.GetMountFromItem = _nil
C_MountJournal.GetMountFromSpell = _nil
C_MountJournal.GetMountIDs = _tbl
C_MountJournal.GetMountInfoByID = _str
C_MountJournal.GetMountInfoExtraByID = _nil
C_MountJournal.GetMountLink = _nil
C_MountJournal.GetMountUsabilityByID = _bool
C_MountJournal.GetNumDisplayedMounts = _num
C_MountJournal.GetNumMounts = _num
C_MountJournal.GetNumMountsNeedingFanfare = _num
C_MountJournal.IsDragonridingUnlocked = _bool
C_MountJournal.IsItemMountEquipment = _bool
C_MountJournal.IsMountEquipmentApplied = _bool
C_MountJournal.IsSourceChecked = _bool
C_MountJournal.IsTypeChecked = _bool
C_MountJournal.IsUsingDefaultFilters = _bool
C_MountJournal.IsValidSourceFilter = _bool
C_MountJournal.IsValidTypeFilter = _bool
C_MountJournal.NeedsFanfare = _bool
C_MountJournal.Pickup = _nil
C_MountJournal.PickupDynamicFlightMode = _nil
C_MountJournal.SetAllSourceFilters = _nil
C_MountJournal.SetAllTypeFilters = _nil
C_MountJournal.SetCollectedFilterSetting = _nil
C_MountJournal.SetDefaultFilters = _nil
C_MountJournal.SetIsFavorite = _nil
C_MountJournal.SetSearch = _nil
C_MountJournal.SetSourceFilter = _nil
C_MountJournal.SetTypeFilter = _nil
C_MountJournal.SummonByID = _nil
C_MountJournal.SwapDynamicFlightMode = _nil
-- Events: MOUNT_EQUIPMENT_APPLY_RESULT, MOUNT_JOURNAL_SEARCH_UPDATED, MOUNT_JOURNAL_USABILITY_CHANGED, NEW_MOUNT_ADDED
`;
