// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5739ab9aae60365ed1c9d9efcbe4fbf932702e3992c0f2a7bc850b6259b7d67b
// @sig-hash: sha256:62bc15e6442b1365
// Source: Blizzard_APIDocumentationGenerated/uimodifiedinstancedocumentation.lua
export const C_ModifiedInstance = `
if C_ModifiedInstance == nil then C_ModifiedInstance = {} end
C_ModifiedInstance.GetModifiedInstanceInfoFromMapID = _tbl
`;
