// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8f1679f7903f8d1a011f64d3e6233e94273a359b902a62271cb61ec30deb99e2
// @sig-hash: sha256:a6373df23a7d9f69
// Source: Blizzard_APIDocumentationGenerated/uimodelinfodocumentation.lua
export const C_ModelInfo = `
if C_ModelInfo == nil then C_ModelInfo = {} end
C_ModelInfo.AddActiveModelScene = _nil
C_ModelInfo.AddActiveModelSceneActor = _nil
C_ModelInfo.ClearActiveModelScene = _nil
C_ModelInfo.ClearActiveModelSceneActor = _nil
C_ModelInfo.GetModelSceneActorDisplayInfoByID = _tbl
C_ModelInfo.GetModelSceneActorInfoByID = _tbl
C_ModelInfo.GetModelSceneCameraInfoByID = _tbl
C_ModelInfo.GetModelSceneInfoByID = _tbl
-- Events: UI_MODEL_SCENE_INFO_UPDATED
`;
