// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:53ce91c4a4537c195b56d10703f003db301ee330299b7adc339d89359ca746cf
// @sig-hash: sha256:ae9628325f6106f5
// Source: Blizzard_APIDocumentationGenerated/mythicplusinfodocumentation.lua
export const C_MythicPlus = `
if C_MythicPlus == nil then C_MythicPlus = {} end
C_MythicPlus.GetCurrentAffixes = _tbl("C_MythicPlus.GetCurrentAffixes")
C_MythicPlus.GetCurrentSeason = _num("C_MythicPlus.GetCurrentSeason")
C_MythicPlus.GetCurrentSeasonValues = _num("C_MythicPlus.GetCurrentSeasonValues")
C_MythicPlus.GetCurrentUIDisplaySeason = _nil("C_MythicPlus.GetCurrentUIDisplaySeason")
C_MythicPlus.GetEndOfRunGearSequenceLevel = _nil("C_MythicPlus.GetEndOfRunGearSequenceLevel")
C_MythicPlus.GetLastWeeklyBestInformation = _num("C_MythicPlus.GetLastWeeklyBestInformation")
C_MythicPlus.GetOwnedKeystoneChallengeMapID = _num("C_MythicPlus.GetOwnedKeystoneChallengeMapID")
C_MythicPlus.GetOwnedKeystoneLevel = _num("C_MythicPlus.GetOwnedKeystoneLevel")
C_MythicPlus.GetOwnedKeystoneMapID = _num("C_MythicPlus.GetOwnedKeystoneMapID")
C_MythicPlus.GetRewardLevelForDifficultyLevel = _num("C_MythicPlus.GetRewardLevelForDifficultyLevel")
C_MythicPlus.GetRewardLevelFromKeystoneLevel = _nil("C_MythicPlus.GetRewardLevelFromKeystoneLevel")
C_MythicPlus.GetRunHistory = _tbl("C_MythicPlus.GetRunHistory")
C_MythicPlus.GetSeasonBestAffixScoreInfoForMap = _tbl("C_MythicPlus.GetSeasonBestAffixScoreInfoForMap")
C_MythicPlus.GetSeasonBestForMap = _nil("C_MythicPlus.GetSeasonBestForMap")
C_MythicPlus.GetSeasonBestMythicRatingFromThisExpansion = _num("C_MythicPlus.GetSeasonBestMythicRatingFromThisExpansion")
C_MythicPlus.GetWeeklyBestForMap = _tbl("C_MythicPlus.GetWeeklyBestForMap")
C_MythicPlus.GetWeeklyChestRewardLevel = _num("C_MythicPlus.GetWeeklyChestRewardLevel")
C_MythicPlus.IsMythicPlusActive = _bool("C_MythicPlus.IsMythicPlusActive")
C_MythicPlus.RequestCurrentAffixes = _nil("C_MythicPlus.RequestCurrentAffixes")
C_MythicPlus.RequestMapInfo = _nil("C_MythicPlus.RequestMapInfo")
C_MythicPlus.RequestRewards = _nil("C_MythicPlus.RequestRewards")
-- Events: MYTHIC_PLUS_CURRENT_AFFIX_UPDATE, MYTHIC_PLUS_NEW_WEEKLY_RECORD
`;
