// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:08e3eb7824865d2b0143004482fc13c6e984a779166735cbb7c2321c628aa977
// @sig-hash: sha256:d691bd1186de8b75
// Source: Blizzard_APIDocumentationGenerated/mythicplusinfodocumentation.lua
export const C_MythicPlus = `
if C_MythicPlus == nil then C_MythicPlus = {} end
C_MythicPlus.GetCurrentAffixes = _tbl
C_MythicPlus.GetCurrentSeason = _num
C_MythicPlus.GetCurrentSeasonValues = _num
C_MythicPlus.GetCurrentUIDisplaySeason = _nil
C_MythicPlus.GetEndOfRunGearSequenceLevel = _nil
C_MythicPlus.GetLastWeeklyBestInformation = _num
C_MythicPlus.GetOwnedKeystoneChallengeMapID = _num
C_MythicPlus.GetOwnedKeystoneLevel = _num
C_MythicPlus.GetOwnedKeystoneMapID = _num
C_MythicPlus.GetRewardLevelForDifficultyLevel = _num
C_MythicPlus.GetRewardLevelFromKeystoneLevel = _nil
C_MythicPlus.GetRunHistory = _tbl
C_MythicPlus.GetSeasonBestAffixScoreInfoForMap = _tbl
C_MythicPlus.GetSeasonBestForMap = _nil
C_MythicPlus.GetSeasonBestMythicRatingFromThisExpansion = _num
C_MythicPlus.GetWeeklyBestForMap = _tbl
C_MythicPlus.GetWeeklyChestRewardLevel = _num
C_MythicPlus.IsMythicPlusActive = _bool
C_MythicPlus.RequestCurrentAffixes = _nil
C_MythicPlus.RequestMapInfo = _nil
C_MythicPlus.RequestRewards = _nil
-- Events: MYTHIC_PLUS_CURRENT_AFFIX_UPDATE, MYTHIC_PLUS_NEW_WEEKLY_RECORD
`;
