// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b2ebf4322b419f0eef5e4bd827e9a5a96285e782f5d546207078e659bebeb691
// @sig-hash: sha256:994d155c32684b11
// Source: Blizzard_APIDocumentationGenerated/nameplatemanagerdocumentation.lua
export const C_NamePlateManager = `
if C_NamePlateManager == nil then C_NamePlateManager = {} end
C_NamePlateManager.GetNamePlateHitTestInsets = _nil
C_NamePlateManager.IsNamePlateUnitBehindCamera = _bool
C_NamePlateManager.SetNamePlateHitTestInsets = _nil
C_NamePlateManager.SetNamePlateSimplified = _nil
-- Events: FORBIDDEN_NAME_PLATE_CREATED, FORBIDDEN_NAME_PLATE_UNIT_ADDED, FORBIDDEN_NAME_PLATE_UNIT_REMOVED, NAME_PLATE_CREATED, NAME_PLATE_UNIT_ADDED, NAME_PLATE_UNIT_BEHIND_CAMERA_CHANGED, NAME_PLATE_UNIT_REMOVED
`;
