// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5e9ccd0ac184c6779f2497e98fbfe1e9d360997987b6268f30400384d9e572c3
// @sig-hash: sha256:5d26245311fa429c
// Source: Blizzard_APIDocumentationGenerated/nameplatemanagerdocumentation.lua
export const C_NamePlateManager = `
if C_NamePlateManager == nil then C_NamePlateManager = {} end
C_NamePlateManager.GetNamePlateHitTestInsets = _nil("C_NamePlateManager.GetNamePlateHitTestInsets")
C_NamePlateManager.IsNamePlateUnitBehindCamera = _bool("C_NamePlateManager.IsNamePlateUnitBehindCamera")
C_NamePlateManager.SetNamePlateHitTestInsets = _nil("C_NamePlateManager.SetNamePlateHitTestInsets")
C_NamePlateManager.SetNamePlateSimplified = _nil("C_NamePlateManager.SetNamePlateSimplified")
-- Events: FORBIDDEN_NAME_PLATE_CREATED, FORBIDDEN_NAME_PLATE_UNIT_ADDED, FORBIDDEN_NAME_PLATE_UNIT_REMOVED, NAME_PLATE_CREATED, NAME_PLATE_UNIT_ADDED, NAME_PLATE_UNIT_BEHIND_CAMERA_CHANGED, NAME_PLATE_UNIT_REMOVED
`;
