// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ed5e3768a9ac119327b7be36b5652e0e8ce35a1714e61daa45f5f62247cdc390
// @sig-hash: sha256:b7b8a389fdd91e80
// Source: Blizzard_APIDocumentationGenerated/ingamenavigationdocumentation.lua
export const C_Navigation = `
if C_Navigation == nil then C_Navigation = {} end
C_Navigation.GetDistance = _num
C_Navigation.GetFrame = _nil
C_Navigation.GetNearestPartyMemberToken = _str
C_Navigation.GetTargetState = _nil
C_Navigation.HasValidScreenPosition = _bool
C_Navigation.WasClampedToScreen = _bool
-- Events: NAVIGATION_DESTINATION_REACHED, NAVIGATION_FRAME_CREATED, NAVIGATION_FRAME_DESTROYED
`;
