// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3845128abe00f819a7441f0164b6a1f9bf229467de0f841340deab621b55e20f
// @sig-hash: sha256:d8fbf40ab4095f26
// Source: Blizzard_APIDocumentationGenerated/nameplatedocumentation.lua
export const C_NamePlate = `
if C_NamePlate == nil then C_NamePlate = {} end
C_NamePlate.GetNamePlateForUnit = _nil("C_NamePlate.GetNamePlateForUnit")
C_NamePlate.GetNamePlateSize = _nil("C_NamePlate.GetNamePlateSize")
C_NamePlate.GetNamePlates = _tbl("C_NamePlate.GetNamePlates")
C_NamePlate.SetNamePlateSize = _nil("C_NamePlate.SetNamePlateSize")
`;
