// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e76e23daa67246cc917801ba84ca474f73c809b70d6885c0f15302e29832616a
// @sig-hash: sha256:9994f3d85a6037a3
// Source: Blizzard_APIDocumentationGenerated/neighborhoodinitiativedocumentation.lua
export const C_NeighborhoodInitiative = `
if C_NeighborhoodInitiative == nil then C_NeighborhoodInitiative = {} end
C_NeighborhoodInitiative.AddTrackedInitiativeTask = _nil
C_NeighborhoodInitiative.GetActiveNeighborhood = _nil
C_NeighborhoodInitiative.GetAvailableHouseXP = _num
C_NeighborhoodInitiative.GetInitiativeActivityLogInfo = _nil
C_NeighborhoodInitiative.GetInitiativeTaskChatLink = _str
C_NeighborhoodInitiative.GetInitiativeTaskInfo = _nil
C_NeighborhoodInitiative.GetNeighborhoodInitiativeInfo = _nil
C_NeighborhoodInitiative.GetRequiredLevel = _num
C_NeighborhoodInitiative.GetTrackedInitiativeTasks = _tbl
C_NeighborhoodInitiative.IsInitiativeEnabled = _bool
C_NeighborhoodInitiative.IsPlayerInNeighborhoodGroup = _bool
C_NeighborhoodInitiative.IsViewingActiveNeighborhood = _bool
C_NeighborhoodInitiative.PlayerHasInitiativeAccess = _bool
C_NeighborhoodInitiative.PlayerMeetsRequiredLevel = _bool
C_NeighborhoodInitiative.RemoveTrackedInitiativeTask = _nil
C_NeighborhoodInitiative.RequestInitiativeActivityLog = _nil
C_NeighborhoodInitiative.RequestNeighborhoodInitiativeInfo = _nil
C_NeighborhoodInitiative.SetActiveNeighborhood = _nil
C_NeighborhoodInitiative.SetViewingNeighborhood = _nil
-- Events: INITIATIVE_ACTIVITY_LOG_UPDATED, INITIATIVE_COMPLETED, INITIATIVE_TASK_COMPLETED, INITIATIVE_TASKS_TRACKED_LIST_CHANGED, INITIATIVE_TASKS_TRACKED_UPDATED, NEIGHBORHOOD_INITIATIVE_UPDATED
`;
