// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:52da8676e0983246f47cf349986b7e6acf7f122d7a0d4c9101c62636ab673391
// @sig-hash: sha256:c63a39e0e4d3ba10
// Source: Blizzard_APIDocumentationGenerated/newitemsdocumentation.lua
export const C_NewItems = `
if C_NewItems == nil then C_NewItems = {} end
C_NewItems.ClearAll = _nil("C_NewItems.ClearAll")
C_NewItems.IsNewItem = _bool("C_NewItems.IsNewItem")
C_NewItems.RemoveNewItem = _nil("C_NewItems.RemoveNewItem")
`;
