// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7d32a789de0f63cae603b341a3217eaf4b2c87a4076ef73ca0cb19a68dd1041c
// @sig-hash: sha256:07656831ac90a501
// Source: Blizzard_APIDocumentationGenerated/neighborhoodinitiativedocumentation.lua
export const C_NeighborhoodInitiative = `
if C_NeighborhoodInitiative == nil then C_NeighborhoodInitiative = {} end
C_NeighborhoodInitiative.AddTrackedInitiativeTask = _nil("C_NeighborhoodInitiative.AddTrackedInitiativeTask")
C_NeighborhoodInitiative.GetActiveNeighborhood = _nil("C_NeighborhoodInitiative.GetActiveNeighborhood")
C_NeighborhoodInitiative.GetAvailableHouseXP = _num("C_NeighborhoodInitiative.GetAvailableHouseXP")
C_NeighborhoodInitiative.GetInitiativeActivityLogInfo = _nil("C_NeighborhoodInitiative.GetInitiativeActivityLogInfo")
C_NeighborhoodInitiative.GetInitiativeTaskChatLink = _str("C_NeighborhoodInitiative.GetInitiativeTaskChatLink")
C_NeighborhoodInitiative.GetInitiativeTaskInfo = _nil("C_NeighborhoodInitiative.GetInitiativeTaskInfo")
C_NeighborhoodInitiative.GetNeighborhoodInitiativeInfo = _nil("C_NeighborhoodInitiative.GetNeighborhoodInitiativeInfo")
C_NeighborhoodInitiative.GetRequiredLevel = _num("C_NeighborhoodInitiative.GetRequiredLevel")
C_NeighborhoodInitiative.GetTrackedInitiativeTasks = _tbl("C_NeighborhoodInitiative.GetTrackedInitiativeTasks")
C_NeighborhoodInitiative.IsInitiativeEnabled = _bool("C_NeighborhoodInitiative.IsInitiativeEnabled")
C_NeighborhoodInitiative.IsPlayerInNeighborhoodGroup = _bool("C_NeighborhoodInitiative.IsPlayerInNeighborhoodGroup")
C_NeighborhoodInitiative.IsViewingActiveNeighborhood = _bool("C_NeighborhoodInitiative.IsViewingActiveNeighborhood")
C_NeighborhoodInitiative.PlayerHasInitiativeAccess = _bool("C_NeighborhoodInitiative.PlayerHasInitiativeAccess")
C_NeighborhoodInitiative.PlayerMeetsRequiredLevel = _bool("C_NeighborhoodInitiative.PlayerMeetsRequiredLevel")
C_NeighborhoodInitiative.RemoveTrackedInitiativeTask = _nil("C_NeighborhoodInitiative.RemoveTrackedInitiativeTask")
C_NeighborhoodInitiative.RequestInitiativeActivityLog = _nil("C_NeighborhoodInitiative.RequestInitiativeActivityLog")
C_NeighborhoodInitiative.RequestNeighborhoodInitiativeInfo = _nil("C_NeighborhoodInitiative.RequestNeighborhoodInitiativeInfo")
C_NeighborhoodInitiative.SetActiveNeighborhood = _nil("C_NeighborhoodInitiative.SetActiveNeighborhood")
C_NeighborhoodInitiative.SetViewingNeighborhood = _nil("C_NeighborhoodInitiative.SetViewingNeighborhood")
-- Events: INITIATIVE_ACTIVITY_LOG_UPDATED, INITIATIVE_COMPLETED, INITIATIVE_TASK_COMPLETED, INITIATIVE_TASKS_TRACKED_LIST_CHANGED, INITIATIVE_TASKS_TRACKED_UPDATED, NEIGHBORHOOD_INITIATIVE_UPDATED
`;
