// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:05880cf15f8f1811f098b204f3063ca039fb6c3dd6b02db403269b1dbde3753a
// @sig-hash: sha256:9d68a631e75484d1
// Source: Blizzard_APIDocumentationGenerated/partyposeuidocumentation.lua
export const C_PartyPose = `
if C_PartyPose == nil then C_PartyPose = {} end
C_PartyPose.ExtraAction = _nil
C_PartyPose.GetPartyPoseInfoByID = _tbl
C_PartyPose.GetPartyPoseInfoByMapID = _tbl
C_PartyPose.HasExtraAction = _nil
-- Events: SHOW_PARTY_POSE_UI
`;
