// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8c906e770faab07684dcc7ed544d87851563189a300b1fe250acc3891c1a85f9
// @sig-hash: sha256:7b0f3c8b5054c0a7
// Source: Blizzard_APIDocumentationGenerated/partyinfodocumentation.lua
export const C_PartyInfo = `
if C_PartyInfo == nil then C_PartyInfo = {} end
C_PartyInfo.AllowedToDoPartyConversion = _nil
C_PartyInfo.CanFormCrossFactionParties = _nil
C_PartyInfo.CanInvite = _nil
C_PartyInfo.CanStartInstanceAbandonVote = _nil
C_PartyInfo.ChallengeModeRestrictionsActive = _nil
C_PartyInfo.ConfirmConvertToRaid = _nil
C_PartyInfo.ConfirmInviteTravelPass = _nil
C_PartyInfo.ConfirmInviteUnit = _nil
C_PartyInfo.ConfirmLeaveParty = _nil
C_PartyInfo.ConfirmRequestInviteFromUnit = _nil
C_PartyInfo.ConvertToParty = _nil
C_PartyInfo.ConvertToRaid = _nil
C_PartyInfo.DelveTeleportOut = _nil
C_PartyInfo.DoCountdown = _nil
C_PartyInfo.GetActiveCategories = _tbl
C_PartyInfo.GetAvailableLootMethods = _tbl
C_PartyInfo.GetInstanceAbandonShutdownTime = _nil
C_PartyInfo.GetInstanceAbandonVoteCooldownTime = _nil
C_PartyInfo.GetInstanceAbandonVoteRequirements = _nil
C_PartyInfo.GetInstanceAbandonVoteResponse = _nil
C_PartyInfo.GetInstanceAbandonVoteTime = _nil
C_PartyInfo.GetInviteConfirmationInvalidQueues = _tbl
C_PartyInfo.GetInviteReferralInfo = _nil
C_PartyInfo.GetLootMethod = _nil
C_PartyInfo.GetLootMethodStyle = _nil
C_PartyInfo.GetMinItemLevel = _nil
C_PartyInfo.GetMinLevel = _nil
C_PartyInfo.GetNumInstanceAbandonGroupVoteResponses = _nil
C_PartyInfo.GetRestrictPings = _nil
C_PartyInfo.InviteUnit = _nil
C_PartyInfo.IsChallengeModeActive = _nil
C_PartyInfo.IsChallengeModeKeystoneOwner = _nil
C_PartyInfo.IsCrossFactionParty = _nil
C_PartyInfo.IsDelveComplete = _nil
C_PartyInfo.IsDelveInProgress = _nil
C_PartyInfo.IsLootMethodAvailable = _nil
C_PartyInfo.IsPartyFull = _nil
C_PartyInfo.IsPartyInJailersTower = _nil
C_PartyInfo.IsPartyWalkIn = _nil
C_PartyInfo.LeaveParty = _nil
C_PartyInfo.RequestInviteFromUnit = _nil
C_PartyInfo.SetInstanceAbandonVoteResponse = _nil
C_PartyInfo.SetLootMethod = _nil
C_PartyInfo.SetRestrictPings = _nil
C_PartyInfo.StartInstanceAbandonVote = _nil
-- Events: BNET_REQUEST_INVITE_CONFIRMATION, CONVERT_TO_RAID_CONFIRMATION, ENTERED_DIFFERENT_INSTANCE_FROM_PARTY, GROUP_FORMED, GROUP_INVITE_CONFIRMATION, GROUP_JOINED, GROUP_LEFT, GROUP_ROSTER_UPDATE, INSTANCE_ABANDON_VOTE_FINISHED, INSTANCE_ABANDON_VOTE_STARTED, INSTANCE_ABANDON_VOTE_UPDATED, INSTANCE_BOOT_START, INSTANCE_BOOT_STOP, INSTANCE_GROUP_SIZE_CHANGED, INVITE_TO_PARTY_CONFIRMATION, INVITE_TRAVEL_PASS_CONFIRMATION, LEAVE_PARTY_CONFIRMATION, PARTY_INVITE_CANCEL, PARTY_INVITE_REQUEST, PARTY_LEADER_CHANGED, PARTY_LFG_RESTRICTED, PARTY_LOOT_METHOD_CHANGED, PARTY_MEMBER_DISABLE, PARTY_MEMBER_ENABLE, PLAYER_DIFFICULTY_CHANGED, PLAYER_ROLES_ASSIGNED, RAID_ROSTER_UPDATE, READY_CHECK, READY_CHECK_CONFIRM, READY_CHECK_FINISHED, REQUEST_INVITE_CONFIRMATION, VOTE_KICK_REASON_NEEDED
`;
