// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:90e77f9227f77744286ce782102012d971ee2ad50be8c99de02257f715cfd984
// @sig-hash: sha256:cc480e0d83102763
// Source: Blizzard_APIDocumentationGenerated/partyposeuidocumentation.lua
export const C_PartyPose = `
if C_PartyPose == nil then C_PartyPose = {} end
C_PartyPose.ExtraAction = _nil("C_PartyPose.ExtraAction")
C_PartyPose.GetPartyPoseInfoByID = _tbl("C_PartyPose.GetPartyPoseInfoByID")
C_PartyPose.GetPartyPoseInfoByMapID = _tbl("C_PartyPose.GetPartyPoseInfoByMapID")
C_PartyPose.HasExtraAction = _bool("C_PartyPose.HasExtraAction")
-- Events: SHOW_PARTY_POSE_UI
`;
