// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:dac591e025dd1cde83e8d0955f8f4028694a5c31b0173c51467a06b90eff1fbb
// @sig-hash: sha256:715b748cd80acc27
// Source: Blizzard_APIDocumentationGenerated/paperdollinfodocumentation.lua
export const C_PaperDollInfo = `
if C_PaperDollInfo == nil then C_PaperDollInfo = {} end
C_PaperDollInfo.CanAutoEquipCursorItem = _bool("C_PaperDollInfo.CanAutoEquipCursorItem")
C_PaperDollInfo.CanCursorCanGoInSlot = _bool("C_PaperDollInfo.CanCursorCanGoInSlot")
C_PaperDollInfo.GetArmorEffectiveness = _num("C_PaperDollInfo.GetArmorEffectiveness")
C_PaperDollInfo.GetArmorEffectivenessAgainstTarget = _nil("C_PaperDollInfo.GetArmorEffectivenessAgainstTarget")
C_PaperDollInfo.GetInspectAzeriteItemEmpoweredChoices = _tbl("C_PaperDollInfo.GetInspectAzeriteItemEmpoweredChoices")
C_PaperDollInfo.GetInspectGuildInfo = _num("C_PaperDollInfo.GetInspectGuildInfo")
C_PaperDollInfo.GetInspectItemLevel = _num("C_PaperDollInfo.GetInspectItemLevel")
C_PaperDollInfo.GetInspectRatedBGBlitzData = _tbl("C_PaperDollInfo.GetInspectRatedBGBlitzData")
C_PaperDollInfo.GetInspectRatedBGData = _tbl("C_PaperDollInfo.GetInspectRatedBGData")
C_PaperDollInfo.GetInspectRatedSoloShuffleData = _tbl("C_PaperDollInfo.GetInspectRatedSoloShuffleData")
C_PaperDollInfo.GetMinItemLevel = _nil("C_PaperDollInfo.GetMinItemLevel")
C_PaperDollInfo.GetStaggerPercentage = _num("C_PaperDollInfo.GetStaggerPercentage")
C_PaperDollInfo.IsInventorySlotEnabled = _bool("C_PaperDollInfo.IsInventorySlotEnabled")
C_PaperDollInfo.IsRangedSlotShown = _bool("C_PaperDollInfo.IsRangedSlotShown")
C_PaperDollInfo.OffhandHasShield = _bool("C_PaperDollInfo.OffhandHasShield")
C_PaperDollInfo.OffhandHasWeapon = _bool("C_PaperDollInfo.OffhandHasWeapon")
-- Events: AVOIDANCE_UPDATE, CHARACTER_POINTS_CHANGED, CHARACTER_UPGRADE_SPELL_TIER_SET, COMBAT_RATING_UPDATE, DISABLE_XP_GAIN, ENABLE_XP_GAIN, EQUIP_BIND_CONFIRM, INSPECT_HONOR_UPDATE, INSPECT_READY, LIFESTEAL_UPDATE, MASTERY_UPDATE, PET_SPELL_POWER_UPDATE, PLAYER_AVG_ITEM_LEVEL_UPDATE, PLAYER_EQUIPMENT_CHANGED, PROFESSION_EQUIPMENT_CHANGED, PVP_POWER_UPDATE, SPEED_UPDATE, SPELL_POWER_CHANGED, STURDINESS_UPDATE, UPDATE_FACTION, UPDATE_INVENTORY_ALERTS, UPDATE_INVENTORY_DURABILITY, WEAPON_SLOT_CHANGED
`;
