// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d3721c8b0de07115507141fc6e227dc9357c6834f2cd4cf00dd785fc92525791
// @sig-hash: sha256:75fa225483e7d86a
// Source: Blizzard_APIDocumentationGenerated/perksprogramdocumentation.lua
export const C_PerksProgram = `
if C_PerksProgram == nil then C_PerksProgram = {} end
C_PerksProgram.ClearFrozenPerksVendorItem = _nil("C_PerksProgram.ClearFrozenPerksVendorItem")
C_PerksProgram.CloseInteraction = _nil("C_PerksProgram.CloseInteraction")
C_PerksProgram.GetAvailableCategoryIDs = _tbl("C_PerksProgram.GetAvailableCategoryIDs")
C_PerksProgram.GetAvailableVendorItemIDs = _tbl("C_PerksProgram.GetAvailableVendorItemIDs")
C_PerksProgram.GetCategoryInfo = _tbl("C_PerksProgram.GetCategoryInfo")
C_PerksProgram.GetCurrencyAmount = _num("C_PerksProgram.GetCurrencyAmount")
C_PerksProgram.GetDraggedPerksVendorItem = _num("C_PerksProgram.GetDraggedPerksVendorItem")
C_PerksProgram.GetFrozenPerksVendorItemInfo = _tbl("C_PerksProgram.GetFrozenPerksVendorItemInfo")
C_PerksProgram.GetPendingChestRewards = _tbl("C_PerksProgram.GetPendingChestRewards")
C_PerksProgram.GetPerksProgramItemDisplayInfo = _tbl("C_PerksProgram.GetPerksProgramItemDisplayInfo")
C_PerksProgram.GetTimeRemaining = _nil("C_PerksProgram.GetTimeRemaining")
C_PerksProgram.GetVendorItemInfo = _tbl("C_PerksProgram.GetVendorItemInfo")
C_PerksProgram.GetVendorItemInfoRefundTimeLeft = _nil("C_PerksProgram.GetVendorItemInfoRefundTimeLeft")
C_PerksProgram.IsAttackAnimToggleEnabled = _bool("C_PerksProgram.IsAttackAnimToggleEnabled")
C_PerksProgram.IsFrozenPerksVendorItem = _bool("C_PerksProgram.IsFrozenPerksVendorItem")
C_PerksProgram.IsMountSpecialAnimToggleEnabled = _bool("C_PerksProgram.IsMountSpecialAnimToggleEnabled")
C_PerksProgram.ItemSelectedTelemetry = _nil("C_PerksProgram.ItemSelectedTelemetry")
C_PerksProgram.PickupPerksVendorItem = _nil("C_PerksProgram.PickupPerksVendorItem")
C_PerksProgram.RequestCartCheckout = _nil("C_PerksProgram.RequestCartCheckout")
C_PerksProgram.RequestPendingChestRewards = _nil("C_PerksProgram.RequestPendingChestRewards")
C_PerksProgram.RequestPurchase = _nil("C_PerksProgram.RequestPurchase")
C_PerksProgram.RequestRefund = _nil("C_PerksProgram.RequestRefund")
C_PerksProgram.ResetHeldItemDragAndDrop = _nil("C_PerksProgram.ResetHeldItemDragAndDrop")
C_PerksProgram.SetFrozenPerksVendorItem = _nil("C_PerksProgram.SetFrozenPerksVendorItem")
-- Events: CHEST_REWARDS_UPDATED_FROM_SERVER, PERKS_PROGRAM_ADD_PENDING_SHOP_ITEM, PERKS_PROGRAM_CLOSE, PERKS_PROGRAM_CURRENCY_AWARDED, PERKS_PROGRAM_CURRENCY_REFRESH, PERKS_PROGRAM_DATA_REFRESH, PERKS_PROGRAM_DATA_SPECIFIC_ITEM_REFRESH, PERKS_PROGRAM_DISABLED, PERKS_PROGRAM_OPEN, PERKS_PROGRAM_PURCHASE_CART_SUCCESS, PERKS_PROGRAM_PURCHASE_SUCCESS, PERKS_PROGRAM_REFUND_SUCCESS, PERKS_PROGRAM_REMOVE_PENDING_SHOP_ITEM, PERKS_PROGRAM_RESULT_ERROR, PERKS_PROGRAM_SET_FROZEN_ITEM
`;
