// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:aeb173ceb6f76e443dfb7392f3797d68c0cf314a7068b61b536e1197d69a5393
// @sig-hash: sha256:6d472f90294cd034
// Source: Blizzard_APIDocumentationGenerated/perksactivitiesdocumentation.lua
export const C_PerksActivities = `
if C_PerksActivities == nil then C_PerksActivities = {} end
C_PerksActivities.AddTrackedPerksActivity = _nil
C_PerksActivities.ClearPerksActivitiesPendingCompletion = _nil
C_PerksActivities.GetAllPerksActivityTags = _tbl
C_PerksActivities.GetPerksActivitiesInfo = _tbl
C_PerksActivities.GetPerksActivitiesPendingCompletion = _tbl
C_PerksActivities.GetPerksActivityChatLink = _nil
C_PerksActivities.GetPerksActivityInfo = _nil
C_PerksActivities.GetPerksUIThemePrefix = _nil
C_PerksActivities.GetTrackedPerksActivities = _tbl
C_PerksActivities.RemoveTrackedPerksActivity = _nil
-- Events: PERKS_ACTIVITIES_TRACKED_LIST_CHANGED, PERKS_ACTIVITIES_TRACKED_UPDATED, PERKS_ACTIVITIES_UPDATED, PERKS_ACTIVITY_COMPLETED
`;
