// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2e5f75fdd8e187a43587d192a7bfc26d7ce8d14303992b8a017626bd685471ab
// @sig-hash: sha256:2e1274526d8a1fd6
// Source: Blizzard_APIDocumentationGenerated/petinfodocumentation.lua
export const C_PetInfo = `
if C_PetInfo == nil then C_PetInfo = {} end
C_PetInfo.GetPetTalentTree = _nil
C_PetInfo.GetPetTamersForMap = _tbl
C_PetInfo.GetSpellForPetAction = _nil
C_PetInfo.IsPetActionPassive = _nil
C_PetInfo.PetAbandon = _nil
C_PetInfo.PetAssistMode = _nil
C_PetInfo.PetRename = _nil
-- Events: PET_ATTACK_START, PET_ATTACK_STOP, PET_BAR_HIDEGRID, PET_BAR_SHOWGRID, PET_BAR_UPDATE_COOLDOWN, PET_DISMISS_START, PET_FORCE_NAME_DECLENSION, PET_UI_CLOSE, RAISED_AS_GHOUL, UPDATE_POSSESS_BAR, UPDATE_VEHICLE_ACTIONBAR
`;
