// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d5582385dd24bbba3a3c0399598f17c52537c15bfde2e51f0f581c120377329b
// @sig-hash: sha256:43a591aa9c4a7bff
// Source: Blizzard_APIDocumentationGenerated/petjournalinfodocumentation.lua
export const C_PetJournal = `
if C_PetJournal == nil then C_PetJournal = {} end
C_PetJournal.ClearHoveredBattlePet = _nil
C_PetJournal.ClearSearchFilter = _nil
C_PetJournal.DismissSummonedPet = _nil
C_PetJournal.GetDisplayIDByIndex = _nil
C_PetJournal.GetDisplayProbabilityByIndex = _nil
C_PetJournal.GetNonBattlePetLinkByIndex = _str
C_PetJournal.GetNumDisplays = _nil
C_PetJournal.GetNumPetsInJournal = _num
C_PetJournal.GetOwnedPetIDs = _tbl
C_PetJournal.GetPetAbilityInfo = _str
C_PetJournal.GetPetAbilityListTable = _tbl
C_PetJournal.GetPetInfoTableByPetID = _tbl
C_PetJournal.GetPetLoadOutInfo = _nil
C_PetJournal.GetPetSummonInfo = _bool
C_PetJournal.GetSearchFilter = _str
C_PetJournal.HasFavoritePets = _bool
C_PetJournal.IsCurrentlySummoned = _bool
C_PetJournal.IsUsingDefaultFilters = _bool
C_PetJournal.PetIsSummonable = _bool
C_PetJournal.PetUsesRandomDisplay = _nil
C_PetJournal.SetDefaultFilters = _nil
C_PetJournal.SetHoveredBattlePet = _nil
C_PetJournal.SetSearchFilter = _nil
C_PetJournal.SpellTargetBattlePet = _nil
-- Events: BATTLEPET_FORCE_NAME_DECLENSION, COMPANION_LEARNED, COMPANION_UNLEARNED, COMPANION_UPDATE, NEW_PET_ADDED, PET_JOURNAL_AUTO_SLOTTED_PET, PET_JOURNAL_CAGE_FAILED, PET_JOURNAL_LIST_UPDATE, PET_JOURNAL_NEW_BATTLE_SLOT, PET_JOURNAL_PET_DELETED, PET_JOURNAL_PET_RESTORED, PET_JOURNAL_PET_REVOKED, PET_JOURNAL_PETS_HEALED, PET_JOURNAL_TRAP_LEVEL_SET, UPDATE_SUMMONPETS_ACTION
`;
