// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6789a703a0e523ab6dde2fef4065eb70089d110ec7ee6161f1d298a984c9f5df
// @sig-hash: sha256:57541c2798dc4818
// Source: Blizzard_APIDocumentationGenerated/perksprogramdocumentation.lua
export const C_PerksProgram = `
if C_PerksProgram == nil then C_PerksProgram = {} end
C_PerksProgram.ClearFrozenPerksVendorItem = _nil
C_PerksProgram.CloseInteraction = _nil
C_PerksProgram.GetAvailableCategoryIDs = _tbl
C_PerksProgram.GetAvailableVendorItemIDs = _tbl
C_PerksProgram.GetCategoryInfo = _tbl
C_PerksProgram.GetCurrencyAmount = _num
C_PerksProgram.GetDraggedPerksVendorItem = _num
C_PerksProgram.GetFrozenPerksVendorItemInfo = _tbl
C_PerksProgram.GetPendingChestRewards = _tbl
C_PerksProgram.GetPerksProgramItemDisplayInfo = _tbl
C_PerksProgram.GetTimeRemaining = _nil
C_PerksProgram.GetVendorItemInfo = _tbl
C_PerksProgram.GetVendorItemInfoRefundTimeLeft = _nil
C_PerksProgram.IsAttackAnimToggleEnabled = _bool
C_PerksProgram.IsFrozenPerksVendorItem = _bool
C_PerksProgram.IsMountSpecialAnimToggleEnabled = _bool
C_PerksProgram.ItemSelectedTelemetry = _nil
C_PerksProgram.PickupPerksVendorItem = _nil
C_PerksProgram.RequestCartCheckout = _nil
C_PerksProgram.RequestPendingChestRewards = _nil
C_PerksProgram.RequestPurchase = _nil
C_PerksProgram.RequestRefund = _nil
C_PerksProgram.ResetHeldItemDragAndDrop = _nil
C_PerksProgram.SetFrozenPerksVendorItem = _nil
-- Events: CHEST_REWARDS_UPDATED_FROM_SERVER, PERKS_PROGRAM_ADD_PENDING_SHOP_ITEM, PERKS_PROGRAM_CLOSE, PERKS_PROGRAM_CURRENCY_AWARDED, PERKS_PROGRAM_CURRENCY_REFRESH, PERKS_PROGRAM_DATA_REFRESH, PERKS_PROGRAM_DATA_SPECIFIC_ITEM_REFRESH, PERKS_PROGRAM_DISABLED, PERKS_PROGRAM_OPEN, PERKS_PROGRAM_PURCHASE_CART_SUCCESS, PERKS_PROGRAM_PURCHASE_SUCCESS, PERKS_PROGRAM_REFUND_SUCCESS, PERKS_PROGRAM_REMOVE_PENDING_SHOP_ITEM, PERKS_PROGRAM_RESULT_ERROR, PERKS_PROGRAM_SET_FROZEN_ITEM
`;
