// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e53226d23df3a6120ba781c90245b493d45f4922f86b38a4c3b0b4248bfedc8b
// @sig-hash: sha256:89b63d6ee0597363
// Source: Blizzard_APIDocumentationGenerated/petbattlesdocumentation.lua
export const C_PetBattles = `
if C_PetBattles == nil then C_PetBattles = {} end
C_PetBattles.GetBreedQuality = _nil
C_PetBattles.GetIcon = _nil
C_PetBattles.GetName = _str
C_PetBattles.IsPlayerNPC = _bool
C_PetBattles.IsWildBattle = _bool
`;
