// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ea0835a53d51e0c5dc199310c02127de7c3792acb2c3a3e7a863b4aad4ab4871
// @sig-hash: sha256:e8d826f29b6966c4
// Source: Blizzard_APIDocumentationGenerated/petbattlesdocumentation.lua
export const C_PetBattles = `
if C_PetBattles == nil then C_PetBattles = {} end
C_PetBattles.GetBreedQuality = _nil("C_PetBattles.GetBreedQuality")
C_PetBattles.GetIcon = _nil("C_PetBattles.GetIcon")
C_PetBattles.GetName = _str("C_PetBattles.GetName")
C_PetBattles.IsPlayerNPC = _bool("C_PetBattles.IsPlayerNPC")
C_PetBattles.IsWildBattle = _bool("C_PetBattles.IsWildBattle")
`;
