// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e10da91ee1a9f628ed0bbe83f87f5a825f94825d66f284463b74f80abc4cc005
// @sig-hash: sha256:ec283c1a4f700c9b
// Source: Blizzard_APIDocumentationGenerated/photosharinguidocumentation.lua
export const C_PhotoSharing = `
if C_PhotoSharing == nil then C_PhotoSharing = {} end
C_PhotoSharing.BeginAuthorizationFlow = _nil
C_PhotoSharing.ClearAuthorization = _nil
C_PhotoSharing.CompleteAuthorizationFlow = _nil
C_PhotoSharing.GetCropRatio = _num
C_PhotoSharing.GetPhotoSharingAuthURL = _str
C_PhotoSharing.GetStatus = _nil
C_PhotoSharing.IsAuthorized = _bool
C_PhotoSharing.IsEnabled = _bool
C_PhotoSharing.SetScreenshotPreviewTexture = _nil
C_PhotoSharing.TakePhoto = _nil
C_PhotoSharing.UploadPhotoToService = _nil
-- Events: PHOTO_SHARING_AUTHORIZATION_NEEDED, PHOTO_SHARING_AUTHORIZATION_UPDATED, PHOTO_SHARING_PHOTO_UPLOAD_STATUS, PHOTO_SHARING_SCREENSHOT_READY, PHOTO_SHARING_THIRD_PARTY_AUTHORIZATION_NEEDED
`;
