// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:65cb5edf74b5345c9a611fd44c4158adca76a962c33ed4befba17c2c6bb97734
// @sig-hash: sha256:8ec5108d661bc45b
// Source: Blizzard_APIDocumentationGenerated/pingmanagersecuredocumentation.lua
export const C_PingSecure = `
if C_PingSecure == nil then C_PingSecure = {} end
C_PingSecure.ClearPendingPingInfo = _nil("C_PingSecure.ClearPendingPingInfo")
C_PingSecure.CreateFrame = _nil("C_PingSecure.CreateFrame")
C_PingSecure.DisplayError = _nil("C_PingSecure.DisplayError")
C_PingSecure.GetTargetPingReceiver = _nil("C_PingSecure.GetTargetPingReceiver")
C_PingSecure.GetTargetWorldPing = _bool("C_PingSecure.GetTargetWorldPing")
C_PingSecure.GetTargetWorldPingAndSend = _tbl("C_PingSecure.GetTargetWorldPingAndSend")
C_PingSecure.SendPing = _nil("C_PingSecure.SendPing")
C_PingSecure.SetPendingPingOffScreenCallback = _nil("C_PingSecure.SetPendingPingOffScreenCallback")
C_PingSecure.SetPingCooldownStartedCallback = _nil("C_PingSecure.SetPingCooldownStartedCallback")
C_PingSecure.SetPingPinFrameAddedCallback = _nil("C_PingSecure.SetPingPinFrameAddedCallback")
C_PingSecure.SetPingPinFrameRemovedCallback = _nil("C_PingSecure.SetPingPinFrameRemovedCallback")
C_PingSecure.SetPingPinFrameScreenClampStateUpdatedCallback = _nil("C_PingSecure.SetPingPinFrameScreenClampStateUpdatedCallback")
C_PingSecure.SetPingRadialWheelCreatedCallback = _nil("C_PingSecure.SetPingRadialWheelCreatedCallback")
C_PingSecure.SetSendMacroPingCallback = _nil("C_PingSecure.SetSendMacroPingCallback")
C_PingSecure.SetTogglePingListenerCallback = _nil("C_PingSecure.SetTogglePingListenerCallback")
`;
