// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a2d83f328bf50a282b9da359ebf269135b3983f54f879cf16a3e75b1a79bb715
// @sig-hash: sha256:5f18c6c3c30bb503
// Source: Blizzard_APIDocumentationGenerated/pingmanagersecuredocumentation.lua
export const C_PingSecure = `
if C_PingSecure == nil then C_PingSecure = {} end
C_PingSecure.ClearPendingPingInfo = _nil
C_PingSecure.CreateFrame = _nil
C_PingSecure.DisplayError = _nil
C_PingSecure.GetTargetPingReceiver = _nil
C_PingSecure.GetTargetWorldPing = _bool
C_PingSecure.GetTargetWorldPingAndSend = _tbl
C_PingSecure.SendPing = _nil
C_PingSecure.SetPendingPingOffScreenCallback = _nil
C_PingSecure.SetPingCooldownStartedCallback = _nil
C_PingSecure.SetPingPinFrameAddedCallback = _nil
C_PingSecure.SetPingPinFrameRemovedCallback = _nil
C_PingSecure.SetPingPinFrameScreenClampStateUpdatedCallback = _nil
C_PingSecure.SetPingRadialWheelCreatedCallback = _nil
C_PingSecure.SetSendMacroPingCallback = _nil
C_PingSecure.SetTogglePingListenerCallback = _nil
`;
