// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:19b1abf7cd02d50a6595ad93c5a0c172aa18b34e5f9232f23a9568e718d2b6c1
// @sig-hash: sha256:40fb1494962983e0
// Source: Blizzard_APIDocumentationGenerated/pingmanagerdocumentation.lua
export const C_Ping = `
if C_Ping == nil then C_Ping = {} end
C_Ping.GetContextualPingTypeForUnit = _nil("C_Ping.GetContextualPingTypeForUnit")
C_Ping.GetCooldownInfo = _tbl("C_Ping.GetCooldownInfo")
C_Ping.GetDefaultPingOptions = _tbl("C_Ping.GetDefaultPingOptions")
C_Ping.GetTextureKitForType = _nil("C_Ping.GetTextureKitForType")
C_Ping.IsPingSystemEnabled = _bool("C_Ping.IsPingSystemEnabled")
C_Ping.SendMacroPing = _nil("C_Ping.SendMacroPing")
C_Ping.TogglePingListener = _nil("C_Ping.TogglePingListener")
-- Events: PING_SYSTEM_ERROR
`;
