// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d4d7dcd19c8a9d3cb9105e123fd53d934865f8e7a162fad7184fa4b2bf6ee784
// @sig-hash: sha256:a65b91c453b85ada
// Source: Blizzard_APIDocumentationGenerated/pingmanagerdocumentation.lua
export const C_Ping = `
if C_Ping == nil then C_Ping = {} end
C_Ping.GetContextualPingTypeForUnit = _nil
C_Ping.GetCooldownInfo = _tbl
C_Ping.GetDefaultPingOptions = _tbl
C_Ping.GetTextureKitForType = _nil
C_Ping.IsPingSystemEnabled = _bool
C_Ping.SendMacroPing = _nil
C_Ping.TogglePingListener = _nil
-- Events: PING_SYSTEM_ERROR
`;
