// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:22ae66e4d37594d9343f14bc3d2919a3a8305a5e5c08fc0b541c99556a7825d9
// @sig-hash: sha256:391fe13727ae5efc
// Source: Blizzard_APIDocumentationGenerated/playerchoicedocumentation.lua
export const C_PlayerChoice = `
if C_PlayerChoice == nil then C_PlayerChoice = {} end
C_PlayerChoice.GetCurrentPlayerChoiceInfo = _tbl("C_PlayerChoice.GetCurrentPlayerChoiceInfo")
C_PlayerChoice.GetNumRerolls = _num("C_PlayerChoice.GetNumRerolls")
C_PlayerChoice.GetRemainingTime = _nil("C_PlayerChoice.GetRemainingTime")
C_PlayerChoice.IsWaitingForPlayerChoiceResponse = _bool("C_PlayerChoice.IsWaitingForPlayerChoiceResponse")
C_PlayerChoice.OnUIClosed = _nil("C_PlayerChoice.OnUIClosed")
C_PlayerChoice.RequestRerollPlayerChoice = _nil("C_PlayerChoice.RequestRerollPlayerChoice")
C_PlayerChoice.SendPlayerChoiceResponse = _nil("C_PlayerChoice.SendPlayerChoiceResponse")
-- Events: PLAYER_CHOICE_CLOSE, PLAYER_CHOICE_UPDATE
`;
