// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:88995b59b4d4958778d08464f317bab4df3a58e0dbd23d1092bbc3d04d84adf0
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/platformdocumentation.lua
export const C_Platform = `
if C_Platform == nil then C_Platform = {} end
`;
