// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5147eb58f60571ff83263c4e07958e4b0133c3fc6bd18bc403d8d58b26370e00
// @sig-hash: sha256:116eca73c373544d
// Source: Blizzard_APIDocumentationGenerated/playerchoicedocumentation.lua
export const C_PlayerChoice = `
if C_PlayerChoice == nil then C_PlayerChoice = {} end
C_PlayerChoice.GetCurrentPlayerChoiceInfo = _tbl
C_PlayerChoice.GetNumRerolls = _num
C_PlayerChoice.GetRemainingTime = _nil
C_PlayerChoice.IsWaitingForPlayerChoiceResponse = _bool
C_PlayerChoice.OnUIClosed = _nil
C_PlayerChoice.RequestRerollPlayerChoice = _nil
C_PlayerChoice.SendPlayerChoiceResponse = _nil
-- Events: PLAYER_CHOICE_CLOSE, PLAYER_CHOICE_UPDATE
`;
