// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:086f27ed0e84995225e40ef92b15df62d19f6b2e382cd5b52c2e6211f8c45663
// @sig-hash: sha256:68a2f30a6074fe91
// Source: Blizzard_APIDocumentationGenerated/playerlocationdocumentation.lua
export const C_PlayerInfo = `
if C_PlayerInfo == nil then C_PlayerInfo = {} end
C_PlayerInfo.GUIDIsPlayer = _bool
C_PlayerInfo.GetClass = _nil
C_PlayerInfo.GetName = _nil
C_PlayerInfo.GetRace = _nil
C_PlayerInfo.GetSex = _nil
C_PlayerInfo.IsConnected = _nil
C_PlayerInfo.UnitIsSameServer = _bool
`;
