// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0f3b06ac776444aad2e66ccacb31b39100279310f35bb4ae5b25fd61eee0479e
// @sig-hash: sha256:ff4439b4c0fe9387
// Source: Blizzard_APIDocumentationGenerated/playerinteractionmanagerdocumentation.lua
export const C_PlayerInteractionManager = `
if C_PlayerInteractionManager == nil then C_PlayerInteractionManager = {} end
C_PlayerInteractionManager.ClearInteraction = _nil("C_PlayerInteractionManager.ClearInteraction")
C_PlayerInteractionManager.ConfirmationInteraction = _nil("C_PlayerInteractionManager.ConfirmationInteraction")
C_PlayerInteractionManager.InteractUnit = _bool("C_PlayerInteractionManager.InteractUnit")
C_PlayerInteractionManager.IsInteractingWithNpcOfType = _bool("C_PlayerInteractionManager.IsInteractingWithNpcOfType")
C_PlayerInteractionManager.IsReplacingUnit = _bool("C_PlayerInteractionManager.IsReplacingUnit")
C_PlayerInteractionManager.IsValidNPCInteraction = _bool("C_PlayerInteractionManager.IsValidNPCInteraction")
C_PlayerInteractionManager.ReopenInteraction = _nil("C_PlayerInteractionManager.ReopenInteraction")
-- Events: PLAYER_INTERACTION_MANAGER_FRAME_HIDE, PLAYER_INTERACTION_MANAGER_FRAME_SHOW
`;
