// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c425e442ded2b77a3e42ef09086fd0dd83162f05a480c0304e112cec60e42c51
// @sig-hash: sha256:68a2f30a6074fe91
// Source: Blizzard_APIDocumentationGenerated/playerlocationdocumentation.lua
export const C_PlayerInfo = `
if C_PlayerInfo == nil then C_PlayerInfo = {} end
C_PlayerInfo.GUIDIsPlayer = _bool("C_PlayerInfo.GUIDIsPlayer")
C_PlayerInfo.GetClass = _nil("C_PlayerInfo.GetClass")
C_PlayerInfo.GetName = _nil("C_PlayerInfo.GetName")
C_PlayerInfo.GetRace = _nil("C_PlayerInfo.GetRace")
C_PlayerInfo.GetSex = _nil("C_PlayerInfo.GetSex")
C_PlayerInfo.IsConnected = _nil("C_PlayerInfo.IsConnected")
C_PlayerInfo.UnitIsSameServer = _bool("C_PlayerInfo.UnitIsSameServer")
`;
