// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:cfe6e488ee6afa2102333d57a7ae548272a195b4d9bf5ec6be835ab7b80c2aed
// @sig-hash: sha256:ba8ab8c9edd5b4e2
// Source: Blizzard_APIDocumentationGenerated/playermentorshipdocumentation.lua
export const C_PlayerMentorship = `
if C_PlayerMentorship == nil then C_PlayerMentorship = {} end
C_PlayerMentorship.GetMentorLevelRequirement = _nil
C_PlayerMentorship.GetMentorRequirements = _tbl
C_PlayerMentorship.GetMentorshipStatus = _nil
C_PlayerMentorship.IsActivePlayerConsideredNewcomer = _bool
C_PlayerMentorship.IsMentorRestricted = _bool
-- Events: MENTORSHIP_STATUS_CHANGED, NEWCOMER_GRADUATION
`;
