// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:b94a95c1f9d4bab4cdad58261e3f696bf2a53b87f5e56e26dd33e46154bab2a5
// @sig-hash: sha256:a8757ae34e450319
// Source: Blizzard_APIDocumentationGenerated/playermentorshipdocumentation.lua
export const C_PlayerMentorship = `
if C_PlayerMentorship == nil then C_PlayerMentorship = {} end
C_PlayerMentorship.GetMentorLevelRequirement = _nil("C_PlayerMentorship.GetMentorLevelRequirement")
C_PlayerMentorship.GetMentorRequirements = _tbl("C_PlayerMentorship.GetMentorRequirements")
C_PlayerMentorship.GetMentorshipStatus = _nil("C_PlayerMentorship.GetMentorshipStatus")
C_PlayerMentorship.IsActivePlayerConsideredNewcomer = _bool("C_PlayerMentorship.IsActivePlayerConsideredNewcomer")
C_PlayerMentorship.IsMentorRestricted = _bool("C_PlayerMentorship.IsMentorRestricted")
-- Events: MENTORSHIP_STATUS_CHANGED, NEWCOMER_GRADUATION
`;
