// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:037d1b495defd8728dcf3a9a87f8ba5d0650b18ff6b7e68638f26894ffe17e22
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/ponydocumentation.lua
export const C_Pony = `
if C_Pony == nil then C_Pony = {} end
`;
