// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a706416f1c2ef788df24012fd32497acb648e9e3757954876c0a52999c011803
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/ponydocumentation.lua
export const C_Pony = `
if C_Pony == nil then C_Pony = {} end
`;
