// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e3608261148ff422c108b19640fd0a8b48a7ede1ccbc52865395f8004c3de24c
// @sig-hash: sha256:c0a4853f8f961670
// Source: Blizzard_APIDocumentationGenerated/professionspecuidocumentation.lua
export const C_ProfSpecs = `
if C_ProfSpecs == nil then C_ProfSpecs = {} end
C_ProfSpecs.CanRefundPath = _bool("C_ProfSpecs.CanRefundPath")
C_ProfSpecs.CanUnlockTab = _bool("C_ProfSpecs.CanUnlockTab")
C_ProfSpecs.GetChildrenForPath = _tbl("C_ProfSpecs.GetChildrenForPath")
C_ProfSpecs.GetConfigIDForSkillLine = _num("C_ProfSpecs.GetConfigIDForSkillLine")
C_ProfSpecs.GetCurrencyInfoForSkillLine = _tbl("C_ProfSpecs.GetCurrencyInfoForSkillLine")
C_ProfSpecs.GetDefaultSpecSkillLine = _nil("C_ProfSpecs.GetDefaultSpecSkillLine")
C_ProfSpecs.GetDescriptionForPath = _str("C_ProfSpecs.GetDescriptionForPath")
C_ProfSpecs.GetDescriptionForPerk = _str("C_ProfSpecs.GetDescriptionForPerk")
C_ProfSpecs.GetEntryIDForPerk = _num("C_ProfSpecs.GetEntryIDForPerk")
C_ProfSpecs.GetNewSpecReminderProfName = _nil("C_ProfSpecs.GetNewSpecReminderProfName")
C_ProfSpecs.GetPerksForPath = _tbl("C_ProfSpecs.GetPerksForPath")
C_ProfSpecs.GetRootPathForTab = _nil("C_ProfSpecs.GetRootPathForTab")
C_ProfSpecs.GetSourceTextForPath = _str("C_ProfSpecs.GetSourceTextForPath")
C_ProfSpecs.GetSpecTabIDsForSkillLine = _tbl("C_ProfSpecs.GetSpecTabIDsForSkillLine")
C_ProfSpecs.GetSpecTabInfo = _tbl("C_ProfSpecs.GetSpecTabInfo")
C_ProfSpecs.GetSpendCurrencyForPath = _nil("C_ProfSpecs.GetSpendCurrencyForPath")
C_ProfSpecs.GetSpendEntryForPath = _num("C_ProfSpecs.GetSpendEntryForPath")
C_ProfSpecs.GetStateForPath = _nil("C_ProfSpecs.GetStateForPath")
C_ProfSpecs.GetStateForPerk = _nil("C_ProfSpecs.GetStateForPerk")
C_ProfSpecs.GetStateForTab = _nil("C_ProfSpecs.GetStateForTab")
C_ProfSpecs.GetTabInfo = _nil("C_ProfSpecs.GetTabInfo")
C_ProfSpecs.GetUnlockEntryForPath = _num("C_ProfSpecs.GetUnlockEntryForPath")
C_ProfSpecs.GetUnlockRankForPerk = _nil("C_ProfSpecs.GetUnlockRankForPerk")
C_ProfSpecs.ShouldShowPointsReminder = _bool("C_ProfSpecs.ShouldShowPointsReminder")
C_ProfSpecs.ShouldShowPointsReminderForSkillLine = _bool("C_ProfSpecs.ShouldShowPointsReminderForSkillLine")
C_ProfSpecs.ShouldShowSpecTab = _bool("C_ProfSpecs.ShouldShowSpecTab")
C_ProfSpecs.SkillLineHasSpecialization = _bool("C_ProfSpecs.SkillLineHasSpecialization")
-- Events: SKILL_LINE_SPECS_RANKS_CHANGED, SKILL_LINE_SPECS_UNLOCKED
`;
