// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:cd6a1456d89e269ca84892bc0287ecdc382ae6c0c81774c8bb69fc91a78c0603
// @sig-hash: sha256:10aea196a68ebd58
// Source: Blizzard_APIDocumentationGenerated/questlineinfodocumentation.lua
export const C_QuestLine = `
if C_QuestLine == nil then C_QuestLine = {} end
C_QuestLine.GetAvailableQuestLines = _tbl("C_QuestLine.GetAvailableQuestLines")
C_QuestLine.GetForceVisibleQuests = _tbl("C_QuestLine.GetForceVisibleQuests")
C_QuestLine.GetQuestLineInfo = _nil("C_QuestLine.GetQuestLineInfo")
C_QuestLine.GetQuestLineQuests = _tbl("C_QuestLine.GetQuestLineQuests")
C_QuestLine.IsComplete = _bool("C_QuestLine.IsComplete")
C_QuestLine.QuestLineIgnoresAccountCompletedFiltering = _bool("C_QuestLine.QuestLineIgnoresAccountCompletedFiltering")
C_QuestLine.RequestQuestLinesForMap = _nil("C_QuestLine.RequestQuestLinesForMap")
`;
