// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ed3e36568deb9e978bb8abe2415d46c1b694b96492e5497c102b63dcbc1df9ea
// @sig-hash: sha256:f0329d5ad9f29918
// Source: Blizzard_APIDocumentationGenerated/questhubinfodocumentation.lua
export const C_QuestHub = `
if C_QuestHub == nil then C_QuestHub = {} end
C_QuestHub.IsQuestCurrentlyRelatedToHub = _bool("C_QuestHub.IsQuestCurrentlyRelatedToHub")
`;
