// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8fa44b1b1ebb9dc46cda75a7cc3b262682ccf4f85869cc09536388d1762c71ca
// @sig-hash: sha256:a5a916be4f74688f
// Source: Blizzard_APIDocumentationGenerated/questofferdocumentation.lua
export const C_QuestOffer = `
if C_QuestOffer == nil then C_QuestOffer = {} end
C_QuestOffer.GetHideRequiredItems = _bool("C_QuestOffer.GetHideRequiredItems")
C_QuestOffer.GetQuestOfferMajorFactionReputationRewards = _tbl("C_QuestOffer.GetQuestOfferMajorFactionReputationRewards")
C_QuestOffer.GetQuestRequiredCurrencyInfo = _nil("C_QuestOffer.GetQuestRequiredCurrencyInfo")
C_QuestOffer.GetQuestRewardCurrencyInfo = _nil("C_QuestOffer.GetQuestRewardCurrencyInfo")
-- Events: QUEST_ACCEPT_CONFIRM, QUEST_FINISHED, QUEST_GREETING, QUEST_ITEM_UPDATE, QUEST_PROGRESS
`;
