// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f6005a5e314d9d49b0493bcfe256f16dd32222329b455cb16630471ace7d1246
// @sig-hash: sha256:238f49c2ff17e9d1
// Source: Blizzard_APIDocumentationGenerated/questsessiondocumentation.lua
export const C_QuestSession = `
if C_QuestSession == nil then C_QuestSession = {} end
C_QuestSession.CanStart = _bool("C_QuestSession.CanStart")
C_QuestSession.CanStop = _bool("C_QuestSession.CanStop")
C_QuestSession.Exists = _bool("C_QuestSession.Exists")
C_QuestSession.GetAvailableSessionCommand = _nil("C_QuestSession.GetAvailableSessionCommand")
C_QuestSession.GetPendingCommand = _nil("C_QuestSession.GetPendingCommand")
C_QuestSession.GetProposedMaxLevelForSession = _num("C_QuestSession.GetProposedMaxLevelForSession")
C_QuestSession.GetSessionBeginDetails = _nil("C_QuestSession.GetSessionBeginDetails")
C_QuestSession.GetSuperTrackedQuest = _nil("C_QuestSession.GetSuperTrackedQuest")
C_QuestSession.HasJoined = _bool("C_QuestSession.HasJoined")
C_QuestSession.HasPendingCommand = _bool("C_QuestSession.HasPendingCommand")
C_QuestSession.RequestSessionStart = _nil("C_QuestSession.RequestSessionStart")
C_QuestSession.RequestSessionStop = _nil("C_QuestSession.RequestSessionStop")
C_QuestSession.SendSessionBeginResponse = _nil("C_QuestSession.SendSessionBeginResponse")
C_QuestSession.SetQuestIsSuperTracked = _nil("C_QuestSession.SetQuestIsSuperTracked")
-- Events: QUEST_SESSION_CREATED, QUEST_SESSION_DESTROYED, QUEST_SESSION_ENABLED_STATE_CHANGED, QUEST_SESSION_JOINED, QUEST_SESSION_LEFT, QUEST_SESSION_MEMBER_CONFIRM, QUEST_SESSION_MEMBER_START_RESPONSE, QUEST_SESSION_NOTIFICATION
`;
