// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4ec2a597fe8e25209843ca59f9b71eddc673ddddf962223b093c69e0fd3a5b62
// @sig-hash: sha256:5de807c606a6218f
// Source: Blizzard_APIDocumentationGenerated/questlineinfodocumentation.lua
export const C_QuestLine = `
if C_QuestLine == nil then C_QuestLine = {} end
C_QuestLine.GetAvailableQuestLines = _tbl
C_QuestLine.GetForceVisibleQuests = _tbl
C_QuestLine.GetQuestLineInfo = _nil
C_QuestLine.GetQuestLineQuests = _tbl
C_QuestLine.IsComplete = _nil
C_QuestLine.QuestLineIgnoresAccountCompletedFiltering = _nil
C_QuestLine.RequestQuestLinesForMap = _nil
`;
