// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:609c6f93a26a0cf92797ca9ad871cec650450953acb32747aefcbe81538988dd
// @sig-hash: sha256:ef350b238cc93a97
// Source: Blizzard_APIDocumentationGenerated/questofferdocumentation.lua
export const C_QuestOffer = `
if C_QuestOffer == nil then C_QuestOffer = {} end
C_QuestOffer.GetHideRequiredItems = _bool
C_QuestOffer.GetQuestOfferMajorFactionReputationRewards = _tbl
C_QuestOffer.GetQuestRequiredCurrencyInfo = _nil
C_QuestOffer.GetQuestRewardCurrencyInfo = _nil
-- Events: QUEST_ACCEPT_CONFIRM, QUEST_FINISHED, QUEST_GREETING, QUEST_ITEM_UPDATE, QUEST_PROGRESS
`;
