// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:117a3fac4c9f5d56702d83184fae90ef558d842b255c8e20c8b741a1ba53697c
// @sig-hash: sha256:c13a5f4b426eb125
// Source: Blizzard_APIDocumentationGenerated/questinfosystemdocumentation.lua
export const C_QuestInfoSystem = `
if C_QuestInfoSystem == nil then C_QuestInfoSystem = {} end
C_QuestInfoSystem.GetQuestClassification = _nil
C_QuestInfoSystem.GetQuestLogRewardFavor = _nil
C_QuestInfoSystem.GetQuestRewardCurrencies = _tbl
C_QuestInfoSystem.GetQuestRewardSpellInfo = _nil
C_QuestInfoSystem.GetQuestRewardSpells = _tbl
C_QuestInfoSystem.GetQuestShouldToastCompletion = _nil
C_QuestInfoSystem.HasQuestRewardCurrencies = _nil
C_QuestInfoSystem.HasQuestRewardSpells = _nil
`;
