// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1a1f46ecb84ace52e5717b86c5186df4f0ecfdb2e2237a47aa6367919c643372
// @sig-hash: sha256:0d4c6880e3c323c9
// Source: Blizzard_APIDocumentationGenerated/raidlocksdocumentation.lua
export const C_RaidLocks = `
if C_RaidLocks == nil then C_RaidLocks = {} end
C_RaidLocks.GetRedirectedDifficultyID = _num
C_RaidLocks.IsEncounterComplete = _bool
C_RaidLocks.IsRaidLockExtendFeatureEnabled = _bool
`;
