// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f4bdb4c884afb2922e11739f2eeb9ff5f8b11581456f5d1c3e45c0eb02f309f6
// @sig-hash: sha256:c787db87b8125d3e
// Source: Blizzard_APIDocumentationGenerated/reputationinfodocumentation.lua
export const C_Reputation = `
if C_Reputation == nil then C_Reputation = {} end
C_Reputation.AreLegacyReputationsShown = _bool
C_Reputation.CollapseAllFactionHeaders = _nil
C_Reputation.CollapseFactionHeader = _nil
C_Reputation.ExpandAllFactionHeaders = _nil
C_Reputation.ExpandFactionHeader = _nil
C_Reputation.GetFactionDataByID = _nil
C_Reputation.GetFactionDataByIndex = _nil
C_Reputation.GetFactionParagonInfo = _num
C_Reputation.GetGuildFactionData = _nil
C_Reputation.GetGuildRepExpirationTime = _nil
C_Reputation.GetNumFactions = _num
C_Reputation.GetReputationSortType = _nil
C_Reputation.GetSelectedFaction = _num
C_Reputation.GetWatchedFactionData = _nil
C_Reputation.IsAccountWideReputation = _bool
C_Reputation.IsFactionActive = _bool
C_Reputation.IsFactionParagon = _bool
C_Reputation.IsFactionParagonForCurrentPlayer = _bool
C_Reputation.IsMajorFaction = _bool
C_Reputation.RequestFactionParagonPreloadRewardData = _nil
C_Reputation.SetFactionActive = _nil
C_Reputation.SetLegacyReputationsShown = _nil
C_Reputation.SetReputationSortType = _nil
C_Reputation.SetSelectedFaction = _nil
C_Reputation.SetWatchedFactionByID = _nil
C_Reputation.SetWatchedFactionByIndex = _nil
C_Reputation.ToggleFactionAtWar = _nil
-- Events: FACTION_STANDING_CHANGED
`;
