// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:61672ad53a68e4920b69d55409eed5689753fed98fbb05624112435635617d52
// @sig-hash: sha256:88b15ea7dc94ab9c
// Source: Blizzard_APIDocumentationGenerated/reportsystemdocumentation.lua
export const C_ReportSystem = `
if C_ReportSystem == nil then C_ReportSystem = {} end
C_ReportSystem.CanReportPlayer = _bool("C_ReportSystem.CanReportPlayer")
C_ReportSystem.CanReportPlayerForLanguage = _bool("C_ReportSystem.CanReportPlayerForLanguage")
C_ReportSystem.GetMajorCategoriesForReportType = _tbl("C_ReportSystem.GetMajorCategoriesForReportType")
C_ReportSystem.GetMajorCategoryString = _str("C_ReportSystem.GetMajorCategoryString")
C_ReportSystem.GetMinorCategoriesForReportTypeAndMajorCategory = _tbl("C_ReportSystem.GetMinorCategoriesForReportTypeAndMajorCategory")
C_ReportSystem.GetMinorCategoryString = _str("C_ReportSystem.GetMinorCategoryString")
C_ReportSystem.ReportServerLag = _nil("C_ReportSystem.ReportServerLag")
C_ReportSystem.ReportStuckInCombat = _nil("C_ReportSystem.ReportStuckInCombat")
C_ReportSystem.RequiresScreenshotForReportType = _bool("C_ReportSystem.RequiresScreenshotForReportType")
C_ReportSystem.SendReport = _nil("C_ReportSystem.SendReport")
C_ReportSystem.SetScreenshotPreviewTexture = _nil("C_ReportSystem.SetScreenshotPreviewTexture")
C_ReportSystem.TakeReportScreenshot = _nil("C_ReportSystem.TakeReportScreenshot")
-- Events: REPORT_PLAYER_RESULT, REPORT_SCREENSHOT_READY
`;
