// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:252e0a40e95a5e787147faf2ffc331e15c9b0639af1460be43e052f6a2af74a5
// @sig-hash: sha256:715c4bbed455240e
// Source: Blizzard_APIDocumentationGenerated/recruitafrienddocumentation.lua
export const C_RecruitAFriend = `
if C_RecruitAFriend == nil then C_RecruitAFriend = {} end
C_RecruitAFriend.CanSummonFriend = _bool
C_RecruitAFriend.ClaimActivityReward = _bool
C_RecruitAFriend.ClaimNextReward = _bool
C_RecruitAFriend.GenerateRecruitmentLink = _bool
C_RecruitAFriend.GetRAFInfo = _tbl
C_RecruitAFriend.GetRAFSystemInfo = _tbl
C_RecruitAFriend.GetRecruitActivityRequirementsText = _tbl
C_RecruitAFriend.GetRecruitInfo = _bool
C_RecruitAFriend.GetSummonFriendCooldown = _num
C_RecruitAFriend.IsEnabled = _bool
C_RecruitAFriend.IsRecruitAFriendLinked = _bool
C_RecruitAFriend.IsRecruitingEnabled = _bool
C_RecruitAFriend.RemoveRAFRecruit = _bool
C_RecruitAFriend.RequestUpdatedRecruitmentInfo = _bool
C_RecruitAFriend.SummonFriend = _nil
-- Events: RAF_INFO_UPDATED, RAF_RECRUITING_ENABLED_STATUS, RAF_REWARD_CLAIM_FAILED, RAF_SYSTEM_ENABLED_STATUS, RAF_SYSTEM_INFO_UPDATED
`;
