// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7b9fb456f560886e58f61312ea4eec742af98334b142ca47cbc5e42d2a33c5af
// @sig-hash: sha256:e8e5f8f9f4789e11
// Source: Blizzard_APIDocumentationGenerated/researchinfodocumentation.lua
export const C_ResearchInfo = `
if C_ResearchInfo == nil then C_ResearchInfo = {} end
C_ResearchInfo.GetDigSitesForMap = _tbl
-- Events: ARCHAEOLOGY_CLOSED, ARCHAEOLOGY_FIND_COMPLETE, ARCHAEOLOGY_SURVEY_CAST, ARCHAEOLOGY_TOGGLE, ARTIFACT_DIGSITE_COMPLETE, RESEARCH_ARTIFACT_COMPLETE, RESEARCH_ARTIFACT_DIG_SITE_UPDATED, RESEARCH_ARTIFACT_UPDATE
`;
