// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:32873ce7e7e45d4b8cf1dbbbf379dbbe0dfdd6eaaa57a1bcdc4e9e872c9b5e1a
// @sig-hash: sha256:11235e382b9aadfb
// Source: Blizzard_APIDocumentationGenerated/reputationinfodocumentation.lua
export const C_Reputation = `
if C_Reputation == nil then C_Reputation = {} end
C_Reputation.AreLegacyReputationsShown = _bool("C_Reputation.AreLegacyReputationsShown")
C_Reputation.CollapseAllFactionHeaders = _nil("C_Reputation.CollapseAllFactionHeaders")
C_Reputation.CollapseFactionHeader = _nil("C_Reputation.CollapseFactionHeader")
C_Reputation.ExpandAllFactionHeaders = _nil("C_Reputation.ExpandAllFactionHeaders")
C_Reputation.ExpandFactionHeader = _nil("C_Reputation.ExpandFactionHeader")
C_Reputation.GetFactionDataByID = _nil("C_Reputation.GetFactionDataByID")
C_Reputation.GetFactionDataByIndex = _nil("C_Reputation.GetFactionDataByIndex")
C_Reputation.GetFactionParagonInfo = _num("C_Reputation.GetFactionParagonInfo")
C_Reputation.GetGuildFactionData = _nil("C_Reputation.GetGuildFactionData")
C_Reputation.GetGuildRepExpirationTime = _nil("C_Reputation.GetGuildRepExpirationTime")
C_Reputation.GetNumFactions = _num("C_Reputation.GetNumFactions")
C_Reputation.GetReputationSortType = _nil("C_Reputation.GetReputationSortType")
C_Reputation.GetSelectedFaction = _nil("C_Reputation.GetSelectedFaction")
C_Reputation.GetWatchedFactionData = _nil("C_Reputation.GetWatchedFactionData")
C_Reputation.IsAccountWideReputation = _bool("C_Reputation.IsAccountWideReputation")
C_Reputation.IsFactionActive = _bool("C_Reputation.IsFactionActive")
C_Reputation.IsFactionParagon = _bool("C_Reputation.IsFactionParagon")
C_Reputation.IsFactionParagonForCurrentPlayer = _bool("C_Reputation.IsFactionParagonForCurrentPlayer")
C_Reputation.IsMajorFaction = _bool("C_Reputation.IsMajorFaction")
C_Reputation.RequestFactionParagonPreloadRewardData = _nil("C_Reputation.RequestFactionParagonPreloadRewardData")
C_Reputation.SetFactionActive = _nil("C_Reputation.SetFactionActive")
C_Reputation.SetLegacyReputationsShown = _nil("C_Reputation.SetLegacyReputationsShown")
C_Reputation.SetReputationSortType = _nil("C_Reputation.SetReputationSortType")
C_Reputation.SetSelectedFaction = _nil("C_Reputation.SetSelectedFaction")
C_Reputation.SetWatchedFactionByID = _nil("C_Reputation.SetWatchedFactionByID")
C_Reputation.SetWatchedFactionByIndex = _nil("C_Reputation.SetWatchedFactionByIndex")
C_Reputation.ToggleFactionAtWar = _nil("C_Reputation.ToggleFactionAtWar")
-- Events: FACTION_STANDING_CHANGED
`;
