// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:54270d6e42bff09e5184186ebd9d0b4c0da221679805129ffb3eff99aaed3eeb
// @sig-hash: sha256:081f3fe161170386
// Source: Blizzard_APIDocumentationGenerated/reportsystemdocumentation.lua
export const C_ReportSystem = `
if C_ReportSystem == nil then C_ReportSystem = {} end
C_ReportSystem.CanReportPlayer = _nil
C_ReportSystem.CanReportPlayerForLanguage = _nil
C_ReportSystem.GetMajorCategoriesForReportType = _tbl
C_ReportSystem.GetMajorCategoryString = _nil
C_ReportSystem.GetMinorCategoriesForReportTypeAndMajorCategory = _tbl
C_ReportSystem.GetMinorCategoryString = _nil
C_ReportSystem.ReportServerLag = _nil
C_ReportSystem.ReportStuckInCombat = _nil
C_ReportSystem.RequiresScreenshotForReportType = _nil
C_ReportSystem.SendReport = _nil
C_ReportSystem.SetScreenshotPreviewTexture = _nil
C_ReportSystem.TakeReportScreenshot = _nil
-- Events: REPORT_PLAYER_RESULT, REPORT_SCREENSHOT_READY
`;
