// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f62b3aca28d3c6b2a2fb31864547afbbc8ca064eb1b8586c804b44b15dc49b6b
// @sig-hash: sha256:cce022dca7cd0dac
// Source: Blizzard_APIDocumentationGenerated/recentalliesdocumentation.lua
export const C_RecentAllies = `
if C_RecentAllies == nil then C_RecentAllies = {} end
C_RecentAllies.CanSetRecentAllyNote = _bool("C_RecentAllies.CanSetRecentAllyNote")
C_RecentAllies.GetRecentAllies = _tbl("C_RecentAllies.GetRecentAllies")
C_RecentAllies.GetRecentAllyByFullName = _nil("C_RecentAllies.GetRecentAllyByFullName")
C_RecentAllies.GetRecentAllyByGUID = _nil("C_RecentAllies.GetRecentAllyByGUID")
C_RecentAllies.IsRecentAllyByFullName = _bool("C_RecentAllies.IsRecentAllyByFullName")
C_RecentAllies.IsRecentAllyByGUID = _bool("C_RecentAllies.IsRecentAllyByGUID")
C_RecentAllies.IsRecentAllyDataReady = _bool("C_RecentAllies.IsRecentAllyDataReady")
C_RecentAllies.IsRecentAllyPinned = _bool("C_RecentAllies.IsRecentAllyPinned")
C_RecentAllies.IsSystemEnabled = _bool("C_RecentAllies.IsSystemEnabled")
C_RecentAllies.IsSystemSupported = _bool("C_RecentAllies.IsSystemSupported")
C_RecentAllies.SetRecentAllyNote = _nil("C_RecentAllies.SetRecentAllyNote")
C_RecentAllies.SetRecentAllyPinned = _nil("C_RecentAllies.SetRecentAllyPinned")
C_RecentAllies.TryRequestRecentAlliesData = _nil("C_RecentAllies.TryRequestRecentAlliesData")
-- Events: LET_RECENT_ALLIES_SEE_LOCATION_SETTING_UPDATED, RECENT_ALLIES_CACHE_UPDATE, RECENT_ALLIES_DATA_READY, RECENT_ALLIES_SYSTEM_STATUS_UPDATED, RECENT_ALLY_DATA_UPDATED
`;
