// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:91f809d313720ce8fe244183e9848d2e4c4748b03a0e1f819b6e94370aa4cf1b
// @sig-hash: sha256:d836a3adb1bce012
// Source: Blizzard_APIDocumentationGenerated/restrictedactionsdocumentation.lua
export const C_RestrictedActions = `
if C_RestrictedActions == nil then C_RestrictedActions = {} end
C_RestrictedActions.CheckAllowProtectedFunctions = _bool("C_RestrictedActions.CheckAllowProtectedFunctions")
C_RestrictedActions.GetAddOnRestrictionState = _nil("C_RestrictedActions.GetAddOnRestrictionState")
C_RestrictedActions.InCombatLockdown = _bool("C_RestrictedActions.InCombatLockdown")
C_RestrictedActions.IsAddOnRestrictionActive = _bool("C_RestrictedActions.IsAddOnRestrictionActive")
-- Events: ADDON_ACTION_BLOCKED, ADDON_ACTION_FORBIDDEN, ADDON_RESTRICTION_STATE_CHANGED, MACRO_ACTION_BLOCKED, MACRO_ACTION_FORBIDDEN
`;
