// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:56a5373f41c23dda8011854b295b8ebe2d19de6d0c2c13fe347ba13a29069db7
// @sig-hash: sha256:9502293a27c8675d
// Source: Blizzard_APIDocumentationGenerated/remixartifactuidocumentation.lua
export const C_RemixArtifactUI = `
if C_RemixArtifactUI == nil then C_RemixArtifactUI = {} end
C_RemixArtifactUI.ClearRemixArtifactItem = _nil
C_RemixArtifactUI.GetAppearanceInfoByID = _num
C_RemixArtifactUI.GetArtifactArtInfo = _tbl
C_RemixArtifactUI.GetArtifactItemInfo = _num
C_RemixArtifactUI.GetCurrArtifactItemID = _nil
C_RemixArtifactUI.GetCurrItemSpecIndex = _nil
C_RemixArtifactUI.GetCurrTraitTreeID = _nil
C_RemixArtifactUI.ItemInSlotIsRemixArtifact = _bool
-- Events: REMIX_ARTIFACT_ITEM_SPECS_LOADED, REMIX_ARTIFACT_UPDATE
`;
