// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:89cdfe2925c81f9f308510976aa85e967303557c1be1770a422d7adccac00b38
// @sig-hash: sha256:042e300d3dde4fdb
// Source: Blizzard_APIDocumentationGenerated/researchinfodocumentation.lua
export const C_ResearchInfo = `
if C_ResearchInfo == nil then C_ResearchInfo = {} end
C_ResearchInfo.GetDigSitesForMap = _tbl("C_ResearchInfo.GetDigSitesForMap")
-- Events: ARCHAEOLOGY_CLOSED, ARCHAEOLOGY_FIND_COMPLETE, ARCHAEOLOGY_SURVEY_CAST, ARCHAEOLOGY_TOGGLE, ARTIFACT_DIGSITE_COMPLETE, RESEARCH_ARTIFACT_COMPLETE, RESEARCH_ARTIFACT_DIG_SITE_UPDATED, RESEARCH_ARTIFACT_UPDATE
`;
