// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5434ac2c1e201e7b7d07ca035c8fceeeb3c090cda353b2cf71703d2a3772f947
// @sig-hash: sha256:fc6e7cd84358f7e0
// Source: Blizzard_APIDocumentationGenerated/recruitafrienddocumentation.lua
export const C_RecruitAFriend = `
if C_RecruitAFriend == nil then C_RecruitAFriend = {} end
C_RecruitAFriend.CanSummonFriend = _bool("C_RecruitAFriend.CanSummonFriend")
C_RecruitAFriend.ClaimActivityReward = _bool("C_RecruitAFriend.ClaimActivityReward")
C_RecruitAFriend.ClaimNextReward = _bool("C_RecruitAFriend.ClaimNextReward")
C_RecruitAFriend.GenerateRecruitmentLink = _bool("C_RecruitAFriend.GenerateRecruitmentLink")
C_RecruitAFriend.GetRAFInfo = _tbl("C_RecruitAFriend.GetRAFInfo")
C_RecruitAFriend.GetRAFSystemInfo = _tbl("C_RecruitAFriend.GetRAFSystemInfo")
C_RecruitAFriend.GetRecruitActivityRequirementsText = _tbl("C_RecruitAFriend.GetRecruitActivityRequirementsText")
C_RecruitAFriend.GetRecruitInfo = _bool("C_RecruitAFriend.GetRecruitInfo")
C_RecruitAFriend.GetSummonFriendCooldown = _num("C_RecruitAFriend.GetSummonFriendCooldown")
C_RecruitAFriend.IsEnabled = _bool("C_RecruitAFriend.IsEnabled")
C_RecruitAFriend.IsRecruitAFriendLinked = _bool("C_RecruitAFriend.IsRecruitAFriendLinked")
C_RecruitAFriend.IsRecruitingEnabled = _bool("C_RecruitAFriend.IsRecruitingEnabled")
C_RecruitAFriend.RemoveRAFRecruit = _bool("C_RecruitAFriend.RemoveRAFRecruit")
C_RecruitAFriend.RequestUpdatedRecruitmentInfo = _bool("C_RecruitAFriend.RequestUpdatedRecruitmentInfo")
C_RecruitAFriend.SummonFriend = _nil("C_RecruitAFriend.SummonFriend")
-- Events: RAF_INFO_UPDATED, RAF_RECRUITING_ENABLED_STATUS, RAF_REWARD_CLAIM_FAILED, RAF_SYSTEM_ENABLED_STATUS, RAF_SYSTEM_INFO_UPDATED
`;
