// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9374230edf479f64023f9a1903d75c469fc3b92009ff36051e23d398ea9df576
// @sig-hash: sha256:02f925ec540366b5
// Source: Blizzard_APIDocumentationGenerated/remixartifactuidocumentation.lua
export const C_RemixArtifactUI = `
if C_RemixArtifactUI == nil then C_RemixArtifactUI = {} end
C_RemixArtifactUI.ClearRemixArtifactItem = _nil("C_RemixArtifactUI.ClearRemixArtifactItem")
C_RemixArtifactUI.GetAppearanceInfoByID = _num("C_RemixArtifactUI.GetAppearanceInfoByID")
C_RemixArtifactUI.GetArtifactArtInfo = _tbl("C_RemixArtifactUI.GetArtifactArtInfo")
C_RemixArtifactUI.GetArtifactItemInfo = _num("C_RemixArtifactUI.GetArtifactItemInfo")
C_RemixArtifactUI.GetCurrArtifactItemID = _nil("C_RemixArtifactUI.GetCurrArtifactItemID")
C_RemixArtifactUI.GetCurrItemSpecIndex = _nil("C_RemixArtifactUI.GetCurrItemSpecIndex")
C_RemixArtifactUI.GetCurrTraitTreeID = _nil("C_RemixArtifactUI.GetCurrTraitTreeID")
C_RemixArtifactUI.ItemInSlotIsRemixArtifact = _bool("C_RemixArtifactUI.ItemInSlotIsRemixArtifact")
-- Events: REMIX_ARTIFACT_ITEM_SPECS_LOADED, REMIX_ARTIFACT_UPDATE
`;
