// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7f598e3938cffea8561b9811e16eeee85660f3930a94b7d3d96a928bac5550d4
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/scriptwarningsdocumentation.lua
export const C_ScriptWarnings = `
if C_ScriptWarnings == nil then C_ScriptWarnings = {} end
-- Events: LUA_WARNING
`;
