// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1156b1f0125eb151352bd618cf84f2d37ef61f78d6bff3245a4b450b7c9c0c6a
// @sig-hash: sha256:a0ebc3467dc39267
// Source: Blizzard_APIDocumentationGenerated/scriptedanimationsdocumentation.lua
export const C_ScriptedAnimations = `
if C_ScriptedAnimations == nil then C_ScriptedAnimations = {} end
C_ScriptedAnimations.GetAllScriptedAnimationEffects = _tbl
-- Events: SCRIPTED_ANIMATIONS_UPDATE
`;
