// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:7ead8da61c7b8291d44352e6dc1085cbd4851304dac7fef6166e215174dda64d
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/scriptwarningsdocumentation.lua
export const C_ScriptWarnings = `
if C_ScriptWarnings == nil then C_ScriptWarnings = {} end
-- Events: LUA_WARNING
`;
