// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:01ec6fdea1aef17cc5603edae6f61f8922d5b2546fb9f3d551cf4d3e7c6a2bc8
// @sig-hash: sha256:6ab28da115ad6571
// Source: Blizzard_APIDocumentationGenerated/secretpredicateapidocumentation.lua
export const C_Secrets = `
if C_Secrets == nil then C_Secrets = {} end
C_Secrets.CanCompareUnitTokens = _bool
C_Secrets.GetPowerTypeSecrecy = _nil
C_Secrets.GetSpellAuraSecrecy = _nil
C_Secrets.GetSpellCastSecrecy = _nil
C_Secrets.GetSpellCooldownSecrecy = _nil
C_Secrets.HasSecretRestrictions = _bool
C_Secrets.ShouldActionCooldownBeSecret = _bool
C_Secrets.ShouldAurasBeSecret = _bool
C_Secrets.ShouldCooldownsBeSecret = _bool
C_Secrets.ShouldSpellAuraBeSecret = _bool
C_Secrets.ShouldSpellBookItemCooldownBeSecret = _bool
C_Secrets.ShouldSpellCooldownBeSecret = _bool
C_Secrets.ShouldTotemSlotBeSecret = _bool
C_Secrets.ShouldTotemSpellBeSecret = _bool
C_Secrets.ShouldUnitAuraIndexBeSecret = _bool
C_Secrets.ShouldUnitAuraInstanceBeSecret = _bool
C_Secrets.ShouldUnitAuraSlotBeSecret = _bool
C_Secrets.ShouldUnitComparisonBeSecret = _bool
C_Secrets.ShouldUnitHealthMaxBeSecret = _bool
C_Secrets.ShouldUnitIdentityBeSecret = _bool
C_Secrets.ShouldUnitPowerBeSecret = _bool
C_Secrets.ShouldUnitPowerMaxBeSecret = _bool
C_Secrets.ShouldUnitSpellCastBeSecret = _bool
C_Secrets.ShouldUnitSpellCastingBeSecret = _bool
C_Secrets.ShouldUnitStatsBeSecret = _bool
C_Secrets.ShouldUnitThreatStateBeSecret = _bool
C_Secrets.ShouldUnitThreatValuesBeSecret = _bool
`;
