// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:cb7a835e7d3b957b367ea38fb29915ecbab480769a70747c3032df3aeb4acddf
// @sig-hash: sha256:96e9e4770dfd4463
// Source: Blizzard_APIDocumentationGenerated/securetransferdocumentation.lua
export const C_SecureTransfer = `
if C_SecureTransfer == nil then C_SecureTransfer = {} end
C_SecureTransfer.AcceptTrade = _nil("C_SecureTransfer.AcceptTrade")
C_SecureTransfer.Cancel = _nil("C_SecureTransfer.Cancel")
C_SecureTransfer.CompleteHousingPurchase = _nil("C_SecureTransfer.CompleteHousingPurchase")
C_SecureTransfer.CompleteHousingVCPurchase = _nil("C_SecureTransfer.CompleteHousingVCPurchase")
C_SecureTransfer.GetHousingPurchaseCost = _num("C_SecureTransfer.GetHousingPurchaseCost")
C_SecureTransfer.GetHousingPurchaseQuantity = _num("C_SecureTransfer.GetHousingPurchaseQuantity")
C_SecureTransfer.GetHousingVCPurchaseProductID = _num("C_SecureTransfer.GetHousingVCPurchaseProductID")
C_SecureTransfer.GetMailInfo = _tbl("C_SecureTransfer.GetMailInfo")
C_SecureTransfer.GetTradePartner = _nil("C_SecureTransfer.GetTradePartner")
C_SecureTransfer.SendMail = _nil("C_SecureTransfer.SendMail")
C_SecureTransfer.ShouldShowTradeOfferWarning = _bool("C_SecureTransfer.ShouldShowTradeOfferWarning")
-- Events: SECURE_TRANSFER_CANCEL, SECURE_TRANSFER_CONFIRM_HOUSING_PURCHASE, SECURE_TRANSFER_CONFIRM_SEND_MAIL, SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT, SECURE_TRANSFER_HOUSING_CURRENCY_PURCHASE_CONFIRMATION
`;
