// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:01ec6fdea1aef17cc5603edae6f61f8922d5b2546fb9f3d551cf4d3e7c6a2bc8
// @sig-hash: sha256:6ab28da115ad6571
// Source: Blizzard_APIDocumentationGenerated/secretpredicateapidocumentation.lua
export const C_Secrets = `
if C_Secrets == nil then C_Secrets = {} end
C_Secrets.CanCompareUnitTokens = _nil
C_Secrets.GetPowerTypeSecrecy = _nil
C_Secrets.GetSpellAuraSecrecy = _nil
C_Secrets.GetSpellCastSecrecy = _nil
C_Secrets.GetSpellCooldownSecrecy = _nil
C_Secrets.HasSecretRestrictions = _nil
C_Secrets.ShouldActionCooldownBeSecret = _nil
C_Secrets.ShouldAurasBeSecret = _nil
C_Secrets.ShouldCooldownsBeSecret = _nil
C_Secrets.ShouldSpellAuraBeSecret = _nil
C_Secrets.ShouldSpellBookItemCooldownBeSecret = _nil
C_Secrets.ShouldSpellCooldownBeSecret = _nil
C_Secrets.ShouldTotemSlotBeSecret = _nil
C_Secrets.ShouldTotemSpellBeSecret = _nil
C_Secrets.ShouldUnitAuraIndexBeSecret = _nil
C_Secrets.ShouldUnitAuraInstanceBeSecret = _nil
C_Secrets.ShouldUnitAuraSlotBeSecret = _nil
C_Secrets.ShouldUnitComparisonBeSecret = _nil
C_Secrets.ShouldUnitHealthMaxBeSecret = _nil
C_Secrets.ShouldUnitIdentityBeSecret = _nil
C_Secrets.ShouldUnitPowerBeSecret = _nil
C_Secrets.ShouldUnitPowerMaxBeSecret = _nil
C_Secrets.ShouldUnitSpellCastBeSecret = _nil
C_Secrets.ShouldUnitSpellCastingBeSecret = _nil
C_Secrets.ShouldUnitStatsBeSecret = _nil
C_Secrets.ShouldUnitThreatStateBeSecret = _nil
C_Secrets.ShouldUnitThreatValuesBeSecret = _nil
`;
