// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2eda73c0a5ad051c5a5a96c6078a3ba559de2ce2decff23b12f62d0c3f3825d6
// @sig-hash: sha256:5b1e6b09e0338791
// Source: Blizzard_APIDocumentationGenerated/settingsutildocumentation.lua
export const C_SettingsUtil = `
if C_SettingsUtil == nil then C_SettingsUtil = {} end
C_SettingsUtil.NotifySettingsLoaded = _nil("C_SettingsUtil.NotifySettingsLoaded")
C_SettingsUtil.OpenSettingsPanel = _nil("C_SettingsUtil.OpenSettingsPanel")
-- Events: SETTINGS_LOADED, SETTINGS_PANEL_OPEN
`;
