// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8d44c8633cb0eb0010ba0154003fe102815426f100df138a75d01ec6ec20992a
// @sig-hash: sha256:247addb928ce9364
// Source: Blizzard_APIDocumentationGenerated/settingsutildocumentation.lua
export const C_SettingsUtil = `
if C_SettingsUtil == nil then C_SettingsUtil = {} end
C_SettingsUtil.NotifySettingsLoaded = _nil
C_SettingsUtil.OpenSettingsPanel = _nil
-- Events: SETTINGS_LOADED, SETTINGS_PANEL_OPEN
`;
