// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:78e9fb303d662201eeb0dcad54dc2aa62815ef2c81bb1889df0dabd27b3f8c93
// @sig-hash: sha256:a92f98ca46a25717
// Source: Blizzard_APIDocumentationGenerated/securetransferdocumentation.lua
export const C_SecureTransfer = `
if C_SecureTransfer == nil then C_SecureTransfer = {} end
C_SecureTransfer.AcceptTrade = _nil
C_SecureTransfer.Cancel = _nil
C_SecureTransfer.CompleteHousingPurchase = _nil
C_SecureTransfer.CompleteHousingVCPurchase = _nil
C_SecureTransfer.GetHousingPurchaseCost = _num
C_SecureTransfer.GetHousingPurchaseQuantity = _num
C_SecureTransfer.GetHousingVCPurchaseProductID = _num
C_SecureTransfer.GetMailInfo = _tbl
C_SecureTransfer.GetTradePartner = _nil
C_SecureTransfer.SendMail = _nil
C_SecureTransfer.ShouldShowTradeOfferWarning = _bool
-- Events: SECURE_TRANSFER_CANCEL, SECURE_TRANSFER_CONFIRM_HOUSING_PURCHASE, SECURE_TRANSFER_CONFIRM_SEND_MAIL, SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT, SECURE_TRANSFER_HOUSING_CURRENCY_PURCHASE_CONFIRMATION
`;
