// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:90a6e6c41f5b45c0b7f777ad849786fc6824c5375b01e6b1b211bf45c4f1b839
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/skillinfodocumentation.lua
export const C_SkillInfo = `
if C_SkillInfo == nil then C_SkillInfo = {} end
-- Events: SKILL_LINES_CHANGED
`;
