// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a09ca813dcfd05e539995cab3e5a1ed1eb12bbd33bc68daea6ee94274254578b
// @sig-hash: sha256:ab84ab7fd4a45f7e
// Source: Blizzard_APIDocumentationGenerated/sounddocumentation.lua
export const C_Sound = `
if C_Sound == nil then C_Sound = {} end
C_Sound.GetSoundScaledVolume = _num("C_Sound.GetSoundScaledVolume")
C_Sound.IsPlaying = _bool("C_Sound.IsPlaying")
C_Sound.PlayItemSound = _nil("C_Sound.PlayItemSound")
C_Sound.PlaySound = _bool("C_Sound.PlaySound")
C_Sound.PlayVocalErrorSound = _nil("C_Sound.PlayVocalErrorSound")
-- Events: SOUND_DEVICE_UPDATE, SOUNDKIT_FINISHED
`;
