// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d1d7539fb3149ac204771a498e7ce6b9ddccfdf8cbf1c0d19165571007e5832d
// @sig-hash: sha256:1e7e3d4fe78a2008
// Source: Blizzard_APIDocumentationGenerated/soulbindsdocumentation.lua
export const C_Soulbinds = `
if C_Soulbinds == nil then C_Soulbinds = {} end
C_Soulbinds.ActivateSoulbind = _nil
C_Soulbinds.CanActivateSoulbind = _nil
C_Soulbinds.CanModifySoulbind = _nil
C_Soulbinds.CanResetConduitsInSoulbind = _nil
C_Soulbinds.CanSwitchActiveSoulbindTreeBranch = _nil
C_Soulbinds.CloseUI = _nil
C_Soulbinds.CommitPendingConduitsInSoulbind = _nil
C_Soulbinds.FindNodeIDActuallyInstalled = _nil
C_Soulbinds.FindNodeIDAppearingInstalled = _nil
C_Soulbinds.FindNodeIDPendingInstall = _nil
C_Soulbinds.FindNodeIDPendingUninstall = _nil
C_Soulbinds.GetActiveSoulbindID = _nil
C_Soulbinds.GetConduitCollection = _tbl
C_Soulbinds.GetConduitCollectionCount = _nil
C_Soulbinds.GetConduitCollectionData = _nil
C_Soulbinds.GetConduitCollectionDataAtCursor = _nil
C_Soulbinds.GetConduitCollectionDataByVirtualID = _nil
C_Soulbinds.GetConduitDisplayed = _nil
C_Soulbinds.GetConduitHyperlink = _nil
C_Soulbinds.GetConduitIDPendingInstall = _nil
C_Soulbinds.GetConduitQuality = _nil
C_Soulbinds.GetConduitRank = _nil
C_Soulbinds.GetConduitSpellID = _nil
C_Soulbinds.GetInstalledConduitID = _nil
C_Soulbinds.GetNode = _tbl
C_Soulbinds.GetSoulbindData = _tbl
C_Soulbinds.GetSpecsAssignedToSoulbind = _tbl
C_Soulbinds.GetTree = _tbl
C_Soulbinds.HasAnyInstalledConduitInSoulbind = _nil
C_Soulbinds.HasAnyPendingConduits = _nil
C_Soulbinds.HasPendingConduitsInSoulbind = _nil
C_Soulbinds.IsConduitInstalled = _nil
C_Soulbinds.IsConduitInstalledInSoulbind = _nil
C_Soulbinds.IsItemConduitByItemInfo = _nil
C_Soulbinds.IsNodePendingModify = _nil
C_Soulbinds.IsUnselectedConduitPendingInSoulbind = _nil
C_Soulbinds.ModifyNode = _nil
C_Soulbinds.SelectNode = _nil
C_Soulbinds.UnmodifyNode = _nil
-- Events: SOULBIND_ACTIVATED, SOULBIND_CONDUIT_COLLECTION_CLEARED, SOULBIND_CONDUIT_COLLECTION_REMOVED, SOULBIND_CONDUIT_COLLECTION_UPDATED, SOULBIND_CONDUIT_INSTALLED, SOULBIND_CONDUIT_UNINSTALLED, SOULBIND_FORGE_INTERACTION_ENDED, SOULBIND_FORGE_INTERACTION_STARTED, SOULBIND_NODE_LEARNED, SOULBIND_NODE_UNLEARNED, SOULBIND_NODE_UPDATED, SOULBIND_PATH_CHANGED, SOULBIND_PENDING_CONDUIT_CHANGED
`;
