// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:471b4d6ec4cbb88172dd3f7fa108293411b2423647f1054d2fe2d161a26b1888
// @sig-hash: sha256:a419870fa019faaf
// Source: Blizzard_APIDocumentationGenerated/socialqueuedocumentation.lua
export const C_SocialQueue = `
if C_SocialQueue == nil then C_SocialQueue = {} end
C_SocialQueue.GetAllGroups = _tbl("C_SocialQueue.GetAllGroups")
C_SocialQueue.GetConfig = _tbl("C_SocialQueue.GetConfig")
C_SocialQueue.GetGroupForPlayer = _nil("C_SocialQueue.GetGroupForPlayer")
C_SocialQueue.GetGroupInfo = _bool("C_SocialQueue.GetGroupInfo")
C_SocialQueue.GetGroupMembers = _tbl("C_SocialQueue.GetGroupMembers")
C_SocialQueue.GetGroupQueues = _tbl("C_SocialQueue.GetGroupQueues")
C_SocialQueue.RequestToJoin = _bool("C_SocialQueue.RequestToJoin")
C_SocialQueue.SignalToastDisplayed = _nil("C_SocialQueue.SignalToastDisplayed")
-- Events: SOCIAL_QUEUE_CONFIG_UPDATED, SOCIAL_QUEUE_UPDATE
`;
