// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:e77001e573c3c37ad225c38a00e72caa54cfe11c5f1bf7b865dd3c0496658911
// @sig-hash: sha256:f2657d755c7feb1b
// Source: Blizzard_APIDocumentationGenerated/socialqueuedocumentation.lua
export const C_SocialQueue = `
if C_SocialQueue == nil then C_SocialQueue = {} end
C_SocialQueue.GetAllGroups = _tbl
C_SocialQueue.GetConfig = _tbl
C_SocialQueue.GetGroupForPlayer = _nil
C_SocialQueue.GetGroupInfo = _nil
C_SocialQueue.GetGroupMembers = _tbl
C_SocialQueue.GetGroupQueues = _tbl
C_SocialQueue.RequestToJoin = _nil
C_SocialQueue.SignalToastDisplayed = _nil
-- Events: SOCIAL_QUEUE_CONFIG_UPDATED, SOCIAL_QUEUE_UPDATE
`;
