// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a2b641bef8b8d48030df5229aa0582d8c02d25047bd0ffd009013b7e4ae7527f
// @sig-hash: sha256:16fca382c2671355
// Source: Blizzard_APIDocumentationGenerated/socialrestrictionsdocumentation.lua
export const C_SocialRestrictions = `
if C_SocialRestrictions == nil then C_SocialRestrictions = {} end
C_SocialRestrictions.AcknowledgeRegionalChatDisabled = _nil
C_SocialRestrictions.CanReceiveChat = _nil
C_SocialRestrictions.CanSendChat = _nil
C_SocialRestrictions.IsChatDisabled = _nil
C_SocialRestrictions.IsMuted = _nil
C_SocialRestrictions.IsSilenced = _nil
C_SocialRestrictions.IsSquelched = _nil
C_SocialRestrictions.SetChatDisabled = _nil
-- Events: ALERT_REGIONAL_CHAT_DISABLED, CHAT_DISABLED_CHANGE_FAILED, CHAT_DISABLED_CHANGED
`;
