// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:000abc3d2bc7a3f0d98128acb144043bea4a6dfadfbb8fdb4dfb9db8588257b1
// @sig-hash: sha256:55810b879821c0a4
// Source: Blizzard_APIDocumentationGenerated/socialrestrictionsdocumentation.lua
export const C_SocialRestrictions = `
if C_SocialRestrictions == nil then C_SocialRestrictions = {} end
C_SocialRestrictions.AcknowledgeRegionalChatDisabled = _nil("C_SocialRestrictions.AcknowledgeRegionalChatDisabled")
C_SocialRestrictions.CanReceiveChat = _bool("C_SocialRestrictions.CanReceiveChat")
C_SocialRestrictions.CanSendChat = _bool("C_SocialRestrictions.CanSendChat")
C_SocialRestrictions.IsChatDisabled = _bool("C_SocialRestrictions.IsChatDisabled")
C_SocialRestrictions.IsMuted = _bool("C_SocialRestrictions.IsMuted")
C_SocialRestrictions.IsSilenced = _bool("C_SocialRestrictions.IsSilenced")
C_SocialRestrictions.IsSquelched = _bool("C_SocialRestrictions.IsSquelched")
C_SocialRestrictions.SetChatDisabled = _nil("C_SocialRestrictions.SetChatDisabled")
-- Events: ALERT_REGIONAL_CHAT_DISABLED, CHAT_DISABLED_CHANGE_FAILED, CHAT_DISABLED_CHANGED
`;
