// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:f25d6d117002924b112dba6d6281771daa7c98fd3ca28a1474aa74ea6701b94e
// @sig-hash: sha256:eea4bbc6700c95bc
// Source: Blizzard_APIDocumentationGenerated/spellactivationoverlaydocumentation.lua
export const C_SpellActivationOverlay = `
if C_SpellActivationOverlay == nil then C_SpellActivationOverlay = {} end
C_SpellActivationOverlay.IsSpellOverlayed = _nil
-- Events: SPELL_ACTIVATION_OVERLAY_GLOW_HIDE, SPELL_ACTIVATION_OVERLAY_GLOW_SHOW, SPELL_ACTIVATION_OVERLAY_HIDE, SPELL_ACTIVATION_OVERLAY_SHOW
`;
