// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4b87e95a1628d94552b79bee06ae567fb9f0eace0f53a62a71f130ff0a3ae72f
// @sig-hash: sha256:404da0b0154ce9f1
// Source: Blizzard_APIDocumentationGenerated/splashscreendocumentation.lua
export const C_SplashScreen = `
if C_SplashScreen == nil then C_SplashScreen = {} end
C_SplashScreen.AcknowledgeSplash = _nil("C_SplashScreen.AcknowledgeSplash")
C_SplashScreen.CanViewSplashScreen = _bool("C_SplashScreen.CanViewSplashScreen")
C_SplashScreen.RequestLatestSplashScreen = _nil("C_SplashScreen.RequestLatestSplashScreen")
C_SplashScreen.SendSplashScreenActionLaunchedTelem = _nil("C_SplashScreen.SendSplashScreenActionLaunchedTelem")
C_SplashScreen.SendSplashScreenCloseTelem = _nil("C_SplashScreen.SendSplashScreenCloseTelem")
-- Events: OPEN_SPLASH_SCREEN
`;
