// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c892b0647fc0fa612643024f74d660e7697137fd88304fd5216ba5f058fee033
// @sig-hash: sha256:90e0df9611a709f8
// Source: Blizzard_APIDocumentationGenerated/spellbookdocumentation.lua
export const C_SpellBook = `
if C_SpellBook == nil then C_SpellBook = {} end
C_SpellBook.CastSpellBookItem = _nil
C_SpellBook.ContainsAnyDisenchantSpell = _bool
C_SpellBook.FindBaseSpellByID = _nil
C_SpellBook.FindFlyoutSlotBySpellID = _num
C_SpellBook.FindSpellBookSlotForSpell = _num
C_SpellBook.FindSpellOverrideByID = _nil
C_SpellBook.GetCurrentLevelSpells = _tbl
C_SpellBook.GetNumSpellBookSkillLines = _num
C_SpellBook.GetSkillLineIndexByID = _nil
C_SpellBook.GetSpellBookItemAutoCast = _bool
C_SpellBook.GetSpellBookItemCastCount = _num
C_SpellBook.GetSpellBookItemChargeDuration = _nil
C_SpellBook.GetSpellBookItemCharges = _tbl
C_SpellBook.GetSpellBookItemCooldown = _tbl
C_SpellBook.GetSpellBookItemCooldownDuration = _nil
C_SpellBook.GetSpellBookItemDescription = _str
C_SpellBook.GetSpellBookItemInfo = _tbl
C_SpellBook.GetSpellBookItemLevelLearned = _num
C_SpellBook.GetSpellBookItemLink = _str
C_SpellBook.GetSpellBookItemLossOfControlCooldownDuration = _nil
C_SpellBook.GetSpellBookItemLossOfControlCooldownInfo = _tbl
C_SpellBook.GetSpellBookItemName = _str
C_SpellBook.GetSpellBookItemPowerCost = _tbl
C_SpellBook.GetSpellBookItemSkillLineIndex = _nil
C_SpellBook.GetSpellBookItemTexture = _nil
C_SpellBook.GetSpellBookItemTradeSkillLink = _str
C_SpellBook.GetSpellBookItemType = _nil
C_SpellBook.GetSpellBookSkillLineInfo = _tbl
C_SpellBook.HasPetSpells = _num
C_SpellBook.IsAutoAttackSpellBookItem = _bool
C_SpellBook.IsClassTalentSpellBookItem = _bool
C_SpellBook.IsPvPTalentSpellBookItem = _bool
C_SpellBook.IsRangedAutoAttackSpellBookItem = _bool
C_SpellBook.IsSpellBookItemHarmful = _bool
C_SpellBook.IsSpellBookItemHelpful = _bool
C_SpellBook.IsSpellBookItemInRange = _nil
C_SpellBook.IsSpellBookItemOffSpec = _bool
C_SpellBook.IsSpellBookItemPassive = _bool
C_SpellBook.IsSpellBookItemUsable = _bool
C_SpellBook.IsSpellInSpellBook = _bool
C_SpellBook.IsSpellKnown = _bool
C_SpellBook.IsSpellKnownOrInSpellBook = _bool
C_SpellBook.PickupSpellBookItem = _nil
C_SpellBook.SetSpellBookItemAutoCastEnabled = _nil
C_SpellBook.SpellBookItemHasRange = _bool
C_SpellBook.ToggleSpellBookItemAutoCast = _nil
-- Events: CURRENT_SPELL_CAST_CHANGED, LEARNED_SPELL_IN_SKILL_LINE, MAX_SPELL_START_RECOVERY_OFFSET_CHANGED, PLAYER_TOTEM_UPDATE, SPELL_FLYOUT_UPDATE, SPELL_PUSHED_TO_ACTIONBAR, SPELL_PUSHED_TO_FLYOUT_ON_ACTIONBAR, SPELL_UPDATE_CHARGES, SPELL_UPDATE_COOLDOWN, SPELL_UPDATE_ICON, SPELL_UPDATE_USABLE, SPELL_UPDATE_USES, SPELLS_CHANGED, START_AUTOREPEAT_SPELL, STOP_AUTOREPEAT_SPELL, UPDATE_SHAPESHIFT_COOLDOWN, UPDATE_SHAPESHIFT_FORM, UPDATE_SHAPESHIFT_FORMS, UPDATE_SHAPESHIFT_USABLE
`;
