// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:bbcdf018df83b6fb324f2c092079f64c26f1ac47234f067a5d2e60af57a0dcf4
// @sig-hash: sha256:5bf33efff2a91118
// Source: Blizzard_APIDocumentationGenerated/spellactivationoverlaydocumentation.lua
export const C_SpellActivationOverlay = `
if C_SpellActivationOverlay == nil then C_SpellActivationOverlay = {} end
C_SpellActivationOverlay.IsSpellOverlayed = _bool("C_SpellActivationOverlay.IsSpellOverlayed")
-- Events: SPELL_ACTIVATION_OVERLAY_GLOW_HIDE, SPELL_ACTIVATION_OVERLAY_GLOW_SHOW, SPELL_ACTIVATION_OVERLAY_HIDE, SPELL_ACTIVATION_OVERLAY_SHOW
`;
