// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d827418d9c55f306252a2169ac3a5f483f2828410f218aca2fa296e7433367f9
// @sig-hash: sha256:0da15b55bdb9da1e
// Source: Blizzard_APIDocumentationGenerated/splashscreendocumentation.lua
export const C_SplashScreen = `
if C_SplashScreen == nil then C_SplashScreen = {} end
C_SplashScreen.AcknowledgeSplash = _nil
C_SplashScreen.CanViewSplashScreen = _nil
C_SplashScreen.RequestLatestSplashScreen = _nil
C_SplashScreen.SendSplashScreenActionLaunchedTelem = _nil
C_SplashScreen.SendSplashScreenCloseTelem = _nil
-- Events: OPEN_SPLASH_SCREEN
`;
