// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:631a43f0635c5ca529f36a8a45762186bf17645b5c517fab1f71c5eb01c21ce7
// @sig-hash: sha256:0742e53770d0e9fe
// Source: Blizzard_APIDocumentationGenerated/specializationinfodocumentation.lua
export const C_SpecializationInfo = `
if C_SpecializationInfo == nil then C_SpecializationInfo = {} end
C_SpecializationInfo.CanPlayerUsePVPTalentUI = _nil
C_SpecializationInfo.CanPlayerUseTalentSpecUI = _nil
C_SpecializationInfo.CanPlayerUseTalentUI = _nil
C_SpecializationInfo.GetActiveSpecGroup = _nil
C_SpecializationInfo.GetAllSelectedPvpTalentIDs = _tbl
C_SpecializationInfo.GetClassIDFromSpecID = _nil
C_SpecializationInfo.GetInspectSelectedPvpTalent = _nil
C_SpecializationInfo.GetNumSpecializationsForClassID = _nil
C_SpecializationInfo.GetPvpTalentAlertStatus = _nil
C_SpecializationInfo.GetPvpTalentInfo = _nil
C_SpecializationInfo.GetPvpTalentSlotInfo = _nil
C_SpecializationInfo.GetPvpTalentSlotUnlockLevel = _nil
C_SpecializationInfo.GetPvpTalentUnlockLevel = _nil
C_SpecializationInfo.GetSpecIDs = _tbl
C_SpecializationInfo.GetSpecialization = _nil
C_SpecializationInfo.GetSpecializationInfo = _nil
C_SpecializationInfo.GetSpecializationMasterySpells = _tbl
C_SpecializationInfo.GetSpellsDisplay = _tbl
C_SpecializationInfo.GetTalentInfo = _nil
C_SpecializationInfo.IsInitialized = _nil
C_SpecializationInfo.IsPvpTalentLocked = _nil
C_SpecializationInfo.MatchesCurrentSpecSet = _nil
C_SpecializationInfo.SetPetSpecialization = _nil
C_SpecializationInfo.SetPvpTalentLocked = _nil
C_SpecializationInfo.SetSpecialization = _nil
-- Events: ACTIVE_TALENT_GROUP_CHANGED, CONFIRM_PET_UNLEARN, CONFIRM_TALENT_WIPE, PET_SPECIALIZATION_CHANGED, PLAYER_LEARN_PVP_TALENT_FAILED, PLAYER_LEARN_TALENT_FAILED, PLAYER_PVP_TALENT_UPDATE, PLAYER_TALENT_UPDATE, SPEC_INVOLUNTARILY_CHANGED, TALENTS_INVOLUNTARILY_RESET
`;
