// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:763aa71245ed59f15c0bcbeb43d76a2e293d0bbf30b684e65b4d01e4ec10d787
// @sig-hash: sha256:ead398a002dc0c90
// Source: Blizzard_APIDocumentationGenerated/stringutildocumentation.lua
export const C_StringUtil = `
if C_StringUtil == nil then C_StringUtil = {} end
C_StringUtil.CreateAbbreviatedNumberFormatter = _nil("C_StringUtil.CreateAbbreviatedNumberFormatter")
C_StringUtil.CreateNumericRuleFormatter = _nil("C_StringUtil.CreateNumericRuleFormatter")
C_StringUtil.CreateSecondsFormatter = _nil("C_StringUtil.CreateSecondsFormatter")
C_StringUtil.EscapeLuaFormatString = _nil("C_StringUtil.EscapeLuaFormatString")
C_StringUtil.EscapeLuaPatterns = _str("C_StringUtil.EscapeLuaPatterns")
C_StringUtil.EscapeQuotedCodes = _nil("C_StringUtil.EscapeQuotedCodes")
C_StringUtil.FloorToNearestString = _str("C_StringUtil.FloorToNearestString")
C_StringUtil.RemoveContiguousSpaces = _str("C_StringUtil.RemoveContiguousSpaces")
C_StringUtil.RoundToNearestString = _str("C_StringUtil.RoundToNearestString")
C_StringUtil.StripHyperlinks = _nil("C_StringUtil.StripHyperlinks")
C_StringUtil.StripTextureMarkupForLooseFiles = _nil("C_StringUtil.StripTextureMarkupForLooseFiles")
C_StringUtil.trim = _nil("C_StringUtil.trim")
C_StringUtil.TruncateWhenZero = _str("C_StringUtil.TruncateWhenZero")
C_StringUtil.WrapString = _str("C_StringUtil.WrapString")
`;
