// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c16ec19e3649556a993b7f254592736230d85f4cc3d0d7ca38e2d1b2789cc4df
// @sig-hash: sha256:9ee09e8cdd4c48e7
// Source: Blizzard_APIDocumentationGenerated/storepublicuidocumentation.lua
export const C_StorePublic = `
if C_StorePublic == nil then C_StorePublic = {} end
C_StorePublic.DoesGroupHavePurchaseableProducts = _bool("C_StorePublic.DoesGroupHavePurchaseableProducts")
C_StorePublic.EventStoreUISetShown = _nil("C_StorePublic.EventStoreUISetShown")
C_StorePublic.IsEnabled = _bool("C_StorePublic.IsEnabled")
`;
