// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:637b3561309f9581dee2086213e0887675801f7ee504f316adb2cf748c915eed
// @sig-hash: sha256:ee785a2c707223a4
// Source: Blizzard_APIDocumentationGenerated/storepublicuidocumentation.lua
export const C_StorePublic = `
if C_StorePublic == nil then C_StorePublic = {} end
C_StorePublic.DoesGroupHavePurchaseableProducts = _nil
C_StorePublic.EventStoreUISetShown = _nil
C_StorePublic.IsEnabled = _nil
`;
