// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d0c6e02f744ae05d156b239c4e27a6e62cdb804028785aef236c5feca56f4b63
// @sig-hash: sha256:7b893fdea70dbbf7
// Source: Blizzard_APIDocumentationGenerated/stableinfodocumentation.lua
export const C_StableInfo = `
if C_StableInfo == nil then C_StableInfo = {} end
C_StableInfo.ClosePetStables = _nil
C_StableInfo.GetActivePetList = _tbl
C_StableInfo.GetAvailablePetSpecInfos = _tbl
C_StableInfo.GetNumActivePets = _nil
C_StableInfo.GetNumStablePets = _nil
C_StableInfo.GetStablePetFoodTypes = _tbl
C_StableInfo.GetStablePetInfo = _nil
C_StableInfo.GetStabledPetList = _tbl
C_StableInfo.IsAtStableMaster = _nil
C_StableInfo.IsBonusPetSlotAvailable = _nil
C_StableInfo.IsPetFavorite = _nil
C_StableInfo.PickupStablePet = _nil
C_StableInfo.SetPetFavorite = _nil
C_StableInfo.SetPetSlot = _nil
-- Events: PET_INFO_UPDATE, PET_STABLE_CLOSED, PET_STABLE_FAVORITES_UPDATED, PET_STABLE_SHOW, PET_STABLE_UPDATE
`;
