// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3dca467154b0d89a740043b51e3ad240422fb3a1e18943a49f8472bd036ce4d5
// @sig-hash: sha256:b1dad3b37413ab9a
// Source: Blizzard_APIDocumentationGenerated/stableinfodocumentation.lua
export const C_StableInfo = `
if C_StableInfo == nil then C_StableInfo = {} end
C_StableInfo.ClosePetStables = _nil("C_StableInfo.ClosePetStables")
C_StableInfo.GetActivePetList = _tbl("C_StableInfo.GetActivePetList")
C_StableInfo.GetAvailablePetSpecInfos = _tbl("C_StableInfo.GetAvailablePetSpecInfos")
C_StableInfo.GetNumActivePets = _num("C_StableInfo.GetNumActivePets")
C_StableInfo.GetNumStablePets = _num("C_StableInfo.GetNumStablePets")
C_StableInfo.GetStablePetFoodTypes = _tbl("C_StableInfo.GetStablePetFoodTypes")
C_StableInfo.GetStablePetInfo = _nil("C_StableInfo.GetStablePetInfo")
C_StableInfo.GetStabledPetList = _tbl("C_StableInfo.GetStabledPetList")
C_StableInfo.IsAtStableMaster = _bool("C_StableInfo.IsAtStableMaster")
C_StableInfo.IsBonusPetSlotAvailable = _bool("C_StableInfo.IsBonusPetSlotAvailable")
C_StableInfo.IsPetFavorite = _bool("C_StableInfo.IsPetFavorite")
C_StableInfo.PickupStablePet = _nil("C_StableInfo.PickupStablePet")
C_StableInfo.SetPetFavorite = _nil("C_StableInfo.SetPetFavorite")
C_StableInfo.SetPetSlot = _nil("C_StableInfo.SetPetSlot")
-- Events: PET_INFO_UPDATE, PET_STABLE_CLOSED, PET_STABLE_FAVORITES_UPDATED, PET_STABLE_SHOW, PET_STABLE_UPDATE
`;
