// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a2b47570c9f920402e05f3c0b3de9ce91b0023a314ab507fa980718d441548c9
// @sig-hash: sha256:7c7f4e84c4d5ee60
// Source: Blizzard_APIDocumentationGenerated/stringutildocumentation.lua
export const C_StringUtil = `
if C_StringUtil == nil then C_StringUtil = {} end
C_StringUtil.CreateAbbreviatedNumberFormatter = _nil
C_StringUtil.CreateNumericRuleFormatter = _nil
C_StringUtil.CreateSecondsFormatter = _nil
C_StringUtil.EscapeLuaFormatString = _nil
C_StringUtil.EscapeLuaPatterns = _nil
C_StringUtil.EscapeQuotedCodes = _nil
C_StringUtil.FloorToNearestString = _nil
C_StringUtil.RemoveContiguousSpaces = _nil
C_StringUtil.RoundToNearestString = _nil
C_StringUtil.StripHyperlinks = _nil
C_StringUtil.StripTextureMarkupForLooseFiles = _nil
C_StringUtil.trim = _nil
C_StringUtil.TruncateWhenZero = _nil
C_StringUtil.WrapString = _nil
`;
