// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:18966121254ee16091b3dd190e66fe1defadc6bc4cad16dad5fdd338c1673fa6
// @sig-hash: sha256:cc3a70d11355a549
// Source: Blizzard_APIDocumentationGenerated/supertrackmanagerdocumentation.lua
export const C_SuperTrack = `
if C_SuperTrack == nil then C_SuperTrack = {} end
C_SuperTrack.ClearAllSuperTracked = _nil("C_SuperTrack.ClearAllSuperTracked")
C_SuperTrack.ClearSuperTrackedContent = _nil("C_SuperTrack.ClearSuperTrackedContent")
C_SuperTrack.ClearSuperTrackedMapPin = _nil("C_SuperTrack.ClearSuperTrackedMapPin")
C_SuperTrack.GetHighestPrioritySuperTrackingType = _nil("C_SuperTrack.GetHighestPrioritySuperTrackingType")
C_SuperTrack.GetNextWaypointForMap = _num("C_SuperTrack.GetNextWaypointForMap")
C_SuperTrack.GetSuperTrackedContent = _nil("C_SuperTrack.GetSuperTrackedContent")
C_SuperTrack.GetSuperTrackedItemName = _str("C_SuperTrack.GetSuperTrackedItemName")
C_SuperTrack.GetSuperTrackedMapPin = _nil("C_SuperTrack.GetSuperTrackedMapPin")
C_SuperTrack.GetSuperTrackedQuestID = _nil("C_SuperTrack.GetSuperTrackedQuestID")
C_SuperTrack.GetSuperTrackedVignette = _nil("C_SuperTrack.GetSuperTrackedVignette")
C_SuperTrack.IsSuperTrackingAnything = _bool("C_SuperTrack.IsSuperTrackingAnything")
C_SuperTrack.IsSuperTrackingContent = _bool("C_SuperTrack.IsSuperTrackingContent")
C_SuperTrack.IsSuperTrackingCorpse = _bool("C_SuperTrack.IsSuperTrackingCorpse")
C_SuperTrack.IsSuperTrackingMapPin = _bool("C_SuperTrack.IsSuperTrackingMapPin")
C_SuperTrack.IsSuperTrackingQuest = _bool("C_SuperTrack.IsSuperTrackingQuest")
C_SuperTrack.IsSuperTrackingUserWaypoint = _bool("C_SuperTrack.IsSuperTrackingUserWaypoint")
C_SuperTrack.SetSuperTrackedContent = _nil("C_SuperTrack.SetSuperTrackedContent")
C_SuperTrack.SetSuperTrackedMapPin = _nil("C_SuperTrack.SetSuperTrackedMapPin")
C_SuperTrack.SetSuperTrackedQuestID = _nil("C_SuperTrack.SetSuperTrackedQuestID")
C_SuperTrack.SetSuperTrackedUserWaypoint = _nil("C_SuperTrack.SetSuperTrackedUserWaypoint")
C_SuperTrack.SetSuperTrackedVignette = _nil("C_SuperTrack.SetSuperTrackedVignette")
-- Events: SUPER_TRACKING_CHANGED, SUPER_TRACKING_PATH_UPDATED
`;
