// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:de9ac011d9b274a8a2e7d3eceded47bd47e364f169c7e1a6db2049e9663605a7
// @sig-hash: sha256:69804afd38eb9772
// Source: Blizzard_APIDocumentationGenerated/summoninfodocumentation.lua
export const C_SummonInfo = `
if C_SummonInfo == nil then C_SummonInfo = {} end
C_SummonInfo.CancelSummon = _nil
C_SummonInfo.ConfirmSummon = _nil
C_SummonInfo.GetSummonConfirmAreaName = _str
C_SummonInfo.GetSummonConfirmSummoner = _nil
C_SummonInfo.GetSummonConfirmTimeLeft = _num
C_SummonInfo.GetSummonReason = _num
C_SummonInfo.IsSummonSkippingStartExperience = _bool
`;
