// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ad92927a709c3cba4cf789507cafa6b2fa39146f00abbc4bacfe443e32e87837
// @sig-hash: sha256:03f2b9a109334486
// Source: Blizzard_APIDocumentationGenerated/supertrackmanagerdocumentation.lua
export const C_SuperTrack = `
if C_SuperTrack == nil then C_SuperTrack = {} end
C_SuperTrack.ClearAllSuperTracked = _nil
C_SuperTrack.ClearSuperTrackedContent = _nil
C_SuperTrack.ClearSuperTrackedMapPin = _nil
C_SuperTrack.GetHighestPrioritySuperTrackingType = _nil
C_SuperTrack.GetNextWaypointForMap = _num
C_SuperTrack.GetSuperTrackedContent = _nil
C_SuperTrack.GetSuperTrackedItemName = _str
C_SuperTrack.GetSuperTrackedMapPin = _nil
C_SuperTrack.GetSuperTrackedQuestID = _nil
C_SuperTrack.GetSuperTrackedVignette = _nil
C_SuperTrack.IsSuperTrackingAnything = _bool
C_SuperTrack.IsSuperTrackingContent = _bool
C_SuperTrack.IsSuperTrackingCorpse = _bool
C_SuperTrack.IsSuperTrackingMapPin = _bool
C_SuperTrack.IsSuperTrackingQuest = _bool
C_SuperTrack.IsSuperTrackingUserWaypoint = _bool
C_SuperTrack.SetSuperTrackedContent = _nil
C_SuperTrack.SetSuperTrackedMapPin = _nil
C_SuperTrack.SetSuperTrackedQuestID = _nil
C_SuperTrack.SetSuperTrackedUserWaypoint = _nil
C_SuperTrack.SetSuperTrackedVignette = _nil
-- Events: SUPER_TRACKING_CHANGED, SUPER_TRACKING_PATH_UPDATED
`;
