// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:9909af4642ff717c47ff54ca422b93c8ace7b41d2af3d59046615b7e87614988
// @sig-hash: sha256:c8604edf9f6e7049
// Source: Blizzard_APIDocumentationGenerated/uisystemvisibilitymanagerdocumentation.lua
export const C_SystemVisibilityManager = `
if C_SystemVisibilityManager == nil then C_SystemVisibilityManager = {} end
C_SystemVisibilityManager.IsSystemVisible = _bool("C_SystemVisibilityManager.IsSystemVisible")
-- Events: SYSTEM_VISIBILITY_CHANGED
`;
