// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:711c95df3423177733ff5de1550388831119997515adcf9bde24b7e8c0ad3414
// @sig-hash: sha256:1e0a27850dd0c594
// Source: Blizzard_APIDocumentationGenerated/luatableutildocumentation.lua
export const C_TableUtil = `
if C_TableUtil == nil then C_TableUtil = {} end
C_TableUtil.count = _num("C_TableUtil.count")
C_TableUtil.create = _nil("C_TableUtil.create")
C_TableUtil.FindIndexedMismatch = _nil("C_TableUtil.FindIndexedMismatch")
C_TableUtil.freeze = _nil("C_TableUtil.freeze")
C_TableUtil.isfrozen = _bool("C_TableUtil.isfrozen")
`;
