// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:562b236ddd6038100bec78398ec31755eebdbbb3bef2254899f2fa634bae2b9f
// @sig-hash: sha256:2bf2ff1b700f9e5d
// Source: Blizzard_APIDocumentationGenerated/questtaskinfodocumentation.lua
export const C_TaskQuest = `
if C_TaskQuest == nil then C_TaskQuest = {} end
C_TaskQuest.DoesMapShowTaskQuestObjectives = _nil
C_TaskQuest.GetQuestInfoByQuestID = _nil
C_TaskQuest.GetQuestLocation = _nil
C_TaskQuest.GetQuestProgressBarInfo = _nil
C_TaskQuest.GetQuestTimeLeftMinutes = _nil
C_TaskQuest.GetQuestTimeLeftSeconds = _nil
C_TaskQuest.GetQuestUIWidgetSetByType = _nil
C_TaskQuest.GetQuestZoneID = _nil
C_TaskQuest.GetQuestsOnMap = _tbl
C_TaskQuest.GetThreatQuests = _tbl
C_TaskQuest.IsActive = _nil
C_TaskQuest.RequestPreloadRewardData = _nil
`;
