// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:33799c60f23eb617d94414e1fe7a31b5eb2349635d6e01d189eeb813ace02924
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/talkingheaddocumentation.lua
export const C_TalkingHead = `
if C_TalkingHead == nil then C_TalkingHead = {} end
-- Events: TALKINGHEAD_CLOSE, TALKINGHEAD_REQUESTED
`;
