// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c459998d4b7b5eccbd7ea52636ba8db19337f588a02b4e55e25d30a4fdc31daa
// @sig-hash: sha256:0c352131563c2a24
// Source: Blizzard_APIDocumentationGenerated/questtaskinfodocumentation.lua
export const C_TaskQuest = `
if C_TaskQuest == nil then C_TaskQuest = {} end
C_TaskQuest.DoesMapShowTaskQuestObjectives = _bool("C_TaskQuest.DoesMapShowTaskQuestObjectives")
C_TaskQuest.GetQuestInfoByQuestID = _str("C_TaskQuest.GetQuestInfoByQuestID")
C_TaskQuest.GetQuestLocation = _num("C_TaskQuest.GetQuestLocation")
C_TaskQuest.GetQuestProgressBarInfo = _num("C_TaskQuest.GetQuestProgressBarInfo")
C_TaskQuest.GetQuestTimeLeftMinutes = _num("C_TaskQuest.GetQuestTimeLeftMinutes")
C_TaskQuest.GetQuestTimeLeftSeconds = _num("C_TaskQuest.GetQuestTimeLeftSeconds")
C_TaskQuest.GetQuestUIWidgetSetByType = _num("C_TaskQuest.GetQuestUIWidgetSetByType")
C_TaskQuest.GetQuestZoneID = _num("C_TaskQuest.GetQuestZoneID")
C_TaskQuest.GetQuestsOnMap = _tbl("C_TaskQuest.GetQuestsOnMap")
C_TaskQuest.GetThreatQuests = _tbl("C_TaskQuest.GetThreatQuests")
C_TaskQuest.IsActive = _bool("C_TaskQuest.IsActive")
C_TaskQuest.RequestPreloadRewardData = _nil("C_TaskQuest.RequestPreloadRewardData")
`;
