// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:07556eb86f72d5a854b417bdad10e3d023317ae0e8b4f101c0165345898bb6a8
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/talkingheaddocumentation.lua
export const C_TalkingHead = `
if C_TalkingHead == nil then C_TalkingHead = {} end
-- Events: TALKINGHEAD_CLOSE, TALKINGHEAD_REQUESTED
`;
