// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5cc1c509f8b54031e8beb95e9a1737c55e356bbaea983ff97a78425006825dab
// @sig-hash: sha256:34da54c871198ea0
// Source: Blizzard_APIDocumentationGenerated/textureutilsdocumentation.lua
export const C_Texture = `
if C_Texture == nil then C_Texture = {} end
C_Texture.ClearTitleIconTexture = _nil
C_Texture.GetAtlasElementID = _nil
C_Texture.GetAtlasElements = _tbl
C_Texture.GetAtlasExists = _nil
C_Texture.GetAtlasID = _nil
C_Texture.GetAtlasInfo = _tbl
C_Texture.GetFilenameFromFileDataID = _nil
C_Texture.GetTitleIconTexture = _nil
C_Texture.IsTitleIconTextureReady = _nil
C_Texture.SetTitleIconTexture = _nil
C_Texture.SetURLTexture = _nil
`;
