// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ac6657b7106ba138752542ccc963d9b984cac4a89f6cdf082ef3d87d7a2f4be1
// @sig-hash: sha256:1cbd9a7b4871546b
// Source: Blizzard_APIDocumentationGenerated/uitimerdocumentation.lua
export const C_Timer = `
if C_Timer == nil then C_Timer = {} end
C_Timer.After = _nil("C_Timer.After")
C_Timer.NewTicker = _nil("C_Timer.NewTicker")
C_Timer.NewTimer = _nil("C_Timer.NewTimer")
`;
