// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:3533f607a4a44cedc599b1c507bb53b6983567ae6362b1f876a99c4b41f2b29c
// @sig-hash: sha256:a60752dfc1537207
// Source: Blizzard_APIDocumentationGenerated/timerunninguidocumentation.lua
export const C_TimerunningUI = `
if C_TimerunningUI == nil then C_TimerunningUI = {} end
C_TimerunningUI.GetActiveTimerunningSeasonID = _num
-- Events: REMIX_END_OF_EVENT
`;
