// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:18eaa5ed62b8a69e2a377b73ed46bc2c7a4c363a3d7812f170abf35e73c556a4
// @sig-hash: sha256:07379f148c51e624
// Source: Blizzard_APIDocumentationGenerated/timerunninguidocumentation.lua
export const C_TimerunningUI = `
if C_TimerunningUI == nil then C_TimerunningUI = {} end
C_TimerunningUI.GetActiveTimerunningSeasonID = _num("C_TimerunningUI.GetActiveTimerunningSeasonID")
-- Events: REMIX_END_OF_EVENT
`;
