// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:72b5d79e91b3d8185cff68e5a6cd91498cb3aecd8ea6809a84e4d0edc805bc4c
// @sig-hash: sha256:f07e7c003d3b956a
// Source: Blizzard_APIDocumentationGenerated/uitimerdocumentation.lua
export const C_Timer = `
if C_Timer == nil then C_Timer = {} end
C_Timer.After = _nil
C_Timer.NewTicker = _nil
C_Timer.NewTimer = _nil
`;
