// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:11b263579d0283a5d8e3e7021cda3ab888b185cb5c56c4a544228b7b86f12004
// @sig-hash: sha256:831010cb14aaedfd
// Source: Blizzard_APIDocumentationGenerated/tooltipcomparisondocumentation.lua
export const C_TooltipComparison = `
if C_TooltipComparison == nil then C_TooltipComparison = {} end
C_TooltipComparison.CompareItem = _nil
C_TooltipComparison.GetItemComparisonDelta = _tbl
C_TooltipComparison.GetItemComparisonInfo = _tbl
-- Events: TOOLTIP_SHOW_ITEM_COMPARISON
`;
