// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:ea60282e77ec208b96218dfaae6e076826510714204b36a7b7aff9c2aa4187e1
// @sig-hash: sha256:9629c48fd3cc2188
// Source: Blizzard_APIDocumentationGenerated/sharedtraitsdocumentation.lua
export const C_Traits = `
if C_Traits == nil then C_Traits = {} end
C_Traits.CanEditConfig = _bool
C_Traits.CanPurchaseRank = _bool
C_Traits.CanRefundRank = _bool
C_Traits.CascadeRepurchaseRanks = _bool
C_Traits.ClearCascadeRepurchaseHistory = _nil
C_Traits.CloseTraitSystemInteraction = _nil
C_Traits.CommitConfig = _bool
C_Traits.ConfigHasStagedChanges = _bool
C_Traits.GenerateImportString = _str
C_Traits.GenerateInspectImportString = _str
C_Traits.GetConditionInfo = _tbl
C_Traits.GetConfigIDBySystemID = _num
C_Traits.GetConfigIDByTreeID = _num
C_Traits.GetConfigInfo = _tbl
C_Traits.GetConfigVariationID = _num
C_Traits.GetConfigsByType = _tbl
C_Traits.GetDefinitionInfo = _tbl
C_Traits.GetEntryInfo = _tbl
C_Traits.GetIncreasedTraitData = _tbl
C_Traits.GetLoadoutSerializationVersion = _num
C_Traits.GetNodeCost = _tbl
C_Traits.GetNodeInfo = _tbl
C_Traits.GetStagedChanges = _tbl
C_Traits.GetStagedChangesCost = _tbl
C_Traits.GetSubTreeInfo = _tbl
C_Traits.GetSystemIDByTreeID = _num
C_Traits.GetTraitCurrencyInfo = _num
C_Traits.GetTraitDescription = _str
C_Traits.GetTraitSystemFlags = _num
C_Traits.GetTraitSystemWidgetSetID = _num
C_Traits.GetTreeCurrencyInfo = _tbl
C_Traits.GetTreeHash = _tbl
C_Traits.GetTreeInfo = _tbl
C_Traits.GetTreeNodes = _tbl
C_Traits.HasValidInspectData = _bool
C_Traits.IsReadyForCommit = _bool
C_Traits.PurchaseAllRanks = _bool
C_Traits.PurchaseRank = _bool
C_Traits.RefundAllRanks = _bool
C_Traits.RefundRank = _bool
C_Traits.ResetTree = _bool
C_Traits.ResetTreeByCurrency = _bool
C_Traits.RollbackConfig = _bool
C_Traits.SetSelection = _bool
C_Traits.StageConfig = _bool
C_Traits.TalentTestUnlearnSpells = _nil
C_Traits.TryPurchaseAllRanks = _bool
C_Traits.TryPurchaseToNode = _bool
C_Traits.TryRefundToNode = _bool
-- Events: CONFIG_COMMIT_FAILED, TRAIT_COND_INFO_CHANGED, TRAIT_CONFIG_CREATED, TRAIT_CONFIG_DELETED, TRAIT_CONFIG_LIST_UPDATED, TRAIT_CONFIG_UPDATED, TRAIT_NODE_CHANGED, TRAIT_NODE_CHANGED_PARTIAL, TRAIT_NODE_ENTRY_UPDATED, TRAIT_SUB_TREE_CHANGED, TRAIT_SYSTEM_INTERACTION_STARTED, TRAIT_SYSTEM_NPC_CLOSED, TRAIT_TREE_CHANGED, TRAIT_TREE_CURRENCY_INFO_UPDATED, TRY_PURCHASE_TO_NODE_PARTIAL_SUCCESS
`;
