// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fab72978f90769e536b3247b4114ba9116e50bc9ed555fff6dc5daf72e1139a6
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/traitconfigdocumentation.lua
export const C_TraitConfig = `
if C_TraitConfig == nil then C_TraitConfig = {} end
`;
