// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:bc8222dd4f5f7c503bcef084526fa8a9e0e9bdbb4a37e443f722ad033e37d473
// @sig-hash: sha256:edab6795e65755ec
// Source: Blizzard_APIDocumentationGenerated/tradeinfodocumentation.lua
export const C_TradeInfo = `
if C_TradeInfo == nil then C_TradeInfo = {} end
C_TradeInfo.AddTradeMoney = _nil("C_TradeInfo.AddTradeMoney")
C_TradeInfo.PickupTradeMoney = _nil("C_TradeInfo.PickupTradeMoney")
C_TradeInfo.SetTradeMoney = _nil("C_TradeInfo.SetTradeMoney")
C_TradeInfo.ShouldShowTradeOfferWarning = _bool("C_TradeInfo.ShouldShowTradeOfferWarning")
-- Events: PLAYER_TRADE_CURRENCY, PLAYER_TRADE_MONEY, TRADE_ACCEPT_UPDATE, TRADE_CLOSED, TRADE_CURRENCY_CHANGED, TRADE_MONEY_CHANGED, TRADE_PLAYER_ITEM_CHANGED, TRADE_POTENTIAL_BIND_ENCHANT, TRADE_POTENTIAL_REMOVE_TRANSMOG, TRADE_REQUEST, TRADE_REQUEST_CANCEL, TRADE_SHOW, TRADE_TARGET_ITEM_CHANGED, TRADE_UPDATE, TRADE_UPDATE_WARNINGS
`;
