// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:aba4c1bcd3a4212ce7becfd93f49a7d3a1819e5f6a75f81de3b53286bb7fe013
// @sig-hash: sha256:7120d0f82cb1a37b
// Source: Blizzard_APIDocumentationGenerated/transmogsetsdocumentation.lua
export const C_TransmogSets = `
if C_TransmogSets == nil then C_TransmogSets = {} end
C_TransmogSets.ClearLatestSource = _nil
C_TransmogSets.ClearNewSource = _nil
C_TransmogSets.ClearSetNewSourcesForSlot = _nil
C_TransmogSets.GetAllSets = _tbl
C_TransmogSets.GetAllSourceIDs = _tbl
C_TransmogSets.GetAvailableSets = _tbl
C_TransmogSets.GetBaseSetID = _num
C_TransmogSets.GetBaseSets = _tbl
C_TransmogSets.GetBaseSetsFilter = _bool
C_TransmogSets.GetCameraIDs = _nil
C_TransmogSets.GetFilteredBaseSetsCounts = _num
C_TransmogSets.GetFullBaseSetsCounts = _num
C_TransmogSets.GetIsFavorite = _bool
C_TransmogSets.GetLatestSource = _num
C_TransmogSets.GetSetInfo = _tbl
C_TransmogSets.GetSetNewSources = _tbl
C_TransmogSets.GetSetPrimaryAppearances = _tbl
C_TransmogSets.GetSetsContainingSourceID = _tbl
C_TransmogSets.GetSetsFilter = _bool
C_TransmogSets.GetSourceIDsForSlot = _tbl
C_TransmogSets.GetSourcesForSlot = _tbl
C_TransmogSets.GetTransmogSetsClassFilter = _num
C_TransmogSets.GetUsableSets = _tbl
C_TransmogSets.GetValidBaseSetsCountsForCharacter = _num
C_TransmogSets.GetValidClassForSet = _nil
C_TransmogSets.GetVariantSets = _tbl
C_TransmogSets.HasAvailableSets = _bool
C_TransmogSets.HasUsableSets = _bool
C_TransmogSets.IsBaseSetCollected = _bool
C_TransmogSets.IsNewSource = _bool
C_TransmogSets.IsSetVisible = _bool
C_TransmogSets.IsUsingDefaultBaseSetsFilters = _bool
C_TransmogSets.IsUsingDefaultSetsFilters = _bool
C_TransmogSets.SetBaseSetsFilter = _nil
C_TransmogSets.SetDefaultBaseSetsFilters = _nil
C_TransmogSets.SetDefaultSetsFilters = _nil
C_TransmogSets.SetHasNewSources = _bool
C_TransmogSets.SetHasNewSourcesForSlot = _bool
C_TransmogSets.SetIsFavorite = _nil
C_TransmogSets.SetSetsFilter = _nil
C_TransmogSets.SetTransmogSetsClassFilter = _nil
`;
