// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:87ad3845f6a90efd81e3286c9996340b9bd3f3acf8135af5eaf1b0c1af9ca1d6
// @sig-hash: sha256:2db9982f934d84f9
// Source: Blizzard_APIDocumentationGenerated/tradeinfodocumentation.lua
export const C_TradeInfo = `
if C_TradeInfo == nil then C_TradeInfo = {} end
C_TradeInfo.AddTradeMoney = _nil
C_TradeInfo.PickupTradeMoney = _nil
C_TradeInfo.SetTradeMoney = _nil
C_TradeInfo.ShouldShowTradeOfferWarning = _bool
-- Events: PLAYER_TRADE_CURRENCY, PLAYER_TRADE_MONEY, TRADE_ACCEPT_UPDATE, TRADE_CLOSED, TRADE_CURRENCY_CHANGED, TRADE_MONEY_CHANGED, TRADE_PLAYER_ITEM_CHANGED, TRADE_POTENTIAL_BIND_ENCHANT, TRADE_POTENTIAL_REMOVE_TRANSMOG, TRADE_REQUEST, TRADE_REQUEST_CANCEL, TRADE_SHOW, TRADE_TARGET_ITEM_CHANGED, TRADE_UPDATE, TRADE_UPDATE_WARNINGS
`;
