// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fbfc5d36feb161188ca11fca4238805aff7784485a16245cdd08265d5a869fd3
// @sig-hash: sha256:694d65f88f1f3d34
// Source: Blizzard_APIDocumentationGenerated/transmogdocumentation.lua
export const C_Transmog = `
if C_Transmog == nil then C_Transmog = {} end
C_Transmog.CanHaveSecondaryAppearanceForSlotID = _bool("C_Transmog.CanHaveSecondaryAppearanceForSlotID")
C_Transmog.ExtractTransmogIDList = _tbl("C_Transmog.ExtractTransmogIDList")
C_Transmog.GetAllSetAppearancesByID = _tbl("C_Transmog.GetAllSetAppearancesByID")
C_Transmog.GetItemIDForSource = _nil("C_Transmog.GetItemIDForSource")
C_Transmog.GetSlotForInventoryType = _nil("C_Transmog.GetSlotForInventoryType")
C_Transmog.GetSlotVisualInfo = _tbl("C_Transmog.GetSlotVisualInfo")
C_Transmog.IsAtTransmogNPC = _bool("C_Transmog.IsAtTransmogNPC")
-- Events: TRANSMOG_COLLECTION_CAMERA_UPDATE, TRANSMOG_COLLECTION_ITEM_FAVORITE_UPDATE, TRANSMOG_COLLECTION_ITEM_UPDATE, TRANSMOG_COLLECTION_SOURCE_ADDED, TRANSMOG_COLLECTION_SOURCE_REMOVED, TRANSMOG_COLLECTION_UPDATED, TRANSMOG_COSMETIC_COLLECTION_SOURCE_ADDED, TRANSMOG_SEARCH_UPDATED, TRANSMOG_SETS_UPDATE_FAVORITE, TRANSMOG_SOURCE_COLLECTABILITY_UPDATE, TRANSMOGRIFY_CLOSE, TRANSMOGRIFY_ITEM_UPDATE, TRANSMOGRIFY_OPEN, TRANSMOGRIFY_SUCCESS, TRANSMOGRIFY_UPDATE
`;
