// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:8b0a77fc582291e605f9ed5d03695c39cf2f926608300c5c8f66e67e018c5009
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/traitconfigdocumentation.lua
export const C_TraitConfig = `
if C_TraitConfig == nil then C_TraitConfig = {} end
`;
