// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:4ad7d786043ff67e0efed4a9938e9e5c1bdd595bcf7491faa65f1ba3ccb1b80b
// @sig-hash: sha256:bdce2c0953019e90
// Source: Blizzard_APIDocumentationGenerated/ttssettingsdocumentation.lua
export const C_TTSSettings = `
if C_TTSSettings == nil then C_TTSSettings = {} end
C_TTSSettings.GetChannelEnabled = _bool
C_TTSSettings.GetCharacterSettingsSaved = _bool
C_TTSSettings.GetChatTypeEnabled = _bool
C_TTSSettings.GetSetting = _bool
C_TTSSettings.GetSpeechRate = _num
C_TTSSettings.GetSpeechVolume = _num
C_TTSSettings.GetVoiceOptionID = _num
C_TTSSettings.GetVoiceOptionName = _str
C_TTSSettings.MarkCharacterSettingsSaved = _nil
C_TTSSettings.SetChannelEnabled = _nil
C_TTSSettings.SetChannelKeyEnabled = _nil
C_TTSSettings.SetChatTypeEnabled = _nil
C_TTSSettings.SetDefaultSettings = _nil
C_TTSSettings.SetSetting = _nil
C_TTSSettings.SetSpeechRate = _nil
C_TTSSettings.SetSpeechVolume = _nil
C_TTSSettings.SetVoiceOption = _nil
C_TTSSettings.SetVoiceOptionName = _nil
C_TTSSettings.ShouldOverrideMessage = _bool
`;
