// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0d6f4b39c0655eb9d2845db7f98013bed1bc4b80fae25f68ea7e4a14b7aad418
// @sig-hash: sha256:3a36d61e9cf512af
// Source: Blizzard_APIDocumentationGenerated/uicolordocumentation.lua
export const C_UIColor = `
if C_UIColor == nil then C_UIColor = {} end
C_UIColor.GetColors = _tbl("C_UIColor.GetColors")
`;
