// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:0d5719f04905bb3a0e1c79f162c8d3fb9a1f264a1804c784962c937b288cd6f0
// @sig-hash: sha256:83dbc15a17849c7e
// Source: Blizzard_APIDocumentationGenerated/uimanagerdocumentation.lua
export const C_UI = `
if C_UI == nil then C_UI = {} end
C_UI.DoesAnyDisplayHaveNotch = _bool("C_UI.DoesAnyDisplayHaveNotch")
C_UI.GetTopLeftNotchSafeRegion = _num("C_UI.GetTopLeftNotchSafeRegion")
C_UI.GetTopRightNotchSafeRegion = _num("C_UI.GetTopRightNotchSafeRegion")
C_UI.GetUIParent = _nil("C_UI.GetUIParent")
C_UI.GetWorldFrame = _nil("C_UI.GetWorldFrame")
C_UI.Reload = _nil("C_UI.Reload")
C_UI.ShouldUIParentAvoidNotch = _bool("C_UI.ShouldUIParentAvoidNotch")
-- Events: NOTCHED_DISPLAY_MODE_CHANGED, UI_SCALE_CHANGED
`;
