// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a72813d928514f98784d36a0fa22f5b0a5620d29f2afe8d19890e8b1b08efcbf
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/uiactiondocumentation.lua
export const C_UIActionHandler = `
if C_UIActionHandler == nil then C_UIActionHandler = {} end
-- Events: HANDLE_UI_ACTION
`;
