// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:efc3a74dbdd0232c1022f15bb6695a15b121fbda115ca5d52731063d17455cfc
// @sig-hash: sha256:cb84c4173018e852
// Source: Blizzard_APIDocumentationGenerated/uimanagerdocumentation.lua
export const C_UI = `
if C_UI == nil then C_UI = {} end
C_UI.DoesAnyDisplayHaveNotch = _bool
C_UI.GetTopLeftNotchSafeRegion = _num
C_UI.GetTopRightNotchSafeRegion = _num
C_UI.GetUIParent = _nil
C_UI.GetWorldFrame = _nil
C_UI.Reload = _nil
C_UI.ShouldUIParentAvoidNotch = _bool
-- Events: NOTCHED_DISPLAY_MODE_CHANGED, UI_SCALE_CHANGED
`;
