// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:beaa24371af0021c5227dddcfc50e64275ac2a4231e326dc721babf434266175
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/uiactiondocumentation.lua
export const C_UIActionHandler = `
if C_UIActionHandler == nil then C_UIActionHandler = {} end
-- Events: HANDLE_UI_ACTION
`;
