// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fbc45f3cd7069946bd384dc78cf8a2ba8708e25889307bcb745fa1cf30ca67f9
// @sig-hash: sha256:3c4ac3b3fe6f2916
// Source: Blizzard_APIDocumentationGenerated/unitauradocumentation.lua
export const C_UnitAuras = `
if C_UnitAuras == nil then C_UnitAuras = {} end
C_UnitAuras.AddBlockedAura = _nil("C_UnitAuras.AddBlockedAura")
C_UnitAuras.AddPrivateAuraAnchor = _nil("C_UnitAuras.AddPrivateAuraAnchor")
C_UnitAuras.AddPrivateAuraAppliedSound = _nil("C_UnitAuras.AddPrivateAuraAppliedSound")
C_UnitAuras.AuraIsBigDefensive = _bool("C_UnitAuras.AuraIsBigDefensive")
C_UnitAuras.AuraIsPrivate = _bool("C_UnitAuras.AuraIsPrivate")
C_UnitAuras.ClearBlockedAuras = _nil("C_UnitAuras.ClearBlockedAuras")
C_UnitAuras.DoesAuraHaveExpirationTime = _bool("C_UnitAuras.DoesAuraHaveExpirationTime")
C_UnitAuras.GetAuraApplicationDisplayCount = _str("C_UnitAuras.GetAuraApplicationDisplayCount")
C_UnitAuras.GetAuraBaseDuration = _nil("C_UnitAuras.GetAuraBaseDuration")
C_UnitAuras.GetAuraDataByAuraInstanceID = _nil("C_UnitAuras.GetAuraDataByAuraInstanceID")
C_UnitAuras.GetAuraDataByIndex = _nil("C_UnitAuras.GetAuraDataByIndex")
C_UnitAuras.GetAuraDataBySlot = _nil("C_UnitAuras.GetAuraDataBySlot")
C_UnitAuras.GetAuraDataBySpellName = _nil("C_UnitAuras.GetAuraDataBySpellName")
C_UnitAuras.GetAuraDispelTypeColor = _nil("C_UnitAuras.GetAuraDispelTypeColor")
C_UnitAuras.GetAuraDuration = _nil("C_UnitAuras.GetAuraDuration")
C_UnitAuras.GetAuraSlots = _nil("C_UnitAuras.GetAuraSlots")
C_UnitAuras.GetBuffDataByIndex = _nil("C_UnitAuras.GetBuffDataByIndex")
C_UnitAuras.GetCooldownAuraBySpellID = _nil("C_UnitAuras.GetCooldownAuraBySpellID")
C_UnitAuras.GetDebuffDataByIndex = _nil("C_UnitAuras.GetDebuffDataByIndex")
C_UnitAuras.GetPlayerAuraBySpellID = _nil("C_UnitAuras.GetPlayerAuraBySpellID")
C_UnitAuras.GetRefreshExtendedDuration = _nil("C_UnitAuras.GetRefreshExtendedDuration")
C_UnitAuras.GetUnitAuraBySpellID = _nil("C_UnitAuras.GetUnitAuraBySpellID")
C_UnitAuras.GetUnitAuraInstanceIDs = _tbl("C_UnitAuras.GetUnitAuraInstanceIDs")
C_UnitAuras.GetUnitAuras = _tbl("C_UnitAuras.GetUnitAuras")
C_UnitAuras.IsAuraFilteredOutByInstanceID = _bool("C_UnitAuras.IsAuraFilteredOutByInstanceID")
C_UnitAuras.RemovePrivateAuraAnchor = _nil("C_UnitAuras.RemovePrivateAuraAnchor")
C_UnitAuras.RemovePrivateAuraAppliedSound = _nil("C_UnitAuras.RemovePrivateAuraAppliedSound")
C_UnitAuras.ResetAuraDataProvider = _nil("C_UnitAuras.ResetAuraDataProvider")
C_UnitAuras.SetPrivateWarningTextAnchor = _nil("C_UnitAuras.SetPrivateWarningTextAnchor")
C_UnitAuras.SwitchAuraDataProvider = _nil("C_UnitAuras.SwitchAuraDataProvider")
C_UnitAuras.TriggerPrivateAuraShowDispelType = _nil("C_UnitAuras.TriggerPrivateAuraShowDispelType")
C_UnitAuras.WantsAlteredForm = _bool("C_UnitAuras.WantsAlteredForm")
-- Events: AURA_DATA_PROVIDER_SWITCH, UNIT_AURA, UNIT_AURA_BLOCK_LIST_CLEARED, UNIT_AURA_BLOCKED
`;
