// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:c5973a9ac971a9fe0acd42750588492dc8a27f677cea2d0b41952b892f6282c4
// @sig-hash: sha256:49ec7358d7e47c1f
// Source: Blizzard_APIDocumentationGenerated/unitauradocumentation.lua
export const C_UnitAuras = `
if C_UnitAuras == nil then C_UnitAuras = {} end
C_UnitAuras.AddBlockedAura = _nil
C_UnitAuras.AddPrivateAuraAnchor = _nil
C_UnitAuras.AddPrivateAuraAppliedSound = _nil
C_UnitAuras.AuraIsBigDefensive = _nil
C_UnitAuras.AuraIsPrivate = _nil
C_UnitAuras.ClearBlockedAuras = _nil
C_UnitAuras.DoesAuraHaveExpirationTime = _nil
C_UnitAuras.GetAuraApplicationDisplayCount = _nil
C_UnitAuras.GetAuraBaseDuration = _nil
C_UnitAuras.GetAuraDataByAuraInstanceID = _nil
C_UnitAuras.GetAuraDataByIndex = _nil
C_UnitAuras.GetAuraDataBySlot = _nil
C_UnitAuras.GetAuraDataBySpellName = _nil
C_UnitAuras.GetAuraDispelTypeColor = _nil
C_UnitAuras.GetAuraDuration = _nil
C_UnitAuras.GetAuraSlots = _nil
C_UnitAuras.GetBuffDataByIndex = _nil
C_UnitAuras.GetCooldownAuraBySpellID = _nil
C_UnitAuras.GetDebuffDataByIndex = _nil
C_UnitAuras.GetPlayerAuraBySpellID = _nil
C_UnitAuras.GetRefreshExtendedDuration = _nil
C_UnitAuras.GetUnitAuraBySpellID = _nil
C_UnitAuras.GetUnitAuraInstanceIDs = _tbl
C_UnitAuras.GetUnitAuras = _tbl
C_UnitAuras.IsAuraFilteredOutByInstanceID = _nil
C_UnitAuras.RemovePrivateAuraAnchor = _nil
C_UnitAuras.RemovePrivateAuraAppliedSound = _nil
C_UnitAuras.ResetAuraDataProvider = _nil
C_UnitAuras.SetPrivateWarningTextAnchor = _nil
C_UnitAuras.SwitchAuraDataProvider = _nil
C_UnitAuras.TriggerPrivateAuraShowDispelType = _nil
C_UnitAuras.WantsAlteredForm = _nil
-- Events: AURA_DATA_PROVIDER_SWITCH, UNIT_AURA, UNIT_AURA_BLOCK_LIST_CLEARED, UNIT_AURA_BLOCKED
`;
