// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:fa59074932799fa8e38b5b9828a16941dbe19d009f54940f4c68dcab0a8e5804
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/vehicledocumentation.lua
export const C_Vehicle = `
if C_Vehicle == nil then C_Vehicle = {} end
-- Events: PLAYER_GAINS_VEHICLE_DATA, PLAYER_LOSES_VEHICLE_DATA, UNIT_ENTERED_VEHICLE, UNIT_ENTERING_VEHICLE, UNIT_EXITED_VEHICLE, UNIT_EXITING_VEHICLE, VEHICLE_ANGLE_SHOW, VEHICLE_PASSENGERS_CHANGED, VEHICLE_POWER_SHOW, VEHICLE_UPDATE
`;
