// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:89e7c169798830eaf31b94049b024f223c79f4a7d51e0a226a1a0e569bb52600
// @sig-hash: sha256:2d9da70b925248cd
// Source: Blizzard_APIDocumentationGenerated/vignetteinfodocumentation.lua
export const C_VignetteInfo = `
if C_VignetteInfo == nil then C_VignetteInfo = {} end
C_VignetteInfo.FindBestUniqueVignette = _nil
C_VignetteInfo.GetHealthPercent = _nil
C_VignetteInfo.GetRecommendedGroupSize = _num
C_VignetteInfo.GetVignetteInfo = _nil
C_VignetteInfo.GetVignettePosition = _nil
C_VignetteInfo.GetVignettes = _tbl
-- Events: VIGNETTE_MINIMAP_UPDATED, VIGNETTES_UPDATED
`;
