// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5982320ccbaec8bca6b022b79e1c5f1bd909438466262d64dce372e6220043fe
// @sig-hash: sha256:49cc3116c219bc53
// Source: Blizzard_APIDocumentationGenerated/videodocumentation.lua
export const C_VideoOptions = `
if C_VideoOptions == nil then C_VideoOptions = {} end
C_VideoOptions.GetCurrentGameWindowSize = _nil("C_VideoOptions.GetCurrentGameWindowSize")
C_VideoOptions.GetDefaultGameWindowSize = _nil("C_VideoOptions.GetDefaultGameWindowSize")
C_VideoOptions.GetGameWindowSizes = _tbl("C_VideoOptions.GetGameWindowSizes")
C_VideoOptions.GetGxAdapterInfo = _tbl("C_VideoOptions.GetGxAdapterInfo")
C_VideoOptions.IsSpellVisualDensitySystemSupported = _bool("C_VideoOptions.IsSpellVisualDensitySystemSupported")
C_VideoOptions.SetGameWindowSize = _nil("C_VideoOptions.SetGameWindowSize")
-- Events: ADAPTER_LIST_CHANGED, DISPLAY_SIZE_CHANGED, GLUE_SCREENSHOT_FAILED, GLUE_SCREENSHOT_STARTED, GLUE_SCREENSHOT_SUCCEEDED, GX_RESTARTED, SCREENSHOT_FAILED, SCREENSHOT_STARTED, SCREENSHOT_SUCCEEDED
`;
