// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:2ccb13571a8bfb42d681c585b4aaad3a97c640479b3742545343dcb5e67b22cf
// @sig-hash: sha256:3c9f79f6bc6ae608
// Source: Blizzard_APIDocumentationGenerated/videodocumentation.lua
export const C_VideoOptions = `
if C_VideoOptions == nil then C_VideoOptions = {} end
C_VideoOptions.GetCurrentGameWindowSize = _nil
C_VideoOptions.GetDefaultGameWindowSize = _nil
C_VideoOptions.GetGameWindowSizes = _tbl
C_VideoOptions.GetGxAdapterInfo = _tbl
C_VideoOptions.IsSpellVisualDensitySystemSupported = _nil
C_VideoOptions.SetGameWindowSize = _nil
-- Events: ADAPTER_LIST_CHANGED, DISPLAY_SIZE_CHANGED, GLUE_SCREENSHOT_FAILED, GLUE_SCREENSHOT_STARTED, GLUE_SCREENSHOT_SUCCEEDED, GX_RESTARTED, SCREENSHOT_FAILED, SCREENSHOT_STARTED, SCREENSHOT_SUCCEEDED
`;
