// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:1fccbc05e51978848f7fd464ece9e23ae40d94ff62e2054964b3dc47f5a7deeb
// @sig-hash: sha256:5c7bf452afb15a18
// Source: Blizzard_APIDocumentationGenerated/warbandsceneinfodocumentation.lua
export const C_WarbandScene = `
if C_WarbandScene == nil then C_WarbandScene = {} end
C_WarbandScene.GetRandomEntryID = _num("C_WarbandScene.GetRandomEntryID")
C_WarbandScene.GetWarbandSceneEntry = _tbl("C_WarbandScene.GetWarbandSceneEntry")
C_WarbandScene.HasWarbandScene = _bool("C_WarbandScene.HasWarbandScene")
C_WarbandScene.IsFavorite = _bool("C_WarbandScene.IsFavorite")
C_WarbandScene.SearchWarbandSceneEntries = _tbl("C_WarbandScene.SearchWarbandSceneEntries")
C_WarbandScene.SetFavorite = _nil("C_WarbandScene.SetFavorite")
-- Events: NEW_WARBAND_SCENE_ADDED, WARBAND_SCENE_FAVORITES_UPDATED
`;
