// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:a66f60d55eef6a2ffd44cc809c1decb9937421ec3f5c476dbfa4e3a088a089d9
// @sig-hash: sha256:335c83ffa516bfdd
// Source: Blizzard_APIDocumentationGenerated/weeklyrewardsdocumentation.lua
export const C_WeeklyRewards = `
if C_WeeklyRewards == nil then C_WeeklyRewards = {} end
C_WeeklyRewards.AreRewardsForCurrentRewardPeriod = _bool("C_WeeklyRewards.AreRewardsForCurrentRewardPeriod")
C_WeeklyRewards.CanClaimRewards = _bool("C_WeeklyRewards.CanClaimRewards")
C_WeeklyRewards.ClaimReward = _nil("C_WeeklyRewards.ClaimReward")
C_WeeklyRewards.CloseInteraction = _nil("C_WeeklyRewards.CloseInteraction")
C_WeeklyRewards.GetActivities = _tbl("C_WeeklyRewards.GetActivities")
C_WeeklyRewards.GetActivityEncounterInfo = _tbl("C_WeeklyRewards.GetActivityEncounterInfo")
C_WeeklyRewards.GetConquestWeeklyProgress = _tbl("C_WeeklyRewards.GetConquestWeeklyProgress")
C_WeeklyRewards.GetDifficultyIDForActivityTier = _num("C_WeeklyRewards.GetDifficultyIDForActivityTier")
C_WeeklyRewards.GetExampleRewardItemHyperlinks = _str("C_WeeklyRewards.GetExampleRewardItemHyperlinks")
C_WeeklyRewards.GetItemHyperlink = _str("C_WeeklyRewards.GetItemHyperlink")
C_WeeklyRewards.GetNextActivitiesIncrease = _bool("C_WeeklyRewards.GetNextActivitiesIncrease")
C_WeeklyRewards.GetNextMythicPlusIncrease = _bool("C_WeeklyRewards.GetNextMythicPlusIncrease")
C_WeeklyRewards.GetNumCompletedDungeonRuns = _num("C_WeeklyRewards.GetNumCompletedDungeonRuns")
C_WeeklyRewards.GetSortedProgressForActivity = _tbl("C_WeeklyRewards.GetSortedProgressForActivity")
C_WeeklyRewards.HasAvailableRewards = _bool("C_WeeklyRewards.HasAvailableRewards")
C_WeeklyRewards.HasGeneratedRewards = _bool("C_WeeklyRewards.HasGeneratedRewards")
C_WeeklyRewards.HasInteraction = _bool("C_WeeklyRewards.HasInteraction")
C_WeeklyRewards.IsWeeklyChestRetired = _bool("C_WeeklyRewards.IsWeeklyChestRetired")
C_WeeklyRewards.OnUIInteract = _nil("C_WeeklyRewards.OnUIInteract")
C_WeeklyRewards.ShouldShowFinalRetirementMessage = _bool("C_WeeklyRewards.ShouldShowFinalRetirementMessage")
C_WeeklyRewards.ShouldShowRetirementMessage = _bool("C_WeeklyRewards.ShouldShowRetirementMessage")
-- Events: WEEKLY_REWARDS_ITEM_CHANGED, WEEKLY_REWARDS_UPDATE
`;
