// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:76791b25cf25e548cb66baf83da688417c0b674634b875531ef283d87af682f8
// @sig-hash: sha256:0b15b59c3be18147
// Source: Blizzard_APIDocumentationGenerated/weeklyrewardsdocumentation.lua
export const C_WeeklyRewards = `
if C_WeeklyRewards == nil then C_WeeklyRewards = {} end
C_WeeklyRewards.AreRewardsForCurrentRewardPeriod = _bool
C_WeeklyRewards.CanClaimRewards = _bool
C_WeeklyRewards.ClaimReward = _nil
C_WeeklyRewards.CloseInteraction = _nil
C_WeeklyRewards.GetActivities = _tbl
C_WeeklyRewards.GetActivityEncounterInfo = _tbl
C_WeeklyRewards.GetConquestWeeklyProgress = _tbl
C_WeeklyRewards.GetDifficultyIDForActivityTier = _num
C_WeeklyRewards.GetExampleRewardItemHyperlinks = _str
C_WeeklyRewards.GetItemHyperlink = _str
C_WeeklyRewards.GetNextActivitiesIncrease = _bool
C_WeeklyRewards.GetNextMythicPlusIncrease = _bool
C_WeeklyRewards.GetNumCompletedDungeonRuns = _num
C_WeeklyRewards.GetSortedProgressForActivity = _tbl
C_WeeklyRewards.HasAvailableRewards = _bool
C_WeeklyRewards.HasGeneratedRewards = _bool
C_WeeklyRewards.HasInteraction = _bool
C_WeeklyRewards.IsWeeklyChestRetired = _bool
C_WeeklyRewards.OnUIInteract = _nil
C_WeeklyRewards.ShouldShowFinalRetirementMessage = _bool
C_WeeklyRewards.ShouldShowRetirementMessage = _bool
-- Events: WEEKLY_REWARDS_ITEM_CHANGED, WEEKLY_REWARDS_UPDATE
`;
