// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:bd219b383fd63b83c96279f83dda91a18f148c9e3ea271fdfd92f5add744ba3a
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/wowentitlementinfodocumentation.lua
export const C_WowEntitlementInfo = `
if C_WowEntitlementInfo == nil then C_WowEntitlementInfo = {} end
-- Events: ENTITLEMENT_DELIVERED, RAF_ENTITLEMENT_DELIVERED
`;
