// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:6a0ff4caa0f9405da25b94b4c65e6ef7ff2a70a0d8bb59fcd3045513ff99c9b0
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/worldstateinfodocumentation.lua
export const C_WorldStateInfo = `
if C_WorldStateInfo == nil then C_WorldStateInfo = {} end
-- Events: CANCEL_PLAYER_COUNTDOWN, START_PLAYER_COUNTDOWN, START_TIMER, STOP_TIMER_OF_TYPE, WORLD_STATE_TIMER_START, WORLD_STATE_TIMER_STOP
`;
