// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:76b0acf5386943e0698325a9b537db392dd1c7317c1b32f51681fd316b782ca4
// @sig-hash: sha256:684b8e0e61cb77b3
// Source: Blizzard_APIDocumentationGenerated/wowsurveydocumentation.lua
export const C_WowSurvey = `
if C_WowSurvey == nil then C_WowSurvey = {} end
C_WowSurvey.OpenSurvey = _nil
C_WowSurvey.TriggerSurveyServe = _nil
-- Events: SURVEY_DELIVERED
`;
