// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:5a107abc45966a5892859e0bca7799d9634dd5181a36b8d11a326bcac8d46d6f
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/wowentitlementinfodocumentation.lua
export const C_WowEntitlementInfo = `
if C_WowEntitlementInfo == nil then C_WowEntitlementInfo = {} end
-- Events: ENTITLEMENT_DELIVERED, RAF_ENTITLEMENT_DELIVERED
`;
