// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:273bebb3ebb790d9226452de1c38bd6b71c9539ca678ce2508b5bddf677f3dfe
// @sig-hash: sha256:e3b0c44298fc1c14
// Source: Blizzard_APIDocumentationGenerated/worldstateinfodocumentation.lua
export const C_WorldStateInfo = `
if C_WorldStateInfo == nil then C_WorldStateInfo = {} end
-- Events: CANCEL_PLAYER_COUNTDOWN, START_PLAYER_COUNTDOWN, START_TIMER, STOP_TIMER_OF_TYPE, WORLD_STATE_TIMER_START, WORLD_STATE_TIMER_STOP
`;
