// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:d025e7e1cf79545c187dac4c1e3a7912f566e5beac9e548081e3288e7f26c4bf
// @sig-hash: sha256:29fea091c2a5dd0b
// Source: Blizzard_APIDocumentationGenerated/worldsafelocsuiinternaldocumentation.lua
export const C_WorldSafeLocsUIInternal = `
if C_WorldSafeLocsUIInternal == nil then C_WorldSafeLocsUIInternal = {} end
C_WorldSafeLocsUIInternal.GetWorldSafeLocs = _tbl
`;
