// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:315997fc2f745078a247f039f1f4fc11f8b941fbffe2974a888a436cb6b15f54
// @sig-hash: sha256:bd39645d68e9fd37
// Source: Blizzard_APIDocumentationGenerated/worldsafelocsuiinternaldocumentation.lua
export const C_WorldSafeLocsUIInternal = `
if C_WorldSafeLocsUIInternal == nil then C_WorldSafeLocsUIInternal = {} end
C_WorldSafeLocsUIInternal.GetWorldSafeLocs = _tbl("C_WorldSafeLocsUIInternal.GetWorldSafeLocs")
`;
