// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:93f4269f76fa65f4af276631fdb989d3f4c66168a0da6f054697566b65bdc21b
// @sig-hash: sha256:f895a8865f657ece
// Source: Blizzard_APIDocumentationGenerated/xmlutildocumentation.lua
export const C_XMLUtil = `
if C_XMLUtil == nil then C_XMLUtil = {} end
C_XMLUtil.GetTemplateInfo = _tbl
C_XMLUtil.GetTemplates = _tbl
`;
