// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:59fc1e48f0efa690626207385b1f3aba67c33c539da75da17446683d4f8d4b6d
// @sig-hash: sha256:0f1fe169e2d3d3f7
// Source: Blizzard_APIDocumentationGenerated/xmlutildocumentation.lua
export const C_XMLUtil = `
if C_XMLUtil == nil then C_XMLUtil = {} end
C_XMLUtil.GetTemplateInfo = _tbl("C_XMLUtil.GetTemplateInfo")
C_XMLUtil.GetTemplates = _tbl("C_XMLUtil.GetTemplates")
`;
