// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:21bf8cd9b81fd536d1f6fd1b74d876b6649dc4edc58c0f39fe4e85886fb60251
// @sig-hash: sha256:a9af86267d7ec66b
// Source: Blizzard_APIDocumentationGenerated/zoneabilitydocumentation.lua
export const C_ZoneAbility = `
if C_ZoneAbility == nil then C_ZoneAbility = {} end
C_ZoneAbility.GetActiveAbilities = _tbl("C_ZoneAbility.GetActiveAbilities")
C_ZoneAbility.GetZoneAbilityIcon = _nil("C_ZoneAbility.GetZoneAbilityIcon")
`;
