// AUTO-GENERATED by dev/gen-api-stubs.ts — DO NOT EDIT
// @gen-hash: sha256:69847349453b51e4876a8ff5bb1fc7909b0f5d818d0c756e783294d8fe9ae258
// @sig-hash: sha256:bd6f2bc1ed74bf2a
// Source: Blizzard_APIDocumentationGenerated/zoneabilitydocumentation.lua
export const C_ZoneAbility = `
if C_ZoneAbility == nil then C_ZoneAbility = {} end
C_ZoneAbility.GetActiveAbilities = _tbl
C_ZoneAbility.GetZoneAbilityIcon = _nil
`;
